import type { BaseEntry } from "@/types";

const entry: BaseEntry = {
  id: "t16",
  slug: "nothing-beats-a-jet2-holiday",
  title: "Nothing Beats a Jet2 Holiday",
  category: "trend",
  description:
    "The upbeat Jet2 ad line turned 2025 TikTok meme — cheerful holiday narration over chaos, disasters, and travel fails.",
  imageGradient: "from-sky-400 via-blue-500 to-red-500",
  scores: { relevance: 27, influence: 52, cringe: 38, brainrot: 32 },
  dynamicMetadata: {
    lastReviewed: "2026-07-25",
    currentRelevance: 27,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "tiktok",
      "news",
    ],
    popularity: 30,
    trendingScore: 26,
    recentRevival: false,
    popularityNotes: "Status: occasionally-referenced · Relevance 27 (today's recognition, not influence) · Trending 26 (recent attention)",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Nothing Beats a Jet2 Holiday”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Nothing”",
      "[news/recent-articles] Google News: 2 items in last 30d (40 returned) for “Nothing Beats a Jet2 Holiday”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Know Your Meme cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Nothing Beats a Jet2 Holiday”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/gen-cohort-adoption] Cohort cue from tags (not used for relevance/trending)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
  },
  addedAt: "2026-07-18",
  lastUpdated: "2026-07-25",
  historicalDate: "2024-01-04",
  views: 2200000,
  trendDirection: "declining",
  tags: ["tiktok", "2025", "advertising", "travel", "uk", "sound"],
  origin:
    "Jet2's 'Nothing Beats a Jet2holiday' campaign (Jess Glynne's 'Hold My Hand,' narration by Zoë Lister) aired as a feel-good UK travel ad. On TikTok, users flipped the cheerful 'Nothing beats a Jet2 holiday' line against chaotic vacation footage — and Jet2 eventually joined the joke (Know Your Meme).",
  summary:
    "A brand audio meme: the wholesome Jet2 holiday slogan becomes ironic soundtrack for travel nightmares, airport meltdowns, and absurd holiday clips. Spread on TikTok through late 2024–2025; the airline's decision to lean in kept the trend culturally sticky.",
  relatedSlugs: ["short-form-takeover", "tiktok-rise", "dupe-economy"],
  relationships: {
    relatedEvent: ["short-form-takeover", "tiktok-rise"],
    sameEra: ["dupe-economy"],
  },
  media: [
    // AI suggested — KYM cover for the Jet2 holiday meme
    {
      role: "featured",
      type: "image",
      url: "https://i.kym-cdn.com/entries/icons/original/000/054/324/jet2_holiday_meme_cover.jpg",
      title: "Nothing Beats a Jet2 Holiday — meme cover",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/nothing-beats-a-jet2-holiday",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Cover imagery for the Jet2 holiday ad audio meme trend.",
      date: "2025",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/nothing-beats-a-jet2-holiday",
      title: "Nothing Beats a Jet2 Holiday — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/nothing-beats-a-jet2-holiday",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Ad origin and sarcastic TikTok usage timeline.",
      date: "2025",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Nothing Beats a Jet2 Holiday — Wikipedia search",
      url: "https://en.wikipedia.org/w/index.php?search=Nothing%20Beats%20a%20Jet2%20Holiday&title=Special:Search&fulltext=1",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
