import type { BaseEntry } from "@/types";

const entry: BaseEntry = {
  id: "t17",
  slug: "performative",
  title: "Performative",
  category: "trend",
  description:
    "The TikTok-era habit of adopting aesthetics, hobbies, and personalities because they look desirable online — not because they feel authentic offline.",
  imageGradient: "from-stone-300 via-rose-200 to-amber-100",
  scores: { relevance: 11, influence: 64, cringe: 56, brainrot: 49 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 11,
    currentStatus: "historical",
    activePlatforms: [
      "tiktok",
    ],
    popularity: 0,
    trendingScore: 0,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (40 returned) for “Performative trend”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Character signals still mark this as strongly representative of chaotic internet brainrot culture. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Performative trend”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Performative”",
      "[news/recent-articles] Google News: 0 items in last 60d (40 returned) for “Performative trend”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Performative trend”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Performative trend\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/gen-cohort-adoption] Cohort cue from tags/title (brainrot character only)",
      "[catalog-evidence/remix-activity] Format/remix / short-form reuse cue (brainrot character only)",
      "Weak corroboration — blended heuristic (0) with AI double-check (22): Documentation exists but low news coverage and trend data indicate only niche awareness, not broad current popularity.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (40 returned) for “Performative trend”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Character signals still mark this as strongly representative of chaotic internet brainrot culture.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-18",
  lastUpdated: "2026-08-16",
  historicalDate: "2025-01-01",
  views: 2600000,
  trendDirection: "declining",
  tags: ["tiktok", "gen z", "aesthetics", "2025", "identity", "performative male"],
  origin:
    "Long-standing sociology idea of 'performative' self-presentation collided with short-form culture: people curate interests (matcha, Clairo, Labubu, tote bags, soft masculinity props) because the aesthetic is socially rewarded. The 2025 'performative male' / 'performative man' discourse on TikTok crystallized the trend — calling out men whose hobbies and personality cues seem staged for desirability rather than lived preference (Know Your Meme).",
  summary:
    "A Gen Z / TikTok cultural pattern: intentionally performing an attractive identity through aesthetics, media tastes, and hobbies. Distinct from a single slang word — it is a broader trend about authenticity vs. audience-optimized personality, with 'performative male' as the defining 2025 wave.",
  relatedSlugs: [
    "labubu",
    "clean-girl-aesthetic",
    "demure-mindful",
    "looksmaxxing",
    "main-character-energy",
    "tiktok-rise",
  ],
  relationships: {
    sameEra: ["labubu", "clean-girl-aesthetic", "demure-mindful"],
    relatedTo: ["looksmaxxing", "main-character-energy"],
    relatedEvent: ["tiktok-rise"],
    relatedSlang: ["main-character-energy"],
  },
  media: [
    // AI suggested — KYM performative-male cover (canonical visual for the trend wave)
    {
      role: "featured",
      type: "image",
      url: "https://i.kym-cdn.com/entries/icons/original/000/054/893/performative-male-meme.jpg",
      title: "Performative — performative male aesthetic cover",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/performative-male",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description:
        "Cover imagery for the performative male meme wave that defines the broader performative aesthetics trend.",
      date: "2025",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/performative-male",
      title: "Performative Male — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/performative-male",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Primary documentation of the 2025 performative male discourse.",
      date: "2025",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Performative — Wikipedia search",
      url: "https://en.wikipedia.org/w/index.php?search=Performative&title=Special:Search&fulltext=1",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
