import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr26",
  slug: "addison-rae",
  title: "Addison Rae",
  category: "creator",
  personType: "Creator",
  description:
    "Louisiana-born TikToker who became one of the platform's first megastars — dance clips, Hype House era fame, and a path from For You pages to music and film.",
  imageGradient: "from-pink-400 via-rose-300 to-orange-300",
  scores: { relevance: 79, influence: 81, cringe: 48, brainrot: 45 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 79,
    currentStatus: "current",
    activePlatforms: [
      "tiktok",
      "wikipedia",
      "news",
    ],
    popularity: 62,
    trendingScore: 56,
    recentRevival: false,
    popularityNotes: "Relevance: Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=62 (Google News: 14 items in last 60d (40 returned) for “Addison Rae”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Character signals still mark this as strongly representative of chaotic internet brainrot culture. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=76,007 for “Addison Rae”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=24719 prev7=25064 (-1%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Addison”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-06-17",
      "[news/recent-articles] Google News: 14 items in last 60d (40 returned) for “Addison Rae”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Addison Rae”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Addison Rae\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/gen-cohort-adoption] Cohort cue from tags/title (brainrot character only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=62 (Google News: 14 items in last 60d (40 returned) for “Addison Rae”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Character signals still mark this as strongly representative of chaotic internet brainrot culture.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  views: 2100000,
  trendDirection: "stable",
  tags: ["tiktok", "dance", "hype house", "influencer", "gen-z"],
  careerStart: "2019",
  platforms: [
    { platform: "tiktok", handle: "addisonre", url: "https://www.tiktok.com/@addisonre" },
    { platform: "youtube", handle: "Addison Rae", url: "https://www.youtube.com/@AddisonRae" },
  ],
  followers: {
    tiktok: "~88M+ (peak era)",
    instagram: "~35M+",
  },
  notableMoments: [
    "Rose with early TikTok dance trends and Hype House collective visibility",
    "Signed with talent agency WME; expanded into music and Netflix's He's All That",
    "Became a reference face for TikTok's 2019–2021 creator boom",
    "Helped normalize TikTok stars crossing into traditional Hollywood pipelines",
  ],
  relatedSlugs: ["charli-damelio", "tiktok-rise", "influencer-culture", "bella-poarch"],
  media: [
    // Replaces prior illustration (File:Addison_Rae_portrait.jpg — drawing, not a photo).
    // AI suggested — concert photograph; human must verify and set verified: true.
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/a/aa/Addison_Rae_for_The_Addison_Tour_in_Toronto%2C_Oct._8_2025.jpg",
      title: "Addison Rae on The Addison Tour (Toronto, 2025)",
      source: "Wikimedia Commons",
      sourceUrl:
        "https://commons.wikimedia.org/wiki/File:Addison_Rae_for_The_Addison_Tour_in_Toronto,_Oct._8_2025.jpg",
      platform: "wikimedia",
      attribution: "Luka0188 (CC BY 4.0)",
      license: "CC BY 4.0",
      description:
        "Addison Rae performing on The Addison Tour at Coca-Cola Coliseum in Toronto, October 8, 2025.",
      date: "2025-10-08",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Addison_Rae",
      title: "Addison Rae — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Addison_Rae",
      platform: "other",
      attribution: "Wikipedia contributors",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Addison Rae — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Addison_Rae",
      domain: "en.wikipedia.org",
    },
    {
      title: "Addison Rae — TikTok",
      url: "https://www.tiktok.com/@addisonre",
      domain: "tiktok.com",
    },
  ],
};

export default entry;
