import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr24",
  slug: "adin-ross",
  title: "Adin Ross",
  category: "creator",
  personType: "Creator",
  description:
    "American Kick/Twitch streamer known for NBA 2K roots, celebrity collabs, and high-drama livestream culture.",
  imageGradient: "from-green-500 via-emerald-500 to-teal-600",
  scores: { relevance: 60, influence: 83, cringe: 60, brainrot: 55 },
  dynamicMetadata: {
    lastReviewed: "2026-08-15",
    currentRelevance: 60,
    currentStatus: "current",
    activePlatforms: [
      "twitch",
      "wikipedia",
      "news",
    ],
    popularity: 47,
    trendingScore: 48,
    recentRevival: false,
    popularityNotes: "Relevance: Creation volume is not peaking, but new content is still being produced regularly. Signals: news/recent-articles=47 (Google News: 7 items in last 60d (40 returned) for “Adin Ross”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Not enough character signals to reassess brainrot independently. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=28,866 for “Adin Ross”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=5584 prev7=5644 (-1%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Adin”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-06-07",
      "[news/recent-articles] Google News: 7 items in last 60d (40 returned) for “Adin Ross”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Adin Ross”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "Weak corroboration — blended heuristic (61) with AI double-check (58): The moderate Wikipedia pageviews, existing Know Your Meme entry, and recent news articles suggest a dedicated following, but the lack of significant spikes in Google Trends and relatively low recent activity on his Know Your Meme page indicate his popularity is consistent but not currently surging.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Creation volume is not peaking, but new content is still being produced regularly. Signals: news/recent-articles=47 (Google News: 7 items in last 60d (40 returned) for “Adin Ross”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Not enough character signals to reassess brainrot independently.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-17",
  lastUpdated: "2026-08-15",
  views: 980000,
  trendDirection: "stable",
  tags: ["kick", "twitch", "streaming", "nba-2k", "celebrity", "controversy"],
  careerStart: "2014",
  platforms: [
    {
      platform: "twitch",
      handle: "AdinRoss",
      url: "https://www.twitch.tv/adinross",
    },
    {
      platform: "youtube",
      handle: "Adin Live",
      url: "https://www.youtube.com/@AdinLive",
    },
  ],
  followers: {
    twitch: "~7M",
    youtube: "~4.6M",
  },
  notableMoments: [
    "Broke out streaming NBA 2K and wager content; early association with Always Excelling / Bronny James circles",
    "Became one of Kick's flagship signings after a 2023 Twitch permanent ban for hateful conduct (ban later lifted in 2025); Kick channel: kick.com/adinross",
    "Hosted a high-viewership 2024 livestream interview with Donald Trump",
    "Frequent flashpoint streamer for celebrity guests, stunts, and platform-moderation drama",
  ],
  relatedSlugs: ["kai-cenat", "ishowspeed", "xqc", "glazing"],
  media: [
    // AI suggested — Commons still (CC BY 3.0)
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/0/0b/Adin_Ross_in_2025.png",
      title: "Adin Ross (2025)",
      source: "Wikimedia Commons / LOU WOP",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Adin_Ross_in_2025.png",
      platform: "wikimedia",
      attribution: "LOU WOP (CC BY 3.0)",
      license: "CC BY 3.0",
      description: "Adin Ross in May 2025 — Kick/Twitch streamer and YouTuber.",
      date: "2025-05-12",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Adin_Ross",
      title: "Adin Ross — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Adin_Ross",
      platform: "wikimedia",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      description: "Career overview, platform moves, and documented controversies.",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://kick.com/adinross",
      title: "Adin Ross — Kick",
      source: "Kick",
      sourceUrl: "https://kick.com/adinross",
      platform: "other",
      attribution: "Adin Ross",
      description: "Primary livestream channel on Kick.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Adin Ross — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Adin_Ross",
      domain: "en.wikipedia.org",
    },
    {
      title: "Adin Ross' Twitch Account Reportedly Unbanned After 2 Years — Complex",
      url: "https://www.complex.com/pop-culture/a/alex-ocho/adin-ross-twitch-account-unbanned-after-2-years",
      domain: "complex.com",
    },
    {
      title: "Adin Ross addresses Kai Cenat beef in Twitch return — Dexerto",
      url: "https://www.dexerto.com/twitch/adin-ross-addresses-kai-cenat-beef-and-his-toxic-fans-in-twitch-return-3173822/",
      domain: "dexerto.com",
    },
  ],
};

export default entry;
