import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr27",
  slug: "alix-earle",
  title: "Alix Earle",
  category: "creator",
  personType: "Creator",
  description:
    "University of Miami student-turned-TikTok phenomenon whose \"Get Ready With Me\" videos and candid tone made her one of 2023's breakout influencer names.",
  imageGradient: "from-rose-300 via-pink-200 to-amber-100",
  scores: { relevance: 66, influence: 65, cringe: 38, brainrot: 45 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 89,
    currentStatus: "highly-active",
    activePlatforms: [
      "tiktok",
      "wikipedia",
      "news",
    ],
    popularity: 81,
    trendingScore: 66,
    recentRevival: false,
    popularityNotes: "Relevance: Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=81 (Google News: 34 items in last 60d (40 returned) for “Alix Earle”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Character signals still mark this as strongly representative of chaotic internet brainrot culture. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=53,406 for “Alix Earle”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=10672 prev7=10609 (1%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Alix”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-02-21",
      "[news/recent-articles] Google News: 34 items in last 60d (40 returned) for “Alix Earle”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Alix Earle”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Alix Earle\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/gen-cohort-adoption] Cohort cue from tags/title (brainrot character only)",
      "Weak corroboration — blended heuristic (100) with AI double-check (78): Strong Wikipedia traffic and recent news coverage show solid popularity, but low Google Trends activity and modest cohort signals indicate it’s not at a peak level.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=81 (Google News: 34 items in last 60d (40 returned) for “Alix Earle”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Character signals still mark this as strongly representative of chaotic internet brainrot culture.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  views: 980000,
  trendDirection: "rising",
  tags: ["tiktok", "grwm", "beauty", "college", "influencer"],
  careerStart: "2022",
  platforms: [
    { platform: "tiktok", handle: "alixearle", url: "https://www.tiktok.com/@alixearle" },
    { platform: "instagram", handle: "alixearle", url: "https://www.instagram.com/alixearle/" },
  ],
  followers: {
    tiktok: "~7M+ (2023 breakout)",
    instagram: "~3M+",
  },
  notableMoments: [
    "GRWM and nightlife vlogs exploded in late 2022–2023 on TikTok",
    "Dubbed \"TikTok's new It Girl\" across beauty and tabloid coverage",
    "Brand deals with major beauty and fashion labels followed rapid follower growth",
    "Represented TikTok's shift toward personality-driven, lo-fi creator fame",
  ],
  relatedSlugs: ["tiktok-rise", "influencer-culture", "instagram-culture", "charli-damelio"],
  media: [
    // AI suggested — 2023 portrait (CC BY 3.0). Human must verify.
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/a/a5/Alix_Earle_in_2023.png",
      title: "Alix Earle in 2023",
      source: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Alix_Earle_in_2023.png",
      platform: "wikimedia",
      attribution: "Sonali Prabhu (CC BY 3.0)",
      license: "CC BY 3.0",
      description: "Alix Earle, 2023.",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Alix_Earle",
      title: "Alix Earle — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Alix_Earle",
      platform: "other",
      attribution: "Wikipedia contributors",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Alix Earle — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Alix_Earle",
      domain: "en.wikipedia.org",
    },
    {
      title: "Alix Earle — TikTok",
      url: "https://www.tiktok.com/@alixearle",
      domain: "tiktok.com",
    },
  ],
};

export default entry;
