import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr28",
  slug: "asmongold",
  title: "Asmongold",
  category: "creator",
  personType: "Creator",
  description:
    "Zack (Asmongold) — Twitch's dominant MMORPG streamer whose WoW marathons, reaction takes, and OTK co-founding made him a pillar of live-stream commentary culture.",
  imageGradient: "from-red-700 via-orange-600 to-amber-500",
  scores: { relevance: 36, influence: 72, cringe: 35, brainrot: 39 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 36,
    currentStatus: "classic",
    activePlatforms: [
      "twitch",
      "news",
    ],
    popularity: 25,
    trendingScore: 25,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=25 (Google News: 2 items in last 60d (40 returned) for “Asmongold creator”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Asmongold creator”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Asmongold”",
      "[news/recent-articles] Google News: 2 items in last 60d (40 returned) for “Asmongold creator”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Asmongold creator”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Asmongold creator\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=25 (Google News: 2 items in last 60d (40 returned) for “Asmongold creator”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  views: 1650000,
  trendDirection: "declining",
  tags: ["twitch", "wow", "streaming", "reaction", "otk"],
  careerStart: "2014",
  platforms: [
    { platform: "twitch", handle: "asmongold", url: "https://www.twitch.tv/asmongold" },
    { platform: "youtube", handle: "Asmongold", url: "https://www.youtube.com/@Asmongold" },
  ],
  followers: {
    twitch: "~3M+",
    youtube: "~2.5M+",
  },
  notableMoments: [
    "Built audience through World of Warcraft progression and loot-drama commentary",
    "Co-founded One True King (OTK) creator collective",
    "Reaction streams and industry commentary expanded reach beyond MMO niche",
    "One of Twitch's most-watched personalities during WoW expansion cycles",
  ],
  relatedSlugs: ["xqc", "pokimane", "discord-culture", "creator-economy"],
  media: [
    // AI suggested — human must verify URL and set verified: true
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/7/75/Asmongold_in_2022.jpg",
      title: "Asmongold at OTK Games Expo (2022)",
      source: "Wikimedia Commons / Esfand",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Asmongold_in_2022.jpg",
      platform: "wikimedia",
      attribution: "Esfand (CC BY 3.0)",
      license: "CC BY 3.0",
      description: "Asmongold presenting at the OTK Games Expo in June 2022.",
      date: "2022-06-09",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Asmongold",
      title: "Asmongold — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Asmongold",
      platform: "other",
      attribution: "Wikipedia contributors",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Asmongold — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Asmongold",
      domain: "en.wikipedia.org",
    },
    {
      title: "Asmongold — Twitch",
      url: "https://www.twitch.tv/asmongold",
      domain: "twitch.tv",
    },
  ],
};

export default entry;
