import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr18",
  slug: "bella-poarch",
  title: "Bella Poarch",
  category: "creator",
  personType: "Creator",
  description:
    "Filipino-American TikToker who created TikTok's all-time most-liked video with a simple head-bobbing lip-sync, then pivoted to a music career with millions of YouTube streams.",
  imageGradient: "from-blue-400 via-purple-400 to-pink-400",
  scores: { relevance: 50, influence: 75, cringe: 52, brainrot: 45 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 50,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "tiktok",
      "wikipedia",
      "news",
    ],
    popularity: 37,
    trendingScore: 44,
    recentRevival: false,
    popularityNotes: "Relevance: Recent creation looks limited versus active internet topics. Signals: news/recent-articles=37 (Google News: 4 items in last 60d (40 returned) for “Bella Poarch”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Character signals still mark this as strongly representative of chaotic internet brainrot culture. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=16,514 for “Bella Poarch”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=3950 prev7=3890 (2%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Bella”",
      "[dictionary/platform-activity] Wiktionary last revision 2025-11-24",
      "[news/recent-articles] Google News: 4 items in last 60d (40 returned) for “Bella Poarch”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Bella Poarch”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Bella Poarch\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/gen-cohort-adoption] Cohort cue from tags/title (brainrot character only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Recent creation looks limited versus active internet topics. Signals: news/recent-articles=37 (Google News: 4 items in last 60d (40 returned) for “Bella Poarch”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Character signals still mark this as strongly representative of chaotic internet brainrot culture.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-17",
  lastUpdated: "2026-08-16",
  views: 1900000,
  trendDirection: "stable",
  tags: ["tiktok", "music", "viral", "filipino", "us-navy", "2020"],
  careerStart: "2020",
  platforms: [
    { platform: "tiktok", handle: "@bellapoarch", url: "https://www.tiktok.com/@bellapoarch" },
    { platform: "youtube", handle: "Bella Poarch", url: "https://www.youtube.com/@BellaPoarch" },
  ],
  followers: {
    tiktok: "~94M+",
    youtube: "~7M+",
  },
  notableMoments: [
    "M to the B lip-sync (August 2020) — became TikTok's most liked video with 60M+ likes, a record it held for years",
    "Former US Navy servicewoman who enlisted before starting her TikTok career",
    "Music debut: 'Build a B*tch' (2021) — reached #1 on multiple charts and 500M+ YouTube views",
    "Collaborated with Sub Urban, Grimes, and other artists on her debut album 'Dolls'",
    "Named one of Time's 100 Most Influential People of 2021",
  ],
  relatedSlugs: ["charli-damelio", "khaby-lame"],
  media: [
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/5/59/Bella_Poarch_-_Pink_Aura_Tour.jpg",
      title: "Bella Poarch — Pink Aura Tour",
      source: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Bella_Poarch_-_Pink_Aura_Tour.jpg",
      platform: "wikimedia",
      attribution: "Wikimedia Commons contributors",
      license: "CC BY-SA 4.0",
      description: "Bella Poarch photographed during the Pink Aura Tour.",
      date: "2023",
      verified: true,
    },
    // ── REFERENCE ──────────────────────────────────────────────────────────────
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Bella_Poarch",
      title: "Bella Poarch — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Bella_Poarch",
      platform: "wikimedia",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      description: "Wikipedia article covering Bella Poarch's TikTok viral rise and music career.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Bella Poarch — TikTok",
      url: "https://www.tiktok.com/@bellapoarch",
      domain: "tiktok.com",
    },
    {
      title: "Bella Poarch — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Bella_Poarch",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
