import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr14",
  slug: "caseoh",
  title: "CaseOh",
  category: "creator",
  personType: "Creator",
  description:
    "Chaotic gaming streamer known for his self-deprecating humor, unfiltered personality, and a distinctively large frame — building a massive audience on YouTube and Twitch through pure comedic authenticity.",
  imageGradient: "from-blue-600 via-indigo-500 to-purple-600",
  scores: { relevance: 8, influence: 83, cringe: 39, brainrot: 44 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 8,
    currentStatus: "historical",
    activePlatforms: [
      "youtube",
      "twitch",
    ],
    popularity: 0,
    trendingScore: 0,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (40 returned) for “CaseOh creator”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “CaseOh creator”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “CaseOh”",
      "[news/recent-articles] Google News: 0 items in last 60d (40 returned) for “CaseOh creator”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Google Trending RSS unavailable",
      "[reddit/discussion-volume] Reddit search unavailable for “CaseOh creator”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"CaseOh creator\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "Weak corroboration — blended heuristic (0) with AI double-check (15): Sparse recent news and low platform activity despite existing documentation suggest only niche recognition, not broad current popularity",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (40 returned) for “CaseOh creator”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-17",
  lastUpdated: "2026-08-16",
  views: 1800000,
  trendDirection: "declining",
  tags: ["gaming", "youtube", "twitch", "humor", "streaming", "viral"],
  careerStart: "2020",
  platforms: [
    { platform: "youtube", handle: "CaseOh", url: "https://www.youtube.com/@CaseOh" },
    { platform: "twitch", handle: "caseoh_", url: "https://www.twitch.tv/caseoh_" },
  ],
  followers: {
    youtube: "~6M+",
    twitch: "~3M+",
  },
  notableMoments: [
    "Viral 'just 5 more minutes' running joke about endlessly extending gaming sessions",
    "Known for honest commentary about his lifestyle and refusing to conform to fitness influencer norms",
    "Collaborations with other popular streamers including Kai Cenat and Adin Ross",
    "Multiple viral compilation clips that drove rapid subscriber growth in 2023–2024",
  ],
  relatedSlugs: ["ishowspeed", "kai-cenat", "amp", "sketch", "duke-dennis"],
  media: [
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/b/b4/CaseOh.jpg",
      title: "CaseOh — Wikimedia Commons",
      source: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:CaseOh.jpg",
      platform: "wikimedia",
      attribution: "Wikimedia Commons contributors",
      license: "CC BY-SA 4.0",
      description: "CaseOh, gaming streamer known for chaotic content and viral moments on YouTube and Twitch.",
      date: "2024",
      verified: true,
    },
    // ── REFERENCE ──────────────────────────────────────────────────────────────
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/CaseOh",
      title: "CaseOh — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/CaseOh",
      platform: "wikimedia",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      description: "Wikipedia article covering CaseOh's gaming streaming career and viral moments.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "CaseOh — YouTube",
      url: "https://www.youtube.com/@CaseOh",
      domain: "youtube.com",
    },
    {
      title: "CaseOh — Wikipedia",
      url: "https://en.wikipedia.org/wiki/CaseOh",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
