import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr29",
  slug: "corpse-husband",
  title: "Corpse Husband",
  category: "creator",
  personType: "Creator",
  description:
    "Anonymous YouTuber and musician known for deep-voice Among Us streams, horror narration, and faceless mystique — a defining voice of 2020 gaming crossover fame.",
  imageGradient: "from-neutral-950 via-zinc-900 to-red-950",
  scores: { relevance: 44, influence: 72, cringe: 28, brainrot: 38 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 44,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "youtube",
      "wikipedia",
      "news",
    ],
    popularity: 32,
    trendingScore: 45,
    recentRevival: false,
    popularityNotes: "Relevance: Recent creation looks limited versus active internet topics. Signals: news/recent-articles=32 (Google News: 3 items in last 60d (40 returned) for “Corpse Husband”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=8,591 for “Corpse Husband”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=2184 prev7=1919 (14%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Corpse”",
      "[news/recent-articles] Google News: 3 items in last 60d (40 returned) for “Corpse Husband”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Corpse Husband”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Corpse Husband\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Recent creation looks limited versus active internet topics. Signals: news/recent-articles=32 (Google News: 3 items in last 60d (40 returned) for “Corpse Husband”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  views: 890000,
  trendDirection: "stable",
  tags: ["youtube", "anonymous", "among us", "music", "faceless"],
  careerStart: "2015",
  platforms: [
    { platform: "youtube", handle: "Corpse Husband", url: "https://www.youtube.com/@Corpse_Husband" },
    { platform: "x", handle: "CORPSE", url: "https://twitter.com/CORPSE" },
  ],
  followers: {
    youtube: "~7M+",
  },
  notableMoments: [
    "Horror story narration built a loyal YouTube audience before streaming crossover",
    "Among Us streams with PewDiePie, Sykkuno, and others exploded during 2020 lockdown",
    "Maintained strict anonymity — rare faceless brand at mainstream scale",
    "Music releases including \"E-Girls Are Ruining My Life\" charted on streaming platforms",
  ],
  relatedSlugs: ["among-us-era", "pewdiepie", "pokimane", "great-meme-reset"],
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Corpse_Husband",
      title: "Corpse Husband — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Corpse_Husband",
      platform: "other",
      attribution: "Wikipedia contributors",
      description: "Biography — no verified public portrait; anonymity is central to the brand.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Corpse Husband — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Corpse_Husband",
      domain: "en.wikipedia.org",
    },
    {
      title: "Corpse Husband — YouTube",
      url: "https://www.youtube.com/@Corpse_Husband",
      domain: "youtube.com",
    },
  ],
};

export default entry;
