import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr2",
  slug: "dafuq-boom",
  title: "DaFuq!?Boom!",
  category: "creator",
  personType: "Creator",
  description:
    "Ukrainian YouTube animator Alexey Gerasimov (DaFuq!?Boom!), best known for Skibidi Toilet — a Garry’s Mod / Source Filmmaker series that became a core Gen Alpha meme lore cycle in 2023–2025.",
  imageGradient: "from-cyan-500 via-blue-600 to-indigo-700",
  scores: { relevance: 50, influence: 79, cringe: 85, brainrot: 99 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 50,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "youtube",
      "news",
    ],
    popularity: 37,
    trendingScore: 37,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Recent creation signals rose modestly. Signals: news/recent-articles=37 (Google News: 4 items in last 60d (21 returned) for “DaFuq!?Boom! creator”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Character signals still mark this as strongly representative of chaotic internet brainrot culture. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “DaFuq!?Boom! creator”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “DaFuq!?Boom!”",
      "[news/recent-articles] Google News: 4 items in last 60d (21 returned) for “DaFuq!?Boom! creator”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “DaFuq!?Boom! creator”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"DaFuq!?Boom! creator\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/absurdity] Tag/title absurdity cue (brainrot character only)",
      "[catalog-evidence/gen-cohort-adoption] Cohort cue from tags/title (brainrot character only)",
      "[catalog-evidence/remix-activity] Format/remix / short-form reuse cue (brainrot character only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Recent creation signals rose modestly. Signals: news/recent-articles=37 (Google News: 4 items in last 60d (21 returned) for “DaFuq!?Boom! creator”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Character signals still mark this as strongly representative of chaotic internet brainrot culture.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-02",
  lastUpdated: "2026-08-16",
  views: 310000,
  trendDirection: "declining",
  tags: ["animation", "gmod", "youtube", "gen-alpha", "skibidi", "brainrot"],
  careerStart: "2019",
  platforms: [
    {
      platform: "youtube",
      handle: "DaFuq!?Boom!",
      url: "https://www.youtube.com/@DaFuqBoom",
    },
  ],
  notableMoments: [
    "Launched Skibidi Toilet on YouTube in February 2023",
    "Released a rapid run of short episodes through 2023–2024",
    "Skibidi Toilet became a major Gen Alpha reference point across YouTube and short-form platforms",
    "Series is built in Garry’s Mod using Half-Life 2 assets",
  ],
  relatedSlugs: [
    "skibidi-toilet",
    "brainrot",
    "ohio-final-boss",
    "tung-tung-tung-sahur",
    "short-form-takeover",
  ],
  relationships: {
    originated: ["skibidi-toilet"],
    relatedTo: ["brainrot", "ohio-final-boss", "tung-tung-tung-sahur"],
    sameEra: ["short-form-takeover"],
  },
  // No reliable CC portrait of Alexey Gerasimov found. Do not use Skibidi
  // animation art as a People hero — keep the defining episode as video only.
  media: [
    {
      role: "video",
      type: "video",
      url: "https://www.youtube.com/watch?v=tzD9OxAHtzU",
      title: "skibidi toilet — Episode 1 (official)",
      source: "YouTube / DaFuq!?Boom!",
      sourceUrl: "https://www.youtube.com/watch?v=tzD9OxAHtzU",
      platform: "youtube",
      attribution: "DaFuq!?Boom!",
      license: "YouTube Standard License",
      description: "Official origin short of Skibidi Toilet by DaFuq!?Boom!",
      date: "2023-02-07",
      verified: true,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://www.youtube.com/@DaFuqBoom",
      title: "DaFuq!?Boom! — YouTube channel",
      source: "YouTube",
      sourceUrl: "https://www.youtube.com/@DaFuqBoom",
      platform: "youtube",
      attribution: "DaFuq!?Boom!",
      description: "Official DaFuq!?Boom! YouTube channel.",
      verified: true,
    },
  ],
  sources: [
    {
      title: "DaFuq!?Boom! — YouTube Channel",
      url: "https://www.youtube.com/@DaFuqBoom",
      domain: "youtube.com",
    },
    {
      title: "Skibidi Toilet — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Skibidi_Toilet",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
