import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr30",
  slug: "dantdm",
  title: "DanTDM",
  category: "creator",
  personType: "Creator",
  description:
    "Daniel Middleton (DanTDM) — British YouTuber whose Minecraft Let's Plays made him one of the highest-earning UK creators of the mid-2010s gaming boom.",
  imageGradient: "from-blue-500 via-cyan-400 to-indigo-500",
  scores: { relevance: 0, influence: 85, cringe: 28, brainrot: 27 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 0,
    currentStatus: "historical",
    activePlatforms: [
      "youtube",
    ],
    popularity: 0,
    trendingScore: 0,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (40 returned) for “DanTDM creator”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “DanTDM creator”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “DanTDM”",
      "[news/recent-articles] Google News: 0 items in last 60d (40 returned) for “DanTDM creator”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “DanTDM creator”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"DanTDM creator\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (40 returned) for “DanTDM creator”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  views: 1200000,
  trendDirection: "declining",
  tags: ["youtube", "minecraft", "gaming", "uk", "child audience"],
  careerStart: "2012",
  platforms: [
    { platform: "youtube", handle: "DanTDM", url: "https://www.youtube.com/@DanTDM" },
    { platform: "twitch", handle: "dantdm", url: "https://www.twitch.tv/dantdm" },
  ],
  followers: {
    youtube: "~28M+",
  },
  notableMoments: [
    "Minecraft mod showcases and survival series dominated mid-2010s kids' YouTube",
    "Guinness World Record for \"Most views for a dedicated Minecraft video channel\"",
    "Arena tour DanTDM On Tour brought YouTube gaming to live UK stages",
    "Appeared at TommyInnit live shows — bridging old-guard and MCYT generations",
  ],
  relatedSlugs: ["dream", "minecraft-movie-premiere", "pewdiepie", "youtube-creator-era"],
  media: [
    // AI suggested — Web Summit photo (CC BY 2.0). Human must verify.
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/b/b9/DanTDM_%40_Sportsfile_%28Web_Summit%29_%28cropped%29.jpg",
      title: "DanTDM at Web Summit",
      source: "Wikimedia Commons",
      sourceUrl:
        "https://commons.wikimedia.org/wiki/File:DanTDM_@_Sportsfile_(Web_Summit)_(cropped).jpg",
      platform: "wikimedia",
      attribution: "Web Summit / Nick Bradshaw / Sportsfile (CC BY 2.0)",
      license: "CC BY 2.0",
      description: "DanTDM at Web Summit.",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/DanTDM",
      title: "DanTDM — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/DanTDM",
      platform: "other",
      attribution: "Wikipedia contributors",
      verified: false,
    },
  ],
  sources: [
    {
      title: "DanTDM — Wikipedia",
      url: "https://en.wikipedia.org/wiki/DanTDM",
      domain: "en.wikipedia.org",
    },
    {
      title: "DanTDM — YouTube",
      url: "https://www.youtube.com/@DanTDM",
      domain: "youtube.com",
    },
  ],
};

export default entry;
