import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr31",
  slug: "david-dobrik",
  title: "David Dobrik",
  category: "creator",
  personType: "Creator",
  description:
    "Slovak-born Vlog Squad leader whose fast-cut four-minute vlogs, Tesla giveaways, and prank energy defined late-2010s YouTube spectacle — before sponsorship scandals slowed the machine.",
  imageGradient: "from-yellow-400 via-amber-300 to-orange-400",
  scores: { relevance: 71, influence: 82, cringe: 65, brainrot: 45 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 71,
    currentStatus: "current",
    activePlatforms: [
      "youtube",
      "wikipedia",
      "news",
    ],
    popularity: 55,
    trendingScore: 45,
    recentRevival: false,
    popularityNotes: "Relevance: Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=55 (Google News: 10 items in last 60d (40 returned) for “David Dobrik”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=29,928 for “David Dobrik”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=5348 prev7=6953 (-23%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “David”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-06-16",
      "[news/recent-articles] Google News: 10 items in last 60d (40 returned) for “David Dobrik”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Google Trending RSS unavailable",
      "[reddit/discussion-volume] Reddit search unavailable for “David Dobrik”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"David Dobrik\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=55 (Google News: 10 items in last 60d (40 returned) for “David Dobrik”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  views: 2400000,
  trendDirection: "stable",
  tags: ["youtube", "vlog squad", "vlogs", "pranks", "giveaways"],
  careerStart: "2015",
  platforms: [
    { platform: "youtube", handle: "David Dobrik", url: "https://www.youtube.com/@DavidDobrik" },
  ],
  followers: {
    youtube: "~17M+ (main vlog channel, era-dependent)",
  },
  notableMoments: [
    "Four-minute vlog format with Vlog Squad ensemble became a YouTube template",
    "Known for elaborate giveaways — cars, cash, and surprise stunts",
    "Stepped back from frequent posting amid 2021–2022 sponsor and safety controversies",
    "Embodied peak \"Vlog Squad era\" creator-as-party-host culture",
  ],
  relatedSlugs: ["youtube-creator-era", "logan-paul", "jake-paul", "influencer-culture"],
  media: [
    // AI suggested — human must verify URL and set verified: true
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/8/8c/David_Dobrik.jpg",
      title: "David Dobrik (2018)",
      source: "Wikimedia Commons / ADHD w/ Travis Mills",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:David_Dobrik.jpg",
      platform: "wikimedia",
      attribution: "ADHD w/ Travis Mills (CC BY 3.0)",
      license: "CC BY 3.0",
      description: "David Dobrik during a 2018 podcast interview.",
      date: "2018",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/David_Dobrik",
      title: "David Dobrik — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/David_Dobrik",
      platform: "other",
      attribution: "Wikipedia contributors",
      verified: false,
    },
  ],
  sources: [
    {
      title: "David Dobrik — Wikipedia",
      url: "https://en.wikipedia.org/wiki/David_Dobrik",
      domain: "en.wikipedia.org",
    },
    {
      title: "David Dobrik — YouTube",
      url: "https://www.youtube.com/@DavidDobrik",
      domain: "youtube.com",
    },
  ],
};

export default entry;
