import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr11",
  slug: "duke-dennis",
  title: "Duke Dennis",
  category: "creator",
  personType: "Creator",
  description:
    "NBA 2K YouTuber and core AMP collective member who built a massive following through gaming content and group entertainment.",
  imageGradient: "from-red-600 via-rose-600 to-pink-600",
  scores: { relevance: 67, influence: 80, cringe: 30, brainrot: 47 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 67,
    currentStatus: "current",
    activePlatforms: [
      "youtube",
      "wikipedia",
      "news",
    ],
    popularity: 58,
    trendingScore: 49,
    recentRevival: false,
    popularityNotes: "Relevance: Creation volume is not peaking, but new content is still being produced regularly. Signals: news/recent-articles=58 (Google News: 12 items in last 60d (40 returned) for “Duke Dennis”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=21,384 for “Duke Dennis”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=3155 prev7=3815 (-17%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Duke”",
      "[dictionary/platform-activity] Wiktionary last revision 2025-10-31",
      "[news/recent-articles] Google News: 12 items in last 60d (40 returned) for “Duke Dennis”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] No Wikipedia / KYM / dictionary / major-news URLs on entry sources",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Duke Dennis”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Duke Dennis\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "Weak corroboration — blended heuristic (74) with AI double-check (60): Steady Wikipedia traffic and some news coverage show moderate interest, but declining pageview trend and low Google‑Trends activity suggest popularity is lower than the heuristic’s 74 estimate.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Creation volume is not peaking, but new content is still being produced regularly. Signals: news/recent-articles=58 (Google News: 12 items in last 60d (40 returned) for “Duke Dennis”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-16",
  lastUpdated: "2026-08-16",
  views: 580000,
  trendDirection: "declining",
  tags: ["youtube", "gaming", "nba 2k", "amp", "basketball", "vlog"],
  careerStart: "2019",
  platforms: [
    {
      platform: "youtube",
      handle: "Duke Dennis Gaming",
      url: "https://www.youtube.com/@DukeDennis",
    },
    {
      platform: "twitch",
      handle: "DukeDennis",
      url: "https://www.twitch.tv/dukedennis",
    },
  ],
  followers: {
    youtube: "~7M+",
  },
  notableMoments: [
    "Core member of AMP (Any Means Possible) — the content collective including Kai Cenat, Fanum, Agent00, Chrisnxtdoor, and ImDavisss",
    "Built one of the largest NBA 2K audiences on YouTube through entertaining and skilled gameplay",
    "AMP group content became some of the most-watched collaborative gaming and vlog content of the era",
  ],
  relatedSlugs: [
    "kai-cenat",
    "amp",
    "fanum-tax",
    "rizz",
    "gyatt",
    "glazing",
  ],
  relationships: {
    memberOf: ["amp"],
    community: ["kai-cenat"],
    relatedSlang: ["fanum-tax", "rizz", "gyatt", "glazing"],
  },
  media: [
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Duke_Dennis_July_2025.jpg",
      title: "Duke Dennis — 2025",
      source: "Wikimedia Commons / ImDavisss Live",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Duke_Dennis_July_2025.jpg",
      platform: "wikimedia",
      attribution: "ImDavisss Live (CC BY 3.0)",
      license: "CC BY 3.0",
      description: "Duke Dennis on a stream with ImDavisss, July 2025.",
      date: "2025-07-16",
      verified: true,
    },
    // ── REFERENCE ──────────────────────────────────────────────────────────────
    {
      role: "reference",
      type: "embed",
      url: "https://www.youtube.com/@DukeDennis",
      title: "Duke Dennis — YouTube channel",
      source: "YouTube",
      sourceUrl: "https://www.youtube.com/@DukeDennis",
      platform: "youtube",
      attribution: "Duke Dennis",
      description: "Official Duke Dennis YouTube channel — NBA 2K content and AMP collective videos.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Duke Dennis — YouTube Channel",
      url: "https://www.youtube.com/@DukeDennis",
      domain: "youtube.com",
    },
  ],
};

export default entry;
