import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr32",
  slug: "emma-chamberlain",
  title: "Emma Chamberlain",
  category: "creator",
  personType: "Creator",
  description:
    "YouTuber who rewired vlogging with messy, ironic editing — from coffee obsession to Met Gala co-host and a generation-defining \"relatable influencer\" archetype.",
  imageGradient: "from-amber-200 via-stone-300 to-rose-200",
  scores: { relevance: 70, influence: 82, cringe: 30, brainrot: 62 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 70,
    currentStatus: "current",
    activePlatforms: [
      "youtube",
      "wikipedia",
      "news",
    ],
    popularity: 44,
    trendingScore: 72,
    recentRevival: true,
    popularityNotes: "Relevance: Creation volume is not peaking, but new content is still being produced regularly. Signals: wikipedia/editorial-trend=100 (Pageviews WoW last7=24270 prev7=11503 (111%)); news/recent-articles=44 (Google News: 6 items in last 60d (40 returned) for “Emma Chamberlain”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Character signals still mark this as strongly representative of chaotic internet brainrot culture. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=55,083 for “Emma Chamberlain”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=24270 prev7=11503 (111%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Emma”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-06-10",
      "[news/recent-articles] Google News: 6 items in last 60d (40 returned) for “Emma Chamberlain”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Emma Chamberlain”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Emma Chamberlain\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/gen-cohort-adoption] Cohort cue from tags/title (brainrot character only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Creation volume is not peaking, but new content is still being produced regularly. Signals: wikipedia/editorial-trend=100 (Pageviews WoW last7=24270 prev7=11503 (111%)); news/recent-articles=44 (Google News: 6 items in last 60d (40 returned) for “Emma Chamberlain”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Character signals still mark this as strongly representative of chaotic internet brainrot culture.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  views: 1900000,
  trendDirection: "stable",
  tags: ["youtube", "vlogging", "coffee", "fashion", "gen-z"],
  careerStart: "2017",
  platforms: [
    { platform: "youtube", handle: "emma chamberlain", url: "https://www.youtube.com/@emmachamberlain" },
    { platform: "instagram", handle: "emmachamberlain", url: "https://www.instagram.com/emmachamberlain/" },
  ],
  followers: {
    youtube: "~12M+",
    instagram: "~15M+",
  },
  notableMoments: [
    "Vlogs with jump-cut editing and deadpan humor defined late-2010s YouTube tone",
    "Launched Chamberlain Coffee brand from her coffee meme persona",
    "Co-hosted Met Gala livestream — rare creator role on fashion's biggest night",
    "Pivot from daily vlogs to podcast and fashion cemented longevity beyond one format",
  ],
  relatedSlugs: ["youtube-creator-era", "influencer-culture", "tiktok-rise", "creator-economy"],
  media: [
    // AI suggested — human must verify URL and set verified: true
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/3/38/Emma_Chamberlain_2019_vidcon.jpg",
      title: "Emma Chamberlain at VidCon (2019)",
      source: "Wikimedia Commons / Lissa Ray",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Emma_Chamberlain_2019_vidcon.jpg",
      platform: "wikimedia",
      attribution: "Lissa Ray (CC BY 3.0)",
      license: "CC BY 3.0",
      description: "Emma Chamberlain at VidCon 2019.",
      date: "2019-07-15",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Emma_Chamberlain",
      title: "Emma Chamberlain — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Emma_Chamberlain",
      platform: "other",
      attribution: "Wikipedia contributors",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Emma Chamberlain — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Emma_Chamberlain",
      domain: "en.wikipedia.org",
    },
    {
      title: "Emma Chamberlain — YouTube",
      url: "https://www.youtube.com/@emmachamberlain",
      domain: "youtube.com",
    },
  ],
};

export default entry;
