import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr33",
  slug: "fanum",
  title: "Fanum",
  category: "creator",
  personType: "Creator",
  description:
    "Fanum (Roberto) — AMP member and Twitch streamer whose food-stealing bits with Kai Cenat popularized \"fanum tax\" as mainstream Gen Z slang.",
  imageGradient: "from-green-500 via-emerald-400 to-lime-500",
  scores: { relevance: 29, influence: 68, cringe: 35, brainrot: 72 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 29,
    currentStatus: "classic",
    activePlatforms: [
      "twitch",
    ],
    popularity: 16,
    trendingScore: 16,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=16 (Google News: 1 items in last 60d (40 returned) for “Fanum creator”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Fanum creator”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Fanum”",
      "[news/recent-articles] Google News: 1 items in last 60d (40 returned) for “Fanum creator”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Fanum creator”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Fanum creator\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/absurdity] Tag/title absurdity cue (brainrot character only)",
      "Weak corroboration — blended heuristic (25) with AI double-check (32): Strong documentation exists but recent news, platform activity, and Google Trends are low, indicating only modest current popularity.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=16 (Google News: 1 items in last 60d (40 returned) for “Fanum creator”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  views: 620000,
  trendDirection: "declining",
  tags: ["twitch", "amp", "streaming", "fanum tax", "comedy"],
  careerStart: "2021",
  platforms: [
    { platform: "twitch", handle: "Fanum", url: "https://www.twitch.tv/fanum" },
    { platform: "youtube", handle: "Fanum", url: "https://www.youtube.com/@Fanum" },
  ],
  followers: {
    twitch: "~2M+",
    youtube: "~1M+",
  },
  notableMoments: [
    "Joined AMP (Any Means Possible) collective alongside Kai Cenat and Duke Dennis",
    "Running gag of taxing friends' food became the \"fanum tax\" meme",
    "Collaboration streams helped AMP dominate Twitch trending during subathon era",
    "Distinct creator entity from the slang term — the person behind the bit",
  ],
  relatedSlugs: ["fanum-tax", "kai-cenat", "amp", "duke-dennis", "rizz"],
  relationships: {
    memberOf: ["amp"],
    relatedSlang: ["fanum-tax"],
    community: ["kai-cenat", "duke-dennis"],
  },
  media: [
    // AI suggested — still from Agent 00 video (CC BY 3.0). Human must verify.
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/e/ec/Fanum_2021.jpg",
      title: "Fanum (2021)",
      source: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Fanum_2021.jpg",
      platform: "wikimedia",
      attribution: "Agent 00 Gaming (CC BY 3.0)",
      license: "CC BY 3.0",
      description: "Fanum in a video with Agent 00, 2021.",
      date: "2021",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Fanum_(streamer)",
      title: "Fanum (streamer) — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Fanum_(streamer)",
      platform: "other",
      attribution: "Wikipedia contributors",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Fanum (streamer) — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Fanum_(streamer)",
      domain: "en.wikipedia.org",
    },
    {
      title: "Fanum — Twitch",
      url: "https://www.twitch.tv/fanum",
      domain: "twitch.tv",
    },
  ],
};

export default entry;
