import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr5",
  slug: "ishowspeed",
  title: "IShowSpeed",
  category: "creator",
  personType: "Creator",
  description:
    "Darren Watkins Jr. — a chaotic YouTube/Twitch streamer whose explosive reactions, soccer fandom, and viral clips made him a defining face of 2020s live streaming.",
  imageGradient: "from-red-500 via-rose-500 to-pink-600",
  scores: { relevance: 82, influence: 90, cringe: 49, brainrot: 70 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 82,
    currentStatus: "highly-active",
    activePlatforms: [
      "youtube",
      "twitch",
      "news",
    ],
    popularity: 76,
    trendingScore: 76,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=76 (Google News: 27 items in last 60d (40 returned) for “IShowSpeed creator”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “IShowSpeed creator”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “IShowSpeed”",
      "[news/recent-articles] Google News: 27 items in last 60d (40 returned) for “IShowSpeed creator”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “IShowSpeed creator”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"IShowSpeed creator\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "Weak corroboration — blended heuristic (96) with AI double-check (68): Strong documentation and recent news suggest solid popularity, but low platform activity and Google Trends indicate the hype has faded, making the heuristic's 96 too high.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=76 (Google News: 27 items in last 60d (40 returned) for “IShowSpeed creator”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-04",
  lastUpdated: "2026-08-16",
  views: 385000,
  trendDirection: "declining",
  tags: ["streaming", "youtube", "viral", "soccer", "football", "chaos", "twitch"],
  careerStart: "2016",
  platforms: [
    {
      platform: "youtube",
      handle: "IShowSpeed",
      url: "https://www.youtube.com/@ishowspeed",
    },
    {
      platform: "tiktok",
      handle: "@ishowspeed",
      url: "https://www.tiktok.com/@ishowspeed",
    },
  ],
  followers: {
    youtube: "~25M+",
  },
  notableMoments: [
    "Known for explosive live stream reactions that consistently generate viral clips",
    "Strong public association with Cristiano Ronaldo and soccer culture",
    "Traveled to Portugal and met Ronaldo — widely covered moment",
    "Multiple high-profile collaborations with international creators",
  ],
  media: [
    // ── FEATURED ───────────────────────────────────────────────────────────────
    // Wikimedia Commons — CC BY 2.0 photo by James Parker.
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/a/a2/IShowSpeed_November_2021_(52502829419).jpg",
      title: "IShowSpeed — November 2021",
      source: "Wikimedia Commons / James Parker",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:IShowSpeed_November_2021_(52502829419).jpg",
      platform: "wikimedia",
      attribution: "James Parker (CC BY 2.0)",
      license: "CC BY 2.0",
      description: "IShowSpeed (Darren Watkins Jr.) posing for a photoshoot in November 2021.",
      date: "2021-11-26",
      verified: true,
    },
    // ── REFERENCE ──────────────────────────────────────────────────────────────
    {
      role: "reference",
      type: "embed",
      url: "https://www.youtube.com/@ishowspeed",
      title: "IShowSpeed — YouTube channel",
      source: "YouTube",
      sourceUrl: "https://www.youtube.com/@ishowspeed",
      platform: "youtube",
      attribution: "IShowSpeed",
      description: "Official IShowSpeed YouTube channel — chaotic live streams and viral clips.",
      verified: false,
    },
  ],
  relatedSlugs: [
    "kai-cenat",
    "adin-ross",
    "xqc",
    "tiktok-rise",
    "short-form-takeover",
  ],
  relationships: {
    community: ["kai-cenat", "adin-ross", "xqc"],
    sameEra: ["tiktok-rise", "short-form-takeover"],
    relatedTo: ["brainrot"],
  },
  sources: [
    {
      title: "IShowSpeed — YouTube Channel",
      url: "https://www.youtube.com/@ishowspeed",
      domain: "youtube.com",
    },
    {
      title: "IShowSpeed — Wikipedia",
      url: "https://en.wikipedia.org/wiki/IShowSpeed",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
