import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr36",
  slug: "jacksepticeye",
  title: "Jacksepticeye",
  category: "creator",
  personType: "Creator",
  description:
    "Seán McLoughlin (Jacksepticeye) — Irish YouTuber whose green-haired energy, charity livestreams, and decade-long gaming catalog made him one of YouTube's most recognizable faces.",
  imageGradient: "from-green-500 via-lime-400 to-emerald-600",
  scores: { relevance: 50, influence: 90, cringe: 25, brainrot: 35 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 50,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "youtube",
      "news",
    ],
    popularity: 41,
    trendingScore: 41,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Recent creation looks limited versus active internet topics. Signals: news/recent-articles=41 (Google News: 5 items in last 60d (40 returned) for “Jacksepticeye creator”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Jacksepticeye creator”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Jacksepticeye”",
      "[news/recent-articles] Google News: 5 items in last 60d (40 returned) for “Jacksepticeye creator”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Jacksepticeye creator”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Jacksepticeye creator\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "Weak corroboration — blended heuristic (54) with AI double-check (45): Steady authority presence and moderate news coverage keep Jacksepticeye moderately popular, but low platform activity and weak trend data suggest no current surge.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Recent creation looks limited versus active internet topics. Signals: news/recent-articles=41 (Google News: 5 items in last 60d (40 returned) for “Jacksepticeye creator”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  views: 1450000,
  trendDirection: "declining",
  tags: ["youtube", "gaming", "irish", "charity", "commentary"],
  careerStart: "2012",
  platforms: [
    { platform: "youtube", handle: "jacksepticeye", url: "https://www.youtube.com/@jacksepticeye" },
    { platform: "twitch", handle: "jacksepticeye", url: "https://www.twitch.tv/jacksepticeye" },
  ],
  followers: {
    youtube: "~30M+",
  },
  notableMoments: [
    "Gaming Let's Plays with signature intro and high-energy commentary",
    "Hosted massive charity livestreams including SpecialEffect collaborations",
    "Appeared at TommyInnit live shows — linking classic YouTube to MCYT era",
    "One of the longest-running top-tier gaming creators on the platform",
  ],
  relatedSlugs: ["pewdiepie", "markiplier", "dream", "youtube-creator-era"],
  media: [
    // AI suggested — human must verify URL and set verified: true
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/0/05/Jacksepticeye_%28cropped%29.png",
      title: "Jacksepticeye at PAX 2016",
      source: "Wikimedia Commons / MissScarletTanager",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Jacksepticeye_(cropped).png",
      platform: "wikimedia",
      attribution: "MissScarletTanager (CC BY 3.0)",
      license: "CC BY 3.0",
      description: "Jacksepticeye at PAX 2016.",
      date: "2016",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Jacksepticeye",
      title: "Jacksepticeye — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Jacksepticeye",
      platform: "other",
      attribution: "Wikipedia contributors",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Jacksepticeye — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Jacksepticeye",
      domain: "en.wikipedia.org",
    },
    {
      title: "Jacksepticeye — YouTube",
      url: "https://www.youtube.com/@jacksepticeye",
      domain: "youtube.com",
    },
  ],
};

export default entry;
