import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr16",
  slug: "jake-paul",
  title: "Jake Paul",
  category: "creator",
  personType: "Creator",
  description:
    "YouTuber turned professional boxer and promoter — Jake Paul transformed from Disney Channel actor to one of the most polarizing figures in combat sports, fighting legends including Mike Tyson and Anderson Silva.",
  imageGradient: "from-blue-500 via-indigo-500 to-violet-500",
  scores: { relevance: 100, influence: 83, cringe: 55, brainrot: 60 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 100,
    currentStatus: "highly-active",
    activePlatforms: [
      "youtube",
      "wikipedia",
      "news",
    ],
    popularity: 83,
    trendingScore: 57,
    recentRevival: false,
    popularityNotes: "Relevance: Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=83 (Google News: 37 items in last 60d (40 returned) for “Jake Paul”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=94,587 for “Jake Paul”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=15992 prev7=23533 (-32%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Jake”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-04-15",
      "[news/recent-articles] Google News: 37 items in last 60d (40 returned) for “Jake Paul”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Google Trending RSS unavailable",
      "[reddit/discussion-volume] Reddit search unavailable for “Jake Paul”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Jake Paul\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=83 (Google News: 37 items in last 60d (40 returned) for “Jake Paul”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-17",
  lastUpdated: "2026-08-16",
  views: 2900000,
  trendDirection: "declining",
  tags: ["youtube", "boxing", "disney", "wwe", "mvp", "controversy"],
  careerStart: "2014",
  platforms: [
    { platform: "youtube", handle: "Jake Paul", url: "https://www.youtube.com/@JakePaul" },
  ],
  followers: {
    youtube: "~20M+",
  },
  notableMoments: [
    "Started on Vine and YouTube, later on Disney Channel (Bizaardvark, 2016–2017)",
    "Team 10 YouTube house became a viral media empire and controversy machine",
    "Boxing career: beat AnEsonGib, Nate Robinson, Ben Askren, Tyron Woodley (x2), Anderson Silva, Nate Diaz",
    "Fought Mike Tyson in a Netflix-streamed event (November 2024)",
    "Founded Most Valuable Promotions (MVP) — promoted major boxing events",
    "Vocal about fighter pay reform in boxing and MMA",
  ],
  relatedSlugs: ["logan-paul", "ksi", "mrbeast", "ishowspeed"],
  media: [
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/8/8d/Jake_Paul_2019.jpg",
      title: "Jake Paul — June 2019",
      source: "Wikimedia Commons / Erik Drost",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Jake_Paul_2019.jpg",
      platform: "wikimedia",
      attribution: "Erik Drost (CC BY 2.0)",
      license: "CC BY 2.0",
      description: "Jake Paul photographed in June 2019.",
      date: "2019-06-15",
      verified: true,
    },
    // ── REFERENCE ──────────────────────────────────────────────────────────────
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Jake_Paul",
      title: "Jake Paul — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Jake_Paul",
      platform: "wikimedia",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      description: "Wikipedia article covering Jake Paul's YouTube, boxing, and influencer career.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Jake Paul — YouTube",
      url: "https://www.youtube.com/@JakePaul",
      domain: "youtube.com",
    },
    {
      title: "Jake Paul — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Jake_Paul",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
