import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr37",
  slug: "james-charles",
  title: "James Charles",
  category: "creator",
  personType: "Creator",
  description:
    "Beauty YouTuber who became CoverBoy's first male ambassador at 17 — mega fame, tutorial empire, and repeated influencer feuds that defined YouTube beauty drama cycles.",
  imageGradient: "from-purple-400 via-pink-300 to-rose-400",
  scores: { relevance: 86, influence: 78, cringe: 70, brainrot: 40 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 86,
    currentStatus: "highly-active",
    activePlatforms: [
      "youtube",
      "wikipedia",
      "news",
    ],
    popularity: 68,
    trendingScore: 55,
    recentRevival: false,
    popularityNotes: "Relevance: Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=68 (Google News: 19 items in last 60d (40 returned) for “James Charles”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=21,613 for “James Charles”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=4330 prev7=5018 (-14%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “James”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-08-12",
      "[news/recent-articles] Google News: 19 items in last 60d (40 returned) for “James Charles”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “James Charles”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"James Charles\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=68 (Google News: 19 items in last 60d (40 returned) for “James Charles”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  views: 1800000,
  trendDirection: "declining",
  tags: ["youtube", "beauty", "makeup", "drama", "influencer"],
  careerStart: "2015",
  platforms: [
    { platform: "youtube", handle: "James Charles", url: "https://www.youtube.com/@JamesCharles" },
    { platform: "instagram", handle: "jamescharles", url: "https://www.instagram.com/jamescharles/" },
  ],
  followers: {
    youtube: "~23M+",
    instagram: "~20M+",
  },
  notableMoments: [
    "Became CoverGirl's first male brand ambassador in 2016 at age 17",
    "Feud with Tati Westbrook in 2019 became a defining YouTube beauty-drama event",
    "Hosted the Instant Influencer reality competition on YouTube",
    "Represented peak beauty-influencer crossover before TikTok reshaped the category",
  ],
  relatedSlugs: ["jeffree-star", "shane-dawson", "influencer-culture", "youtube-creator-era"],
  media: [
    // AI suggested — human must verify URL and set verified: true
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/b/bc/James_Charles_%282019%29_%28cropped%29.png",
      title: "James Charles (2019)",
      source: "Wikimedia Commons / Lone Fox",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:James_Charles_(2019)_(cropped).png",
      platform: "wikimedia",
      attribution: "Lone Fox (CC BY 3.0)",
      license: "CC BY 3.0",
      description: "James Charles appearing in a 2019 YouTube collaboration.",
      date: "2019",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/James_Charles",
      title: "James Charles — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/James_Charles",
      platform: "other",
      attribution: "Wikipedia contributors",
      verified: false,
    },
  ],
  sources: [
    {
      title: "James Charles — Wikipedia",
      url: "https://en.wikipedia.org/wiki/James_Charles",
      domain: "en.wikipedia.org",
    },
    {
      title: "James Charles — YouTube",
      url: "https://www.youtube.com/@JamesCharles",
      domain: "youtube.com",
    },
  ],
};

export default entry;
