import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr38",
  slug: "jeffree-star",
  title: "Jeffree Star",
  category: "creator",
  personType: "Creator",
  description:
    "MySpace-era musician turned beauty mogul — Jeffree Star Cosmetics, mansion tour vlogs, and central role in 2010s YouTube beauty drama before controversies reshaped his brand.",
  imageGradient: "from-pink-500 via-fuchsia-400 to-purple-600",
  scores: { relevance: 44, influence: 82, cringe: 75, brainrot: 48 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 44,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "youtube",
      "wikipedia",
      "news",
    ],
    popularity: 32,
    trendingScore: 41,
    recentRevival: false,
    popularityNotes: "Relevance: Recent creation looks limited versus active internet topics. Signals: news/recent-articles=32 (Google News: 3 items in last 60d (40 returned) for “Jeffree Star”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=25,425 for “Jeffree Star”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=5473 prev7=5433 (1%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Jeffree”",
      "[news/recent-articles] Google News: 3 items in last 60d (40 returned) for “Jeffree Star”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Google Trending RSS unavailable",
      "[reddit/discussion-volume] Reddit search unavailable for “Jeffree Star”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Jeffree Star\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Recent creation looks limited versus active internet topics. Signals: news/recent-articles=32 (Google News: 3 items in last 60d (40 returned) for “Jeffree Star”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  views: 1600000,
  trendDirection: "stable",
  tags: ["youtube", "beauty", "myspace", "cosmetics", "drama"],
  careerStart: "2006",
  platforms: [
    { platform: "youtube", handle: "Jeffree Star", url: "https://www.youtube.com/@JeffreeStar" },
  ],
  followers: {
    youtube: "~16M+ (era-dependent)",
  },
  notableMoments: [
    "Rose on MySpace as a musician before pivoting to beauty YouTube",
    "Built Jeffree Star Cosmetics into a major influencer-owned makeup line",
    "Tati Westbrook and James Charles feuds placed him at center of beauty drama",
    "Stepped back from prominence amid 2020 controversy and brand restructuring",
  ],
  relatedSlugs: ["james-charles", "shane-dawson", "myspace", "influencer-culture"],
  media: [
    // AI suggested — RuPaul's DragCon 2018 photo (CC BY 2.0). Human must verify.
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Jeffree_Star_Rupaul_Dragcon_2018-337_%2841377487274%29_%28cropped%29.jpg",
      title: "Jeffree Star at RuPaul's DragCon 2018",
      source: "Wikimedia Commons",
      sourceUrl:
        "https://commons.wikimedia.org/wiki/File:Jeffree_Star_Rupaul_Dragcon_2018-337_(41377487274)_(cropped).jpg",
      platform: "wikimedia",
      attribution: "dvsross (CC BY 2.0)",
      license: "CC BY 2.0",
      description: "Jeffree Star at RuPaul's DragCon, 2018.",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Jeffree_Star",
      title: "Jeffree Star — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Jeffree_Star",
      platform: "other",
      attribution: "Wikipedia contributors",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Jeffree Star — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Jeffree_Star",
      domain: "en.wikipedia.org",
    },
    {
      title: "Jeffree Star — YouTube",
      url: "https://www.youtube.com/@JeffreeStar",
      domain: "youtube.com",
    },
  ],
};

export default entry;
