import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr39",
  slug: "jenna-marbles",
  title: "Jenna Marbles",
  category: "creator",
  personType: "Creator",
  description:
    "Jenna Mourey (Jenna Marbles) — early YouTube comedy star whose absurdist vlogs and \"What Are You Doing?\" energy influenced a decade of creator humor before her 2020 exit.",
  imageGradient: "from-yellow-300 via-amber-200 to-orange-300",
  scores: { relevance: 36, influence: 88, cringe: 35, brainrot: 40 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 36,
    currentStatus: "classic",
    activePlatforms: [
      "youtube",
      "wikipedia",
      "news",
    ],
    popularity: 25,
    trendingScore: 32,
    recentRevival: false,
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=25 (Google News: 2 items in last 60d (40 returned) for “Jenna Marbles”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=25,115 for “Jenna Marbles”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=4068 prev7=5030 (-19%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Jenna”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-07-12",
      "[news/recent-articles] Google News: 2 items in last 60d (40 returned) for “Jenna Marbles”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Jenna Marbles”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Jenna Marbles\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=25 (Google News: 2 items in last 60d (40 returned) for “Jenna Marbles”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  views: 1300000,
  trendDirection: "declining",
  tags: ["youtube", "comedy", "vlogs", "2010s", "legacy"],
  careerStart: "2010",
  platforms: [
    { platform: "youtube", handle: "JennaMarbles", url: "https://www.youtube.com/@JennaMarbles" },
  ],
  followers: {
    youtube: "~20M+ (legacy channel)",
  },
  notableMoments: [
    "\"How to Trick People Into Thinking You're Good Looking\" launched her to early YouTube stardom",
    "Years of weekly comedy vlogs with dogs Kermit and Peach as co-stars",
    "Announced indefinite YouTube hiatus in June 2020 amid past video resurfacing",
    "Cited by later creators as a foundational influence on YouTube comedy tone",
  ],
  relatedSlugs: ["youtube-creator-era", "pewdiepie", "markiplier", "influencer-culture"],
  media: [
    // AI suggested — human must verify URL and set verified: true
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/1/11/RISE_-_Jenna_Marbles_01_%28cropped%29.jpg",
      title: "Jenna Marbles at RISE 2018",
      source: "Wikimedia Commons / RISE / Harry Murphy",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:RISE_-_Jenna_Marbles_01_(cropped).jpg",
      platform: "wikimedia",
      attribution: "Harry Murphy / RISE via Sportsfile (CC BY 2.0)",
      license: "CC BY 2.0",
      description: "Jenna Marbles on stage at RISE conference, Hong Kong 2018.",
      date: "2018-07-12",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Jenna_Marbles",
      title: "Jenna Marbles — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Jenna_Marbles",
      platform: "other",
      attribution: "Wikipedia contributors",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Jenna Marbles — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Jenna_Marbles",
      domain: "en.wikipedia.org",
    },
    {
      title: "Jenna Marbles — YouTube",
      url: "https://www.youtube.com/@JennaMarbles",
      domain: "youtube.com",
    },
  ],
};

export default entry;
