import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr3",
  slug: "jools-lebron",
  title: "Jools Lebron",
  category: "creator",
  personType: "Creator",
  description:
    "TikTok creator who launched 'very demure, very mindful' into mainstream culture in 2024.",
  imageGradient: "from-violet-500 via-purple-500 to-fuchsia-500",
  scores: { relevance: 8, influence: 58, cringe: 37, brainrot: 45 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 94,
    currentStatus: "highly-active",
    activePlatforms: [
      "tiktok",
      "wikipedia",
      "news",
    ],
    popularity: 71,
    trendingScore: 86,
    recentRevival: true,
    popularityNotes: "Relevance: Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: wikipedia/editorial-trend=100 (Pageviews WoW last7=4185 prev7=247 (1594%)); news/recent-articles=71 (Google News: 22 items in last 60d (40 returned) for “Jools Lebron”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Character signals still mark this as strongly representative of chaotic internet brainrot culture. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=5,046 for “Jools Lebron”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=4185 prev7=247 (1594%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Jools”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-03-27",
      "[news/recent-articles] Google News: 22 items in last 60d (40 returned) for “Jools Lebron”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] No Wikipedia / KYM / dictionary / major-news URLs on entry sources",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Jools Lebron”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Jools Lebron\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/gen-cohort-adoption] Cohort cue from tags/title (brainrot character only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: wikipedia/editorial-trend=100 (Pageviews WoW last7=4185 prev7=247 (1594%)); news/recent-articles=71 (Google News: 22 items in last 60d (40 returned) for “Jools Lebron”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Character signals still mark this as strongly representative of chaotic internet brainrot culture.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-03",
  lastUpdated: "2026-08-16",
  views: 195000,
  trendDirection: "rising",
  tags: ["tiktok", "viral", "phrase", "demure"],
  careerStart: "2024",
  platforms: [
    {
      platform: "tiktok",
      handle: "@joolieannie",
      url: "https://www.tiktok.com/@joolieannie",
    },
  ],
  notableMoments: [
    "Posted the original 'very demure, very mindful' TikTok in August 2024",
    "Phrase spread rapidly to brand marketing, news segments, and political commentary",
    "Became one of the most-quoted TikTok phrases of 2024",
  ],
  relatedSlugs: ["demure-mindful", "brat-summer", "clean-girl-aesthetic", "girl-dinner"],
  media: [
    // AI suggested — KYM demure entry icon includes Jools (right panel). No Commons
    // portrait; TikTok CDN forbidden. Human must verify and set verified: true.
    {
      role: "featured",
      type: "image",
      url: "https://i.kym-cdn.com/entries/icons/original/000/050/925/demure.jpg",
      title: "Jools Lebron — Very Demure, Very Mindful",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/very-demure-very-mindful",
      platform: "knowyourmeme",
      attribution: "Jools Lebron / @joolieannie (via Know Your Meme documentation)",
      description:
        "Still of Jools Lebron from the viral 'very demure, very mindful' workplace makeup videos.",
      date: "2024",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://www.tiktok.com/@joolieannie",
      title: "Jools Lebron — TikTok (@joolieannie)",
      source: "TikTok",
      sourceUrl: "https://www.tiktok.com/@joolieannie",
      platform: "tiktok",
      attribution: "Jools Lebron / @joolieannie",
      description:
        "Official TikTok account where the 'very demure, very mindful' videos were posted.",
      date: "2024",
      verified: true,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Jools_Lebron",
      title: "Jools Lebron — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Jools_Lebron",
      platform: "other",
      attribution: "Wikipedia contributors",
      description: "Biography and demure-trend coverage.",
      date: "2024",
      verified: true,
    },
  ],
  sources: [
    {
      title: "Jools Lebron — TikTok",
      url: "https://www.tiktok.com/@joolieannie",
      domain: "tiktok.com",
    },
  ],
};

export default entry;
