import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr12",
  slug: "jynxzi",
  title: "Jynxzi",
  category: "creator",
  personType: "Creator",
  description:
    "Nicholas Stewart — the Rainbow Six Siege streamer who built a massive Twitch audience through high-level gameplay and an entertaining personality.",
  imageGradient: "from-orange-500 via-amber-500 to-yellow-400",
  scores: { relevance: 91, influence: 89, cringe: 33, brainrot: 78 },
  dynamicMetadata: {
    lastReviewed: "2026-08-18",
    currentRelevance: 47,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "twitch",
      "news",
    ],
    popularity: 41,
    trendingScore: 41,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Recent creation looks limited versus active internet topics. Signals: news/recent-articles=41 (Google News: 5 items in last 60d (40 returned) for “Jynxzi creator”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Jynxzi creator”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Jynxzi”",
      "[news/recent-articles] Google News: 5 items in last 60d (40 returned) for “Jynxzi creator”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] No Wikipedia / KYM / dictionary / major-news URLs on entry sources",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Jynxzi creator”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Jynxzi creator\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "Weak corroboration — blended heuristic (49) with AI double-check (45): Signals show modest documentation and news coverage but low platform activity and no trend spikes, indicating a steady but not currently booming popularity.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Recent creation looks limited versus active internet topics. Signals: news/recent-articles=41 (Google News: 5 items in last 60d (40 returned) for “Jynxzi creator”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-16",
  lastUpdated: "2026-08-18",
  views: 640000,
  trendDirection: "declining",
  tags: ["twitch", "rainbow six siege", "gaming", "fps", "streaming"],
  careerStart: "2021",
  platforms: [
    {
      platform: "twitch",
      handle: "Jynxzi",
      url: "https://www.twitch.tv/jynxzi",
    },
    {
      platform: "youtube",
      handle: "Jynxzi",
      url: "https://www.youtube.com/@jynxzi",
    },
  ],
  followers: {
    twitch: "~7M+",
  },
  notableMoments: [
    "One of the most-watched Rainbow Six Siege streamers on Twitch",
    "Known for combining high-level competitive gameplay with a highly entertaining stream personality",
    "Rapid growth made him one of the fastest-rising gaming streamers in 2022–2023",
  ],
  relatedSlugs: ["kai-cenat", "ninja"],
  media: [
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/1/1d/Jynxzi_ohnePixel_2025_02.png",
      title: "Jynxzi — May 2025",
      source: "Wikimedia Commons / ohnepixel",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Jynxzi_ohnePixel_2025_02.png",
      platform: "wikimedia",
      attribution: "ohnepixel (CC BY 3.0)",
      license: "CC BY 3.0",
      description: "Jynxzi (Nicholas Stewart) photographed from an ohnepixel YouTube video, May 2025.",
      date: "2025-05-23",
      verified: true,
    },
    // ── REFERENCE ──────────────────────────────────────────────────────────────
    {
      role: "reference",
      type: "embed",
      url: "https://www.youtube.com/@jynxzi",
      title: "Jynxzi — YouTube channel",
      source: "YouTube",
      sourceUrl: "https://www.youtube.com/@jynxzi",
      platform: "youtube",
      attribution: "Jynxzi",
      description: "Official Jynxzi YouTube channel — Rainbow Six Siege gameplay and stream highlights.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Jynxzi — Twitch Channel",
      url: "https://www.twitch.tv/jynxzi",
      domain: "twitch.tv",
    },
  ],
};

export default entry;
