import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr40",
  slug: "keemstar",
  title: "Keemstar (DramaAlert)",
  category: "creator",
  personType: "Creator",
  description:
    "Daniel Keem — DramaAlert host whose daily YouTube drama coverage, Twitter feuds, and \"Dollar in the Studio\" memes made him a polarizing fixture of creator gossip culture.",
  imageGradient: "from-red-600 via-orange-500 to-yellow-400",
  scores: { relevance: 8, influence: 75, cringe: 80, brainrot: 45 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 8,
    currentStatus: "historical",
    activePlatforms: [
      "youtube",
      "x",
    ],
    popularity: 0,
    trendingScore: 0,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (40 returned) for “Keemstar (DramaAlert)”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Keemstar (DramaAlert)”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Keemstar”",
      "[news/recent-articles] Google News: 0 items in last 60d (40 returned) for “Keemstar (DramaAlert)”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Keemstar (DramaAlert)”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Keemstar (DramaAlert)\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "Weak corroboration — blended heuristic (0) with AI double-check (15): Low recent news, trends, and platform activity indicate Keemstar's current popularity is minimal despite existing documentation.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (40 returned) for “Keemstar (DramaAlert)”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  views: 950000,
  trendDirection: "declining",
  tags: ["youtube", "drama", "news", "twitter", "controversy"],
  careerStart: "2009",
  platforms: [
    { platform: "youtube", handle: "DramaAlert", url: "https://www.youtube.com/@DramaAlert" },
    { platform: "x", handle: "KEEMSTAR", url: "https://twitter.com/KEEMSTAR" },
  ],
  followers: {
    youtube: "~6M+",
  },
  notableMoments: [
    "DramaAlert became a daily hub for YouTube feuds and streaming news",
    "Feuds with Ethan Klein, LeafyIsHere, and others defined mid-2010s drama cycles",
    "Hosted creator boxing and event coverage during influencer crossover era",
    "Polarizing reputation — credited with speed, criticized for accuracy and tone",
  ],
  relatedSlugs: ["h3h3-ethan-hila-klein", "pewdiepie", "youtube-creator-era", "jake-paul"],
  media: [
    // AI suggested — Cold Ones 2020 still (CC BY 3.0). Human must verify.
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/0/0c/KeemstarColdOnes2020_%28cropped%29.jpg",
      title: "Keemstar on Cold Ones (2020)",
      source: "Wikimedia Commons",
      sourceUrl:
        "https://commons.wikimedia.org/wiki/File:KeemstarColdOnes2020_(cropped).jpg",
      platform: "wikimedia",
      attribution: "Cold Ones Clips (CC BY 3.0)",
      license: "CC BY 3.0",
      description: "Keemstar appearing on Cold Ones, 2020.",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Keemstar",
      title: "Keemstar — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Keemstar",
      platform: "other",
      attribution: "Wikipedia contributors",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Keemstar — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Keemstar",
      domain: "en.wikipedia.org",
    },
    {
      title: "DramaAlert — YouTube",
      url: "https://www.youtube.com/@DramaAlert",
      domain: "youtube.com",
    },
  ],
};

export default entry;
