import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr17",
  slug: "khaby-lame",
  title: "Khaby Lame",
  category: "creator",
  personType: "Creator",
  description:
    "Senegalese-Italian TikToker who became the most-followed person on TikTok through silent, deadpan reaction videos — mocking overcomplicated 'life hacks' with simple common-sense solutions.",
  imageGradient: "from-black via-gray-800 to-gray-700",
  scores: { relevance: 58, influence: 87, cringe: 22, brainrot: 45 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 58,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "tiktok",
      "wikipedia",
      "news",
    ],
    popularity: 44,
    trendingScore: 45,
    recentRevival: false,
    popularityNotes: "Relevance: Recent creation looks limited versus active internet topics. Signals: news/recent-articles=44 (Google News: 6 items in last 60d (40 returned) for “Khaby Lame”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Character signals still mark this as strongly representative of chaotic internet brainrot culture. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=24,944 for “Khaby Lame”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=5090 prev7=5507 (-8%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Khaby”",
      "[news/recent-articles] Google News: 6 items in last 60d (40 returned) for “Khaby Lame”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Khaby Lame”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Khaby Lame\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/gen-cohort-adoption] Cohort cue from tags/title (brainrot character only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Recent creation looks limited versus active internet topics. Signals: news/recent-articles=44 (Google News: 6 items in last 60d (40 returned) for “Khaby Lame”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Character signals still mark this as strongly representative of chaotic internet brainrot culture.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-17",
  lastUpdated: "2026-08-16",
  views: 2800000,
  trendDirection: "stable",
  tags: ["tiktok", "viral", "silent-comedy", "life-hacks", "italian", "senegalese"],
  careerStart: "2020",
  platforms: [
    { platform: "tiktok", handle: "@khaby.lame", url: "https://www.tiktok.com/@khaby.lame" },
    { platform: "instagram", handle: "@khaby00", url: "https://www.instagram.com/khaby00/" },
  ],
  followers: {
    tiktok: "~162M+",
    instagram: "~80M+",
  },
  notableMoments: [
    "Lost his factory job during COVID-19 lockdowns in 2020 and started posting on TikTok",
    "Became the most-followed creator on TikTok in June 2022, overtaking Charli D'Amelio",
    "His silent deadpan reaction format transcended language barriers — viral in every country",
    "Appeared at the Cannes Film Festival 2022 and multiple major brand campaigns",
    "Italian citizenship granted in August 2022 (was previously a legal resident from Senegal)",
  ],
  relatedSlugs: ["charli-damelio", "zach-king"],
  media: [
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/1/15/KhabyLame.jpg",
      title: "Khaby Lame — Cannes 2022",
      source: "Wikimedia Commons / Gilzetbase",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:KhabyLame.jpg",
      platform: "wikimedia",
      attribution: "Gilzetbase (CC BY-SA 4.0)",
      license: "CC BY-SA 4.0",
      description: "Khaby Lame photographed at the Cannes Film Festival, May 2022.",
      date: "2022-05-18",
      verified: true,
    },
    // ── REFERENCE ──────────────────────────────────────────────────────────────
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Khaby_Lame",
      title: "Khaby Lame — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Khaby_Lame",
      platform: "wikimedia",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      description: "Wikipedia article covering Khaby Lame's TikTok career and silent-comedy format.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Khaby Lame — TikTok",
      url: "https://www.tiktok.com/@khaby.lame",
      domain: "tiktok.com",
    },
    {
      title: "Khaby Lame — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Khaby_Lame",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
