import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr9",
  slug: "ksi",
  title: "KSI",
  category: "creator",
  personType: "Creator",
  description:
    "Olajide Olatunji — British YouTuber, rapper, and boxer who built one of the internet's most influential multi-hyphenate careers and co-founded Prime Hydration.",
  imageGradient: "from-yellow-500 via-amber-500 to-orange-500",
  scores: { relevance: 45, influence: 84, cringe: 33, brainrot: 40 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 45,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "youtube",
      "news",
    ],
    popularity: 32,
    trendingScore: 32,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Recent creation looks limited versus active internet topics. Signals: news/recent-articles=32 (Google News: 3 items in last 60d (40 returned) for “KSI creator”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “KSI creator”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “KSI”",
      "[dictionary/platform-activity] Wiktionary last revision 2025-06-21",
      "[news/recent-articles] Google News: 3 items in last 60d (40 returned) for “KSI creator”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “KSI creator”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"KSI creator\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "Weak corroboration — blended heuristic (44) with AI double-check (45): Signals show solid historical presence but low recent news and trend activity, indicating moderate current popularity.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Recent creation looks limited versus active internet topics. Signals: news/recent-articles=32 (Google News: 3 items in last 60d (40 returned) for “KSI creator”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-16",
  lastUpdated: "2026-08-16",
  views: 1100000,
  trendDirection: "declining",
  tags: ["youtube", "boxing", "music", "british", "sidemen", "prime hydration"],
  careerStart: "2009",
  platforms: [
    {
      platform: "youtube",
      handle: "KSI",
      url: "https://www.youtube.com/@KSI",
    },
    {
      platform: "x",
      handle: "@KSI",
      url: "https://x.com/KSI",
    },
    {
      platform: "instagram",
      handle: "@ksi",
      url: "https://www.instagram.com/ksi",
    },
  ],
  followers: {
    youtube: "~24M+",
  },
  notableMoments: [
    "Founded the Sidemen — one of YouTube's most influential creator groups (including Miniminter, Vikkstar123, TBJZL, Behzinga, Wroetoshaw, and Zerkaa)",
    "Fought Logan Paul twice: split draw (August 2018), KSI wins by majority decision (November 2019) — the first major creator boxing matches of the era",
    "Music career includes international chart entries including 'Holiday' (feat. Don Toliver) and 'Lighter'",
    "Co-founded Prime Hydration with Logan Paul in 2022 — became one of the fastest-growing sports drinks globally",
  ],
  media: [
    // ── FEATURED ───────────────────────────────────────────────────────────────
    // Wikimedia Commons — extracted from a CC BY YouTube video by Gymshark.
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/2/2b/JJ_Olatunji_(KSI)_1.jpg",
      title: "KSI (JJ Olatunji) — 2020",
      source: "Wikimedia Commons / Gymshark",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:JJ_Olatunji_(KSI)_1.jpg",
      platform: "wikimedia",
      attribution: "Gymshark (CC BY 3.0)",
      license: "CC BY 3.0",
      description: "JJ Olatunji (KSI) in 2020 — British YouTuber, rapper, boxer, and co-founder of Prime Hydration.",
      date: "2020",
      verified: true,
    },
    // ── REFERENCE ──────────────────────────────────────────────────────────────
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/KSI",
      title: "KSI — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/KSI",
      platform: "wikimedia",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      description: "Wikipedia article covering KSI's YouTube, music, boxing, and Prime Hydration career.",
      verified: false,
    },
  ],
  relatedSlugs: ["mrbeast", "pewdiepie"],
  sources: [
    {
      title: "KSI — YouTube Channel",
      url: "https://www.youtube.com/@KSI",
      domain: "youtube.com",
    },
    {
      title: "KSI — Wikipedia",
      url: "https://en.wikipedia.org/wiki/KSI",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
