import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr15",
  slug: "logan-paul",
  title: "Logan Paul",
  category: "creator",
  personType: "Creator",
  description:
    "Ohio-born YouTuber, professional boxer, WWE superstar, and co-founder of Prime Hydration — one of the most influential and controversial internet celebrities of the past decade.",
  imageGradient: "from-yellow-500 via-amber-400 to-orange-500",
  scores: { relevance: 84, influence: 84, cringe: 50, brainrot: 55 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 84,
    currentStatus: "highly-active",
    activePlatforms: [
      "youtube",
      "wikipedia",
      "news",
    ],
    popularity: 84,
    trendingScore: 61,
    recentRevival: false,
    popularityNotes: "Relevance: Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=84 (Google News: 39 items in last 60d (40 returned) for “Logan Paul”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=91,216 for “Logan Paul”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=14135 prev7=17542 (-19%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Logan”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-02-18",
      "[news/recent-articles] Google News: 39 items in last 60d (40 returned) for “Logan Paul”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Logan Paul”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Logan Paul\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "Weak corroboration — blended heuristic (100) with AI double-check (68): Steady but declining pageviews, modest news coverage, and low Google Trends indicate solid but not peak popularity.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=84 (Google News: 39 items in last 60d (40 returned) for “Logan Paul”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-17",
  lastUpdated: "2026-08-16",
  views: 3200000,
  trendDirection: "declining",
  tags: ["youtube", "boxing", "wwe", "prime", "controversy", "influencer"],
  careerStart: "2014",
  platforms: [
    { platform: "youtube", handle: "Logan Paul", url: "https://www.youtube.com/@LoganPaul" },
    { platform: "youtube", handle: "Impaulsive", url: "https://www.youtube.com/@Impaulsive" },
  ],
  followers: {
    youtube: "~23M+",
  },
  notableMoments: [
    "2018 Japan forest controversy: posted a video showing a suicide victim, leading to YouTube demonetization and global backlash",
    "Two viral boxing matches vs. KSI (2018, 2019) — the first major influencer boxing events",
    "Exhibition boxing match vs. Floyd Mayweather Jr. (2021)",
    "WWE career — joined WWE and became a legitimate main-event presence by 2022",
    "Co-founded Prime Hydration with KSI in 2022 — became a billion-dollar brand",
    "Impaulsive podcast has ranked among the top podcasts globally",
  ],
  relatedSlugs: ["jake-paul", "ksi"],
  media: [
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/5/50/Logan_Paul_%2848086619418%29.jpg",
      title: "Logan Paul — June 2019",
      source: "Wikimedia Commons / Erik Drost",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Logan_Paul_(48086619418).jpg",
      platform: "wikimedia",
      attribution: "Erik Drost (CC BY 2.0)",
      license: "CC BY 2.0",
      description: "Logan Paul photographed in June 2019 by sports photographer Erik Drost.",
      date: "2019-06-15",
      verified: true,
    },
    // ── REFERENCE ──────────────────────────────────────────────────────────────
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Logan_Paul",
      title: "Logan Paul — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Logan_Paul",
      platform: "wikimedia",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      description: "Wikipedia article covering Logan Paul's YouTube, boxing, WWE, and Prime Hydration career.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Logan Paul — YouTube",
      url: "https://www.youtube.com/@LoganPaul",
      domain: "youtube.com",
    },
    {
      title: "Logan Paul — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Logan_Paul",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
