import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr10",
  slug: "ninja",
  title: "Ninja",
  category: "creator",
  personType: "Creator",
  description:
    "Tyler Blevins — the streamer who made Fortnite a cultural phenomenon and became the most-recognized name in gaming content.",
  imageGradient: "from-blue-500 via-cyan-500 to-sky-400",
  scores: { relevance: 58, influence: 92, cringe: 38, brainrot: 33 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 58,
    currentStatus: "current",
    activePlatforms: [
      "twitch",
      "youtube",
      "news",
    ],
    popularity: 47,
    trendingScore: 47,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Creation volume is not peaking, but new content is still being produced regularly. Signals: news/recent-articles=47 (Google News: 7 items in last 60d (40 returned) for “Ninja creator”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Ninja creator”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Ninja”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-07-01",
      "[news/recent-articles] Google News: 7 items in last 60d (40 returned) for “Ninja creator”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Ninja creator”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Ninja creator\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "Weak corroboration — blended heuristic (61) with AI double-check (55): Signals show solid historical presence but low recent news and trend activity, indicating moderate but waning current popularity.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Creation volume is not peaking, but new content is still being produced regularly. Signals: news/recent-articles=47 (Google News: 7 items in last 60d (40 returned) for “Ninja creator”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-16",
  lastUpdated: "2026-08-16",
  views: 1050000,
  trendDirection: "declining",
  tags: ["twitch", "youtube", "fortnite", "gaming", "competitive", "streaming"],
  careerStart: "2011",
  platforms: [
    {
      platform: "twitch",
      handle: "Ninja",
      url: "https://www.twitch.tv/Ninja",
    },
    {
      platform: "youtube",
      handle: "Ninja",
      url: "https://www.youtube.com/@Ninja",
    },
  ],
  followers: {
    twitch: "~19M+",
  },
  notableMoments: [
    "Most-followed Twitch streamer by 2018 — driven by Fortnite's mainstream explosion",
    "Played Fortnite with Drake and Travis Scott in March 2018 — broke concurrent viewer streaming records at the time",
    "Signed an exclusive deal with Microsoft's Mixer streaming platform in 2019; Mixer shut down in July 2020",
    "Publicly announced a melanoma diagnosis in 2024 and spoke openly about treatment and early detection",
  ],
  media: [
    // ── FEATURED ───────────────────────────────────────────────────────────────
    // Wikimedia Commons — CC BY 4.0 photo by Pétur Felix Bergmansson (2023).
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/1/13/Tyler_Ninja_Blevins.jpg",
      title: "Ninja (Tyler Blevins) — 2023",
      source: "Wikimedia Commons / Pétur Felix Bergmansson",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Tyler_Ninja_Blevins.jpg",
      platform: "wikimedia",
      attribution: "Pétur Felix Bergmansson (CC BY 4.0)",
      license: "CC BY 4.0",
      description: "Tyler Blevins (Ninja) in 2023 — the streamer who made Fortnite a cultural phenomenon.",
      date: "2023",
      verified: true,
    },
    // ── REFERENCE ──────────────────────────────────────────────────────────────
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Tyler_Blevins",
      title: "Tyler Blevins (Ninja) — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Tyler_Blevins",
      platform: "wikimedia",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      description: "Wikipedia article covering Tyler Blevins's streaming career and Fortnite cultural impact.",
      verified: false,
    },
  ],
  relatedSlugs: [
    "mrbeast",
    "kai-cenat",
    "pewdiepie",
    "imagine-if-ninja-got-a-low-taper-fade",
  ],
  relationships: {
    popularized: ["imagine-if-ninja-got-a-low-taper-fade"],
    relatedTo: ["mrbeast", "kai-cenat", "pewdiepie"],
  },
  sources: [
    {
      title: "Ninja — Twitch Channel",
      url: "https://www.twitch.tv/Ninja",
      domain: "twitch.tv",
    },
    {
      title: "Tyler Blevins (Ninja) — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Tyler_Blevins",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
