import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr6",
  slug: "pewdiepie",
  title: "PewDiePie",
  category: "creator",
  personType: "Creator",
  description:
    "Felix Kjellberg — Swedish YouTuber who held the most-subscribed individual channel title for years and defined the gaming commentary era of YouTube.",
  imageGradient: "from-red-600 via-rose-500 to-orange-400",
  scores: { relevance: 28, influence: 96, cringe: 35, brainrot: 30 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 28,
    currentStatus: "classic",
    activePlatforms: [
      "youtube",
    ],
    popularity: 16,
    trendingScore: 16,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=16 (Google News: 1 items in last 60d (40 returned) for “PewDiePie creator”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “PewDiePie creator”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “PewDiePie”",
      "[news/recent-articles] Google News: 1 items in last 60d (40 returned) for “PewDiePie creator”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “PewDiePie creator”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"PewDiePie creator\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "Weak corroboration — blended heuristic (25) with AI double-check (30): Strong historical authority signals but low recent news and trend activity indicate modest current popularity.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=16 (Google News: 1 items in last 60d (40 returned) for “PewDiePie creator”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-16",
  lastUpdated: "2026-08-16",
  views: 1200000,
  trendDirection: "declining",
  tags: ["youtube", "gaming", "commentary", "swedish", "video essays"],
  careerStart: "2010",
  platforms: [
    {
      platform: "youtube",
      handle: "PewDiePie",
      url: "https://www.youtube.com/@PewDiePie",
    },
  ],
  followers: {
    youtube: "~110M+",
  },
  notableMoments: [
    "Most-subscribed individual YouTube channel from 2013 through multiple years",
    "'Subscribe to PewDiePie' campaign against T-Series in 2018–2019 — a defining YouTube cultural moment",
    "Transitioned from gaming commentary to meme reviews, commentary, and video essays",
    "Married Marzia Bisognin in 2019",
  ],
  relatedSlugs: ["harlem-shake", "doge"],
  media: [
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/5/53/Pewdiepie_head_shot.jpg",
      title: "PewDiePie — 2019",
      source: "Wikimedia Commons / Cold Ones Clips (YouTube)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Pewdiepie_head_shot.jpg",
      platform: "wikimedia",
      attribution: "Cold Ones Clips (CC BY 3.0)",
      license: "CC BY 3.0",
      description: "Felix Kjellberg (PewDiePie) photographed from the Cold Ones podcast, July 2019.",
      date: "2019-07-13",
      verified: true,
    },
    // ── REFERENCE ──────────────────────────────────────────────────────────────
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/PewDiePie",
      title: "PewDiePie — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/PewDiePie",
      platform: "wikimedia",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      description: "Wikipedia article covering Felix Kjellberg's YouTube career and cultural impact.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "PewDiePie — YouTube Channel",
      url: "https://www.youtube.com/@PewDiePie",
      domain: "youtube.com",
    },
    {
      title: "PewDiePie — Wikipedia",
      url: "https://en.wikipedia.org/wiki/PewDiePie",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
