import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr21",
  slug: "plaqueboymax",
  title: "PlaqueBoyMax",
  category: "creator",
  personType: "Creator",
  description:
    "Live streamer and content creator known for his chaotic, unfiltered personality and association with the Kick streaming platform — rising through viral clips and collaborations with creators like Adin Ross.",
  imageGradient: "from-red-500 via-orange-500 to-yellow-500",
  scores: { relevance: 79, influence: 72, cringe: 42, brainrot: 40 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 79,
    currentStatus: "current",
    activePlatforms: [
      "twitch",
      "news",
    ],
    popularity: 62,
    trendingScore: 62,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Recent creation activity still looks similar (steady ongoing creation). Signals: news/recent-articles=62 (Google News: 14 items in last 60d (40 returned) for “PlaqueBoyMax creator”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “PlaqueBoyMax creator”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “PlaqueBoyMax”",
      "[news/recent-articles] Google News: 14 items in last 60d (40 returned) for “PlaqueBoyMax creator”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] No Wikipedia / KYM / dictionary / major-news URLs on entry sources",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “PlaqueBoyMax creator”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"PlaqueBoyMax creator\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Recent creation activity still looks similar (steady ongoing creation). Signals: news/recent-articles=62 (Google News: 14 items in last 60d (40 returned) for “PlaqueBoyMax creator”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-17",
  lastUpdated: "2026-08-16",
  views: 950000,
  trendDirection: "declining",
  tags: ["streaming", "kick", "twitch", "viral", "gaming", "live"],
  careerStart: "2021",
  platforms: [
    { platform: "twitch", handle: "PlaqueBoyMax", url: "https://www.twitch.tv/plaqueboymax" },
    { platform: "youtube", handle: "PlaqueBoyMax", url: "https://www.youtube.com/@PlaqueBoyMax" },
  ],
  followers: {
    twitch: "~1M+",
    youtube: "~800K+",
  },
  notableMoments: [
    "Known for viral reaction and gaming clips that spread across TikTok and Twitter",
    "Multiple high-profile collaborations with Adin Ross and other top streamers",
    "Signed to Kick streaming platform as part of the broader creator migration from Twitch",
    "Participation in viral internet culture moments and debates within streaming communities",
  ],
  relatedSlugs: ["xqc", "caseoh", "ishowspeed"],
  media: [
    // CC BY 4.0 event portrait — verified HTTP 200.
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/b/b6/PlaqueBoyMax_JD_Sports_event_18_(cropped)_04.jpg",
      title: "PlaqueBoyMax — JD Sports event portrait (2025)",
      source: "Wikimedia Commons",
      sourceUrl:
        "https://commons.wikimedia.org/wiki/File:PlaqueBoyMax_JD_Sports_event_18_(cropped)_04.jpg",
      platform: "wikimedia",
      attribution: "Wikimedia Commons contributors (CC BY 4.0)",
      license: "CC BY 4.0",
      description:
        "Cropped portrait of PlaqueBoyMax at a 2025 JD Sports event — a recognizable public photo of the streamer.",
      date: "2025",
      verified: true,
    },
    {
      role: "supporting",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/4/41/PlaqueBoyMax_2025.jpg",
      title: "PlaqueBoyMax at Fanatics Fest (2025)",
      source: "Wikimedia Commons / MILLION DOLLAZ WORTH OF GAME",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:PlaqueBoyMax_2025.jpg",
      platform: "wikimedia",
      attribution: "MILLION DOLLAZ WORTH OF GAME (CC BY 3.0)",
      license: "CC BY 3.0",
      description: "PlaqueBoyMax photographed at Fanatics Fest NYC, June 2025.",
      date: "2025-06-25",
      verified: true,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://www.youtube.com/@PlaqueBoyMax",
      title: "PlaqueBoyMax — YouTube",
      source: "YouTube",
      sourceUrl: "https://www.youtube.com/@PlaqueBoyMax",
      platform: "youtube",
      attribution: "PlaqueBoyMax",
      description: "Official PlaqueBoyMax YouTube channel.",
      verified: true,
    },
  ],
  sources: [
    {
      title: "PlaqueBoyMax — Twitch",
      url: "https://www.twitch.tv/plaqueboymax",
      domain: "twitch.tv",
    },
    {
      title: "PlaqueBoyMax — YouTube",
      url: "https://www.youtube.com/@PlaqueBoyMax",
      domain: "youtube.com",
    },
  ],
};

export default entry;
