import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr8",
  slug: "pokimane",
  title: "Pokimane",
  category: "creator",
  personType: "Creator",
  description:
    "Imane Anys — one of the most-followed streamers on Twitch and a defining voice in discussions about parasocial relationships in online creator culture.",
  imageGradient: "from-violet-500 via-purple-500 to-indigo-600",
  scores: { relevance: 38, influence: 85, cringe: 31, brainrot: 30 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 38,
    currentStatus: "classic",
    activePlatforms: [
      "twitch",
      "news",
    ],
    popularity: 25,
    trendingScore: 25,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=25 (Google News: 2 items in last 60d (40 returned) for “Pokimane creator”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Pokimane creator”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Pokimane”",
      "[news/recent-articles] Google News: 2 items in last 60d (40 returned) for “Pokimane creator”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Pokimane creator”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Pokimane creator\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "Weak corroboration — blended heuristic (36) with AI double-check (40): Pokimane remains a well-known creator (high authority scores) but recent news and trend signals are low, indicating only moderate current popularity.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=25 (Google News: 2 items in last 60d (40 returned) for “Pokimane creator”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-16",
  lastUpdated: "2026-08-16",
  views: 870000,
  trendDirection: "declining",
  tags: ["twitch", "streaming", "gaming", "league of legends", "offline-tv"],
  careerStart: "2013",
  platforms: [
    {
      platform: "twitch",
      handle: "pokimane",
      url: "https://www.twitch.tv/pokimane",
    },
    {
      platform: "youtube",
      handle: "Pokimane",
      url: "https://www.youtube.com/@pokimane",
    },
  ],
  followers: {
    twitch: "~9M+",
  },
  notableMoments: [
    "One of the most-followed female streamers on Twitch for multiple consecutive years",
    "Founding member of OfflineTV — one of the most prominent content creator collectives in streaming culture",
    "Central figure in ongoing public discourse about parasocial relationships and the dynamics of streamer-audience culture",
    "Has spoken publicly about managing audience expectations and the challenges of personal boundaries as a public figure",
  ],
  media: [
    // ── FEATURED ───────────────────────────────────────────────────────────────
    // Wikimedia Commons — screenshot from SlikeR's CC BY YouTube stream.
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/8/8d/Pokimane_at_Twitchcon_Berlin_2019.png",
      title: "Pokimane at TwitchCon Berlin 2019",
      source: "Wikimedia Commons / SlikeR",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Pokimane_at_Twitchcon_Berlin_2019.png",
      platform: "wikimedia",
      attribution: "SlikeR (CC BY 3.0)",
      license: "CC BY 3.0",
      description: "Pokimane (Imane Anys) at TwitchCon Berlin in 2019.",
      date: "2019",
      verified: true,
    },
    // ── REFERENCE ──────────────────────────────────────────────────────────────
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Pokimane",
      title: "Pokimane — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Pokimane",
      platform: "wikimedia",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      description: "Wikipedia article covering Imane Anys's streaming career and cultural impact.",
      verified: false,
    },
  ],
  relatedSlugs: ["kai-cenat", "ninja"],
  sources: [
    {
      title: "Pokimane — Twitch Channel",
      url: "https://www.twitch.tv/pokimane",
      domain: "twitch.tv",
    },
    {
      title: "Pokimane — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Pokimane",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
