import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr41",
  slug: "shane-dawson",
  title: "Shane Dawson",
  category: "creator",
  personType: "Creator",
  description:
    "Early YouTube sketch and conspiracy-era creator whose documentary pivots, beauty collaborations, and 2020 controversies marked a rise-and-reckoning arc in influencer history.",
  imageGradient: "from-neutral-700 via-zinc-600 to-stone-500",
  scores: { relevance: 25, influence: 85, cringe: 82, brainrot: 42 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 25,
    currentStatus: "classic",
    activePlatforms: [
      "youtube",
      "wikipedia",
    ],
    popularity: 16,
    trendingScore: 31,
    recentRevival: false,
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=16 (Google News: 1 items in last 60d (40 returned) for “Shane Dawson”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=22,173 for “Shane Dawson”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=5522 prev7=5927 (-7%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Shane”",
      "[dictionary/platform-activity] Wiktionary last revision 2025-12-25",
      "[news/recent-articles] Google News: 1 items in last 60d (40 returned) for “Shane Dawson”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Google Trending RSS unavailable",
      "[reddit/discussion-volume] Reddit search unavailable for “Shane Dawson”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Shane Dawson\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=16 (Google News: 1 items in last 60d (40 returned) for “Shane Dawson”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  views: 1400000,
  trendDirection: "stable",
  tags: ["youtube", "documentary", "conspiracy", "beauty", "controversy"],
  careerStart: "2008",
  platforms: [
    { platform: "youtube", handle: "shane", url: "https://www.youtube.com/@shane" },
  ],
  followers: {
    youtube: "~20M+ (legacy channel)",
  },
  notableMoments: [
    "One of YouTube's earliest crossover stars with sketch comedy and song parodies",
    "Pivot to conspiracy and documentary series drew massive 2018–2019 viewership",
    "The Secret World of Jeffree Star series peaked beauty-doc influencer format",
    "Stepped back from YouTube amid 2020 resurfaced content and controversy",
  ],
  relatedSlugs: ["jeffree-star", "james-charles", "youtube-creator-era", "jake-paul"],
  media: [
    // AI suggested — Streamy Awards photo (CC BY 2.0). Human must verify.
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/b/b9/Shane_Dawson.jpg",
      title: "Shane Dawson",
      source: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Shane_Dawson.jpg",
      platform: "wikimedia",
      attribution: "The Bui Brothers (CC BY 2.0)",
      license: "CC BY 2.0",
      description: "Shane Dawson at the Streamy Awards.",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Shane_Dawson",
      title: "Shane Dawson — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Shane_Dawson",
      platform: "other",
      attribution: "Wikipedia contributors",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Shane Dawson — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Shane_Dawson",
      domain: "en.wikipedia.org",
    },
    {
      title: "shane — YouTube",
      url: "https://www.youtube.com/@shane",
      domain: "youtube.com",
    },
  ],
};

export default entry;
