import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr13",
  slug: "sketch",
  title: "Sketch",
  category: "creator",
  personType: "Creator",
  description:
    "A gaming and lifestyle content creator known for Roblox content on YouTube and Twitch.",
  imageGradient: "from-blue-400 via-sky-400 to-cyan-400",
  scores: { relevance: 41, influence: 72, cringe: 37, brainrot: 45 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 41,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "youtube",
      "news",
    ],
    popularity: 32,
    trendingScore: 32,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Recent creation looks limited versus active internet topics. Signals: news/recent-articles=32 (Google News: 3 items in last 60d (40 returned) for “Sketch creator”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Sketch creator”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Sketch”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-05-10",
      "[news/recent-articles] Google News: 3 items in last 60d (40 returned) for “Sketch creator”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] No Wikipedia / KYM / dictionary / major-news URLs on entry sources",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Sketch creator”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Sketch creator\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "Weak corroboration — blended heuristic (44) with AI double-check (38): Mixed documentation scores are offset by low recent news, trend data, and platform activity, indicating modest but not strong current popularity.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Recent creation looks limited versus active internet topics. Signals: news/recent-articles=32 (Google News: 3 items in last 60d (40 returned) for “Sketch creator”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-16",
  lastUpdated: "2026-08-16",
  views: 380000,
  trendDirection: "declining",
  tags: ["youtube", "roblox", "gaming", "streaming"],
  careerStart: "2020",
  platforms: [
    {
      platform: "youtube",
      handle: "SketchYT",
      url: "https://www.youtube.com/@SketchYT",
    },
  ],
  notableMoments: [
    "Known for Roblox gaming content and interactive entertainment on YouTube",
  ],
  relatedSlugs: ["duke-dennis", "amp", "kai-cenat", "ishowspeed", "caseoh"],
  media: [
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/5/51/Sketch_2025_Streamer_Games.png",
      title: "Sketch at the 2025 Streamer Games",
      source: "Wikimedia Commons / MISTERARTHERVODS",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Sketch_2025_Streamer_Games.png",
      platform: "wikimedia",
      attribution: "MISTERARTHERVODS (CC BY 4.0)",
      license: "CC BY 4.0",
      description: "Sketch (streamer) at the 2025 Streamer Games event, August 2025.",
      date: "2025-08-16",
      verified: true,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://www.youtube.com/@SketchYT",
      title: "Sketch — YouTube channel",
      source: "YouTube",
      sourceUrl: "https://www.youtube.com/@SketchYT",
      platform: "youtube",
      attribution: "Sketch / @SketchYT",
      description: "Primary YouTube channel for Sketch's Roblox and lifestyle content.",
      date: "2020",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Sketch — YouTube",
      url: "https://www.youtube.com/@SketchYT",
      domain: "youtube.com",
    },
  ],
};

export default entry;
