import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr43",
  slug: "sssniperwolf",
  title: "SSSniperWolf",
  category: "creator",
  personType: "Creator",
  description:
    "Lia Shelesh (SSSniperWolf) — gaming reaction and vlog creator whose Call of Duty roots, \"react\" format, and 2023 doxxing controversy kept her in YouTube drama headlines.",
  imageGradient: "from-purple-600 via-violet-500 to-indigo-600",
  scores: { relevance: 0, influence: 74, cringe: 53, brainrot: 44 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 0,
    currentStatus: "historical",
    activePlatforms: [
      "youtube",
    ],
    popularity: 0,
    trendingScore: 0,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (40 returned) for “SSSniperWolf creator”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “SSSniperWolf creator”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “SSSniperWolf”",
      "[news/recent-articles] Google News: 0 items in last 60d (40 returned) for “SSSniperWolf creator”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “SSSniperWolf creator”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"SSSniperWolf creator\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (40 returned) for “SSSniperWolf creator”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  views: 1050000,
  trendDirection: "declining",
  tags: ["youtube", "gaming", "reaction", "vlogs", "controversy"],
  careerStart: "2011",
  platforms: [
    { platform: "youtube", handle: "SSSniperWolf", url: "https://www.youtube.com/@SSSniperWolf" },
  ],
  followers: {
    youtube: "~34M+",
  },
  notableMoments: [
    "Built channel on Call of Duty gameplay before expanding to reaction content",
    "Among the most-subscribed female creators on YouTube for several years",
    "2023 confrontation with Jacksfilms over reaction content sparked platform debate",
    "Represents YouTube's shift toward short reaction clips in gaming-adjacent niches",
  ],
  relatedSlugs: ["youtube-creator-era", "pewdiepie", "influencer-culture", "cringe"],
  media: [
    // AI suggested — still from her YouTube Shorts (CC BY 3.0). Human must verify.
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/1/19/Alia_Shelesh_YouTube_shorts_screenshot.jpg",
      title: "SSSniperWolf (Alia Shelesh), 2022",
      source: "Wikimedia Commons",
      sourceUrl:
        "https://commons.wikimedia.org/wiki/File:Alia_Shelesh_YouTube_shorts_screenshot.jpg",
      platform: "wikimedia",
      attribution: "SSSniperWolf (CC BY 3.0)",
      license: "CC BY 3.0",
      description: "Alia Shelesh (SSSniperWolf) in a 2022 YouTube Shorts still.",
      date: "2022",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/SSSniperWolf",
      title: "SSSniperWolf — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/SSSniperWolf",
      platform: "other",
      attribution: "Wikipedia contributors",
      verified: false,
    },
  ],
  sources: [
    {
      title: "SSSniperWolf — Wikipedia",
      url: "https://en.wikipedia.org/wiki/SSSniperWolf",
      domain: "en.wikipedia.org",
    },
    {
      title: "SSSniperWolf — YouTube",
      url: "https://www.youtube.com/@SSSniperWolf",
      domain: "youtube.com",
    },
  ],
};

export default entry;
