import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr44",
  slug: "technoblade",
  title: "Technoblade",
  category: "creator",
  personType: "Creator",
  description:
    "Alexander (Technoblade) — Minecraft PvP legend and Dream SMP member whose \"so long nerds\" farewell video after an cancer diagnosis became one of YouTube's most-watched tributes.",
  imageGradient: "from-red-700 via-rose-600 to-amber-500",
  scores: { relevance: 28, influence: 87, cringe: 35, brainrot: 30 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 28,
    currentStatus: "classic",
    activePlatforms: [
      "youtube",
    ],
    popularity: 16,
    trendingScore: 16,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=16 (Google News: 1 items in last 60d (40 returned) for “Technoblade creator”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Technoblade creator”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Technoblade”",
      "[news/recent-articles] Google News: 1 items in last 60d (40 returned) for “Technoblade creator”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Technoblade creator”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Technoblade creator\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "Weak corroboration — blended heuristic (25) with AI double-check (30): While Technoblade still has strong historical documentation, recent news coverage and trend data are low, indicating modest current popularity.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=16 (Google News: 1 items in last 60d (40 returned) for “Technoblade creator”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  views: 3200000,
  trendDirection: "declining",
  tags: ["minecraft", "youtube", "dream smp", "mcyt", "memorial"],
  careerStart: "2013",
  platforms: [
    { platform: "youtube", handle: "Technoblade", url: "https://www.youtube.com/@Technoblade" },
  ],
  followers: {
    youtube: "~15M+",
  },
  notableMoments: [
    "Dominant Minecraft Hypixel Skywars player known for skill and trash talk",
    "Dream SMP anarchist role brought him to Gen Z fandom mainstream",
    "August 2022 farewell video announced death from sarcoma — massive global tribute",
    "Minecraft added pig crown tribute skin honoring his \"Technoblade never dies\" legacy",
  ],
  relatedSlugs: ["dream", "tommyinnit", "wilbur-soot", "minecraft-movie-premiere"],
  relationships: {
    sameEra: ["dream", "tommyinnit", "wilbur-soot"],
    relatedEvent: ["minecraft-movie-premiere"],
  },
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Technoblade",
      title: "Technoblade — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Technoblade",
      platform: "other",
      attribution: "Wikipedia contributors",
      description: "No verified CC portrait on Commons — Technoblade maintained partial anonymity.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Technoblade — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Technoblade",
      domain: "en.wikipedia.org",
    },
    {
      title: "Technoblade — YouTube",
      url: "https://www.youtube.com/@Technoblade",
      domain: "youtube.com",
    },
  ],
};

export default entry;
