import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr47",
  slug: "valkyrae",
  title: "Valkyrae",
  category: "creator",
  personType: "Creator",
  description:
    "Rachell Hofstetter (Valkyrae) — streamer who rose from Fortnite to 100 Thieves co-owner, Among Us crossover fame, and mainstream red-carpet creator visibility.",
  imageGradient: "from-red-500 via-rose-400 to-pink-500",
  scores: { relevance: 58, influence: 78, cringe: 32, brainrot: 38 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 58,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "twitch",
      "youtube",
      "news",
    ],
    popularity: 44,
    trendingScore: 44,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Recent creation looks limited versus active internet topics. Signals: news/recent-articles=44 (Google News: 6 items in last 60d (40 returned) for “Valkyrae creator”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Valkyrae creator”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Valkyrae”",
      "[news/recent-articles] Google News: 6 items in last 60d (40 returned) for “Valkyrae creator”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Valkyrae creator”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Valkyrae creator\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Recent creation looks limited versus active internet topics. Signals: news/recent-articles=44 (Google News: 6 items in last 60d (40 returned) for “Valkyrae creator”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  views: 920000,
  trendDirection: "declining",
  tags: ["twitch", "youtube", "100 thieves", "among us", "streaming"],
  careerStart: "2015",
  platforms: [
    { platform: "youtube", handle: "Valkyrae", url: "https://www.youtube.com/@Valkyrae" },
    { platform: "twitch", handle: "valkyrae", url: "https://www.twitch.tv/valkyrae" },
  ],
  followers: {
    youtube: "~4M+",
    twitch: "~1M+ (prior peak higher)",
  },
  notableMoments: [
    "Among Us streams with Corpse Husband, PewDiePie, and others spiked 2020 viewership",
    "Named co-owner of esports org 100 Thieves in 2020 — rare creator equity deal",
    "Appeared at Game Awards and fashion events as creator crossed into mainstream",
    "Shifted primary platform between Twitch and YouTube over contract years",
  ],
  relatedSlugs: ["corpse-husband", "pokimane", "among-us-era", "creator-economy"],
  media: [
    // AI suggested — 100 Thieves portrait (CC BY-SA 2.0). Human must verify.
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/0/03/Valkyrae_for_100_Thieves_%28cropped%29.jpg",
      title: "Valkyrae for 100 Thieves",
      source: "Wikimedia Commons",
      sourceUrl:
        "https://commons.wikimedia.org/wiki/File:Valkyrae_for_100_Thieves_(cropped).jpg",
      platform: "wikimedia",
      attribution: "Sean Finnegan (CC BY-SA 2.0)",
      license: "CC BY-SA 2.0",
      description: "Valkyrae in a 100 Thieves portrait.",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Valkyrae",
      title: "Valkyrae — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Valkyrae",
      platform: "other",
      attribution: "Wikipedia contributors",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Valkyrae — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Valkyrae",
      domain: "en.wikipedia.org",
    },
    {
      title: "Valkyrae — YouTube",
      url: "https://www.youtube.com/@Valkyrae",
      domain: "youtube.com",
    },
  ],
};

export default entry;
