import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr48",
  slug: "wilbur-soot",
  title: "Wilbur Soot",
  category: "creator",
  personType: "Creator",
  description:
    "Will Gold (Wilbur Soot) — British YouTuber, musician, and Dream SMP writer whose \"Your New Boyfriend\" era and Sofar lore blended indie music with Minecraft fandom.",
  imageGradient: "from-indigo-600 via-violet-500 to-purple-700",
  scores: { relevance: 0, influence: 75, cringe: 38, brainrot: 42 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 0,
    currentStatus: "historical",
    activePlatforms: [
      "youtube",
      "wikipedia",
    ],
    popularity: 0,
    trendingScore: 25,
    recentRevival: false,
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (40 returned) for “Wilbur Soot”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=12,440 for “Wilbur Soot”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=3091 prev7=3136 (-1%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Wilbur”",
      "[dictionary/platform-activity] Wiktionary last revision 2025-05-18",
      "[news/recent-articles] Google News: 0 items in last 60d (40 returned) for “Wilbur Soot”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Wilbur Soot”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Wilbur Soot\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (40 returned) for “Wilbur Soot”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  views: 870000,
  trendDirection: "declining",
  tags: ["youtube", "music", "minecraft", "dream smp", "mcyt"],
  careerStart: "2013",
  platforms: [
    { platform: "youtube", handle: "Wilbur Soot", url: "https://www.youtube.com/@WilburSoot" },
    { platform: "twitch", handle: "wilbursoot", url: "https://www.twitch.tv/wilbursoot" },
  ],
  followers: {
    youtube: "~6M+",
  },
  notableMoments: [
    "SootHouse comedy collective preceded solo music and Minecraft crossover fame",
    "Dream SMP Pogtopia writing and performance drew music fans into MCYT",
    "\"Your New Boyfriend\" and \"Lmanberg\" era songs charted on Gen Z playlists",
    "Lovejoy band project expanded beyond Minecraft audience into indie live shows",
  ],
  relatedSlugs: ["dream", "tommyinnit", "technoblade", "minecraft-movie-premiere"],
  relationships: {
    sameEra: ["dream", "tommyinnit", "technoblade"],
    relatedEvent: ["minecraft-movie-premiere"],
  },
  media: [
    // AI suggested — 2020 photo (CC BY 3.0). Human must verify.
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/0/0e/Wilbur_Soot_2020.jpg",
      title: "Wilbur Soot in 2020",
      source: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Wilbur_Soot_2020.jpg",
      platform: "wikimedia",
      attribution: "Nihachu (CC BY 3.0)",
      license: "CC BY 3.0",
      description: "Wilbur Soot, 2020.",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Wilbur_Soot",
      title: "Wilbur Soot — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Wilbur_Soot",
      platform: "other",
      attribution: "Wikipedia contributors",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Wilbur Soot — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Wilbur_Soot",
      domain: "en.wikipedia.org",
    },
    {
      title: "Wilbur Soot — YouTube",
      url: "https://www.youtube.com/@WilburSoot",
      domain: "youtube.com",
    },
  ],
};

export default entry;
