import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr20",
  slug: "xqc",
  title: "xQc",
  category: "creator",
  personType: "Creator",
  description:
    "French-Canadian streamer Félix Lengyel — former Overwatch League pro who became one of Twitch's most-watched creators, known for high-energy variety content, controversy, and a $100M Kick deal.",
  imageGradient: "from-blue-600 via-violet-500 to-purple-600",
  scores: { relevance: 33, influence: 86, cringe: 40, brainrot: 51 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 33,
    currentStatus: "classic",
    activePlatforms: [
      "twitch",
    ],
    popularity: 16,
    trendingScore: 16,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=16 (Google News: 1 items in last 60d (40 returned) for “xQc creator”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “xQc creator”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “xQc”",
      "[news/recent-articles] Google News: 1 items in last 60d (40 returned) for “xQc creator”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “xQc creator”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"xQc creator\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "Weak corroboration — blended heuristic (25) with AI double-check (40): Strong historical authority signals but low recent news, platform activity, and trend data indicate moderate, not peak, current popularity.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=16 (Google News: 1 items in last 60d (40 returned) for “xQc creator”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-17",
  lastUpdated: "2026-08-16",
  views: 2600000,
  trendDirection: "declining",
  tags: ["streaming", "twitch", "kick", "overwatch", "variety", "gambling", "french-canadian"],
  careerStart: "2014",
  platforms: [
    { platform: "twitch", handle: "xQc", url: "https://www.twitch.tv/xqc" },
    { platform: "youtube", handle: "xQcOW", url: "https://www.youtube.com/@xQcOW" },
  ],
  followers: {
    twitch: "~12M+",
    youtube: "~2M+",
  },
  notableMoments: [
    "Played as a tank main for Dallas Fuel and other teams in the Overwatch League (2018–2019)",
    "Multiple Twitch bans for controversial content — became one of the platform's most controversial figures",
    "Broke multiple Twitch concurrent viewership records",
    "Gambling streams controversy (2022) — promoted online gambling to millions of viewers, leading to industry-wide debate",
    "Signed a reported $70M–$100M deal with Kick streaming platform (2023), then returned to Twitch",
    "Livestreamed watching entire series and movies in 24-hour+ marathon sessions",
  ],
  relatedSlugs: ["ishowspeed", "caseoh"],
  media: [
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/d/d7/XQc_July_4_2023.jpg",
      title: "xQc — July 4, 2023",
      source: "Wikimedia Commons / Esfand (CC BY 3.0)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:XQc_July_4_2023.jpg",
      platform: "wikimedia",
      attribution: "Esfand (CC BY 3.0)",
      license: "CC BY 3.0",
      description: "xQc (Félix Lengyel) photographed on July 4, 2023.",
      date: "2023-07-04",
      verified: true,
    },
    // ── REFERENCE ──────────────────────────────────────────────────────────────
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/XQc",
      title: "xQc — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/XQc",
      platform: "wikimedia",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      description: "Wikipedia article covering xQc's streaming career, controversies, and cultural impact.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "xQc — Twitch",
      url: "https://www.twitch.tv/xqc",
      domain: "twitch.tv",
    },
    {
      title: "xQc — Wikipedia",
      url: "https://en.wikipedia.org/wiki/XQc",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
