import type { CreatorEntry } from "@/types";

const entry: CreatorEntry = {
  id: "cr22",
  slug: "zach-king",
  title: "Zach King",
  category: "creator",
  personType: "Creator",
  description:
    "Digital illusionist and filmmaker Zach King pioneered 'magic video' content — short clips with seamless, impossible edits that made ordinary objects transform in ways that defied reality.",
  imageGradient: "from-purple-500 via-violet-500 to-indigo-500",
  scores: { relevance: 80, influence: 86, cringe: 20, brainrot: 45 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 80,
    currentStatus: "current",
    activePlatforms: [
      "tiktok",
      "youtube",
      "wikipedia",
      "news",
    ],
    popularity: 63,
    trendingScore: 56,
    recentRevival: false,
    popularityNotes: "Relevance: Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=63 (Google News: 15 items in last 60d (40 returned) for “Zach King”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Character signals still mark this as strongly representative of chaotic internet brainrot culture. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=8,425 for “Zach King”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=1965 prev7=2042 (-4%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Zach”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-06-28",
      "[news/recent-articles] Google News: 15 items in last 60d (40 returned) for “Zach King”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Zach King”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Zach King\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/gen-cohort-adoption] Cohort cue from tags/title (brainrot character only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=63 (Google News: 15 items in last 60d (40 returned) for “Zach King”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Character signals still mark this as strongly representative of chaotic internet brainrot culture.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-17",
  lastUpdated: "2026-08-16",
  views: 1700000,
  trendDirection: "stable",
  tags: ["magic", "illusion", "vine", "tiktok", "youtube", "filmmaking"],
  careerStart: "2008",
  platforms: [
    { platform: "tiktok", handle: "@zachking", url: "https://www.tiktok.com/@zachking" },
    { platform: "youtube", handle: "Zach King", url: "https://www.youtube.com/@ZachKing" },
  ],
  followers: {
    tiktok: "~82M+",
    youtube: "~4M+",
  },
  notableMoments: [
    "Started creating film editing tricks on YouTube in 2008 under the channel 'FinalCutKing'",
    "Vine made him famous — 'magic vines' compiled millions of followers before Vine's shutdown",
    "Flying Broomstick TikTok (2020) — became TikTok's most viewed video with 2.2B views",
    "Appeared on The Amazing Race Season 27 (2015) with Kelsey Gerber",
    "Winner of Shorty Award for Best Viner (2015)",
    "Content consistently family-friendly and technically impressive — broad demographic appeal",
  ],
  relatedSlugs: ["khaby-lame", "bella-poarch", "charli-damelio", "mrbeast"],
  media: [
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/f/f3/Zach_King_Photo.jpg",
      title: "Zach King — official photo",
      source: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Zach_King_Photo.jpg",
      platform: "wikimedia",
      attribution: "Wikimedia Commons contributors",
      license: "CC BY-SA 4.0",
      description: "Zach King, digital illusionist and short-form video pioneer.",
      date: "2022",
      verified: true,
    },
    // ── REFERENCE ──────────────────────────────────────────────────────────────
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Zach_King",
      title: "Zach King — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Zach_King",
      platform: "wikimedia",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      description: "Wikipedia article covering Zach King's magic-video content and career.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Zach King — YouTube",
      url: "https://www.youtube.com/@ZachKing",
      domain: "youtube.com",
    },
    {
      title: "Zach King — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Zach_King",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
