/**
 * Internet Culture Hub — content expansion roadmap (planning data only).
 *
 * ~100 curated missing/planned entries organized by era + category.
 * Does not create articles. No UI / DB / API.
 *
 * Docs: docs/CONTENT_EXPANSION_ROADMAP.md
 */

import type { CulturalEra } from "@/types";
import type { CulturalClusterId } from "./clusters";
import type {
  ContentGapCategory,
  ContentGapEntry,
  ContentGapImportance,
  RoadmapEraId,
  RoadmapPriority,
} from "./contentGapTypes";

export type { RoadmapEraId, RoadmapPriority } from "./contentGapTypes";

export const ROADMAP_ERA_META: Record<
  RoadmapEraId,
  { label: string; years: string; culturalEras: CulturalEra[] }
> = {
  "early-internet": {
    label: "Early internet",
    years: "1990s–2005",
    culturalEras: ["pre-internet", "early-web"],
  },
  "web-2": {
    label: "Web 2.0",
    years: "2005–2015",
    culturalEras: ["web-2"],
  },
  "social-media": {
    label: "Social media era",
    years: "2015–2020",
    culturalEras: ["social"],
  },
  "tiktok-modern": {
    label: "TikTok / modern era",
    years: "2020–present",
    culturalEras: ["short-form", "gen-alpha"],
  },
};

export interface RoadmapEntry extends ContentGapEntry {
  roadmapEra: RoadmapEraId;
  /** Suggested build priority (1 = highest urgency). */
  priority: RoadmapPriority;
}

type RoadmapSeed = {
  id: string;
  name: string;
  suggestedSlug: string;
  category: ContentGapCategory;
  importance: ContentGapImportance;
  priority: RoadmapPriority;
  roadmapEra: RoadmapEraId;
  reason: string;
  relatedTopics: string[];
  clusters?: CulturalClusterId[];
  status?: ContentGapEntry["status"];
  satisfiedBy?: string[];
  matchHints?: string[];
  notes?: string;
};

function eraFor(roadmapEra: RoadmapEraId): CulturalEra | CulturalEra[] {
  const eras = ROADMAP_ERA_META[roadmapEra].culturalEras;
  return eras.length === 1 ? eras[0]! : eras;
}

function seed(row: RoadmapSeed): RoadmapEntry {
  return {
    id: row.id,
    name: row.name,
    suggestedSlug: row.suggestedSlug,
    category: row.category,
    importance: row.importance,
    priority: row.priority,
    roadmapEra: row.roadmapEra,
    culturalEra: eraFor(row.roadmapEra),
    relatedTopics: row.relatedTopics,
    clusters: row.clusters,
    status: row.status ?? "planned",
    reason: row.reason,
    satisfiedBy: row.satisfiedBy ?? [],
    matchHints: row.matchHints ?? [row.name.toLowerCase()],
    notes: row.notes,
  };
}

/**
 * Initial content expansion roadmap (~100 planned entries).
 * Prefer priority 1 + importance high when choosing what to write next.
 */
export const CONTENT_EXPANSION_ROADMAP: readonly RoadmapEntry[] = [
  // ── Early internet (1990s–2005) ───────────────────────────────────────────
  seed({
    id: "gap-copypasta",
    name: "Copypasta",
    suggestedSlug: "copypasta",
    category: "meme",
    importance: "high",
    priority: 1,
    roadmapEra: "early-internet",
    reason: "Foundational copy-and-paste humor format still used across platforms.",
    relatedTopics: ["4chan", "greentext", "rickroll"],
    clusters: ["classic-internet"],
    status: "missing",
  }),
  seed({
    id: "gap-greentext",
    name: "Greentext",
    suggestedSlug: "greentext",
    category: "meme",
    importance: "high",
    priority: 1,
    roadmapEra: "early-internet",
    reason: "Core imageboard storytelling grammar; high search and history demand.",
    relatedTopics: ["4chan", "copypasta"],
    clusters: ["classic-internet"],
    status: "missing",
  }),
  seed({
    id: "gap-rule-34",
    name: "Rule 34",
    suggestedSlug: "rule-34",
    category: "meme",
    importance: "medium",
    priority: 2,
    roadmapEra: "early-internet",
    reason: "Early-web “rules of the internet” entry with lasting cultural references.",
    relatedTopics: ["4chan"],
    clusters: ["classic-internet"],
    notes: "Encyclopedia tone only; no NSFW media.",
  }),
  seed({
    id: "gap-godwins-law",
    name: "Godwin's Law",
    suggestedSlug: "godwins-law",
    category: "meme",
    importance: "high",
    priority: 1,
    roadmapEra: "early-internet",
    reason: "Classic Usenet/forum adage that still structures online argument culture.",
    relatedTopics: ["4chan", "reddit-culture"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-lolcats",
    name: "LOLcats",
    suggestedSlug: "lolcats",
    category: "meme",
    importance: "high",
    priority: 1,
    roadmapEra: "early-internet",
    reason: "Bridge from early image macros to mainstream meme literacy (I Can Has Cheezburger).",
    relatedTopics: ["ceiling-cat", "longcat", "doge"],
    clusters: ["animal-memes", "classic-internet"],
  }),
  seed({
    id: "gap-ytmnd",
    name: "YTMND",
    suggestedSlug: "ytmnd",
    category: "meme",
    importance: "medium",
    priority: 2,
    roadmapEra: "early-internet",
    reason: "You’re the Man Now Dog — early user-generated sound+image site culture.",
    relatedTopics: ["all-your-base-are-belong-to-us", "newgrounds"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-homestar-runner",
    name: "Homestar Runner",
    suggestedSlug: "homestar-runner",
    category: "meme",
    importance: "high",
    priority: 1,
    roadmapEra: "early-internet",
    reason: "Flash-era web cartoon empire; Strong Bad email shaped early web humor.",
    relatedTopics: ["newgrounds", "badger-badger-badger"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-dancing-baby",
    name: "Dancing Baby",
    suggestedSlug: "dancing-baby",
    category: "meme",
    importance: "medium",
    priority: 2,
    roadmapEra: "early-internet",
    reason: "Proto-viral 1990s clip that previewed shareable web video culture.",
    relatedTopics: ["hamster-dance", "numa-numa"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-leet-speak",
    name: "Leet speak (1337)",
    suggestedSlug: "leet-speak",
    category: "slang",
    importance: "high",
    priority: 1,
    roadmapEra: "early-internet",
    reason: "Foundational hacker/gamer orthography that still appears in internet irony.",
    relatedTopics: ["noob", "pwned", "gg"],
    clusters: ["gaming-culture", "classic-internet"],
  }),
  seed({
    id: "gap-lurk-moar",
    name: "Lurk moar",
    suggestedSlug: "lurk-moar",
    category: "slang",
    importance: "low",
    priority: 3,
    roadmapEra: "early-internet",
    reason: "Imageboard etiquette slang: read before posting.",
    relatedTopics: ["4chan", "greentext"],
    clusters: ["classic-internet"],
    status: "missing",
  }),
  seed({
    id: "gap-pwned",
    name: "Pwned",
    suggestedSlug: "pwned",
    category: "slang",
    importance: "medium",
    priority: 2,
    roadmapEra: "early-internet",
    reason: "Classic gaming/hacker misspelling of “owned”; still used in breach discourse.",
    relatedTopics: ["leet-speak", "noob", "ez"],
    clusters: ["gaming-culture"],
  }),
  seed({
    id: "gap-afk",
    name: "AFK",
    suggestedSlug: "afk",
    category: "slang",
    importance: "medium",
    priority: 2,
    roadmapEra: "early-internet",
    reason: "Universal chat shorthand (away from keyboard) from IRC/gaming into mainstream.",
    relatedTopics: ["gg", "noob", "lag"],
    clusters: ["gaming-culture"],
  }),
  seed({
    id: "gap-tl-dr",
    name: "TL;DR",
    suggestedSlug: "tl-dr",
    category: "slang",
    importance: "high",
    priority: 1,
    roadmapEra: "early-internet",
    reason: "Forum summary culture that became default internet reading etiquette.",
    relatedTopics: ["reddit-culture", "copypasta"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-geocities",
    name: "GeoCities",
    suggestedSlug: "geocities",
    category: "platform",
    importance: "high",
    priority: 1,
    roadmapEra: "early-internet",
    reason: "Homestead web aesthetics and amateur homepage culture before social feeds.",
    relatedTopics: ["myspace", "newgrounds"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-aim-culture",
    name: "AOL Instant Messenger (AIM)",
    suggestedSlug: "aim-culture",
    category: "platform",
    importance: "high",
    priority: 1,
    roadmapEra: "early-internet",
    reason: "Chat profiles, away messages, and buddy-list social life for a generation.",
    relatedTopics: ["myspace", "geocities"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-livejournal",
    name: "LiveJournal",
    suggestedSlug: "livejournal",
    category: "platform",
    importance: "medium",
    priority: 2,
    roadmapEra: "early-internet",
    reason: "Early blogging + fandom community platform that shaped later Tumblr habits.",
    relatedTopics: ["tumblr", "stan-culture"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-usenet",
    name: "Usenet",
    suggestedSlug: "usenet",
    category: "platform",
    importance: "high",
    priority: 1,
    roadmapEra: "early-internet",
    reason: "Pre-web discussion network; origin soil for flamewars, FAQs, and Godwin’s Law.",
    relatedTopics: ["godwins-law", "4chan"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-irc-culture",
    name: "IRC culture",
    suggestedSlug: "irc-culture",
    category: "platform",
    importance: "medium",
    priority: 2,
    roadmapEra: "early-internet",
    reason: "Realtime chat channels that trained later Discord/Twitch community norms.",
    relatedTopics: ["discord-culture", "afk"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-something-awful",
    name: "Something Awful",
    suggestedSlug: "something-awful",
    category: "community",
    importance: "high",
    priority: 1,
    roadmapEra: "early-internet",
    reason: "FYAD/goon culture incubator for many web 2.0 meme formats and creators.",
    relatedTopics: ["rage-comics", "4chan", "homestar-runner"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-anonymous-collective",
    name: "Anonymous (collective)",
    suggestedSlug: "anonymous-collective",
    category: "community",
    importance: "high",
    priority: 1,
    roadmapEra: "early-internet",
    reason: "Imageboard-born collective identity with major political/internet-history impact.",
    relatedTopics: ["4chan", "greentext"],
    clusters: ["classic-internet"],
    notes: "Treat carefully; focus on cultural history, not operational detail.",
  }),
  seed({
    id: "gap-fark",
    name: "Fark",
    suggestedSlug: "fark",
    category: "community",
    importance: "low",
    priority: 3,
    roadmapEra: "early-internet",
    reason: "Early link-aggregation community with distinctive comment culture.",
    relatedTopics: ["reddit-culture", "something-awful"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-strong-bad",
    name: "Strong Bad",
    suggestedSlug: "strong-bad",
    category: "creator",
    importance: "medium",
    priority: 2,
    roadmapEra: "early-internet",
    reason: "Homestar Runner’s breakout character; emblem of Flash-era web celebrity.",
    relatedTopics: ["homestar-runner", "newgrounds"],
    clusters: ["classic-internet", "creator-economy"],
  }),
  seed({
    id: "gap-napster-era",
    name: "Napster era",
    suggestedSlug: "napster-era",
    category: "event",
    importance: "medium",
    priority: 2,
    roadmapEra: "early-internet",
    reason: "File-sharing flashpoint that reshaped digital music and online piracy discourse.",
    relatedTopics: ["myspace", "youtube-creator-era"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-flash-animation-era",
    name: "Flash animation era",
    suggestedSlug: "flash-animation-era",
    category: "event",
    importance: "high",
    priority: 1,
    roadmapEra: "early-internet",
    reason: "Newgrounds/Homestar/YTMND creative boom before Flash’s end-of-life.",
    relatedTopics: ["newgrounds", "homestar-runner", "ytmnd"],
    clusters: ["classic-internet"],
  }),

  // ── Web 2.0 (2005–2015) ───────────────────────────────────────────────────
  seed({
    id: "gap-advice-animals",
    name: "Advice Animals",
    suggestedSlug: "advice-animals",
    category: "meme",
    importance: "high",
    priority: 1,
    roadmapEra: "web-2",
    reason: "Meta format family for classic image macros (Wonka, Penguin, Brian, etc.).",
    relatedTopics: ["bad-luck-brian", "success-kid", "philosoraptor"],
    clusters: ["classic-internet", "animal-memes"],
  }),
  seed({
    id: "gap-scumbag-steve",
    name: "Scumbag Steve",
    suggestedSlug: "scumbag-steve",
    category: "meme",
    importance: "medium",
    priority: 2,
    roadmapEra: "web-2",
    reason: "Defining advice-animal antihero of Reddit’s early meme boom.",
    relatedTopics: ["advice-animals", "reddit-culture"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-forever-alone",
    name: "Forever Alone",
    suggestedSlug: "forever-alone",
    category: "meme",
    importance: "medium",
    priority: 2,
    roadmapEra: "web-2",
    reason: "Rage-comic emotion face that became a standalone loneliness meme.",
    relatedTopics: ["rage-comics", "trollface"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-condescending-wonka",
    name: "Condescending Wonka",
    suggestedSlug: "condescending-wonka",
    category: "meme",
    importance: "medium",
    priority: 2,
    roadmapEra: "web-2",
    reason: "Sarcasm image macro staple of Web 2.0 caption culture.",
    relatedTopics: ["advice-animals", "one-does-not-simply"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-ancient-aliens",
    name: "Ancient Aliens guy",
    suggestedSlug: "ancient-aliens",
    category: "meme",
    importance: "medium",
    priority: 2,
    roadmapEra: "web-2",
    reason: "Giorgio Tsoukalos reaction macro; History Channel → meme pipeline.",
    relatedTopics: ["expanding-brain", "philosoraptor"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-ermahgerd",
    name: "Ermahgerd",
    suggestedSlug: "ermahgerd",
    category: "meme",
    importance: "medium",
    priority: 2,
    roadmapEra: "web-2",
    reason: "Phonetic caption meme that defined early-2010s Tumblr/Reddit humor.",
    relatedTopics: ["tumblr", "advice-animals"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-first-world-problems",
    name: "First World Problems",
    suggestedSlug: "first-world-problems",
    category: "meme",
    importance: "medium",
    priority: 2,
    roadmapEra: "web-2",
    reason: "Advice-animal / hashtag format for privileged complaints.",
    relatedTopics: ["advice-animals", "success-kid"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-socially-awkward-penguin",
    name: "Socially Awkward Penguin",
    suggestedSlug: "socially-awkward-penguin",
    category: "meme",
    importance: "medium",
    priority: 2,
    roadmapEra: "web-2",
    reason: "Iconic awkward-social-situation advice animal.",
    relatedTopics: ["advice-animals", "forever-alone"],
    clusters: ["animal-memes", "classic-internet"],
  }),
  seed({
    id: "gap-chocolate-rain",
    name: "Chocolate Rain",
    suggestedSlug: "chocolate-rain",
    category: "meme",
    importance: "medium",
    priority: 2,
    roadmapEra: "web-2",
    reason: "Early YouTube viral song meme; Tay Zonday as proto-creator celebrity.",
    relatedTopics: ["numa-numa", "youtube-creator-era"],
    clusters: ["youtube-culture", "classic-internet"],
  }),
  seed({
    id: "gap-yolo",
    name: "YOLO",
    suggestedSlug: "yolo",
    category: "slang",
    importance: "high",
    priority: 1,
    roadmapEra: "web-2",
    reason: "Peak early-2010s catchphrase; Drake + teen Twitter era marker.",
    relatedTopics: ["fomo", "drake-hotline-bling"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-on-fleek",
    name: "On fleek",
    suggestedSlug: "on-fleek",
    category: "slang",
    importance: "medium",
    priority: 2,
    roadmapEra: "web-2",
    reason: "Vine-era slang breakthrough into mainstream advertising language.",
    relatedTopics: ["vine-culture", "slay"],
    clusters: ["tiktok-culture"],
  }),
  seed({
    id: "gap-bae",
    name: "Bae",
    suggestedSlug: "bae",
    category: "slang",
    importance: "medium",
    priority: 2,
    roadmapEra: "web-2",
    reason: "Mid-2010s affectionate slang that flooded brand social accounts.",
    relatedTopics: ["on-fleek", "yolo"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-basic",
    name: "Basic",
    suggestedSlug: "basic",
    category: "slang",
    importance: "medium",
    priority: 2,
    roadmapEra: "web-2",
    reason: "Taste/class judgment slang central to Tumblr and Twitter discourse.",
    relatedTopics: ["cringe", "stan-culture"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-smh",
    name: "SMH",
    suggestedSlug: "smh",
    category: "slang",
    importance: "low",
    priority: 3,
    roadmapEra: "web-2",
    reason: "Ubiquitous disapproval acronym from forums/Twitter into everyday chat.",
    relatedTopics: ["tl-dr", "ratio"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-facebook-culture",
    name: "Facebook / Meta culture",
    suggestedSlug: "facebook-culture",
    category: "platform",
    importance: "high",
    priority: 1,
    roadmapEra: "web-2",
    reason: "Dominant social graph of the Web 2.0 decade; memes, groups, and news feed politics.",
    relatedTopics: ["myspace", "instagram-culture"],
    clusters: ["classic-internet"],
    status: "missing",
  }),
  seed({
    id: "gap-twitter-culture",
    name: "Twitter / X culture",
    suggestedSlug: "twitter-culture",
    category: "platform",
    importance: "high",
    priority: 1,
    roadmapEra: "web-2",
    reason: "Ratio, quote-tweet wars, and real-time discourse platform grammar.",
    relatedTopics: ["twitter-x-transition", "ratio", "brand-social-media-wars"],
    clusters: ["classic-internet"],
    satisfiedBy: ["twitter-x-transition", "ratio"],
  }),
  seed({
    id: "gap-vine-culture",
    name: "Vine (platform culture)",
    suggestedSlug: "vine-culture",
    category: "platform",
    importance: "high",
    priority: 1,
    roadmapEra: "web-2",
    reason: "Six-second comedy grammar that trained the short-form generation.",
    relatedTopics: ["vine-shutdown", "tiktok-rise", "short-form-takeover"],
    clusters: ["tiktok-culture", "classic-internet"],
    satisfiedBy: ["vine-shutdown"],
  }),
  seed({
    id: "gap-digg",
    name: "Digg",
    suggestedSlug: "digg",
    category: "platform",
    importance: "medium",
    priority: 2,
    roadmapEra: "web-2",
    reason: "Link-ranking giant whose v4 collapse accelerated Reddit’s rise.",
    relatedTopics: ["reddit-culture", "fark"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-google-plus",
    name: "Google+",
    suggestedSlug: "google-plus",
    category: "platform",
    importance: "low",
    priority: 3,
    roadmapEra: "web-2",
    reason: "Failed major social network; useful contrast case in platform history.",
    relatedTopics: ["facebook-culture", "youtube-creator-era"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-jenna-marbles",
    name: "Jenna Marbles",
    suggestedSlug: "jenna-marbles",
    category: "creator",
    importance: "high",
    priority: 1,
    roadmapEra: "web-2",
    reason: "Defining early YouTube comedy creator; shaped personality-vlog norms.",
    relatedTopics: ["youtube-creator-era", "pewdiepie"],
    clusters: ["youtube-culture", "creator-economy"],
  }),
  seed({
    id: "gap-filthy-frank",
    name: "Filthy Frank",
    suggestedSlug: "filthy-frank",
    category: "creator",
    importance: "high",
    priority: 1,
    roadmapEra: "web-2",
    reason: "Absurdist YouTube character era that later collided with Joji’s music fame.",
    relatedTopics: ["youtube-creator-era", "brainrot"],
    clusters: ["youtube-culture"],
    notes: "Separate persona history from later music career carefully.",
  }),
  seed({
    id: "gap-smosh",
    name: "Smosh",
    suggestedSlug: "smosh",
    category: "creator",
    importance: "medium",
    priority: 2,
    roadmapEra: "web-2",
    reason: "Long-running sketch channel central to early YouTube comedy brands.",
    relatedTopics: ["youtube-creator-era", "fred"],
    clusters: ["youtube-culture", "creator-economy"],
  }),
  seed({
    id: "gap-kony-2012",
    name: "Kony 2012",
    suggestedSlug: "kony-2012",
    category: "event",
    importance: "medium",
    priority: 2,
    roadmapEra: "web-2",
    reason: "Viral activism case study — shareability vs. oversimplification backlash.",
    relatedTopics: ["ice-bucket-challenge", "facebook-culture"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-digg-v4-exodus",
    name: "Digg v4 exodus",
    suggestedSlug: "digg-v4-exodus",
    category: "event",
    importance: "medium",
    priority: 2,
    roadmapEra: "web-2",
    reason: "Platform redesign revolt that redistributed attention to Reddit.",
    relatedTopics: ["digg", "reddit-culture"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-encyclopedia-dramatica",
    name: "Encyclopedia Dramatica",
    suggestedSlug: "encyclopedia-dramatica",
    category: "community",
    importance: "medium",
    priority: 2,
    roadmapEra: "web-2",
    reason: "Satirical wiki documenting internet drama; influential and contested archive.",
    relatedTopics: ["something-awful", "4chan"],
    clusters: ["classic-internet"],
    notes: "Editorial caution: insult comedy archive; summarize culturally, don’t amplify harm.",
  }),
  seed({
    id: "gap-tumblr-fandom",
    name: "Tumblr fandom culture",
    suggestedSlug: "tumblr-fandom",
    category: "community",
    importance: "high",
    priority: 1,
    roadmapEra: "web-2",
    reason: "Reblog/fandom machine that invented much modern stan and aesthetic language.",
    relatedTopics: ["tumblr", "stan-culture", "delulu"],
    clusters: ["classic-internet"],
  }),

  // ── Social media era (2015–2020) ──────────────────────────────────────────
  seed({
    id: "gap-deep-fried-memes",
    name: "Deep-fried memes",
    suggestedSlug: "deep-fried-memes",
    category: "meme",
    importance: "medium",
    priority: 2,
    roadmapEra: "social-media",
    reason: "Compression/irony aesthetic adjacent to distorted meme face.",
    relatedTopics: ["distorted-meme-face", "loss"],
    clusters: ["classic-internet"],
    satisfiedBy: ["distorted-meme-face"],
  }),
  seed({
    id: "gap-ugandan-knuckles",
    name: "Ugandan Knuckles",
    suggestedSlug: "ugandan-knuckles",
    category: "meme",
    importance: "medium",
    priority: 2,
    roadmapEra: "social-media",
    reason: "VRChat swarm meme; late-2010s absurdist multiplayer humor.",
    relatedTopics: ["among-us-era", "discord-culture"],
    clusters: ["gaming-culture"],
  }),
  seed({
    id: "gap-big-chungus",
    name: "Big Chungus",
    suggestedSlug: "big-chungus",
    category: "meme",
    importance: "medium",
    priority: 2,
    roadmapEra: "social-media",
    reason: "Ironic fat Bugs Bunny meme; Reddit/iFunny late-2010s staple.",
    relatedTopics: ["reddit-culture", "deep-fried-memes"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-absolute-unit",
    name: "Absolute Unit",
    suggestedSlug: "absolute-unit",
    category: "meme",
    importance: "low",
    priority: 3,
    roadmapEra: "social-media",
    reason: "British Twitter caption format for oversized subjects.",
    relatedTopics: ["twitter-culture", "they-did-surgery-on-a-grape"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-ok-boomer",
    name: "OK Boomer",
    suggestedSlug: "ok-boomer",
    category: "meme",
    importance: "high",
    priority: 1,
    roadmapEra: "social-media",
    reason: "Generational clapback phrase that crossed into news and advertising.",
    relatedTopics: ["tiktok-rise", "cringe"],
    clusters: ["tiktok-culture"],
  }),
  seed({
    id: "gap-wholesome-memes",
    name: "Wholesome memes",
    suggestedSlug: "wholesome-memes",
    category: "meme",
    importance: "medium",
    priority: 2,
    roadmapEra: "social-media",
    reason: "Counter-ironic kindness meme lane after mid-2010s edginess fatigue.",
    relatedTopics: ["reddit-culture", "this-is-fine"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-bone-hurting-juice",
    name: "Bone Hurting Juice",
    suggestedSlug: "bone-hurting-juice",
    category: "meme",
    importance: "low",
    priority: 3,
    roadmapEra: "social-media",
    reason: "Anti-caption / surreal edit community format.",
    relatedTopics: ["surreal-memes", "loss"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-surreal-memes",
    name: "Surreal memes",
    suggestedSlug: "surreal-memes",
    category: "meme",
    importance: "medium",
    priority: 2,
    roadmapEra: "social-media",
    reason: "Post-ironic absurdism wave (2016–2019) between deep-fried and brainrot.",
    relatedTopics: ["deep-fried-memes", "brainrot"],
    clusters: ["classic-internet", "brainrot-culture"],
  }),
  seed({
    id: "gap-they-did-surgery-on-a-grape",
    name: "They Did Surgery On A Grape",
    suggestedSlug: "they-did-surgery-on-a-grape",
    category: "meme",
    importance: "low",
    priority: 3,
    roadmapEra: "social-media",
    reason: "Bizarre Facebook comment screenshot that became late-2010s absurdist catchphrase.",
    relatedTopics: ["facebook-culture", "surreal-memes"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-stan",
    name: "Stan",
    suggestedSlug: "stan",
    category: "slang",
    importance: "high",
    priority: 1,
    roadmapEra: "social-media",
    reason: "Eminem → fandom verb; root word for stan culture.",
    relatedTopics: ["stan-culture", "delulu", "slay"],
    clusters: ["tiktok-culture"],
  }),
  seed({
    id: "gap-vibe-check",
    name: "Vibe check",
    suggestedSlug: "vibe-check",
    category: "slang",
    importance: "medium",
    priority: 2,
    roadmapEra: "social-media",
    reason: "Late-2010s mood-assessment slang across Twitter and TikTok.",
    relatedTopics: ["its-giving", "main-character-energy"],
    clusters: ["tiktok-culture"],
  }),
  seed({
    id: "gap-hits-different",
    name: "Hits different",
    suggestedSlug: "hits-different",
    category: "slang",
    importance: "low",
    priority: 3,
    roadmapEra: "social-media",
    reason: "Emotional-intensity slang that spread from Black Twitter into mainstream feeds.",
    relatedTopics: ["vibe-check", "its-giving"],
    clusters: ["tiktok-culture"],
  }),
  seed({
    id: "gap-vsco-girl",
    name: "VSCO girl",
    suggestedSlug: "vsco-girl",
    category: "slang",
    importance: "medium",
    priority: 2,
    roadmapEra: "social-media",
    reason: "2019 aesthetic stereotype (scrunchies, Hydro Flask) as slang + trend label.",
    relatedTopics: ["instagram-culture", "e-girl"],
    clusters: ["tiktok-culture"],
  }),
  seed({
    id: "gap-twitch-culture",
    name: "Twitch culture",
    suggestedSlug: "twitch-culture",
    category: "platform",
    importance: "high",
    priority: 1,
    roadmapEra: "social-media",
    reason: "Live chat grammar, emotes, raids, and parasocial stream norms.",
    relatedTopics: ["streamer-culture", "xqc", "pokimane", "discord-culture"],
    clusters: ["streaming-culture", "gaming-culture"],
    satisfiedBy: ["streamer-culture"],
  }),
  seed({
    id: "gap-pewdiepie-tseries",
    name: "PewDiePie vs T-Series",
    suggestedSlug: "pewdiepie-vs-t-series",
    category: "event",
    importance: "high",
    priority: 1,
    roadmapEra: "social-media",
    reason: "Subscriber-war spectacle that mobilized YouTube fandom globally.",
    relatedTopics: ["pewdiepie", "youtube-creator-era", "youtube-rewind"],
    clusters: ["youtube-culture", "creator-economy"],
  }),
  seed({
    id: "gap-tide-pod-challenge",
    name: "Tide Pod Challenge",
    suggestedSlug: "tide-pod-challenge",
    category: "event",
    importance: "medium",
    priority: 2,
    roadmapEra: "social-media",
    reason: "Dangerous-challenge moral panic cycle; meme vs. real-harm coverage lesson.",
    relatedTopics: ["one-chip-challenge", "harambe"],
    clusters: ["classic-internet"],
    notes: "Do not glamorize harm; document media cycle and meme response.",
  }),
  seed({
    id: "gap-mannequin-challenge",
    name: "Mannequin Challenge",
    suggestedSlug: "mannequin-challenge",
    category: "event",
    importance: "medium",
    priority: 2,
    roadmapEra: "social-media",
    reason: "2016 freeze-frame challenge that jumped from Twitter/Vine into mainstream TV.",
    relatedTopics: ["ice-bucket-challenge", "vine-culture"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-cancel-culture",
    name: "Cancel culture",
    suggestedSlug: "cancel-culture",
    category: "community",
    importance: "high",
    priority: 1,
    roadmapEra: "social-media",
    reason: "Major accountability/callout discourse with huge search and news demand.",
    relatedTopics: ["brand-social-media-wars", "ratio", "stan-culture"],
    clusters: ["classic-internet"],
    status: "missing",
  }),
  seed({
    id: "gap-stan-culture",
    name: "Stan culture",
    suggestedSlug: "stan-culture",
    category: "community",
    importance: "high",
    priority: 1,
    roadmapEra: "social-media",
    reason: "Organized fandom intensity from Tumblr/Twitter into TikTok.",
    relatedTopics: ["stan", "delulu", "slay", "tumblr-fandom"],
    clusters: ["tiktok-culture"],
    status: "missing",
  }),
  seed({
    id: "gap-stan-twitter",
    name: "Stan Twitter",
    suggestedSlug: "stan-twitter",
    category: "community",
    importance: "high",
    priority: 1,
    roadmapEra: "social-media",
    reason: "Specific Twitter neighborhood for fandom wars, stan language, and charting discourse.",
    relatedTopics: ["stan-culture", "twitter-culture", "ratio"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-weird-twitter",
    name: "Weird Twitter",
    suggestedSlug: "weird-twitter",
    category: "community",
    importance: "medium",
    priority: 2,
    roadmapEra: "social-media",
    reason: "Absurdist comedy scene that influenced later alt meme accounts.",
    relatedTopics: ["twitter-culture", "surreal-memes"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-david-dobrik",
    name: "David Dobrik",
    suggestedSlug: "david-dobrik",
    category: "creator",
    importance: "medium",
    priority: 2,
    roadmapEra: "social-media",
    reason: "Vlog squad era of YouTube/Instagram friendship-content empires.",
    relatedTopics: ["youtube-creator-era", "influencer-culture"],
    clusters: ["youtube-culture", "creator-economy"],
  }),
  seed({
    id: "gap-emma-chamberlain",
    name: "Emma Chamberlain",
    suggestedSlug: "emma-chamberlain",
    category: "creator",
    importance: "medium",
    priority: 2,
    roadmapEra: "social-media",
    reason: "Relatable-vlog aesthetic shift that changed YouTube editing and tone.",
    relatedTopics: ["youtube-creator-era", "influencer-culture"],
    clusters: ["youtube-culture", "creator-economy"],
  }),

  // ── TikTok / modern era (2020–present) ────────────────────────────────────
  seed({
    id: "gap-e-girl",
    name: "E-girl / E-boy",
    suggestedSlug: "e-girl",
    category: "meme",
    importance: "medium",
    priority: 2,
    roadmapEra: "tiktok-modern",
    reason: "Aesthetic identity from Tumblr/Discord into TikTok mainstream fashion slang.",
    relatedTopics: ["vsco-girl", "tiktok-rise", "instagram-culture"],
    clusters: ["tiktok-culture"],
  }),
  seed({
    id: "gap-corecore",
    name: "Corecore",
    suggestedSlug: "corecore",
    category: "meme",
    importance: "medium",
    priority: 2,
    roadmapEra: "tiktok-modern",
    reason: "Anti-aesthetic edit genre reacting to endless -core trend labeling.",
    relatedTopics: ["cottagecore", "dark-academia", "brainrot"],
    clusters: ["tiktok-culture"],
  }),
  seed({
    id: "gap-grimace-shake",
    name: "Grimace Shake",
    suggestedSlug: "grimace-shake",
    category: "meme",
    importance: "medium",
    priority: 2,
    roadmapEra: "tiktok-modern",
    reason: "2023 McDonald’s promo → horror skit meme wave on TikTok.",
    relatedTopics: ["tiktok-rise", "barbenheimer"],
    clusters: ["tiktok-culture"],
  }),
  seed({
    id: "gap-sea-shanty-tiktok",
    name: "Sea Shanty TikTok",
    suggestedSlug: "sea-shanty-tiktok",
    category: "meme",
    importance: "low",
    priority: 3,
    roadmapEra: "tiktok-modern",
    reason: "Wellerman duet boom; early-pandemic collective singing moment.",
    relatedTopics: ["tiktok-rise", "short-form-takeover"],
    clusters: ["tiktok-culture"],
  }),
  seed({
    id: "gap-erm-what-the-sigma",
    name: "Erm what the sigma",
    suggestedSlug: "erm-what-the-sigma",
    category: "meme",
    importance: "medium",
    priority: 2,
    roadmapEra: "tiktok-modern",
    reason: "Gen Alpha brainrot catchphrase remixing sigma slang.",
    relatedTopics: ["sigma", "sigma-grindset", "brainrot", "skibidi-toilet"],
    clusters: ["brainrot-culture"],
  }),
  seed({
    id: "gap-ai-slop",
    name: "AI slop",
    suggestedSlug: "ai-slop",
    category: "slang",
    importance: "high",
    priority: 1,
    roadmapEra: "tiktok-modern",
    reason: "Key term for low-effort AI content flood; pairs with AI chatbot wars.",
    relatedTopics: ["ai-chatbot-wars", "brainrot"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-doomscrolling",
    name: "Doomscrolling",
    suggestedSlug: "doomscrolling",
    category: "slang",
    importance: "high",
    priority: 1,
    roadmapEra: "tiktok-modern",
    reason: "Pandemic-era word for compulsive negative news/feed consumption.",
    relatedTopics: ["touch-grass", "fomo", "tiktok-rise"],
    clusters: ["tiktok-culture"],
  }),
  seed({
    id: "gap-parasocial",
    name: "Parasocial",
    suggestedSlug: "parasocial",
    category: "slang",
    importance: "high",
    priority: 1,
    roadmapEra: "tiktok-modern",
    reason: "Mainstreamed academic term for one-sided fan–creator attachment.",
    relatedTopics: ["streamer-culture", "stan-culture", "influencer-culture"],
    clusters: ["creator-economy", "streaming-culture"],
  }),
  seed({
    id: "gap-situationship",
    name: "Situationship",
    suggestedSlug: "situationship",
    category: "slang",
    importance: "medium",
    priority: 2,
    roadmapEra: "tiktok-modern",
    reason: "Relationship-status slang amplified by TikTok advice culture.",
    relatedTopics: ["ick", "delulu", "main-character-energy"],
    clusters: ["tiktok-culture"],
  }),
  seed({
    id: "gap-understood-the-assignment-gap",
    name: "It's the ___ for me",
    suggestedSlug: "its-the-for-me",
    category: "slang",
    importance: "low",
    priority: 3,
    roadmapEra: "tiktok-modern",
    reason: "Black Twitter/TikTok observation format still widely reused.",
    relatedTopics: ["its-giving", "understood-the-assignment"],
    clusters: ["tiktok-culture"],
  }),
  seed({
    id: "gap-youtube-shorts-culture",
    name: "YouTube Shorts culture",
    suggestedSlug: "youtube-shorts-culture",
    category: "platform",
    importance: "high",
    priority: 1,
    roadmapEra: "tiktok-modern",
    reason: "YouTube’s short-form counter to TikTok; reshaped creator incentives.",
    relatedTopics: ["tiktok-rise", "short-form-takeover", "youtube-creator-era"],
    clusters: ["youtube-culture", "tiktok-culture"],
  }),
  seed({
    id: "gap-bluesky-culture",
    name: "Bluesky culture",
    suggestedSlug: "bluesky-culture",
    category: "platform",
    importance: "medium",
    priority: 2,
    roadmapEra: "tiktok-modern",
    reason: "Post-Twitter migration hub with emerging norms and meme scenes.",
    relatedTopics: ["twitter-x-transition", "threads-launch"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-kick-streaming",
    name: "Kick (streaming platform)",
    suggestedSlug: "kick-streaming",
    category: "platform",
    importance: "medium",
    priority: 2,
    roadmapEra: "tiktok-modern",
    reason: "Twitch rival platform central to 2020s streaming drama and deals.",
    relatedTopics: ["twitch-culture", "streamer-culture", "adin-ross", "xqc"],
    clusters: ["streaming-culture"],
  }),
  seed({
    id: "gap-vtuber-culture",
    name: "VTuber culture",
    suggestedSlug: "vtuber-culture",
    category: "platform",
    importance: "high",
    priority: 1,
    roadmapEra: "tiktok-modern",
    reason: "Avatar streaming model with huge global fandom and meme production.",
    relatedTopics: ["streamer-culture", "twitch-culture"],
    clusters: ["streaming-culture", "creator-economy"],
  }),
  seed({
    id: "gap-capcut-culture",
    name: "CapCut culture",
    suggestedSlug: "capcut-culture",
    category: "platform",
    importance: "medium",
    priority: 2,
    roadmapEra: "tiktok-modern",
    reason: "Editing app that standardized TikTok transitions and template memes.",
    relatedTopics: ["tiktok-rise", "short-form-takeover"],
    clusters: ["tiktok-culture"],
  }),
  seed({
    id: "gap-booktok",
    name: "BookTok",
    suggestedSlug: "booktok",
    category: "community",
    importance: "high",
    priority: 1,
    roadmapEra: "tiktok-modern",
    reason: "TikTok reading community with real publishing-industry impact.",
    relatedTopics: ["tiktok-rise", "stan-culture"],
    clusters: ["tiktok-culture"],
  }),
  seed({
    id: "gap-true-crime-tiktok",
    name: "True crime TikTok",
    suggestedSlug: "true-crime-tiktok",
    category: "community",
    importance: "medium",
    priority: 2,
    roadmapEra: "tiktok-modern",
    reason: "Storytime crime community with ethics debates and massive reach.",
    relatedTopics: ["tiktok-rise", "parasocial"],
    clusters: ["tiktok-culture"],
  }),
  seed({
    id: "gap-aita",
    name: "Am I the Asshole (AITA)",
    suggestedSlug: "am-i-the-asshole",
    category: "community",
    importance: "high",
    priority: 1,
    roadmapEra: "tiktok-modern",
    reason: "Reddit judgment forum that became a cross-platform storytelling format.",
    relatedTopics: ["reddit-culture", "tiktok-rise"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-speedrunning",
    name: "Speedrunning community",
    suggestedSlug: "speedrunning",
    category: "community",
    importance: "medium",
    priority: 2,
    roadmapEra: "tiktok-modern",
    reason: "Games-as-sport culture with Twitch events, drama, and meme crossovers.",
    relatedTopics: ["twitch-culture", "git-gud", "gaming-culture"],
    clusters: ["gaming-culture", "streaming-culture"],
  }),
  seed({
    id: "gap-dream-smp",
    name: "Dream SMP",
    suggestedSlug: "dream-smp",
    category: "community",
    importance: "medium",
    priority: 2,
    roadmapEra: "tiktok-modern",
    reason: "Minecraft roleplay server fandom that dominated early-2020s youth internet.",
    relatedTopics: ["dream", "minecraft-movie-premiere", "stan-culture"],
    clusters: ["gaming-culture", "youtube-culture"],
  }),
  seed({
    id: "gap-grwm",
    name: "GRWM (Get Ready With Me)",
    suggestedSlug: "grwm",
    category: "community",
    importance: "medium",
    priority: 2,
    roadmapEra: "tiktok-modern",
    reason: "Dominant short-form lifestyle format linking beauty, gossip, and parasocial chat.",
    relatedTopics: ["influencer-culture", "tiktok-rise", "clean-girl-aesthetic"],
    clusters: ["tiktok-culture", "creator-economy"],
  }),
  seed({
    id: "gap-commentary-youtube",
    name: "Commentary YouTube",
    suggestedSlug: "commentary-youtube",
    category: "community",
    importance: "medium",
    priority: 2,
    roadmapEra: "tiktok-modern",
    reason: "Drama/react/essay ecosystem that mediates internet events for mass audiences.",
    relatedTopics: ["youtube-creator-era", "cancel-culture", "pewdiepie"],
    clusters: ["youtube-culture"],
  }),
  seed({
    id: "gap-nft-culture",
    name: "NFT culture",
    suggestedSlug: "nft-culture",
    category: "event",
    importance: "medium",
    priority: 2,
    roadmapEra: "tiktok-modern",
    reason: "2021 hype-and-crash cycle with lasting meme language and art discourse.",
    relatedTopics: ["ai-chatbot-wars", "twitter-culture"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-metaverse-hype",
    name: "Metaverse hype cycle",
    suggestedSlug: "metaverse-hype",
    category: "event",
    importance: "medium",
    priority: 2,
    roadmapEra: "tiktok-modern",
    reason: "Corporate rebrand moment (Meta) that the internet satirized relentlessly.",
    relatedTopics: ["facebook-culture", "nft-culture"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-covid-internet",
    name: "COVID internet (2020)",
    suggestedSlug: "covid-internet",
    category: "event",
    importance: "high",
    priority: 1,
    roadmapEra: "tiktok-modern",
    reason: "Pandemic accelerated TikTok, Zoom fatigue memes, and doomscrolling language.",
    relatedTopics: ["tiktok-rise", "doomscrolling", "sea-shanty-tiktok"],
    clusters: ["tiktok-culture"],
  }),
  seed({
    id: "gap-duet-stitch",
    name: "Duet / Stitch culture",
    suggestedSlug: "duet-stitch-culture",
    category: "event",
    importance: "medium",
    priority: 2,
    roadmapEra: "tiktok-modern",
    reason: "Native TikTok reply formats that changed how jokes and discourse spread.",
    relatedTopics: ["tiktok-rise", "short-form-takeover"],
    clusters: ["tiktok-culture"],
  }),
  seed({
    id: "gap-pov-tiktok",
    name: "POV TikTok format",
    suggestedSlug: "pov-tiktok",
    category: "meme",
    importance: "high",
    priority: 1,
    roadmapEra: "tiktok-modern",
    reason: "Point-of-view caption format that became a default short-form storytelling tool.",
    relatedTopics: ["tiktok-rise", "main-character-energy"],
    clusters: ["tiktok-culture"],
  }),
  seed({
    id: "gap-asmr-culture",
    name: "ASMR culture",
    suggestedSlug: "asmr-culture",
    category: "community",
    importance: "medium",
    priority: 2,
    roadmapEra: "tiktok-modern",
    reason: "YouTube/TikTok whisper-content genre with huge parasocial and meme footprint.",
    relatedTopics: ["youtube-creator-era", "parasocial"],
    clusters: ["youtube-culture", "creator-economy"],
  }),
  seed({
    id: "gap-mukbang",
    name: "Mukbang culture",
    suggestedSlug: "mukbang",
    category: "community",
    importance: "medium",
    priority: 2,
    roadmapEra: "tiktok-modern",
    reason: "Eating-broadcast genre spanning YouTube/Twitch/TikTok with global reach.",
    relatedTopics: ["unboxing-culture", "streamer-culture"],
    clusters: ["youtube-culture", "creator-economy"],
  }),
  seed({
    id: "gap-charlie-damelio-era",
    name: "Charli D’Amelio rise",
    suggestedSlug: "charli-damelio-rise",
    category: "event",
    importance: "medium",
    priority: 2,
    roadmapEra: "tiktok-modern",
    reason: "Early TikTok fame blueprint; complements creator bio with platform-history angle.",
    relatedTopics: ["charli-damelio", "tiktok-rise", "musical-ly"],
    clusters: ["tiktok-culture", "creator-economy"],
    notes: "Distinct from creator page: focus on the rise-as-event and platform effects.",
  }),
  seed({
    id: "gap-mrbeast-philanthropy-era",
    name: "MrBeast spectacle era",
    suggestedSlug: "mrbeast-spectacle-era",
    category: "event",
    importance: "medium",
    priority: 2,
    roadmapEra: "tiktok-modern",
    reason: "High-budget challenge/philanthropy video model that redefined YouTube scale.",
    relatedTopics: ["mrbeast", "youtube-creator-era", "creator-economy"],
    clusters: ["youtube-culture", "creator-economy"],
  }),
  seed({
    id: "gap-algorithmic-culture",
    name: "Algorithmic culture",
    suggestedSlug: "algorithmic-culture",
    category: "community",
    importance: "high",
    priority: 1,
    roadmapEra: "tiktok-modern",
    reason: "How For You feeds reshaped what “going viral” means across platforms.",
    relatedTopics: ["tiktok-rise", "short-form-takeover", "doomscrolling"],
    clusters: ["tiktok-culture"],
  }),
  seed({
    id: "gap-callout-culture",
    name: "Callout culture",
    suggestedSlug: "callout-culture",
    category: "community",
    importance: "medium",
    priority: 2,
    roadmapEra: "tiktok-modern",
    reason: "Related to cancel culture but focused on public accusation norms and pile-ons.",
    relatedTopics: ["cancel-culture", "stan-twitter", "ratio"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-podcast-internet",
    name: "Podcast internet culture",
    suggestedSlug: "podcast-internet",
    category: "community",
    importance: "medium",
    priority: 2,
    roadmapEra: "tiktok-modern",
    reason: "Clip economy from long-form podcasts into TikTok/YouTube discourse.",
    relatedTopics: ["commentary-youtube", "streamer-culture"],
    clusters: ["creator-economy"],
  }),
  seed({
    id: "gap-original-sound",
    name: "TikTok original sounds",
    suggestedSlug: "tiktok-original-sounds",
    category: "meme",
    importance: "high",
    priority: 1,
    roadmapEra: "tiktok-modern",
    reason: "Sound-first meme transmission; how audio becomes the template.",
    relatedTopics: ["tiktok-rise", "duet-stitch-culture", "capcut-culture"],
    clusters: ["tiktok-culture"],
  }),
  seed({
    id: "gap-quiet-quitting",
    name: "Quiet quitting (online discourse)",
    suggestedSlug: "quiet-quitting",
    category: "slang",
    importance: "low",
    priority: 3,
    roadmapEra: "tiktok-modern",
    reason: "Workplace slang that became a TikTok/LinkedIn culture-war flashpoint.",
    relatedTopics: ["tiktok-rise", "main-character-energy"],
    clusters: ["tiktok-culture"],
  }),
  seed({
    id: "gap-rizz-wars",
    name: "Rizz discourse",
    suggestedSlug: "rizz-discourse",
    category: "event",
    importance: "low",
    priority: 3,
    roadmapEra: "tiktok-modern",
    reason: "Oxford-word-of-the-year moment around rizz; complements slang entry.",
    relatedTopics: ["rizz", "the-rizzler", "gyatt"],
    clusters: ["brainrot-culture", "tiktok-culture"],
    notes: "Optional companion to existing rizz slang — only if it stays distinct.",
  }),
  seed({
    id: "gap-friendster",
    name: "Friendster",
    suggestedSlug: "friendster",
    category: "platform",
    importance: "low",
    priority: 3,
    roadmapEra: "early-internet",
    reason: "Early social network; useful pre-Facebook lineage page.",
    relatedTopics: ["myspace", "facebook-culture"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-orkut",
    name: "Orkut",
    suggestedSlug: "orkut",
    category: "platform",
    importance: "low",
    priority: 3,
    roadmapEra: "web-2",
    reason: "Google social network with major Brazil/India cultural footprint.",
    relatedTopics: ["google-plus", "facebook-culture"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-slashdot",
    name: "Slashdot",
    suggestedSlug: "slashdot",
    category: "community",
    importance: "low",
    priority: 3,
    roadmapEra: "early-internet",
    reason: "“News for nerds” community that shaped early tech-link culture.",
    relatedTopics: ["usenet", "reddit-culture"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-neopets",
    name: "Neopets",
    suggestedSlug: "neopets",
    category: "platform",
    importance: "medium",
    priority: 2,
    roadmapEra: "early-internet",
    reason: "Millennial virtual-pet platform with lasting nostalgia and scam-ad lore.",
    relatedTopics: ["geocities", "myspace"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-habbo-hotel",
    name: "Habbo Hotel",
    suggestedSlug: "habbo-hotel",
    category: "platform",
    importance: "low",
    priority: 3,
    roadmapEra: "web-2",
    reason: "Teen virtual world famous for pool’s closed memes and early social VR vibes.",
    relatedTopics: ["neopets", "discord-culture"],
    clusters: ["gaming-culture"],
  }),
  seed({
    id: "gap-club-penguin",
    name: "Club Penguin",
    suggestedSlug: "club-penguin",
    category: "platform",
    importance: "medium",
    priority: 2,
    roadmapEra: "web-2",
    reason: "Disney kids’ MMO with huge nostalgia and meme afterlife.",
    relatedTopics: ["neopets", "habbo-hotel"],
    clusters: ["gaming-culture"],
  }),
  seed({
    id: "gap-runescape-culture",
    name: "RuneScape culture",
    suggestedSlug: "runescape-culture",
    category: "community",
    importance: "medium",
    priority: 2,
    roadmapEra: "web-2",
    reason: "Long-lived MMO community with distinct slang, scams lore, and Twitch crossovers.",
    relatedTopics: ["twitch-culture", "git-gud"],
    clusters: ["gaming-culture"],
  }),
  seed({
    id: "gap-minecraft-youtube",
    name: "Minecraft YouTube era",
    suggestedSlug: "minecraft-youtube",
    category: "community",
    importance: "high",
    priority: 1,
    roadmapEra: "web-2",
    reason: "Let’s-play boom that minted a generation of creators and kids’ internet.",
    relatedTopics: ["dream-smp", "youtube-creator-era", "markiplier"],
    clusters: ["youtube-culture", "gaming-culture"],
  }),
  seed({
    id: "gap-mlg-montages",
    name: "MLG montages",
    suggestedSlug: "mlg-montages",
    category: "meme",
    importance: "medium",
    priority: 2,
    roadmapEra: "web-2",
    reason: "Airhorn/illuminati edit style that defined mid-2010s YouTube irony.",
    relatedTopics: ["press-f-to-pay-respects", "youtube-creator-era"],
    clusters: ["gaming-culture", "youtube-culture"],
  }),
  seed({
    id: "gap-salt",
    name: "Salt (slang)",
    suggestedSlug: "salt-slang",
    category: "slang",
    importance: "low",
    priority: 3,
    roadmapEra: "web-2",
    reason: "Gaming bitterness slang that crossed into general internet speech.",
    relatedTopics: ["gg", "ez", "git-gud"],
    clusters: ["gaming-culture"],
  }),
  seed({
    id: "gap-irl",
    name: "IRL",
    suggestedSlug: "irl",
    category: "slang",
    importance: "medium",
    priority: 2,
    roadmapEra: "early-internet",
    reason: "In real life — basic online/offline boundary term still everywhere.",
    relatedTopics: ["afk", "touch-grass"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-nsfw",
    name: "NSFW",
    suggestedSlug: "nsfw",
    category: "slang",
    importance: "medium",
    priority: 2,
    roadmapEra: "early-internet",
    reason: "Content-warning acronym foundational to forum and social moderation language.",
    relatedTopics: ["reddit-culture", "tl-dr"],
    clusters: ["classic-internet"],
    notes: "Define the label culturally; do not host NSFW media.",
  }),
  seed({
    id: "gap-hashtag-activism",
    name: "Hashtag activism",
    suggestedSlug: "hashtag-activism",
    category: "event",
    importance: "medium",
    priority: 2,
    roadmapEra: "social-media",
    reason: "How Twitter hashtags became protest and awareness infrastructure.",
    relatedTopics: ["twitter-culture", "kony-2012", "ice-bucket-challenge"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-influencer",
    name: "Influencer (term)",
    suggestedSlug: "influencer-term",
    category: "slang",
    importance: "high",
    priority: 1,
    roadmapEra: "social-media",
    reason: "The word itself — complements influencer-culture trend with etymology/usage.",
    relatedTopics: ["influencer-culture", "influencer-marketing", "creator-economy"],
    clusters: ["creator-economy"],
  }),
  seed({
    id: "gap-fyp",
    name: "FYP (For You Page)",
    suggestedSlug: "fyp",
    category: "slang",
    importance: "high",
    priority: 1,
    roadmapEra: "tiktok-modern",
    reason: "Core TikTok distribution slang; readers need a clear definition entry.",
    relatedTopics: ["tiktok-rise", "algorithmic-culture", "youtube-shorts-culture"],
    clusters: ["tiktok-culture"],
  }),
  seed({
    id: "gap-iykyk",
    name: "IYKYK",
    suggestedSlug: "iykyk",
    category: "slang",
    importance: "low",
    priority: 3,
    roadmapEra: "social-media",
    reason: "If you know you know — insider-reference slang across IG/TikTok captions.",
    relatedTopics: ["no-cap", "vibe-check"],
    clusters: ["tiktok-culture"],
  }),
  seed({
    id: "gap-caught-in-4k",
    name: "Caught in 4K",
    suggestedSlug: "caught-in-4k",
    category: "slang",
    importance: "medium",
    priority: 2,
    roadmapEra: "tiktok-modern",
    reason: "Exposure/receipts slang amplified by TikTok and Twitter screenshot culture.",
    relatedTopics: ["ratio", "callout-culture"],
    clusters: ["tiktok-culture"],
  }),
  seed({
    id: "gap-letting-the-cook",
    name: "Let him cook",
    suggestedSlug: "let-him-cook",
    category: "slang",
    importance: "medium",
    priority: 2,
    roadmapEra: "tiktok-modern",
    reason: "Sports/internet encouragement phrase that exploded on Twitter and TikTok.",
    relatedTopics: ["cooked", "aura", "w-dub"],
    clusters: ["tiktok-culture"],
  }),
  seed({
    id: "gap-its-giving-companion",
    name: "Periodt",
    suggestedSlug: "periodt",
    category: "slang",
    importance: "low",
    priority: 3,
    roadmapEra: "social-media",
    reason: "Emphatic AAVE-derived slang widely used (and appropriated) online.",
    relatedTopics: ["slay", "its-giving", "ate-left-no-crumbs"],
    clusters: ["tiktok-culture"],
    notes: "Credit linguistic origins carefully.",
  }),
  seed({
    id: "gap-wojak-variants",
    name: "Wojak variants",
    suggestedSlug: "wojak-variants",
    category: "meme",
    importance: "medium",
    priority: 2,
    roadmapEra: "social-media",
    reason: "Soyjak, Doomer, Bloomer, etc. — family tree under the Wojak entry.",
    relatedTopics: ["wojak", "gigachad", "npc"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-pepe-variants",
    name: "Pepe variants",
    suggestedSlug: "pepe-variants",
    category: "meme",
    importance: "medium",
    priority: 2,
    roadmapEra: "web-2",
    reason: "Feels Guy → apolitical/political forks; helps readers navigate Pepe history.",
    relatedTopics: ["pepe", "4chan", "wojak"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-loss-explained",
    name: "Is this Loss?",
    suggestedSlug: "is-this-loss",
    category: "meme",
    importance: "medium",
    priority: 2,
    roadmapEra: "web-2",
    reason: "Companion to Loss — the meta “did you spot Loss?” recognition game.",
    relatedTopics: ["loss", "rage-comics"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-bert-is-evil",
    name: "Bert is Evil",
    suggestedSlug: "bert-is-evil",
    category: "meme",
    importance: "low",
    priority: 3,
    roadmapEra: "early-internet",
    reason: "Early photoshop humor site; precursor energy to later remix culture.",
    relatedTopics: ["ytmnd", "something-awful"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-webring",
    name: "Webrings",
    suggestedSlug: "webrings",
    category: "community",
    importance: "low",
    priority: 3,
    roadmapEra: "early-internet",
    reason: "Pre-search discovery networks linking amateur sites by theme.",
    relatedTopics: ["geocities", "neopets"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-ebay-culture",
    name: "eBay culture",
    suggestedSlug: "ebay-culture",
    category: "platform",
    importance: "low",
    priority: 3,
    roadmapEra: "early-internet",
    reason: "Auction-site vernacular and scam lore that entered general internet speech.",
    relatedTopics: ["geocities", "napster-era"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-wikipedia-edit-wars",
    name: "Wikipedia edit wars",
    suggestedSlug: "wikipedia-edit-wars",
    category: "community",
    importance: "medium",
    priority: 2,
    roadmapEra: "web-2",
    reason: "Collaborative encyclopedia drama as its own internet-culture genre.",
    relatedTopics: ["reddit-culture", "godwins-law"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-know-your-meme",
    name: "Know Your Meme",
    suggestedSlug: "know-your-meme",
    category: "platform",
    importance: "high",
    priority: 1,
    roadmapEra: "web-2",
    reason: "The documentation site that made meme historiography mainstream.",
    relatedTopics: ["rage-comics", "advice-animals", "reddit-culture"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-cheezburger",
    name: "I Can Has Cheezburger",
    suggestedSlug: "i-can-has-cheezburger",
    category: "platform",
    importance: "medium",
    priority: 2,
    roadmapEra: "web-2",
    reason: "LOLcats publishing empire that commercialized early meme blogs.",
    relatedTopics: ["lolcats", "advice-animals"],
    clusters: ["animal-memes", "classic-internet"],
  }),
  seed({
    id: "gap-9gag",
    name: "9GAG",
    suggestedSlug: "9gag",
    category: "platform",
    importance: "medium",
    priority: 2,
    roadmapEra: "web-2",
    reason: "Aggregator often blamed for meme lag; important in global meme distribution fights.",
    relatedTopics: ["reddit-culture", "advice-animals"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-iFunny",
    name: "iFunny",
    suggestedSlug: "ifunny",
    category: "platform",
    importance: "medium",
    priority: 2,
    roadmapEra: "social-media",
    reason: "Mobile meme app scene with distinct feature/collective culture.",
    relatedTopics: ["deep-fried-memes", "reddit-culture"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-vsco-app",
    name: "VSCO (app culture)",
    suggestedSlug: "vsco-app",
    category: "platform",
    importance: "low",
    priority: 3,
    roadmapEra: "social-media",
    reason: "Photo-app culture behind the VSCO girl stereotype.",
    relatedTopics: ["vsco-girl", "instagram-culture"],
    clusters: ["tiktok-culture"],
  }),
  seed({
    id: "gap-bereal-companion",
    name: "Authenticity app wave",
    suggestedSlug: "authenticity-app-wave",
    category: "event",
    importance: "low",
    priority: 3,
    roadmapEra: "tiktok-modern",
    reason: "Broader framing around BeReal and anti-influencer authenticity products.",
    relatedTopics: ["bereal-wave", "instagram-culture", "performative"],
    clusters: ["tiktok-culture"],
  }),
  seed({
    id: "gap-zoom-fatigue",
    name: "Zoom fatigue",
    suggestedSlug: "zoom-fatigue",
    category: "slang",
    importance: "medium",
    priority: 2,
    roadmapEra: "tiktok-modern",
    reason: "Pandemic work-from-home slang that entered mainstream news vocabulary.",
    relatedTopics: ["covid-internet", "doomscrolling"],
    clusters: ["classic-internet"],
  }),
  seed({
    id: "gap-hot-girl-summer",
    name: "Hot Girl Summer",
    suggestedSlug: "hot-girl-summer",
    category: "slang",
    importance: "medium",
    priority: 2,
    roadmapEra: "social-media",
    reason: "Megan Thee Stallion phrase turned seasonal internet lifestyle meme.",
    relatedTopics: ["brat-summer", "slay", "main-character-energy"],
    clusters: ["tiktok-culture"],
  }),
  seed({
    id: "gap-girlboss",
    name: "Girlboss",
    suggestedSlug: "girlboss",
    category: "slang",
    importance: "medium",
    priority: 2,
    roadmapEra: "social-media",
    reason: "Lean-in feminism buzzword → ironic internet critique cycle.",
    relatedTopics: ["girl-dinner", "performative", "hot-girl-summer"],
    clusters: ["tiktok-culture"],
  }),
  seed({
    id: "gap-cheugy",
    name: "Cheugy",
    suggestedSlug: "cheugy",
    category: "slang",
    importance: "low",
    priority: 3,
    roadmapEra: "tiktok-modern",
    reason: "2021 millennial-vs-Gen-Z taste insult with brief but intense search spike.",
    relatedTopics: ["basic", "vsco-girl", "cringe"],
    clusters: ["tiktok-culture"],
  }),
  seed({
    id: "gap-sideeye",
    name: "Side-eye (internet usage)",
    suggestedSlug: "side-eye",
    category: "slang",
    importance: "low",
    priority: 3,
    roadmapEra: "social-media",
    reason: "Gesture/slang usage online; pairs with Side-Eyeing Chloe meme entry.",
    relatedTopics: ["side-eyeing-chloe", "ick"],
    clusters: ["tiktok-culture"],
  }),
  seed({
    id: "gap-ratio-event",
    name: "Ratio (as event culture)",
    suggestedSlug: "ratio-culture",
    category: "event",
    importance: "low",
    priority: 3,
    roadmapEra: "social-media",
    reason: "Optional event-angle companion only if kept distinct from ratio slang.",
    relatedTopics: ["ratio", "twitter-culture"],
    clusters: ["classic-internet"],
    notes: "Skip if too overlapping with existing ratio slang entry.",
  }),
];

export function listRoadmapByEra(era: RoadmapEraId): RoadmapEntry[] {
  return CONTENT_EXPANSION_ROADMAP.filter((e) => e.roadmapEra === era);
}

export function listRoadmapByCategory(
  category: ContentGapCategory,
): RoadmapEntry[] {
  return CONTENT_EXPANSION_ROADMAP.filter((e) => e.category === category);
}

export function listRoadmapByPriority(
  priority: RoadmapPriority,
): RoadmapEntry[] {
  return CONTENT_EXPANSION_ROADMAP.filter((e) => e.priority === priority);
}

/** Compact counts for tooling / docs generation. */
export function summarizeContentRoadmap(): {
  total: number;
  byEra: Record<RoadmapEraId, number>;
  byCategory: Record<string, number>;
  byPriority: Record<RoadmapPriority, number>;
  byImportance: Record<ContentGapImportance, number>;
} {
  const byEra = {
    "early-internet": 0,
    "web-2": 0,
    "social-media": 0,
    "tiktok-modern": 0,
  } satisfies Record<RoadmapEraId, number>;
  const byCategory: Record<string, number> = {};
  const byPriority = { 1: 0, 2: 0, 3: 0 } satisfies Record<
    RoadmapPriority,
    number
  >;
  const byImportance = {
    high: 0,
    medium: 0,
    low: 0,
  } satisfies Record<ContentGapImportance, number>;

  for (const row of CONTENT_EXPANSION_ROADMAP) {
    byEra[row.roadmapEra] += 1;
    byCategory[row.category] = (byCategory[row.category] ?? 0) + 1;
    byPriority[row.priority] += 1;
    byImportance[row.importance] += 1;
  }

  return {
    total: CONTENT_EXPANSION_ROADMAP.length,
    byEra,
    byCategory,
    byPriority,
    byImportance,
  };
}