import type { EventEntry } from "@/types";

const entry: EventEntry = {
  id: "e4",
  slug: "ai-chatbot-wars",
  title: "AI Chatbot Wars",
  category: "event",
  description:
    "The mid-2020s fight over AI chatbots — especially after ChatGPT’s late-2022 launch — when memes, job fears, and tool debates flooded X, Reddit, and YouTube.",
  imageGradient: "from-slate-600 via-zinc-500 to-gray-400",
  scores: { relevance: 46, influence: 81, cringe: 37, brainrot: 49 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 46,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "news",
    ],
    popularity: 37,
    trendingScore: 37,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Recent creation looks limited versus active internet topics. Signals: news/recent-articles=37 (Google News: 4 items in last 60d (40 returned) for “AI Chatbot Wars”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “AI Chatbot Wars”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “AI”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-08-11",
      "[news/recent-articles] Google News: 4 items in last 60d (40 returned) for “AI Chatbot Wars”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “AI Chatbot Wars”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"AI Chatbot Wars\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "Weak corroboration — blended heuristic (50) with AI double-check (42): Mixed signals—some authority listings boost the score, but low news volume, weak platform activity, and flat Google Trends indicate only modest current buzz.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Recent creation looks limited versus active internet topics. Signals: news/recent-articles=37 (Google News: 4 items in last 60d (40 returned) for “AI Chatbot Wars”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-01",
  lastUpdated: "2026-08-16",
  views: 2300000,
  trendDirection: "declining",
  platform: "X, Reddit, YouTube, everywhere",
  impact:
    "After ChatGPT went mainstream, AI stopped feeling like a niche tech topic. People argued about whether chatbots would replace writers, artists, and coders. Screenshots of weird wrong answers — hallucinations — became a humor format. Terms like “AI slop” named the flood of low-effort generated content. The debate showed up in news, workplace policy, and politics, and it still shapes how people talk about new AI products online.",
  highlights: [
    "OpenAI launched ChatGPT publicly on November 30, 2022",
    "ChatGPT became the fastest product to reach 100M users in history",
    "AI slop became a recognized term for low-effort AI-generated content",
    "Writers, artists, and coders pushed back against AI replacement fears",
    "AI hallucinations spawned a genre of screenshots shared as cautionary humor",
  ],
  relatedSlugs: [
    "twitter-x-transition",
    "short-form-takeover",
    "influencer-culture",
    "ai-generated-content-boom",
    "shrimp-jesus",
  ],
  tags: ["AI", "chatgpt", "technology", "jobs", "culture war"],
  media: [
    // AI suggested — human must verify URL and set verified: true
    // Defining visual: ChatGPT product mark (the face of the chatbot-wars era).
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/e/ef/ChatGPT-Logo.svg",
      title: "ChatGPT — official logo",
      source: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:ChatGPT-Logo.svg",
      platform: "wikimedia",
      attribution: "OpenAI (public domain / PD-textlogo)",
      license: "Public domain",
      description:
        "Official ChatGPT logo — the product that catalyzed mainstream AI chatbot culture.",
      date: "2022",
      verified: false,
    },
    {
      role: "supporting",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/9/97/OpenAI_logo_2025.svg",
      title: "OpenAI — 2025 wordmark / symbol",
      source: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:OpenAI_logo_2025.svg",
      platform: "wikimedia",
      attribution: "OpenAI (public domain)",
      license: "Public domain",
      description: "OpenAI brand mark associated with ChatGPT and the AI platform race.",
      date: "2025",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/ChatGPT",
      title: "ChatGPT — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/ChatGPT",
      platform: "other",
      attribution: "Wikipedia contributors",
      description: "Launch history, cultural impact, and product timeline for ChatGPT.",
      date: "2022",
      verified: false,
    },
  ],
  sources: [
    {
      title: "ChatGPT — Wikipedia",
      url: "https://en.wikipedia.org/wiki/ChatGPT",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
