import type { EventEntry } from "@/types";

const entry: EventEntry = {
  id: "e15",
  slug: "area-51-raid",
  title: "Area 51 Raid",
  category: "event",
  description:
    "The 2019 'Storm Area 51' Facebook event — millions RSVP'd to 'see them aliens,' and a few thousand actually showed up in the desert.",
  imageGradient: "from-emerald-800 via-green-600 to-lime-400",
  scores: { relevance: 5, influence: 70, cringe: 45, brainrot: 40 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 5,
    currentStatus: "historical",
    activePlatforms: [],
    popularity: 0,
    trendingScore: 0,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (40 returned) for “Area 51 Raid”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Character signals still mark this as strongly representative of chaotic internet brainrot culture. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Area 51 Raid”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Area”",
      "[news/recent-articles] Google News: 0 items in last 60d (40 returned) for “Area 51 Raid”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Area 51 Raid”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Area 51 Raid\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/absurdity] Tag/title absurdity cue (brainrot character only)",
      "Weak corroboration — blended heuristic (0) with AI double-check (10): All recent signals (news, Google Trends) are near zero, indicating the 2019 raid is only historically documented and not currently popular.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (40 returned) for “Area 51 Raid”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Character signals still mark this as strongly representative of chaotic internet brainrot culture.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-18",
  lastUpdated: "2026-08-16",
  historicalDate: "2019-09-20",
  views: 3200000,
  trendDirection: "declining",
  tags: ["2019", "facebook", "meme-event", "area-51", "naruto-run"],
  platform: "Facebook, Twitter, Instagram",
  impact:
    "A pure meme-to-IRL crossover: an ironic Facebook event became international news, tourism, and Naruto-run jokes. Proved that absurdist internet coordination could produce real-world gatherings — even when almost nobody expected a literal raid.",
  highlights: [
    "Facebook event 'Storm Area 51, They Can't Stop All of Us' drew millions of RSVPs in mid-2019",
    "September 2019 gatherings near the Nevada site drew thousands of curious attendees",
    "Naruto-run memes and alien merch defined the joke's visual language",
    "Authorities and media treated the meme seriously enough to issue warnings",
  ],
  relatedSlugs: ["harlem-shake", "ice-bucket-challenge", "rickroll", "yeet"],
  relationships: {
    sameFormat: ["ice-bucket-challenge"],
    sameEra: ["tiktok-rise"],
  },
  media: [
    // AI suggested — crowd at Area 51 back gate (Commons); defining IRL moment
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/9/96/Crowd_gathered_at_the_back_gate_of_Area_51.jpg",
      title: "Crowd at Area 51 back gate during Storm Area 51",
      source: "Wikimedia Commons",
      sourceUrl:
        "https://commons.wikimedia.org/wiki/File:Crowd_gathered_at_the_back_gate_of_Area_51.jpg",
      platform: "wikimedia",
      attribution: "Photograph on Wikimedia Commons (see file page)",
      license: "See Commons file page",
      description:
        "People gathered at the Area 51 perimeter during the Storm Area 51 meme event.",
      date: "2019",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Storm_Area_51",
      title: "Storm Area 51 — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Storm_Area_51",
      platform: "other",
      attribution: "Wikipedia contributors",
      description: "Overview of the Facebook event and September 2019 gatherings.",
      date: "2019",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Storm Area 51 — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Storm_Area_51",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
