import type { EventEntry } from "@/types";

const entry: EventEntry = {
  id: "e28",
  slug: "balloon-boy",
  title: "Balloon Boy Hoax",
  category: "event",
  description:
    "The October 2009 Colorado incident when Richard Heene claimed his six-year-old son Falcon was trapped aboard a runaway helium balloon — a story that collapsed live on TV and became an early viral-news meme.",
  imageGradient: "from-sky-500 via-blue-400 to-slate-300",
  scores: { relevance: 0, influence: 78, cringe: 72, brainrot: 40 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 0,
    currentStatus: "historical",
    activePlatforms: [
      "wikipedia",
    ],
    popularity: 0,
    trendingScore: 10,
    recentRevival: false,
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (40 returned) for “Balloon Boy Hoax”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Character signals still mark this as strongly representative of chaotic internet brainrot culture. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=19,561 for “Balloon boy hoax”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=2085 prev7=4144 (-50%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Balloon”",
      "[news/recent-articles] Google News: 0 items in last 60d (40 returned) for “Balloon Boy Hoax”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Balloon Boy Hoax”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Balloon Boy Hoax\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/absurdity] Tag/title absurdity cue (brainrot character only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (40 returned) for “Balloon Boy Hoax”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Character signals still mark this as strongly representative of chaotic internet brainrot culture.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "2009-10-15",
  views: 1800000,
  trendDirection: "declining",
  tags: ["2009", "hoax", "viral news", "cable tv", "meme-event"],
  platform: "Cable TV, Twitter, YouTube",
  impact:
    "Before TikTok, this was what a full internet cycle looked like: cable news treated a family stunt as breaking news, millions watched the balloon drift, and the boy's on-air admission — \"We did this for the show\" — turned the story inside out in real time. The Heenes later pleaded guilty to charges related to the hoax. Balloon Boy became shorthand for manufactured virality, credulous live coverage, and the hunger for a spectacle that could dominate a whole afternoon online.",
  highlights: [
    "October 15, 2009: a silver helium balloon flew over Colorado while the Heene family claimed six-year-old Falcon was aboard",
    "Hours of live cable coverage ended when Falcon was found safe at home and later said on CNN they did it \"for the show\"",
    "Richard and Mayumi Heene pleaded guilty to charges related to the hoax in 2009",
    "Became an early template for how a local stunt could hijack national attention and spawn years of jokes",
  ],
  relatedSlugs: ["4chan", "reddit-culture", "harambe", "area-51-raid"],
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Balloon_boy_hoax",
      title: "Balloon boy hoax — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Balloon_boy_hoax",
      platform: "other",
      attribution: "Wikipedia contributors",
      description: "Timeline of the 2009 Colorado balloon incident and criminal pleas.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Balloon boy hoax — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Balloon_boy_hoax",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
