import type { EventEntry } from "@/types";

const entry: EventEntry = {
  id: "e12",
  slug: "barbenheimer",
  title: "Barbenheimer",
  category: "event",
  description:
    "The cultural phenomenon of the simultaneous July 21, 2023 release of Barbie and Oppenheimer — which audiences watched in back-to-back sessions, creating one of the biggest cinema events of the modern era.",
  imageGradient: "from-pink-500 via-fuchsia-400 to-gray-700",
  scores: { relevance: 85, brainrot: 45, cringe: 15 },
  addedAt: "2026-07-17",
  historicalDate: "2023-07-21",
  views: 4200000,
  trendDirection: "declining",
  tags: ["film", "cinema", "2023", "cultural-event", "meme", "twitter"],
  platform: "Twitter, TikTok, Cinema",
  impact:
    "Barbenheimer demonstrated that internet meme culture could drive record-breaking cinema attendance. The double feature — bright pink Barbie followed by a three-hour WWII atomic bomb drama — created an absurd tonal contrast that the internet turned into a meme and audiences turned into a pilgrimage. Combined box office: $2.4B+. Both films were cultural touchstones that dominated conversation for months.",
  highlights: [
    "Barbie (Greta Gerwig) earned $1.4B worldwide, the highest-grossing film ever by a female director",
    "Oppenheimer (Christopher Nolan) earned $952M worldwide, Nolan's highest-grossing film",
    "Both films released on exactly the same date — July 21, 2023 — in direct competition",
    "Double feature became a social movement: audiences dressed in pink for Barbie, then gravely for Oppenheimer",
    "Meme format: bright pink Barbie aesthetics vs. atomic bomb imagery became universal shorthand for contradictory pairings",
    "AMC Theatres saw record daily ticket sales, servers crashed under demand",
  ],
  relatedSlugs: [],
  media: [
    // Cinema marquee announcing both films — the real-world Barbenheimer moment.
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/e/e2/Barbenheimer_-_July_2023.jpg",
      title: "Barbenheimer cinema sign — July 2023",
      source: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Barbenheimer_-_July_2023.jpg",
      platform: "wikimedia",
      attribution: "Captain Galaxy (CC BY 4.0)",
      license: "CC BY 4.0",
      description:
        "A cinema sign listing both Barbie and Oppenheimer — the defining public face of the Barbenheimer double-feature phenomenon.",
      date: "2023-07-19",
      verified: true,
    },
    {
      role: "supporting",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/d/de/Barbenheimer_on_display.jpg",
      title: "Fine Arts Theatre Barbenheimer showtimes — Asheville, NC",
      source: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Barbenheimer_on_display.jpg",
      platform: "wikimedia",
      attribution: "RyanAl6 (CC BY-SA 4.0)",
      license: "CC BY-SA 4.0",
      description:
        "Theater showtimes board showing Barbie and Oppenheimer as the only films screening — another real-world Barbenheimer artifact.",
      date: "2023-08-16",
      verified: true,
    },
    // Official studio trailers — oembed-verified embeddable.
    {
      role: "video",
      type: "video",
      url: "https://www.youtube.com/watch?v=8zIf0XvoL9Y",
      title: "Barbie — Official Teaser Trailer",
      source: "YouTube / Warner Bros. Pictures",
      sourceUrl: "https://www.youtube.com/watch?v=8zIf0XvoL9Y",
      platform: "youtube",
      attribution: "Warner Bros. Pictures",
      description: "Official Barbie teaser that fueled pink-side Barbenheimer hype.",
      date: "2022",
      verified: false,
    },
    {
      role: "video",
      type: "video",
      url: "https://www.youtube.com/watch?v=uYPbbksJxIg",
      title: "Oppenheimer — Official Trailer",
      source: "YouTube / Universal Pictures",
      sourceUrl: "https://www.youtube.com/watch?v=uYPbbksJxIg",
      platform: "youtube",
      attribution: "Universal Pictures",
      description: "Official Oppenheimer trailer — the dramatic half of the Barbenheimer pairing.",
      date: "2023",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Barbenheimer",
      title: "Barbenheimer — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Barbenheimer",
      platform: "other",
      attribution: "Wikipedia contributors",
      description: "Encyclopedia overview of the simultaneous Barbie / Oppenheimer release phenomenon.",
      date: "2023",
      verified: true,
    },
  ],
  sources: [
    {
      title: "Barbenheimer — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Barbenheimer",
      domain: "en.wikipedia.org",
    },
    {
      title: "Barbenheimer — Know Your Meme",
      url: "https://knowyourmeme.com/memes/barbenheimer",
      domain: "knowyourmeme.com",
    },
  ],
};

export default entry;
