import type { EventEntry } from "@/types";

const entry: EventEntry = {
  id: "e12",
  slug: "barbenheimer",
  title: "Barbenheimer",
  category: "event",
  description:
    "The July 21, 2023 same-day release of Barbie and Oppenheimer — when audiences treated the two films as a double feature, and Twitter and TikTok turned the contrast into a meme.",
  imageGradient: "from-pink-500 via-fuchsia-400 to-gray-700",
  scores: { relevance: 37, influence: 72, cringe: 15, brainrot: 45 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 37,
    currentStatus: "classic",
    activePlatforms: [
      "x",
      "news",
    ],
    popularity: 25,
    trendingScore: 25,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Recent creation signals rose modestly. Signals: news/recent-articles=25 (Google News: 2 items in last 60d (40 returned) for “Barbenheimer event”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Barbenheimer event”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Barbenheimer”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-04-14",
      "[news/recent-articles] Google News: 2 items in last 60d (40 returned) for “Barbenheimer event”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Barbenheimer event”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Barbenheimer event\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/absurdity] Tag/title absurdity cue (brainrot character only)",
      "Weak corroboration — blended heuristic (36) with AI double-check (38): Strong documentation but low recent news, platform activity, and Google Trends suggest only modest lingering popularity.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Recent creation signals rose modestly. Signals: news/recent-articles=25 (Google News: 2 items in last 60d (40 returned) for “Barbenheimer event”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-17",
  lastUpdated: "2026-08-16",
  historicalDate: "2023-07-21",
  views: 4200000,
  trendDirection: "declining",
  tags: ["film", "cinema", "2023", "cultural-event", "meme", "twitter"],
  platform: "Twitter, TikTok, Cinema",
  impact:
    "Studios put Barbie (bright, satirical, pink) and Oppenheimer (a long WWII atomic-bomb drama) on the same Friday. Online, people joked about watching both back-to-back. Offline, many actually did — dressing in pink for one film, then switching tone for the other. The meme helped turn opening weekend into a shared event. Combined worldwide box office passed $2.4B. The pairing became shorthand for odd cultural contrasts, and it still gets cited when social media and moviegoing collide.",
  highlights: [
    "Barbie (Greta Gerwig) earned $1.4B worldwide, the highest-grossing film ever by a female director",
    "Oppenheimer (Christopher Nolan) earned $952M worldwide, Nolan's highest-grossing film",
    "Both films released on exactly the same date — July 21, 2023 — in direct competition",
    "Audiences dressed in pink for Barbie, then shifted tone for Oppenheimer double features",
    "Pink Barbie aesthetics vs. atomic-bomb imagery became shorthand for contradictory pairings",
    "AMC Theatres saw record daily ticket sales; servers struggled under demand",
  ],
  relatedSlugs: [
    "brat-summer",
    "great-meme-reset",
    "tiktok-rise",
    "short-form-takeover",
  ],
  relationships: {
    sameEra: ["brat-summer", "tiktok-rise"],
    relatedTo: ["great-meme-reset", "short-form-takeover"],
  },
  media: [
    // Cinema marquee announcing both films — the real-world Barbenheimer moment.
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/e/e2/Barbenheimer_-_July_2023.jpg",
      title: "Barbenheimer cinema sign — July 2023",
      source: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Barbenheimer_-_July_2023.jpg",
      platform: "wikimedia",
      attribution: "Captain Galaxy (CC BY 4.0)",
      license: "CC BY 4.0",
      description:
        "A cinema sign listing both Barbie and Oppenheimer — the defining public face of the Barbenheimer double-feature phenomenon.",
      date: "2023-07-19",
      verified: true,
    },
    {
      role: "supporting",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/d/de/Barbenheimer_on_display.jpg",
      title: "Fine Arts Theatre Barbenheimer showtimes — Asheville, NC",
      source: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Barbenheimer_on_display.jpg",
      platform: "wikimedia",
      attribution: "RyanAl6 (CC BY-SA 4.0)",
      license: "CC BY-SA 4.0",
      description:
        "Theater showtimes board showing Barbie and Oppenheimer as the only films screening — another real-world Barbenheimer artifact.",
      date: "2023-08-16",
      verified: true,
    },
    // Official studio trailers — oembed-verified embeddable.
    {
      role: "video",
      type: "video",
      url: "https://www.youtube.com/watch?v=8zIf0XvoL9Y",
      title: "Barbie — Official Teaser Trailer",
      source: "YouTube / Warner Bros. Pictures",
      sourceUrl: "https://www.youtube.com/watch?v=8zIf0XvoL9Y",
      platform: "youtube",
      attribution: "Warner Bros. Pictures",
      description: "Official Barbie teaser that fueled pink-side Barbenheimer hype.",
      date: "2022",
      verified: false,
    },
    {
      role: "video",
      type: "video",
      url: "https://www.youtube.com/watch?v=uYPbbksJxIg",
      title: "Oppenheimer — Official Trailer",
      source: "YouTube / Universal Pictures",
      sourceUrl: "https://www.youtube.com/watch?v=uYPbbksJxIg",
      platform: "youtube",
      attribution: "Universal Pictures",
      description: "Official Oppenheimer trailer — the dramatic half of the Barbenheimer pairing.",
      date: "2023",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Barbenheimer",
      title: "Barbenheimer — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Barbenheimer",
      platform: "other",
      attribution: "Wikipedia contributors",
      description: "Encyclopedia overview of the simultaneous Barbie / Oppenheimer release phenomenon.",
      date: "2023",
      verified: true,
    },
  ],
  sources: [
    {
      title: "Barbenheimer — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Barbenheimer",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
