import type { EventEntry } from "@/types";

const entry: EventEntry = {
  id: "e29",
  slug: "bed-bug-paris-panic",
  title: "Paris Bed Bug Panic (2023)",
  category: "event",
  description:
    "A late-2023 wave of fear and memes after reports of bed bugs on Paris Metro trains, cinemas, and Charles de Gaulle Airport went viral ahead of the 2024 Olympics.",
  imageGradient: "from-red-800 via-rose-700 to-amber-600",
  scores: { relevance: 0, influence: 62, cringe: 48, brainrot: 45 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 0,
    currentStatus: "historical",
    activePlatforms: [
      "tiktok",
      "wikipedia",
    ],
    popularity: 0,
    trendingScore: 29,
    recentRevival: false,
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (40 returned) for “Paris Bed Bug Panic (2023)”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Character signals still mark this as strongly representative of chaotic internet brainrot culture. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=1,014 for “2023 Paris bedbug infestation”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=262 prev7=236 (11%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Paris”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-08-15",
      "[news/recent-articles] Google News: 0 items in last 60d (40 returned) for “Paris Bed Bug Panic (2023)”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Major news organization cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Paris Bed Bug Panic (2023)”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Paris Bed Bug Panic (2023)\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/gen-cohort-adoption] Cohort cue from tags/title (brainrot character only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (40 returned) for “Paris Bed Bug Panic (2023)”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Character signals still mark this as strongly representative of chaotic internet brainrot culture.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "2023-09-01",
  views: 890000,
  trendDirection: "declining",
  tags: ["2023", "paris", "public health", "tiktok", "travel"],
  platform: "TikTok, X, French TV, Reddit",
  impact:
    "Paris was already under global scrutiny with the Olympics approaching. When social clips showed insects on seats and in theaters, anxiety spread faster than verified infestation data. French officials and transit agencies responded publicly; dermatologists and pest experts flooded news segments. Online, the panic mixed genuine disgust with travel memes, \"check your hotel\" threads, and dark humor about Olympic visitors. It showed how a localized public-health scare could become international content within days.",
  highlights: [
    "September–October 2023: viral videos claimed bed bugs on Paris Metro lines, movie theaters, and airport seating",
    "French transport and tourism officials issued public reassurances and cleaning measures",
    "Coverage peaked ahead of the 2024 Paris Olympics, amplifying travel anxiety",
    "Spawned TikTok inspection tutorials, meme posts, and global news segments on urban pest resurgence",
  ],
  relatedSlugs: ["tiktok-rise", "reddit-culture", "brat-summer", "dupe-economy"],
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Bed_bug",
      title: "Bed bug — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Bed_bug",
      platform: "other",
      attribution: "Wikipedia contributors",
      description: "Background on bed bug resurgence and public-health context.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Paris bed bug scare — The Guardian",
      url: "https://www.theguardian.com/world/2023/oct/03/paris-bed-bug-scare-france",
      domain: "theguardian.com",
    },
    {
      title: "Bed bugs in Paris — BBC News",
      url: "https://www.bbc.com/news/world-europe-66987654",
      domain: "bbc.com",
    },
  ],
};

export default entry;
