import type { EventEntry } from "@/types";

const entry: EventEntry = {
  id: "e16",
  slug: "bereal-wave",
  title: "BeReal Wave",
  category: "event",
  description:
    "The early-2020s BeReal boom — a once-a-day authentic photo app that briefly challenged polished Instagram culture.",
  imageGradient: "from-yellow-300 via-amber-200 to-stone-300",
  scores: { relevance: 0, influence: 70, cringe: 22, brainrot: 62 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 0,
    currentStatus: "historical",
    activePlatforms: [],
    popularity: 0,
    trendingScore: 0,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (35 returned) for “BeReal Wave”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Character signals still mark this as strongly representative of chaotic internet brainrot culture. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “BeReal Wave”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “BeReal”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-07-26",
      "[news/recent-articles] Google News: 0 items in last 60d (35 returned) for “BeReal Wave”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “BeReal Wave”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"BeReal Wave\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/gen-cohort-adoption] Cohort cue from tags/title (brainrot character only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (35 returned) for “BeReal Wave”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Character signals still mark this as strongly representative of chaotic internet brainrot culture.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-18",
  lastUpdated: "2026-08-16",
  historicalDate: "2022-01-01",
  views: 1800000,
  trendDirection: "declining",
  tags: ["bereal", "2022", "authenticity", "social-apps", "gen-z"],
  platform: "BeReal, TikTok, Instagram",
  impact:
    "Briefly repositioned 'authenticity' as a product feature: one daily dual-camera capture, no filters, FOMO via timed notifications. Sparked discourse about performative casualness and showed how fast Gen Z can elevate — then abandon — a social app.",
  highlights: [
    "BeReal downloads surged in 2022 among teens and college students",
    "Daily notification + front/back camera format became a recognizable ritual",
    "Influencer and brand accounts struggled with the 'unpolished' aesthetic",
    "Hype cooled as engagement habituated and competitors copied the format",
  ],
  relatedSlugs: ["short-form-takeover", "tiktok-rise", "dupe-economy", "clean-girl-aesthetic"],
  relationships: {
    sameEra: ["short-form-takeover", "threads-launch"],
    relatedEvent: ["tiktok-rise"],
  },
  media: [
    // AI suggested — official BeReal wordmark (Commons SVG)
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/a/a6/BeReal._Logo.svg",
      title: "BeReal logo",
      source: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:BeReal._Logo.svg",
      platform: "wikimedia",
      attribution: "BeReal (see Commons file page)",
      license: "See Commons file page",
      description: "Official BeReal wordmark — the app that defined the authenticity wave.",
      date: "2022",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/BeReal",
      title: "BeReal — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/BeReal",
      platform: "other",
      attribution: "Wikipedia contributors",
      description: "App history and cultural reception.",
      date: "2022",
      verified: false,
    },
  ],
  sources: [
    {
      title: "BeReal — Wikipedia",
      url: "https://en.wikipedia.org/wiki/BeReal",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
