import type { EventEntry } from "@/types";

const entry: EventEntry = {
  id: "e1",
  slug: "brat-summer",
  title: "Brat Summer",
  category: "event",
  description:
    "Charli XCX's lime-green album era that defined a chaotic, party-forward cultural movement in 2024.",
  imageGradient: "from-lime-400 via-green-400 to-emerald-500",
  scores: { relevance: 58, influence: 72, cringe: 34, brainrot: 32 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 58,
    currentStatus: "current",
    activePlatforms: [
      "wikipedia",
      "news",
    ],
    popularity: 47,
    trendingScore: 42,
    recentRevival: false,
    popularityNotes: "Relevance: Creation volume is not peaking, but new content is still being produced regularly. Signals: news/recent-articles=47 (Google News: 7 items in last 60d (40 returned) for “Brat Summer”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=8,498 for “Brat Summer”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=1720 prev7=2207 (-22%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Brat”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-06-22",
      "[news/recent-articles] Google News: 7 items in last 60d (40 returned) for “Brat Summer”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Brat Summer”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Brat Summer\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "Weak corroboration — blended heuristic (61) with AI double-check (55): Decent Wikipedia traffic and some media coverage show moderate awareness, but declining pageviews and low Google‑Trends signal a waning buzz, making a mid‑range popularity estimate appropriate.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Creation volume is not peaking, but new content is still being produced regularly. Signals: news/recent-articles=47 (Google News: 7 items in last 60d (40 returned) for “Brat Summer”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-06-20",
  lastUpdated: "2026-08-16",
  views: 650000,
  trendDirection: "declining",
  platform: "TikTok, X, Instagram",
  impact:
    "Redefined how music eras become internet personalities. 'Brat' became a political endorsement, a beauty aesthetic, and a lifestyle philosophy simultaneously.",
  highlights: [
    "Kamala Harris's campaign used 'brat' branding, endorsed by Charli XCX",
    "The lime green became one of the most recognizable brand colors of 2024",
    "\"Brat girl\" became a recognizable archetype across fashion and music",
    "Sparked debate about what 'brat' actually means across generations",
  ],
  relatedSlugs: ["delulu", "slay"],
  tags: ["music", "charli xcx", "2024", "album era", "aesthetic"],
  // Defining visual: lime-green Brat wordmark cover (Commons PD-textlogo).
  media: [
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/6/60/Charli_XCX_-_Brat_%28album_cover%29.png",
      title: "Brat — Charli XCX album cover (lime-green wordmark)",
      source: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Charli_XCX_-_Brat_(album_cover).png",
      platform: "wikimedia",
      attribution: "Asylum / Atlantic / Warner UK (PD-textlogo)",
      license: "Public domain (textlogo)",
      description:
        "Official Brat album cover — the lime-green wordmark that defined Brat Summer 2024.",
      date: "2024-02-28",
      verified: true,
    },
    {
      role: "video",
      type: "video",
      url: "https://www.youtube.com/watch?v=WJW-VvmRKsE",
      title: "Charli xcx — 360 (official video)",
      source: "YouTube / Charli xcx",
      sourceUrl: "https://www.youtube.com/watch?v=WJW-VvmRKsE",
      platform: "youtube",
      attribution: "Charli xcx",
      license: "YouTube Standard License",
      description:
        "Official Brat-era music video for 360 — a defining clip of the album's cultural moment.",
      date: "2024-05-09",
      verified: true,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Brat_(album)",
      title: "Brat (album) — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Brat_(album)",
      platform: "other",
      attribution: "Wikipedia contributors",
      description:
        "Album page for Charli XCX's Brat — the lime-green era that defined Brat Summer.",
      date: "2024",
      verified: true,
    },
  ],
  sources: [
    {
      title: "Brat (album) — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Brat_(album)",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
