import type { EventEntry } from "@/types";

const entry: EventEntry = {
  id: "e31",
  slug: "chewbacca-mom",
  title: "Chewbacca Mom",
  category: "event",
  description:
    "Candace Payne's May 2016 Facebook Live video laughing in a Chewbacca mask — one of the first mega-viral Facebook Live moments, with hundreds of millions of views.",
  imageGradient: "from-amber-600 via-orange-500 to-brown-700",
  scores: { relevance: 0, influence: 82, cringe: 25, brainrot: 30 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 0,
    currentStatus: "historical",
    activePlatforms: [
      "wikipedia",
    ],
    popularity: 0,
    trendingScore: 29,
    recentRevival: false,
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (40 returned) for “Chewbacca Mom”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=38,064 for “List of viral videos”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=9439 prev7=8281 (14%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Chewbacca”",
      "[news/recent-articles] Google News: 0 items in last 60d (40 returned) for “Chewbacca Mom”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Chewbacca Mom”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Chewbacca Mom\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (40 returned) for “Chewbacca Mom”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "2016-05-19",
  views: 4100000,
  trendDirection: "declining",
  tags: ["2016", "facebook", "viral video", "star wars", "wholesome"],
  platform: "Facebook Live, YouTube, TV",
  impact:
    "Payne bought a roaring Chewbacca mask at Kohl's, filmed herself in the car, and laughed until she cried. Facebook's live product was still new; the clip spread across news, talk shows, and YouTube mirrors faster than almost any prior Facebook-native video. Hasbro and Kohl's sent gifts; Payne appeared on James Corden. Chewbacca Mom proved that unfiltered joy — not a produced sketch — could define a platform era and inspire years of reaction memes.",
  highlights: [
    "May 19, 2016: Candace Payne streamed herself wearing a Chewbacca mask on Facebook Live",
    "The video passed 100 million views within days — among Facebook's most-watched clips at the time",
    "Major outlets and late-night TV amplified the clip; retailers and Lucasfilm joined the response",
    "Became a reference point for wholesome viral video before TikTok dominated short-form",
  ],
  relatedSlugs: ["vine-shutdown", "tiktok-rise", "ice-bucket-challenge", "youtube-creator-era"],
  media: [
    // AI suggested — human must verify URL and set verified: true
    {
      role: "featured",
      type: "image",
      url: "https://i.ytimg.com/vi/y6Q7Hq7ApjY/hqdefault.jpg",
      title: "Chewbacca Mom on The Late Late Show",
      source: "YouTube / The Late Late Show with James Corden",
      sourceUrl: "https://www.youtube.com/watch?v=y6Q7Hq7ApjY",
      platform: "youtube",
      attribution: "The Late Late Show with James Corden",
      description: "Candace Payne (Chewbacca Mom) appearing on late-night TV after the viral clip.",
      date: "2016",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Chewbacca_mask_lady",
      title: "Chewbacca mask lady — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Chewbacca_mask_lady",
      platform: "other",
      attribution: "Wikipedia contributors",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Chewbacca mask lady — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Chewbacca_mask_lady",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
