import type { EventEntry } from "@/types";

const entry: EventEntry = {
  id: "e32",
  slug: "crypto-collapse-scandals",
  title: "Crypto Collapse & Scandals",
  category: "event",
  description:
    "The 2022–2023 cascade of crypto bankruptcies and fraud cases — FTX, Terra/Luna, Celsius — that turned \"Web3\" hype into cautionary memes and congressional hearings.",
  imageGradient: "from-emerald-700 via-teal-600 to-slate-800",
  scores: { relevance: 0, influence: 85, cringe: 55, brainrot: 35 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 0,
    currentStatus: "historical",
    activePlatforms: [],
    popularity: 0,
    trendingScore: 0,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (40 returned) for “Crypto Collapse & Scandals”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Crypto Collapse & Scandals”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Crypto”",
      "[news/recent-articles] Google News: 0 items in last 60d (40 returned) for “Crypto Collapse & Scandals”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited; Major news organization cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Crypto Collapse & Scandals”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Crypto Collapse & Scandals\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (40 returned) for “Crypto Collapse & Scandals”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "2022-05-01",
  views: 2100000,
  trendDirection: "declining",
  tags: ["crypto", "ftx", "2022", "finance", "scandal"],
  platform: "Twitter, Reddit, YouTube, Discord",
  impact:
    "After years of influencer-promoted coins and \"not financial advice\" threads, Terra's May 2022 collapse wiped billions and shook stablecoin faith. Celsius, Voyager, and BlockFi froze withdrawals; FTX imploded in November 2022 with Sam Bankman-Fried facing fraud charges. Reddit and Twitter filled with loss screenshots, \"trust me bro\" jokes, and congressional hearing clips. The era rewired how mainstream audiences saw crypto marketing — especially celebrity endorsements and NFT tie-ins.",
  highlights: [
    "May 2022: TerraUSD and Luna collapse erased tens of billions in market value",
    "Summer 2022: Celsius, Voyager, and other platforms halted withdrawals",
    "November 2022: FTX filed for bankruptcy; Sam Bankman-Fried was later convicted of fraud",
    "Spawned congressional hearings, meme discourse, and skepticism toward influencer crypto promos",
  ],
  relatedSlugs: ["gamestop-wallstreetbets", "nft-boom-bored-ape", "reddit-culture", "influencer-culture"],
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Bankruptcy_of_FTX",
      title: "Bankruptcy of FTX — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Bankruptcy_of_FTX",
      platform: "other",
      attribution: "Wikipedia contributors",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Bankruptcy of FTX — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Bankruptcy_of_FTX",
      domain: "en.wikipedia.org",
    },
    {
      title: "Terra (LUNA) crash — BBC News",
      url: "https://www.bbc.com/news/technology-61475055",
      domain: "bbc.com",
    },
  ],
};

export default entry;
