import type { EventEntry } from "@/types";

const entry: EventEntry = {
  id: "e33",
  slug: "damn-daniel",
  title: "Damn Daniel",
  category: "event",
  description:
    "A February 2016 Vine loop of Josh Holz hyping his friend Daniel Lara's white Vans — a short catchphrase that jumped to Ellen, Spotify, and Vans marketing.",
  imageGradient: "from-white via-gray-100 to-blue-400",
  scores: { relevance: 0, influence: 80, cringe: 45, brainrot: 40 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 0,
    currentStatus: "historical",
    activePlatforms: [
      "wikipedia",
    ],
    popularity: 0,
    trendingScore: 21,
    recentRevival: false,
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (40 returned) for “Damn Daniel”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Character signals still mark this as strongly representative of chaotic internet brainrot culture. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=4,584 for “Damn Daniel”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=936 prev7=1076 (-13%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Damn”",
      "[news/recent-articles] Google News: 0 items in last 60d (40 returned) for “Damn Daniel”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Damn Daniel”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Damn Daniel\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/absurdity] Tag/title absurdity cue (brainrot character only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (40 returned) for “Damn Daniel”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Character signals still mark this as strongly representative of chaotic internet brainrot culture.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "2016-02-15",
  views: 3500000,
  trendDirection: "declining",
  tags: ["2016", "vine", "catchphrase", "vans", "teen meme"],
  platform: "Vine, Twitter, YouTube",
  impact:
    "Damn Daniel was peak Vine: six seconds, repeated catchphrase, friend-group chemistry. Holz's voice and Lara's outfits became instantly quotable. Twitter accelerated the spread; Ellen DeGeneres brought both teens on her show; Vans sent Daniel a lifetime supply of shoes. The meme also marked the last stretch of Vine as a dominant culture factory before the platform shut down in 2017.",
  highlights: [
    "February 2016: Josh Holz posted Vine clips saying \"Damn Daniel\" about friend Daniel Lara's outfits",
    "Clips went viral on Twitter and YouTube compilations within days",
    "Ellen DeGeneres featured both teens; Vans gifted Lara shoes in a branded response",
    "Became one of the final mega-memes of the Vine era before its 2017 shutdown",
  ],
  relatedSlugs: ["vine-shutdown", "tiktok-rise", "harlem-shake", "youtube-creator-era"],
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Damn_Daniel",
      title: "Damn Daniel — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Damn_Daniel",
      platform: "other",
      attribution: "Wikipedia contributors",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Damn Daniel — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Damn_Daniel",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
