import type { EventEntry } from "@/types";

const entry: EventEntry = {
  id: "e34",
  slug: "diddy-scandal",
  title: "Sean Combs Legal Cases",
  category: "event",
  description:
    "The 2023–2025 federal prosecution of Sean \"Diddy\" Combs — civil lawsuits, a Homeland Security raid, and sex-trafficking charges that dominated music and internet discourse.",
  imageGradient: "from-neutral-900 via-zinc-800 to-red-950",
  scores: { relevance: 36, influence: 88, cringe: 50, brainrot: 20 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 36,
    currentStatus: "classic",
    activePlatforms: [
      "news",
    ],
    popularity: 25,
    trendingScore: 25,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=25 (Google News: 2 items in last 60d (40 returned) for “Sean Combs Legal Cases”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Sean Combs Legal Cases”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Sean”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-07-13",
      "[news/recent-articles] Google News: 2 items in last 60d (40 returned) for “Sean Combs Legal Cases”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Major news organization cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Sean Combs Legal Cases”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Sean Combs Legal Cases\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=25 (Google News: 2 items in last 60d (40 returned) for “Sean Combs Legal Cases”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "2023-11-01",
  views: 4800000,
  trendDirection: "declining",
  tags: ["2024", "music", "legal", "news", "scandal"],
  platform: "X, Instagram, YouTube, news",
  impact:
    "Civil suits filed in late 2023 alleging abuse and coercion drew intense social-media coverage. Federal agents searched Combs's properties in March 2024; he was indicted in September 2024 on racketeering and sex-trafficking charges. The story intersected with years of behind-the-scenes music-industry rumors now discussed openly online. Coverage mixed documented court filings with speculation — a reminder of how serious criminal cases travel through the same meme-and-thread infrastructure as entertainment gossip.",
  highlights: [
    "November 2023: Cassie Ventura filed a civil suit against Combs, settled within days but amplified further claims",
    "March 2024: Homeland Security agents executed searches at Combs properties in New York, Miami, and Los Angeles",
    "September 2024: A federal indictment charged Combs with racketeering conspiracy and sex trafficking",
    "Case generated sustained news and social discourse about power in the music industry",
  ],
  relatedSlugs: ["influencer-culture", "tiktok-rise", "creator-economy", "instagram-culture"],
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://www.bbc.com/news/articles/clyrvp5vp20o",
      title: "Sean Combs indictment — BBC News",
      source: "BBC News",
      sourceUrl: "https://www.bbc.com/news/articles/clyrvp5vp20o",
      platform: "other",
      attribution: "BBC News",
      description: "Reporting on federal charges against Sean Combs.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Sean Combs indicted — BBC News",
      url: "https://www.bbc.com/news/articles/clyrvp5vp20o",
      domain: "bbc.com",
    },
    {
      title: "Sean Combs charged — The New York Times",
      url: "https://www.nytimes.com/2024/09/16/arts/music/sean-combs-diddy-charges.html",
      domain: "nytimes.com",
    },
    {
      title: "Sean Combs lawsuit timeline — The Guardian",
      url: "https://www.theguardian.com/music/2024/mar/26/sean-diddy-combs-lawsuits-allegations-timeline",
      domain: "theguardian.com",
    },
  ],
};

export default entry;
