import type { EventEntry } from "@/types";

const entry: EventEntry = {
  id: "e3",
  slug: "dupe-economy",
  title: "The Dupe Economy",
  category: "event",
  description:
    "The cultural moment when buying dupes — knockoff luxury goods — became not just accepted but celebrated.",
  imageGradient: "from-amber-400 via-yellow-400 to-orange-400",
  scores: { relevance: 37, influence: 78, cringe: 27, brainrot: 29 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 37,
    currentStatus: "classic",
    activePlatforms: [
      "news",
    ],
    popularity: 25,
    trendingScore: 25,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=25 (Google News: 2 items in last 60d (40 returned) for “The Dupe Economy”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “The Dupe Economy”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “The”",
      "[news/recent-articles] Google News: 2 items in last 60d (40 returned) for “The Dupe Economy”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited; Dictionary / Britannica cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “The Dupe Economy”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"The Dupe Economy\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "Weak corroboration — blended heuristic (36) with AI double-check (38): Strong documentation but low recent news and trend activity suggest a modest, sub‑mid popularity right now.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=25 (Google News: 2 items in last 60d (40 returned) for “The Dupe Economy”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-06-10",
  lastUpdated: "2026-08-16",
  views: 540000,
  trendDirection: "declining",
  platform: "TikTok, YouTube, Reddit",
  impact:
    "Shifted consumer culture. The stigma around knockoffs flipped — finding a great dupe became a flex. Brands were forced to respond as their cachet eroded.",
  highlights: [
    "Stanley tumbler dupes from Amazon outsold the originals in some categories",
    "'Dupe culture' declared by major fashion outlets as the dominant consumer trend",
    "Luxury brands started releasing budget lines in response to dupe demand",
    "Influencer 'dupe hauls' became a dominant TikTok content format",
  ],
  relatedSlugs: [
    "girl-dinner",
    "unboxing-culture",
    "influencer-marketing",
    "fomo",
    "tiktok-rise",
    "old-money",
    "fast-fashion-boom",
    "hydro-flask",
    "crumbl-cookie",
  ],
  tags: ["consumer culture", "fashion", "luxury", "budget", "2024", "stanley", "quencher", "tumbler"],
  media: [
    // AI suggested — human must verify URL and set verified: true
    // Defining product of the dupe-economy moment: Stanley Quencher shelves (the item everyone duped).
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/c/c7/Stanley_Quencher_in_a_shop.jpg",
      title: "Stanley Quencher tumblers on retail shelves",
      source: "Wikimedia Commons / ishmael daro",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Stanley_Quencher_in_a_shop.jpg",
      platform: "wikimedia",
      attribution: "ishmael daro (CC BY 2.0)",
      license: "CC BY 2.0",
      description:
        "Stanley Quencher tumblers in a shop — the viral product whose Amazon/TikTok dupes defined dupe-economy discourse.",
      date: "2024",
      verified: false,
    },
    {
      role: "supporting",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Stanley_Quencher_H2.0_Tumbler_%E2%80%94Limit_2_per_customer.png",
      title: "Stanley Quencher H2.0 — limit 2 per customer retail sign",
      source: "Wikimedia Commons",
      sourceUrl:
        "https://commons.wikimedia.org/wiki/File:Stanley_Quencher_H2.0_Tumbler_%E2%80%94Limit_2_per_customer.png",
      platform: "wikimedia",
      attribution: "See Commons file page",
      license: "See Commons file page",
      description:
        "Retail scarcity signage for Stanley Quencher H2.0 — scarcity that fueled both original demand and dupe hunting.",
      date: "2024",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Stanley_Cup_(drinkware)",
      title: "Stanley Cup (drinkware) — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Stanley_Cup_(drinkware)",
      platform: "other",
      attribution: "Wikipedia contributors",
      description: "Background on the Stanley Quencher tumbler phenomenon.",
      date: "2024",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Stanley Cup (drinkware) — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Stanley_Cup_(drinkware)",
      domain: "en.wikipedia.org",
    },
    {
      title: "Dupe — Dictionary.com culture",
      url: "https://www.dictionary.com/e/slang/dupe/",
      domain: "dictionary.com",
    },
  ],
};

export default entry;
