import type { EventEntry } from "@/types";

const entry: EventEntry = {
  id: "e35",
  slug: "fyre-festival",
  title: "Fyre Festival",
  category: "event",
  description:
    "The April 2017 luxury-island festival that never happened — FEMA tents, cheese sandwiches, and influencer-promoted hype that became the defining scam-event of the Instagram era.",
  imageGradient: "from-orange-500 via-rose-400 to-teal-500",
  scores: { relevance: 58, influence: 71, cringe: 48, brainrot: 30 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 58,
    currentStatus: "current",
    activePlatforms: [
      "instagram",
      "wikipedia",
      "news",
    ],
    popularity: 47,
    trendingScore: 51,
    recentRevival: false,
    popularityNotes: "Relevance: Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=47 (Google News: 7 items in last 60d (40 returned) for “Fyre Festival”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=21,188 for “Fyre Festival”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=5143 prev7=4798 (7%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Fyre”",
      "[news/recent-articles] Google News: 7 items in last 60d (40 returned) for “Fyre Festival”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Fyre Festival”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Fyre Festival\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "Weak corroboration — blended heuristic (61) with AI double-check (55): Steady but modest interest (wiki views, slight week‑over‑week rise) without a current trend spike suggests a mid‑range popularity, lower than the heuristic’s 61.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=47 (Google News: 7 items in last 60d (40 returned) for “Fyre Festival”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "2017-04-28",
  views: 6200000,
  trendDirection: "stable",
  tags: ["2017", "festival", "scam", "instagram", "influencer"],
  platform: "Instagram, Twitter, YouTube",
  impact:
    "Organizers Billy McFarland and Ja Rule sold a Bahamas \"immersive\" experience using orange-tile Instagram posts and supermodel promos. Attendees arrived to unfinished sites, soaked mattresses, and cancelled acts. Twitter and Instagram documented the disaster in real time; lawsuits and a Netflix/Hulu documentary duo cemented Fyre as the cautionary tale for influencer marketing, startup hype, and private-jet aesthetics without logistics.",
  highlights: [
    "April 2017: Fyre Festival was cancelled mid-arrival on Great Exuma, Bahamas",
    "Attendees documented FEMA tents, boxed lunches, and lack of basic infrastructure",
    "Billy McFarland pleaded guilty to wire fraud; the event spawned major documentaries",
    "Became the reference meme for overpromised luxury experiences and influencer accountability",
  ],
  relatedSlugs: ["influencer-culture", "instagram-culture", "creator-economy", "logan-paul"],
  media: [
    // AI suggested — human must verify URL and set verified: true
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/2/23/N458UW_-_Swift_Air_-_Boeing_737-400_-_Fyre_Festival.jpg",
      title: "Charter aircraft branded for Fyre Festival",
      source: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:N458UW_-_Swift_Air_-_Boeing_737-400_-_Fyre_Festival.jpg",
      platform: "wikimedia",
      attribution: "Photograph on Wikimedia Commons (see file page)",
      license: "See Commons file page",
      description: "Fyre Festival–branded charter jet — symbol of the promoted luxury experience.",
      date: "2017",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Fyre_Festival",
      title: "Fyre Festival — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Fyre_Festival",
      platform: "other",
      attribution: "Wikipedia contributors",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Fyre Festival — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Fyre_Festival",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
