import type { EventEntry } from "@/types";

const entry: EventEntry = {
  id: "e14",
  slug: "gamestop-wallstreetbets",
  title: "GameStop / WallStreetBets",
  category: "event",
  description:
    "The January 2021 GameStop short squeeze — Reddit's r/WallStreetBets vs. hedge funds, memes, and retail-trader chaos.",
  imageGradient: "from-red-600 via-rose-500 to-amber-400",
  scores: { relevance: 24, influence: 82, cringe: 28, brainrot: 40 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 24,
    currentStatus: "classic",
    activePlatforms: [
      "reddit",
    ],
    popularity: 16,
    trendingScore: 16,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=16 (Google News: 1 items in last 60d (40 returned) for “GameStop event”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “GameStop event”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “GameStop”",
      "[news/recent-articles] Google News: 1 items in last 60d (40 returned) for “GameStop event”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “GameStop event”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"GameStop event\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/absurdity] Tag/title absurdity cue (brainrot character only)",
      "Weak corroboration — blended heuristic (25) with AI double-check (22): Despite strong historical documentation, recent news, Google Trends, and platform activity are low, indicating minimal current popularity.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=16 (Google News: 1 items in last 60d (40 returned) for “GameStop event”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-18",
  lastUpdated: "2026-08-16",
  historicalDate: "2021-01-01",
  views: 4500000,
  trendDirection: "declining",
  tags: ["reddit", "finance", "2021", "gamestop", "wallstreetbets", "meme-stocks"],
  platform: "Reddit, Twitter, Robinhood",
  impact:
    "Showed how coordinated internet communities could move markets and force institutional attention. Popularized diamond-hands / to-the-moon slang, meme-stock culture, and debates about retail brokerage power — a defining late-2010s/early-2020s internet-finance collision.",
  highlights: [
    "r/WallStreetBets pushed GameStop (GME) into a historic short squeeze in January 2021",
    "Trading apps briefly restricted buying — sparking outrage and congressional attention",
    "Spawned a wave of meme-stock discourse, livestreams, and finance memes",
    "Cemented WSB language (apes, diamond hands, tendies) in mainstream media",
  ],
  relatedSlugs: ["ratio", "great-meme-reset", "short-form-takeover", "based"],
  relationships: {
    sameEra: ["great-meme-reset", "among-us-era"],
    community: ["ratio"],
  },
  media: [
    // AI suggested — GameStop retail interior (Commons); represents the company at the center of the squeeze
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/a/a8/GameStop_interior_2019.jpg",
      title: "GameStop store interior",
      source: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:GameStop_interior_2019.jpg",
      platform: "wikimedia",
      attribution: "Photograph on Wikimedia Commons (see file page)",
      license: "See Commons file page",
      description:
        "GameStop retail floor — the brick-and-mortar brand at the center of the 2021 squeeze.",
      date: "2019",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/GameStop_short_squeeze",
      title: "GameStop short squeeze — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/GameStop_short_squeeze",
      platform: "other",
      attribution: "Wikipedia contributors",
      description: "Timeline and market impact of the January 2021 squeeze.",
      date: "2021",
      verified: false,
    },
  ],
  sources: [
    {
      title: "GameStop short squeeze — Wikipedia",
      url: "https://en.wikipedia.org/wiki/GameStop_short_squeeze",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
