import type { EventEntry } from "@/types";

const entry: EventEntry = {
  id: "e10",
  slug: "gta-6-release",
  title: "GTA 6",
  category: "event",
  description:
    "The GTA 6 hype cycle — Grand Theft Auto VI's trailers broke records and turned years of speculation, Florida memes, and launch discourse into a cultural event before the game shipped.",
  imageGradient: "from-orange-500 via-red-500 to-rose-600",
  scores: { relevance: 85, influence: 80, cringe: 29, brainrot: 26 },
  addedAt: "2026-07-16",
  historicalDate: "2023-12-04",
  views: 6200000,
  trendDirection: "stable",
  platform: "PlayStation, Xbox, PC",
  impact:
    "Demonstrated that major video game releases are now as culturally significant as blockbuster films. The GTA 6 announcement and hype cycle generated years of cultural content — memes, speculation, and discourse — before the game itself was available to play.",
  highlights: [
    "Trailer 1 released December 4, 2023 — broke YouTube records for views in 24 hours for a game trailer",
    "Featured Lucia, the first female protagonist in a mainline GTA game",
    "Set in Leonida — a fictional version of Florida, primarily centered on Vice City (Miami)",
    "Florida woman memes inspired by the trailer setting flooded Twitter and TikTok immediately after the reveal",
    "Multi-year delay/hype discourse kept GTA 6 as a permanent meme reference for 'when will it drop?'",
  ],
  relatedSlugs: [
    "short-form-takeover",
    "tiktok-rise",
    "minecraft-movie-premiere",
    "ai-chatbot-wars",
  ],
  relationships: {
    sameEra: ["tiktok-rise", "minecraft-movie-premiere"],
    relatedTo: ["short-form-takeover", "ai-chatbot-wars"],
  },
  participants: ["Rockstar Games"],
  tags: ["gaming", "rockstar", "gta", "playstation", "xbox", "2023", "2025", "vice city"],
  media: [
    // Official Rockstar Trailer 1 — oembed author_name confirmed.
    {
      role: "featured",
      type: "image",
      url: "https://i.ytimg.com/vi/QdBZY2fkU-0/hqdefault.jpg",
      title: "Grand Theft Auto VI — Trailer 1 thumbnail",
      source: "YouTube / Rockstar Games",
      sourceUrl: "https://www.youtube.com/watch?v=QdBZY2fkU-0",
      platform: "youtube",
      attribution: "Rockstar Games",
      license: "YouTube Standard License",
      description:
        "Official Rockstar Games Trailer 1 thumbnail — the December 2023 reveal that made GTA 6 a cultural event.",
      date: "2023-12-04",
      verified: true,
    },
    {
      role: "video",
      type: "video",
      url: "https://www.youtube.com/watch?v=QdBZY2fkU-0",
      title: "Grand Theft Auto VI Trailer 1",
      source: "YouTube / Rockstar Games",
      sourceUrl: "https://www.youtube.com/watch?v=QdBZY2fkU-0",
      platform: "youtube",
      attribution: "Rockstar Games",
      license: "YouTube Standard License",
      description: "Official first trailer for Grand Theft Auto VI from Rockstar Games.",
      date: "2023-12-04",
      verified: true,
    },
    {
      role: "video",
      type: "video",
      url: "https://www.youtube.com/watch?v=VQRLujxTm3c",
      title: "Grand Theft Auto VI Trailer 2",
      source: "YouTube / Rockstar Games",
      sourceUrl: "https://www.youtube.com/watch?v=VQRLujxTm3c",
      platform: "youtube",
      attribution: "Rockstar Games",
      license: "YouTube Standard License",
      description: "Official second trailer for Grand Theft Auto VI from Rockstar Games.",
      date: "2025",
      verified: true,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://www.rockstargames.com/VI",
      title: "Grand Theft Auto VI — Official Site",
      source: "Rockstar Games",
      sourceUrl: "https://www.rockstargames.com/VI",
      platform: "other",
      attribution: "Rockstar Games",
      description: "Official Rockstar Games GTA VI product page.",
      date: "2023",
      verified: true,
    },
  ],
  sources: [
    {
      title: "Grand Theft Auto VI — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Grand_Theft_Auto_VI",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
