import type { EventEntry } from "@/types";

const entry: EventEntry = {
  id: "e10",
  slug: "gta-6-release",
  title: "GTA 6",
  category: "event",
  description:
    "The GTA 6 hype cycle — Grand Theft Auto VI's trailers broke records and turned years of speculation, Florida memes, and launch discourse into a cultural event before the game shipped.",
  imageGradient: "from-orange-500 via-red-500 to-rose-600",
  scores: { relevance: 85, influence: 80, cringe: 29, brainrot: 26 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 85,
    currentStatus: "highly-active",
    activePlatforms: [
      "news",
    ],
    popularity: 85,
    trendingScore: 85,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=85 (Google News: 40 items in last 60d (40 returned) for “GTA 6”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “GTA 6”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “GTA”",
      "[dictionary/platform-activity] Wiktionary last revision 2025-06-22",
      "[news/recent-articles] Google News: 40 items in last 60d (40 returned) for “GTA 6”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “GTA 6”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"GTA 6\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "Weak corroboration — blended heuristic (100) with AI double-check (70): Strong recent news and documentation keep GTA 6 hype high, but the lack of a current search spike (Google Trends 28) suggests its popularity is below a perfect score.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=85 (Google News: 40 items in last 60d (40 returned) for “GTA 6”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-16",
  lastUpdated: "2026-08-16",
  historicalDate: "2023-12-04",
  views: 6200000,
  trendDirection: "declining",
  platform: "PlayStation, Xbox, PC",
  impact:
    "Demonstrated that major video game releases are now as culturally significant as blockbuster films. The GTA 6 announcement and hype cycle generated years of cultural content — memes, speculation, and discourse — before the game itself was available to play.",
  highlights: [
    "Trailer 1 released December 4, 2023 — broke YouTube records for views in 24 hours for a game trailer",
    "Featured Lucia, the first female protagonist in a mainline GTA game",
    "Set in Leonida — a fictional version of Florida, primarily centered on Vice City (Miami)",
    "Florida woman memes inspired by the trailer setting flooded Twitter and TikTok immediately after the reveal",
    "Multi-year delay/hype discourse kept GTA 6 as a permanent meme reference for 'when will it drop?'",
  ],
  relatedSlugs: [
    "short-form-takeover",
    "tiktok-rise",
    "minecraft-movie-premiere",
    "ai-chatbot-wars",
  ],
  relationships: {
    sameEra: ["tiktok-rise", "minecraft-movie-premiere"],
    relatedTo: ["short-form-takeover", "ai-chatbot-wars"],
  },
  participants: ["Rockstar Games"],
  tags: ["gaming", "rockstar", "gta", "playstation", "xbox", "2023", "2025", "vice city"],
  media: [
    // Official Rockstar Trailer 1 — oembed author_name confirmed.
    {
      role: "featured",
      type: "image",
      url: "https://i.ytimg.com/vi/QdBZY2fkU-0/hqdefault.jpg",
      title: "Grand Theft Auto VI — Trailer 1 thumbnail",
      source: "YouTube / Rockstar Games",
      sourceUrl: "https://www.youtube.com/watch?v=QdBZY2fkU-0",
      platform: "youtube",
      attribution: "Rockstar Games",
      license: "YouTube Standard License",
      description:
        "Official Rockstar Games Trailer 1 thumbnail — the December 2023 reveal that made GTA 6 a cultural event.",
      date: "2023-12-04",
      verified: true,
    },
    {
      role: "video",
      type: "video",
      url: "https://www.youtube.com/watch?v=QdBZY2fkU-0",
      title: "Grand Theft Auto VI Trailer 1",
      source: "YouTube / Rockstar Games",
      sourceUrl: "https://www.youtube.com/watch?v=QdBZY2fkU-0",
      platform: "youtube",
      attribution: "Rockstar Games",
      license: "YouTube Standard License",
      description: "Official first trailer for Grand Theft Auto VI from Rockstar Games.",
      date: "2023-12-04",
      verified: true,
    },
    {
      role: "video",
      type: "video",
      url: "https://www.youtube.com/watch?v=VQRLujxTm3c",
      title: "Grand Theft Auto VI Trailer 2",
      source: "YouTube / Rockstar Games",
      sourceUrl: "https://www.youtube.com/watch?v=VQRLujxTm3c",
      platform: "youtube",
      attribution: "Rockstar Games",
      license: "YouTube Standard License",
      description: "Official second trailer for Grand Theft Auto VI from Rockstar Games.",
      date: "2025",
      verified: true,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://www.rockstargames.com/VI",
      title: "Grand Theft Auto VI — Official Site",
      source: "Rockstar Games",
      sourceUrl: "https://www.rockstargames.com/VI",
      platform: "other",
      attribution: "Rockstar Games",
      description: "Official Rockstar Games GTA VI product page.",
      date: "2023",
      verified: true,
    },
  ],
  sources: [
    {
      title: "Grand Theft Auto VI — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Grand_Theft_Auto_VI",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
