import type { EventEntry } from "@/types";

const entry: EventEntry = {
  id: "e36",
  slug: "kony-2012",
  title: "Kony 2012",
  category: "event",
  description:
    "Invisible Children's March 2012 documentary campaign to capture Ugandan warlord Joseph Kony — the fastest-spreading viral cause video before modern TikTok activism.",
  imageGradient: "from-red-700 via-stone-600 to-neutral-800",
  scores: { relevance: 36, influence: 88, cringe: 55, brainrot: 25 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 36,
    currentStatus: "classic",
    activePlatforms: [
      "youtube",
      "wikipedia",
      "news",
    ],
    popularity: 25,
    trendingScore: 39,
    recentRevival: false,
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=25 (Google News: 2 items in last 60d (40 returned) for “Kony 2012”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=15,279 for “Kony 2012”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=3583 prev7=3433 (4%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Kony”",
      "[news/recent-articles] Google News: 2 items in last 60d (40 returned) for “Kony 2012”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Kony 2012”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Kony 2012\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=25 (Google News: 2 items in last 60d (40 returned) for “Kony 2012”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "2012-03-05",
  views: 5500000,
  trendDirection: "stable",
  tags: ["2012", "activism", "youtube", "viral video", "documentary"],
  platform: "YouTube, Facebook, Twitter",
  impact:
    "The 30-minute film hit 100 million views in roughly a week — unprecedented for a charity campaign in 2012. Young viewers shared \"Cover the Night\" posters and donation links; critics questioned simplification of Central African conflict and the group's finances. Creator Jason Russell's public breakdown became its own news cycle. Kony 2012 taught the internet both the power and the pitfalls of cause virality: emotion scales faster than nuance.",
  highlights: [
    "March 5, 2012: Invisible Children released \"KONY 2012\" on YouTube",
    "Video reached 100 million views within about six days — record pace for the time",
    "Sparked global awareness, criticism of oversimplification, and debates on slacktivism",
    "Cover the Night poster campaign was planned for April 2012 amid intense media scrutiny",
  ],
  relatedSlugs: ["ice-bucket-challenge", "youtube-creator-era", "reddit-culture", "4chan"],
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Kony_2012",
      title: "Kony 2012 — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Kony_2012",
      platform: "other",
      attribution: "Wikipedia contributors",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Kony 2012 — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Kony_2012",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
