import type { EventEntry } from "@/types";

const entry: EventEntry = {
  id: "e37",
  slug: "llama-chase",
  title: "Arizona Llama Chase",
  category: "event",
  description:
    "The February 2015 Sun City, Arizona televised pursuit of two escaped llamas — a breaking-news absurdity that briefly owned Twitter and cable split-screens.",
  imageGradient: "from-amber-400 via-orange-300 to-sky-400",
  scores: { relevance: 0, influence: 72, cringe: 30, brainrot: 40 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 0,
    currentStatus: "historical",
    activePlatforms: [
      "x",
    ],
    popularity: 0,
    trendingScore: 0,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (40 returned) for “Arizona Llama Chase”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Arizona Llama Chase”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Arizona”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-06-14",
      "[news/recent-articles] Google News: 0 items in last 60d (40 returned) for “Arizona Llama Chase”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited; Major news organization cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Arizona Llama Chase”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Arizona Llama Chase\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (40 returned) for “Arizona Llama Chase”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "2015-02-26",
  views: 2200000,
  trendDirection: "declining",
  tags: ["2015", "viral", "twitter", "animals", "news"],
  platform: "Twitter, cable news, YouTube",
  impact:
    "While news choppers tracked two llamas dodging capture through retirement-community streets, Twitter treated it like sport commentary. GIFs, pun threads, and split-screen jokes spread alongside serious headlines elsewhere. The chase ended when residents helped corral the animals. It became a pre-TikTok example of live absurdity converted instantly into participatory meme culture.",
  highlights: [
    "February 26, 2015: two llamas escaped a retirement-community visit in Sun City, Arizona",
    "Local TV helicopters broadcast the chase; Twitter exploded with live commentary",
    "Both llamas were captured after an hour-long pursuit",
    "Remembered as a classic \"slow news day\" internet moment alongside The Dress era",
  ],
  relatedSlugs: ["yanny-vs-laurel", "harambe", "area-51-raid", "reddit-culture"],
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Llama_chase_in_Arizona",
      title: "Llama chase in Arizona — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Llama_chase_in_Arizona",
      platform: "other",
      attribution: "Wikipedia contributors",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Llama chase in Arizona — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Llama_chase_in_Arizona",
      domain: "en.wikipedia.org",
    },
    {
      title: "Arizona llama chase — BBC News",
      url: "https://www.bbc.com/news/world-us-canada-31642657",
      domain: "bbc.com",
    },
  ],
};

export default entry;
