import type { EventEntry } from "@/types";

const entry: EventEntry = {
  id: "e38",
  slug: "love-island-uk-viral",
  title: "Love Island UK Goes Viral",
  category: "event",
  description:
    "How ITV's Love Island became a UK-to-global social-TV phenomenon — memes, recouplings, and \"it is what it is\" discourse flooding Twitter and TikTok each summer.",
  imageGradient: "from-pink-500 via-rose-400 to-orange-400",
  scores: { relevance: 44, influence: 74, cringe: 62, brainrot: 55 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 44,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "x",
      "tiktok",
      "wikipedia",
      "news",
    ],
    popularity: 32,
    trendingScore: 45,
    recentRevival: false,
    popularityNotes: "Relevance: Recent creation looks limited versus active internet topics. Signals: news/recent-articles=32 (Google News: 3 items in last 60d (40 returned) for “Love Island UK Goes Viral”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=38,064 for “List of viral videos”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=9439 prev7=8281 (14%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Love”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-06-10",
      "[news/recent-articles] Google News: 3 items in last 60d (40 returned) for “Love Island UK Goes Viral”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Love Island UK Goes Viral”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Love Island UK Goes Viral\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/gen-cohort-adoption] Cohort cue from tags/title (brainrot character only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Recent creation looks limited versus active internet topics. Signals: news/recent-articles=32 (Google News: 3 items in last 60d (40 returned) for “Love Island UK Goes Viral”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "2019-06-01",
  views: 1400000,
  trendDirection: "stable",
  tags: ["reality tv", "uk", "twitter", "tiktok", "dating"],
  platform: "ITV, Twitter, TikTok, Instagram",
  impact:
    "Reality dating on a Spanish villa might have stayed regional without simultaneous social viewing. Love Island UK turned contestants into meme characters nightly: catchphrases, water-bottle branding, and \"dayroom\" drama became Twitter sport. U.S. and international audiences joined via clips and VPN culture; TikTok reaction formats extended the show beyond broadcast hours. It helped define \"social TV\" where the second screen is the main event.",
  highlights: [
    "Love Island UK relaunched on ITV2 in 2015; cultural peak arrived with mid/late-2010s social viewing",
    "Catchphrases like \"it is what it is\" (2019) crossed from villa to mainstream meme vocabulary",
    "Twitter live-reaction threads and Love Island memes became summer ritual content",
    "International TikTok and clip channels spread UK villa drama to non-UK audiences",
  ],
  relatedSlugs: ["tiktok-rise", "instagram-culture", "influencer-culture", "brat-summer"],
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Love_Island_(2015_TV_series)",
      title: "Love Island (2015 TV series) — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Love_Island_(2015_TV_series)",
      platform: "other",
      attribution: "Wikipedia contributors",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Love Island (2015 TV series) — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Love_Island_(2015_TV_series)",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
