import type { EventEntry } from "@/types";

const entry: EventEntry = {
  id: "e2",
  slug: "minecraft-movie-premiere",
  title: "Minecraft Movie Premiere",
  category: "event",
  description:
    "The A Minecraft Movie opening weekend became a live theatrical meme event — audiences went feral for the Chicken Jockey.",
  imageGradient: "from-green-500 via-lime-400 to-yellow-300",
  scores: { relevance: 28, influence: 67, cringe: 40, brainrot: 88 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 28,
    currentStatus: "classic",
    activePlatforms: [],
    popularity: 16,
    trendingScore: 16,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=16 (Google News: 1 items in last 60d (40 returned) for “Minecraft Movie Premiere”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Character signals still mark this as strongly representative of chaotic internet brainrot culture. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Minecraft Movie Premiere”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Minecraft”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-08-12",
      "[news/recent-articles] Google News: 1 items in last 60d (40 returned) for “Minecraft Movie Premiere”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Minecraft Movie Premiere”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Minecraft Movie Premiere\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/absurdity] Tag/title absurdity cue (brainrot character only)",
      "[catalog-evidence/gen-cohort-adoption] Cohort cue from tags/title (brainrot character only)",
      "Weak corroboration — blended heuristic (25) with AI double-check (30): Most concrete signals (news, trends) are low, indicating the premiere meme isn’t currently viral despite high absurdity tags.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=16 (Google News: 1 items in last 60d (40 returned) for “Minecraft Movie Premiere”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Character signals still mark this as strongly representative of chaotic internet brainrot culture.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-12",
  lastUpdated: "2026-08-16",
  views: 1800000,
  trendDirection: "declining",
  platform: "Theaters, TikTok, YouTube",
  impact:
    "Redefined the movie premiere experience for Gen Alpha. Theater reaction compilations became their own genre of content, spawning a new form of participatory cinema.",
  highlights: [
    "Theater audiences screaming, standing, and throwing popcorn at the Chicken Jockey scene",
    "IMAX screenings sold out in minutes across multiple cities",
    "TikTok compilations of theater reactions hit 500M+ total views",
    "'Chicken Jockey' became the shorthand for unexpected viral cinema moments",
  ],
  relatedSlugs: [
    "chicken-jockey",
    "skibidi-toilet",
    "brainrot",
    "dream",
    "tiktok-rise",
  ],
  relationships: {
    relatedTo: ["chicken-jockey", "skibidi-toilet", "brainrot"],
    community: ["dream"],
    sameEra: ["tiktok-rise"],
  },
  tags: ["minecraft", "movie", "cinema", "gen alpha", "jack black"],
  media: [
    // Official WB movie trailer — premiere/promotional identity for the event.
    {
      role: "featured",
      type: "image",
      url: "https://i.ytimg.com/vi/wJO_vIDZn-I/hqdefault.jpg",
      title: "A Minecraft Movie — Official Trailer thumbnail",
      source: "YouTube / Warner Bros.",
      sourceUrl: "https://www.youtube.com/watch?v=wJO_vIDZn-I",
      platform: "youtube",
      attribution: "Warner Bros. Pictures",
      license: "YouTube Standard License",
      description:
        "Official Warner Bros. trailer thumbnail for A Minecraft Movie — the promotional face of the premiere event.",
      date: "2024-11-19",
      verified: true,
    },
    {
      role: "video",
      type: "video",
      url: "https://www.youtube.com/watch?v=wJO_vIDZn-I",
      title: "A Minecraft Movie | Official Trailer",
      source: "YouTube / Warner Bros.",
      sourceUrl: "https://www.youtube.com/watch?v=wJO_vIDZn-I",
      platform: "youtube",
      attribution: "Warner Bros. Pictures",
      license: "YouTube Standard License",
      description: "Official theatrical trailer for A Minecraft Movie.",
      date: "2024-11-19",
      verified: true,
    },
    {
      role: "video",
      type: "video",
      url: "https://www.youtube.com/watch?v=EY4h38NaXwU",
      title: "A Minecraft Movie | Chicken Jockey | Movie Clip",
      source: "YouTube / Warner Bros. Entertainment",
      sourceUrl: "https://www.youtube.com/watch?v=EY4h38NaXwU",
      platform: "youtube",
      attribution: "Warner Bros. Entertainment",
      license: "YouTube Standard License",
      description:
        "Official Chicken Jockey clip — the scene that turned opening weekend into a live meme event.",
      date: "2025",
      verified: true,
    },
  ],
  sources: [
    {
      title: "A Minecraft Movie — Wikipedia",
      url: "https://en.wikipedia.org/wiki/A_Minecraft_Movie",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
