import type { EventEntry } from "@/types";

const entry: EventEntry = {
  id: "e19",
  slug: "most-liked-egg",
  title: "Most Liked Egg",
  category: "event",
  description:
    "The January 2019 Instagram post that briefly became the most-liked post on the platform — a pure engagement stunt turned into a global meme.",
  imageGradient: "from-amber-100 via-yellow-200 to-orange-300",
  scores: { relevance: 25, influence: 65, cringe: 40, brainrot: 28 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 25,
    currentStatus: "classic",
    activePlatforms: [
      "instagram",
    ],
    popularity: 16,
    trendingScore: 16,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Recent creation signals rose modestly. Signals: news/recent-articles=16 (Google News: 1 items in last 60d (40 returned) for “Most Liked Egg”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Most Liked Egg”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Most”",
      "[dictionary/platform-activity] Wiktionary last revision 2025-11-04",
      "[news/recent-articles] Google News: 1 items in last 60d (40 returned) for “Most Liked Egg”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Most Liked Egg”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Most Liked Egg\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Recent creation signals rose modestly. Signals: news/recent-articles=16 (Google News: 1 items in last 60d (40 returned) for “Most Liked Egg”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-18",
  lastUpdated: "2026-08-16",
  historicalDate: "2019-01-04",
  views: 3800000,
  trendDirection: "declining",
  tags: ["2019", "instagram", "viral", "engagement", "world-record"],
  platform: "Instagram",
  impact:
    "Proved a blank stock photo plus a clear call-to-action could outpace celebrity posts for likes. Sparked 'Egg Gang' fandom, cracked-egg sequel posts, mental-health ad pivots, and years of jokes about empty virality — until Messi's 2022 World Cup post overtook the record.",
  highlights: [
    "@world_record_egg posted a plain egg photo on January 4, 2019 challenging Kylie Jenner's like record",
    "Within ~10 days it became Instagram's most-liked post (tens of millions of likes)",
    "Follow-up posts showed the egg cracking; creators later revealed as ad creatives including Chris Godfrey",
    "Record stood until Lionel Messi's December 2022 World Cup celebration post",
  ],
  relatedSlugs: ["short-form-takeover", "tiktok-rise", "area-51-raid"],
  relationships: {
    sameEra: ["area-51-raid", "tiktok-rise"],
    relatedTo: ["short-form-takeover"],
  },
  media: [
    // AI suggested — KYM cover of the Instagram egg post
    {
      role: "featured",
      type: "image",
      url: "https://i.kym-cdn.com/entries/icons/original/000/028/148/1527c092-1da5-4f7a-b638-f30543382b0b-large16x9_EGGGANGInstagramPost.png",
      title: "World Record Egg — Instagram egg post",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/world-record-egg",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "The plain egg photograph that became Instagram's most-liked post in 2019.",
      date: "2019",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/world-record-egg",
      title: "World Record Egg — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/world-record-egg",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Timeline of the Instagram egg like record.",
      date: "2019",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Instagram_egg",
      title: "Instagram egg — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Instagram_egg",
      platform: "other",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      description: "Encyclopedic account of the egg post and later record loss.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Instagram egg — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Instagram_egg",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
