import type { EventEntry } from "@/types";

const entry: EventEntry = {
  id: "e39",
  slug: "nft-boom-bored-ape",
  title: "NFT Boom & Bored Ape Yacht Club",
  category: "event",
  description:
    "The 2021–2022 NFT mania — profile-picture projects, celebrity mints, and Bored Ape Yacht Club as the face of JPEG speculation before the crypto winter.",
  imageGradient: "from-lime-400 via-yellow-300 to-amber-500",
  scores: { relevance: 28, influence: 82, cringe: 75, brainrot: 50 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 28,
    currentStatus: "classic",
    activePlatforms: [],
    popularity: 16,
    trendingScore: 16,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=16 (Google News: 1 items in last 60d (40 returned) for “NFT Boom & Bored Ape Yacht Club”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “NFT Boom & Bored Ape Yacht Club”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “NFT”",
      "[dictionary/platform-activity] Wiktionary last revision 2025-11-06",
      "[news/recent-articles] Google News: 1 items in last 60d (40 returned) for “NFT Boom & Bored Ape Yacht Club”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “NFT Boom & Bored Ape Yacht Club”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"NFT Boom & Bored Ape Yacht Club\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "Weak corroboration — blended heuristic (25) with AI double-check (30): Recent news and Google Trends are low, indicating the NFT boom hype has faded despite strong historical documentation.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=16 (Google News: 1 items in last 60d (40 returned) for “NFT Boom & Bored Ape Yacht Club”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "2021-04-01",
  views: 2800000,
  trendDirection: "declining",
  tags: ["nft", "crypto", "2021", "bored ape", "web3"],
  platform: "Twitter, Discord, OpenSea",
  impact:
    "When Ethereum NFT trading surged, Bored Ape Yacht Club became the status symbol: cartoon apes as identity, Discord as country club, celebrity flips as headlines. Right-click save became the dominant joke; skeptics mocked environmental cost and speculation. The boom tied internet culture to wallets and influencer shilling — then the 2022 crypto collapse wiped much of the floor-value hype while leaving legal and tax questions behind.",
  highlights: [
    "April 2021: Yuga Labs launched Bored Ape Yacht Club on Ethereum",
    "2021 peak: celebrity purchases and ape avatars flooded Twitter profile pictures",
    "\"Right-click save\" meme encapsulated mainstream skepticism of NFT ownership claims",
    "NFT market cooled sharply after the 2022 crypto collapse and FTX fallout",
  ],
  relatedSlugs: ["crypto-collapse-scandals", "gamestop-wallstreetbets", "twitter-x-transition", "influencer-culture"],
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Bored_Ape",
      title: "Bored Ape — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Bored_Ape",
      platform: "other",
      attribution: "Wikipedia contributors",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Bored Ape — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Bored_Ape",
      domain: "en.wikipedia.org",
    },
    {
      title: "NFT bubble — Wikipedia",
      url: "https://en.wikipedia.org/wiki/NFT_bubble",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
