import type { EventEntry } from "@/types";

const entry: EventEntry = {
  id: "e40",
  slug: "plane-bae",
  title: "Plane Bae",
  category: "event",
  description:
    "The July 2017 Twitter thread documenting a flirtation between strangers on a flight — viral romance until participants said it was partially staged.",
  imageGradient: "from-sky-400 via-indigo-300 to-purple-400",
  scores: { relevance: 36, influence: 68, cringe: 78, brainrot: 35 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 36,
    currentStatus: "classic",
    activePlatforms: [
      "x",
      "news",
    ],
    popularity: 25,
    trendingScore: 25,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Recent creation signals rose modestly. Signals: news/recent-articles=25 (Google News: 2 items in last 60d (40 returned) for “Plane Bae”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Plane Bae”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Plane”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-08-06",
      "[news/recent-articles] Google News: 2 items in last 60d (40 returned) for “Plane Bae”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Major news organization cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Plane Bae”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Plane Bae\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Recent creation signals rose modestly. Signals: news/recent-articles=25 (Google News: 2 items in last 60d (40 returned) for “Plane Bae”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "2017-07-06",
  views: 1600000,
  trendDirection: "declining",
  tags: ["2017", "twitter", "viral", "romance", "ethics"],
  platform: "Twitter, media",
  impact:
    "Rosey Blair live-tweeted photos and updates from an Alaska Airlines flight, inventing hashtags and a meet-cute narrative millions followed overnight. Brands jumped in; talk shows wanted the couple. Within days both passengers pushed back — one said attention was unwanted; Blair later acknowledged staging elements. Plane Bae became a lesson in consent, voyeuristic virality, and how Twitter could turn strangers into unwilling characters.",
  highlights: [
    "July 2017: Rosey Blair documented two passengers on a flight in a viral Twitter thread",
    "Thread gained millions of impressions and mainstream media coverage within 24 hours",
    "Passengers later said the attention was unwanted; staging questions followed",
    "Widely cited in debates about live-tweeting strangers and viral ethics",
  ],
  relatedSlugs: ["twitter-x-transition", "instagram-culture", "main-character-energy", "influencer-culture"],
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/plane-bae",
      title: "Plane Bae — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/plane-bae",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Plane Bae thread — BBC News",
      url: "https://www.bbc.com/news/blogs-trending-40548455",
      domain: "bbc.com",
    },
  ],
};

export default entry;
