import type { EventEntry } from "@/types";

const entry: EventEntry = {
  id: "e5",
  slug: "short-form-takeover",
  title: "Short-Form Video Takeover",
  category: "event",
  description:
    "How TikTok, Reels, and YouTube Shorts rewired attention spans and fundamentally changed how culture spreads.",
  imageGradient: "from-fuchsia-600 via-pink-500 to-rose-400",
  scores: { relevance: 36, influence: 99, cringe: 55, brainrot: 88 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 36,
    currentStatus: "classic",
    activePlatforms: [
      "tiktok",
      "news",
    ],
    popularity: 25,
    trendingScore: 25,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=25 (Google News: 2 items in last 60d (40 returned) for “Short-Form Video Takeover”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Character signals still mark this as strongly representative of chaotic internet brainrot culture. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Short-Form Video Takeover”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Short-Form”",
      "[news/recent-articles] Google News: 2 items in last 60d (40 returned) for “Short-Form Video Takeover”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Short-Form Video Takeover”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Short-Form Video Takeover\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/absurdity] Tag/title absurdity cue (brainrot character only)",
      "[catalog-evidence/gen-cohort-adoption] Cohort cue from tags/title (brainrot character only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=25 (Google News: 2 items in last 60d (40 returned) for “Short-Form Video Takeover”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Character signals still mark this as strongly representative of chaotic internet brainrot culture.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-05-20",
  lastUpdated: "2026-08-16",
  views: 3100000,
  trendDirection: "declining",
  platform: "TikTok, Instagram, YouTube",
  impact:
    "Permanently altered how trends are born and die. A meme can now go from zero to mainstream in 48 hours and be dead within a week. The entire internet culture lifecycle accelerated.",
  highlights: [
    "Average trend lifespan dropped from 3 weeks to under 5 days",
    "TikTok became the dominant search engine for Gen Z, surpassing Google for discovery",
    "Critics and creators argued over whether short-form feeds shortened attention spans",
    "The 'brain-rot' generation emerged as a response to short-form saturation",
  ],
  relatedSlugs: ["skibidi-toilet", "brainrot", "rizz"],
  tags: ["tiktok", "social media", "attention span", "gen z", "gen alpha"],
  media: [
    // AI suggested — human must verify URL and set verified: true
    // Platform branding defines the takeover — TikTok led; Shorts/Reels followed.
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/2/20/TikTok_app.jpg",
      title: "TikTok app icon on a smartphone home screen",
      source: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:TikTok_app.jpg",
      platform: "wikimedia",
      attribution: "Photograph of TikTok app icon (see Commons file page)",
      license: "See Commons file page",
      description:
        "TikTok's mobile presence — the platform that set the short-form standard competitors copied.",
      date: "2020",
      verified: false,
    },
    {
      role: "supporting",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/a/a6/Tiktok_icon.svg",
      title: "TikTok — official note icon",
      source: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Tiktok_icon.svg",
      platform: "wikimedia",
      attribution: "TikTok (CC0)",
      license: "CC0",
      description: "Clean official TikTok musical-note mark.",
      date: "2016",
      verified: false,
    },
    {
      role: "supporting",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/4/44/YouTube_Shorts_icon_2024.svg",
      title: "YouTube Shorts — 2024 icon",
      source: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:YouTube_Shorts_icon_2024.svg",
      platform: "wikimedia",
      attribution: "YouTube / Google (public domain textlogo)",
      license: "Public domain",
      description: "YouTube Shorts brand mark — Google's short-form competitor format.",
      date: "2024",
      verified: false,
    },
    {
      role: "supporting",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/3/32/Instagram_Reels_logo.svg",
      title: "Instagram Reels — official logo",
      source: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Instagram_Reels_logo.svg",
      platform: "wikimedia",
      attribution: "Meta / Instagram (public domain textlogo)",
      license: "Public domain",
      description: "Instagram Reels mark — Meta's short-form response to TikTok.",
      date: "2020",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/TikTok",
      title: "TikTok — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/TikTok",
      platform: "other",
      attribution: "Wikipedia contributors",
      description: "Context for the short-form platform that triggered the industry shift.",
      date: "2018",
      verified: false,
    },
  ],
  sources: [
    {
      title: "TikTok — Wikipedia",
      url: "https://en.wikipedia.org/wiki/TikTok",
      domain: "en.wikipedia.org",
    },
    {
      title: "YouTube Shorts — Wikipedia",
      url: "https://en.wikipedia.org/wiki/YouTube_Shorts",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
