import type { EventEntry } from "@/types";

const entry: EventEntry = {
  id: "e41",
  slug: "taylor-swift-eras-tour",
  title: "Taylor Swift Eras Tour",
  category: "event",
  description:
    "Taylor Swift's 2023–2024 stadium tour — a record-breaking live phenomenon that reshaped ticketing, local economies, and friendship-bracelet fan culture online.",
  imageGradient: "from-purple-600 via-pink-500 to-amber-400",
  scores: { relevance: 70, influence: 89, cringe: 25, brainrot: 45 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 96,
    currentStatus: "highly-active",
    activePlatforms: [
      "tiktok",
      "wikipedia",
      "news",
    ],
    popularity: 76,
    trendingScore: 61,
    recentRevival: false,
    popularityNotes: "Relevance: Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=76 (Google News: 27 items in last 60d (40 returned) for “Taylor Swift Eras Tour”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Character signals still mark this as strongly representative of chaotic internet brainrot culture. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=10,755 for “Taylor Swift: The Eras Tour”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=1961 prev7=2145 (-9%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Taylor”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-06-25",
      "[news/recent-articles] Google News: 27 items in last 60d (40 returned) for “Taylor Swift Eras Tour”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Taylor Swift Eras Tour”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Taylor Swift Eras Tour\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/gen-cohort-adoption] Cohort cue from tags/title (brainrot character only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=76 (Google News: 27 items in last 60d (40 returned) for “Taylor Swift Eras Tour”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Character signals still mark this as strongly representative of chaotic internet brainrot culture.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "2023-03-17",
  views: 8900000,
  trendDirection: "rising",
  tags: ["2023", "music", "taylor swift", "tour", "tiktok"],
  platform: "Stadiums, TikTok, Instagram, X",
  impact:
    "The Eras Tour opened in Glendale in March 2023 and became a moving city-block party: three-hour setlists spanning Swift's catalog, surprise songs, and bead-trading traditions documented nightly on TikTok. Ticketmaster's presale meltdown led to congressional scrutiny. Cities reported hotel and spending booms; \"Swiftie\" tourism became an economic story. Online, the tour proved how a pre-social artist could dominate algorithm culture through fan-generated clip networks.",
  highlights: [
    "March 17, 2023: The Eras Tour opened at State Farm Stadium in Glendale, Arizona",
    "Ticketmaster presale failures prompted a U.S. Senate hearing on competition and bots",
    "Tour gross passed $1 billion — among the highest-grossing concert runs ever reported",
    "Friendship bracelet trading and surprise-song clips became defining TikTok subcultures",
  ],
  relatedSlugs: ["tiktok-rise", "brat-summer", "instagram-culture", "creator-economy"],
  media: [
    // AI suggested — human must verify URL and set verified: true
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/c/c4/Taylor_Swift_The_Eras_Tour_Midnights_Era_Set_%2853109777579%29_%28cropped%29.jpg",
      title: "Taylor Swift — Eras Tour (2023)",
      source: "Wikimedia Commons / Paolo V",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Taylor_Swift_The_Eras_Tour_Midnights_Era_Set_(53109777579)_(cropped).jpg",
      platform: "wikimedia",
      attribution: "Paolo V (CC BY 2.0)",
      license: "CC BY 2.0",
      description: "Taylor Swift performing the Midnights era set on the Eras Tour.",
      date: "2023-08-09",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/The_Eras_Tour",
      title: "The Eras Tour — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/The_Eras_Tour",
      platform: "other",
      attribution: "Wikipedia contributors",
      verified: false,
    },
  ],
  sources: [
    {
      title: "The Eras Tour — Wikipedia",
      url: "https://en.wikipedia.org/wiki/The_Eras_Tour",
      domain: "en.wikipedia.org",
    },
    {
      title: "Ticketmaster Senate hearing — NPR",
      url: "https://www.npr.org/2023/01/31/1155030038/ticketmaster-taylor-swift-hearing-senate-judiciary-committee",
      domain: "npr.org",
    },
  ],
};

export default entry;
