import type { EventEntry } from "@/types";

const entry: EventEntry = {
  id: "e7",
  slug: "tiktok-rise",
  title: "TikTok's Rise",
  category: "event",
  description:
    "How TikTok (after the Musical.ly merger) became the default engine for global memes, music, slang, and short-form fame — and remade how internet culture spreads.",
  imageGradient: "from-pink-600 via-fuchsia-500 to-purple-600",
  scores: { relevance: 50, influence: 93, cringe: 38, brainrot: 88 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 50,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "tiktok",
      "news",
    ],
    popularity: 37,
    trendingScore: 37,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Recent creation looks limited versus active internet topics. Signals: news/recent-articles=37 (Google News: 4 items in last 60d (40 returned) for “TikTok's Rise”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Character signals still mark this as strongly representative of chaotic internet brainrot culture. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “TikTok's Rise”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “TikTok's”",
      "[news/recent-articles] Google News: 4 items in last 60d (40 returned) for “TikTok's Rise”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “TikTok's Rise”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"TikTok's Rise\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/absurdity] Tag/title absurdity cue (brainrot character only)",
      "[catalog-evidence/gen-cohort-adoption] Cohort cue from tags/title (brainrot character only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Recent creation looks limited versus active internet topics. Signals: news/recent-articles=37 (Google News: 4 items in last 60d (40 returned) for “TikTok's Rise”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Character signals still mark this as strongly representative of chaotic internet brainrot culture.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-16",
  lastUpdated: "2026-08-16",
  historicalDate: "2018-08-02",
  views: 2800000,
  trendDirection: "declining",
  platform: "TikTok",
  impact:
    "TikTok fundamentally changed how trends are born, spread, and die. Its recommendation algorithm — not follower counts — determines what goes viral. This shifted cultural power from established creators to anyone with a phone and an idea, and became the distribution layer for Gen Alpha brainrot, streamer slang, and modern meme formats.",
  highlights: [
    "ByteDance launched TikTok internationally in September 2017",
    "Merged with Musical.ly in August 2018, inheriting its US creator base",
    "Became the most downloaded app in the US in Q1 2018",
    "COVID-19 lockdowns in 2020 drove explosive growth worldwide",
    "Triggered repeated US ban attempts and global regulatory scrutiny from 2020 onward",
    "Became the primary surface for slang like rizz/gyatt and formats like NPC streaming",
  ],
  relatedSlugs: [
    "short-form-takeover",
    "vine-shutdown",
    "great-meme-reset",
    "npc-streaming",
    "brainrot",
    "rizz",
    "musical-ly",
    "creator-economy",
    "influencer-culture",
    "dupe-economy",
  ],
  relationships: {
    relatedTo: [
      "short-form-takeover",
      "vine-shutdown",
      "great-meme-reset",
      "musical-ly",
      "creator-economy",
      "influencer-culture",
      "dupe-economy",
    ],
    relatedEvent: ["musical-ly", "vine-shutdown"],
    relatedSlang: ["rizz", "brainrot"],
    spawnedVariants: ["npc-streaming"],
  },
  tags: [
    "tiktok",
    "social media",
    "algorithm",
    "short-form video",
    "viral",
    "gen z",
    "gen alpha",
  ],
  media: [
    // AI suggested — human must verify URL and set verified: true
    // Defining visual: official TikTok app icon on a phone home screen (branding, not a random creator).
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/2/20/TikTok_app.jpg",
      title: "TikTok app icon on a smartphone home screen",
      source: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:TikTok_app.jpg",
      platform: "wikimedia",
      attribution: "Photograph of TikTok app icon (see Commons file page)",
      license: "See Commons file page",
      description:
        "Official TikTok mobile app icon — the platform branding that defined its global rise.",
      date: "2020",
      verified: false,
    },
    {
      role: "supporting",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/a/a6/Tiktok_icon.svg",
      title: "TikTok — official note icon (SVG)",
      source: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Tiktok_icon.svg",
      platform: "wikimedia",
      attribution: "TikTok (CC0)",
      license: "CC0",
      description: "Clean official TikTok musical-note mark used as platform identity.",
      date: "2016",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/TikTok",
      title: "TikTok — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/TikTok",
      platform: "other",
      attribution: "Wikipedia contributors",
      description: "History of TikTok from Musical.ly merger through global scale.",
      date: "2018",
      verified: false,
    },
  ],
  sources: [
    {
      title: "TikTok — Wikipedia",
      url: "https://en.wikipedia.org/wiki/TikTok",
      domain: "en.wikipedia.org",
    },
    {
      title: "ByteDance — Wikipedia",
      url: "https://en.wikipedia.org/wiki/ByteDance",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
