import type { EventEntry } from "@/types";

const entry: EventEntry = {
  id: "e7",
  slug: "tiktok-rise",
  title: "TikTok's Rise",
  category: "event",
  description:
    "How TikTok (after the Musical.ly merger) became the default engine for global memes, music, slang, and short-form fame — and remade how internet culture spreads.",
  imageGradient: "from-pink-600 via-fuchsia-500 to-purple-600",
  scores: { relevance: 97, influence: 97, cringe: 40, brainrot: 70 },
  addedAt: "2026-07-16",
  historicalDate: "2018-08-02",
  views: 2800000,
  trendDirection: "stable",
  platform: "TikTok",
  impact:
    "TikTok fundamentally changed how trends are born, spread, and die. Its recommendation algorithm — not follower counts — determines what goes viral. This shifted cultural power from established creators to anyone with a phone and an idea, and became the distribution layer for Gen Alpha brainrot, streamer slang, and modern meme formats.",
  highlights: [
    "ByteDance launched TikTok internationally in September 2017",
    "Merged with Musical.ly in August 2018, inheriting its US creator base",
    "Became the most downloaded app in the US in Q1 2018",
    "COVID-19 lockdowns in 2020 drove explosive growth worldwide",
    "Triggered repeated US ban attempts and global regulatory scrutiny from 2020 onward",
    "Became the primary surface for slang like rizz/gyatt and formats like NPC streaming",
  ],
  relatedSlugs: [
    "short-form-takeover",
    "vine-shutdown",
    "great-meme-reset",
    "npc-streaming",
    "brainrot",
    "rizz",
    "musical-ly",
    "creator-economy",
    "influencer-culture",
    "dupe-economy",
  ],
  relationships: {
    relatedTo: [
      "short-form-takeover",
      "vine-shutdown",
      "great-meme-reset",
      "musical-ly",
      "creator-economy",
      "influencer-culture",
      "dupe-economy",
    ],
    relatedEvent: ["musical-ly", "vine-shutdown"],
    relatedSlang: ["rizz", "brainrot"],
    spawnedVariants: ["npc-streaming"],
  },
  tags: [
    "tiktok",
    "social media",
    "algorithm",
    "short-form video",
    "viral",
    "gen z",
    "gen alpha",
  ],
  media: [
    // AI suggested — human must verify URL and set verified: true
    // Defining visual: official TikTok app icon on a phone home screen (branding, not a random creator).
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/2/20/TikTok_app.jpg",
      title: "TikTok app icon on a smartphone home screen",
      source: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:TikTok_app.jpg",
      platform: "wikimedia",
      attribution: "Photograph of TikTok app icon (see Commons file page)",
      license: "See Commons file page",
      description:
        "Official TikTok mobile app icon — the platform branding that defined its global rise.",
      date: "2020",
      verified: false,
    },
    {
      role: "supporting",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/a/a6/Tiktok_icon.svg",
      title: "TikTok — official note icon (SVG)",
      source: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Tiktok_icon.svg",
      platform: "wikimedia",
      attribution: "TikTok (CC0)",
      license: "CC0",
      description: "Clean official TikTok musical-note mark used as platform identity.",
      date: "2016",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/TikTok",
      title: "TikTok — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/TikTok",
      platform: "other",
      attribution: "Wikipedia contributors",
      description: "History of TikTok from Musical.ly merger through global scale.",
      date: "2018",
      verified: false,
    },
  ],
  sources: [
    {
      title: "TikTok — Wikipedia",
      url: "https://en.wikipedia.org/wiki/TikTok",
      domain: "en.wikipedia.org",
    },
    {
      title: "ByteDance — Wikipedia",
      url: "https://en.wikipedia.org/wiki/ByteDance",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
