import type { EventEntry } from "@/types";

const entry: EventEntry = {
  id: "e6",
  slug: "vine-shutdown",
  title: "Vine Shutdown",
  category: "event",
  description:
    "Twitter's decision to shut down Vine in 2016 ended the first great short-form video era and scattered a generation of creators who went on to dominate YouTube and TikTok.",
  imageGradient: "from-lime-500 via-green-500 to-emerald-600",
  scores: { relevance: 63, influence: 82, cringe: 15, brainrot: 45 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 63,
    currentStatus: "current",
    activePlatforms: [
      "x",
      "news",
    ],
    popularity: 58,
    trendingScore: 58,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Creation volume is not peaking, but new content is still being produced regularly. Signals: news/recent-articles=58 (Google News: 12 items in last 60d (40 returned) for “Vine Shutdown”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Character signals still mark this as strongly representative of chaotic internet brainrot culture. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Vine Shutdown”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Vine”",
      "[dictionary/platform-activity] Wiktionary last revision 2025-11-01",
      "[news/recent-articles] Google News: 12 items in last 60d (40 returned) for “Vine Shutdown”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Vine Shutdown”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Vine Shutdown\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/gen-cohort-adoption] Cohort cue from tags/title (brainrot character only)",
      "Weak corroboration — blended heuristic (74) with AI double-check (52): Most signals reflect historical documentation rather than current buzz, with low Google Trends and modest recent news, indicating moderate but not high present interest.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Creation volume is not peaking, but new content is still being produced regularly. Signals: news/recent-articles=58 (Google News: 12 items in last 60d (40 returned) for “Vine Shutdown”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Character signals still mark this as strongly representative of chaotic internet brainrot culture.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-16",
  lastUpdated: "2026-08-16",
  historicalDate: "2017-01-17",
  views: 890000,
  trendDirection: "declining",
  platform: "Vine, Twitter",
  impact:
    "Vine's closure proved that even culturally essential platforms are not permanent. The creators it produced — Logan Paul, King Bach, David Dobrik, Lele Pons — became the first cohort of internet-native superstars and defined the creator economy that followed.",
  highlights: [
    "Twitter acquired Vine in October 2012 before it had even launched publicly",
    "Vine launched on January 24, 2013 — 6-second looping videos",
    "Twitter announced the shutdown on October 27, 2016",
    "Vine went offline on January 17, 2017 — archives were preserved",
    "Many Vine creators immediately migrated to YouTube and later TikTok",
  ],
  relatedSlugs: ["short-form-takeover", "yeet", "tiktok-rise", "harlem-shake", "rage-comics"],
  relationships: {
    relatedEvent: ["tiktok-rise", "short-form-takeover"],
    sameEra: ["harlem-shake"],
  },
  tags: ["vine", "twitter", "short-form video", "creators", "2016", "2017"],
  media: [
    // Official Vine wordmark — PD-textlogo on Commons (simple geometric logo).
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Vine_logo.svg",
      title: "Vine — official logo",
      source: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Vine_logo.svg",
      platform: "wikimedia",
      attribution: "Vine Labs, Inc. (PD-textlogo)",
      license: "Public domain (textlogo)",
      description:
        "Official Vine app logo — the visual identity of the short-form platform shut down in 2017.",
      date: "2013",
      verified: true,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Vine_(service)",
      title: "Vine (service) — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Vine_(service)",
      platform: "other",
      attribution: "Wikipedia contributors",
      description: "History of Vine from launch through the 2016–2017 shutdown.",
      date: "2017",
      verified: true,
    },
  ],
  sources: [
    {
      title: "Vine — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Vine_(service)",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
