import type { EventEntry } from "@/types";

const entry: EventEntry = {
  id: "e42",
  slug: "will-smith-oscars-slap",
  title: "Will Smith Oscar Slap",
  category: "event",
  description:
    "Will Smith striking Chris Rock on live TV at the 2022 Academy Awards after a joke about Jada Pinkett Smith — an instantly memed Oscars moment.",
  imageGradient: "from-yellow-500 via-amber-400 to-neutral-900",
  scores: { relevance: 80, influence: 87, cringe: 35, brainrot: 40 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 80,
    currentStatus: "current",
    activePlatforms: [
      "wikipedia",
      "news",
    ],
    popularity: 63,
    trendingScore: 52,
    recentRevival: false,
    popularityNotes: "Relevance: Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=63 (Google News: 15 items in last 60d (40 returned) for “Will Smith Oscar Slap”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Character signals still mark this as strongly representative of chaotic internet brainrot culture. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=39,769 for “Chris Rock–Will Smith slapping incident”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=9222 prev7=10753 (-14%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Will”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-07-18",
      "[news/recent-articles] Google News: 15 items in last 60d (40 returned) for “Will Smith Oscar Slap”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited; Major news organization cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Will Smith Oscar Slap”",
      "[bluesky/discussion-volume] Bluesky search unavailable for \"Will Smith Oscar Slap\"",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/absurdity] Tag/title absurdity cue (brainrot character only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "bluesky",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=63 (Google News: 15 items in last 60d (40 returned) for “Will Smith Oscar Slap”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Character signals still mark this as strongly representative of chaotic internet brainrot culture.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "2022-03-27",
  views: 7200000,
  trendDirection: "declining",
  tags: ["2022", "oscars", "viral", "awards", "meme-event"],
  platform: "ABC, Twitter, TikTok, YouTube",
  impact:
    "During the 94th Oscars broadcast, Chris Rock joked about Jada Pinkett Smith's hair; Will Smith walked on stage and slapped Rock, then won Best Actor minutes later. Clips circulated before the show ended — reaction GIFs, audio-only memes, and debate about violence vs. comedy on live TV. The Academy banned Smith from attending Oscars events for 10 years in April 2022. The moment joined Kanye–Taylor and envelope chaos as Oscars infrastructure breaking into pure internet event.",
  highlights: [
    "March 27, 2022: Will Smith slapped Chris Rock on stage at the 94th Academy Awards",
    "Smith later won Best Actor for King Richard during the same broadcast",
    "The Academy banned Smith from attending Oscars events for 10 years in April 2022",
    "Clips and memes spread globally within minutes of the live broadcast",
  ],
  relatedSlugs: ["tiktok-rise", "twitter-x-transition", "influencer-culture", "cringe"],
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Chris_Rock%E2%80%93Will_Smith_slapping_incident",
      title: "Chris Rock–Will Smith slapping incident — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Chris_Rock%E2%80%93Will_Smith_slapping_incident",
      platform: "other",
      attribution: "Wikipedia contributors",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Chris Rock–Will Smith slapping incident — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Chris_Rock%E2%80%93Will_Smith_slapping_incident",
      domain: "en.wikipedia.org",
    },
    {
      title: "Oscars slap — BBC News",
      url: "https://www.bbc.com/news/entertainment-arts-60887337",
      domain: "bbc.com",
    },
  ],
};

export default entry;
