import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m99",
  slug: "always-has-been",
  title: "Always Has Been",
  category: "meme",
  description:
    "Two astronauts in space — one discovers a shocking truth about Earth, the other replies 'Always has been' while aiming a gun.",
  imageGradient: "from-slate-700 via-blue-900 to-indigo-800",
  scores: { relevance: 62, influence: 65, cringe: 21, brainrot: 41 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 88,
    currentStatus: "highly-active",
    activePlatforms: [
      "wikipedia",
      "news",
    ],
    popularity: 64,
    trendingScore: 82,
    recentRevival: true,
    popularityNotes: "Relevance: Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: wikipedia/editorial-trend=100 (Pageviews WoW last7=16 prev7=4 (300%)); news/recent-articles=64 (Google News: 16 items in last 60d (40 returned) for “Always Has Been”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Character signals still mark this as strongly representative of chaotic internet brainrot culture. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=33 for “Always Has Been”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=16 prev7=4 (300%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Always”",
      "[news/recent-articles] Google News: 16 items in last 60d (40 returned) for “Always Has Been”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] No Wikipedia / KYM / dictionary / major-news URLs on entry sources",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Always Has Been”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/absurdity] Tag/title absurdity cue (brainrot character only)",
      "[catalog-evidence/gen-cohort-adoption] Cohort cue from tags/title (brainrot character only)",
      "[catalog-evidence/remix-activity] Format/remix / short-form reuse cue (brainrot character only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: wikipedia/editorial-trend=100 (Pageviews WoW last7=16 prev7=4 (300%)); news/recent-articles=64 (Google News: 16 items in last 60d (40 returned) for “Always Has Been”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Character signals still mark this as strongly representative of chaotic internet brainrot culture.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "2016-12-11",
  views: 5200000,
  trendDirection: "rising",
  tags: ["astronaut", "exploitable", "2020", "ohio", "conspiracy", "template"],
  meaning:
    "An exploitable two-panel meme: Astronaut A realizes the planet is entirely made of something unexpected ('Wait, it's all X?'). Astronaut B, already holding a gun, confirms the secret was always known ('Always has been'). Used for ironic reveals, inside jokes, and bait-and-switch punchlines — the Ohio version ('Wait, it's all Ohio?') became the most famous variant.",
  origin:
    "Know Your Meme traces the earliest version to December 11, 2016, when Redditor Wiegand6 posted an MS Paint drawing to r/dankmemes showing astronauts discovering a flat Earth; the armed astronaut said 'Sry fam.' In August 2018, a 4chan post used the 'Wait, it's all America?' / 'Always has been' phrasing. The Ohio punchline spread via iFunny user iOhioian in October 2019. A photorealistic astronaut template went viral on Reddit in June 2020 during lockdown meme culture.",
  timeline: [
    { date: "Dec 2016", event: "Earliest MS Paint astronaut meme on r/dankmemes (flat Earth version)" },
    { date: "Aug 2018", event: "4chan post introduces 'Wait, it's all America?' / 'Always has been'" },
    { date: "Oct 2019", event: "Ohio variant spreads on iFunny — ties into 'Ohio vs. the World' jokes" },
    { date: "Jun 2020", event: "High-res astronaut template explodes on Reddit and Twitter" },
    { date: "2020–2022", event: "Becomes a default exploitable format across platforms" },
  ],
  examples: [
    "Wait, it's all Ohio? Always has been.",
    "Wait, it's all capitalism? Always has been. [gun]",
    "Discovering your favorite show was cancelled years ago — Always has been",
  ],
  relatedSlugs: ["ohio-final-boss", "this-is-fine", "expanding-brain"],
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/wait-its-all-ohio-always-has-been",
      title: "Wait, It's All Ohio? Always Has Been — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/wait-its-all-ohio-always-has-been",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Full origin timeline from 2016 MS Paint to 2020 viral template.",
      date: "2020",
      verified: false,
    },
  ],
  sources: [
    {
      title: "What Is The 'Always Has Been' Meme? — Yahoo Entertainment",
      url: "https://www.yahoo.com/entertainment/articles/always-meme-classic-wait-ohio-154500379.html",
      domain: "yahoo.com",
    },
  ],
};

export default entry;
