import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m45",
  slug: "among-us-era",
  title: "Among Us Meme Era",
  category: "meme",
  description:
    "The 2020 Among Us boom — crewmate impostor jokes, 'sus,' emergency meetings, and endless fan content.",
  imageGradient: "from-red-600 via-rose-500 to-orange-400",
  scores: { relevance: 44, influence: 78, cringe: 21, brainrot: 42 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 44,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "tiktok",
      "twitch",
      "wikipedia",
      "news",
    ],
    popularity: 32,
    trendingScore: 40,
    recentRevival: false,
    popularityNotes: "Relevance: Recent creation signals rose modestly. Signals: news/recent-articles=32 (Google News: 3 items in last 60d (40 returned) for “Among Us Meme Era”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Character signals still mark this as strongly representative of chaotic internet brainrot culture. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=24,372 for “Karen (slang)”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=5078 prev7=5326 (-5%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Among”",
      "[news/recent-articles] Google News: 3 items in last 60d (40 returned) for “Among Us Meme Era”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Among Us Meme Era”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/absurdity] Tag/title absurdity cue (brainrot character only)",
      "[catalog-evidence/gen-cohort-adoption] Cohort cue from tags/title (brainrot character only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Recent creation signals rose modestly. Signals: news/recent-articles=32 (Google News: 3 items in last 60d (40 returned) for “Among Us Meme Era”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Character signals still mark this as strongly representative of chaotic internet brainrot culture.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-18",
  lastUpdated: "2026-08-16",
  historicalDate: "2020-08-01",
  views: 7000000,
  trendDirection: "stable",
  tags: ["among-us", "2020", "gaming", "sus", "tiktok", "twitch"],
  meaning:
    "A catch-all for the meme culture around InnerSloth's Among Us during its 2020 explosion: calling things 'sus,' impostor jokes, 'emergency meeting' edits, and the bean-shaped crewmates as reaction avatars. The game became a shared language for betrayal and group chaos.",
  origin:
    "Among Us (2018) exploded in popularity in mid-to-late 2020 via Twitch streamers and TikTok. Memes, fan animations, and slang (especially 'sus') flooded every platform, defining a distinct COVID-era gaming meme moment.",
  timeline: [
    { date: "2018", event: "Among Us released with modest audience" },
    { date: "Summer–Fall 2020", event: "Streamer-driven boom; memes go mainstream" },
    { date: "2021+", event: "Peak fades; 'sus' and crewmate imagery remain in the lexicon" },
  ],
  examples: [
    "Someone acting weird in a group chat: 'kinda sus'",
    "Emergency meeting edits over everyday arguments",
  ],
  relatedSlugs: ["sus", "great-meme-reset", "coffin-dance", "npc", "brainrot"],
  relationships: {
    relatedSlang: ["sus"],
    sameEra: ["coffin-dance", "great-meme-reset"],
    relatedEvent: ["great-meme-reset"],
  },
  media: [
    // AI suggested — KYM Among Us entry icon; human must verify
    {
      role: "featured",
      type: "image",
      url: "https://i.kym-cdn.com/entries/icons/original/000/035/151/among_us.jpg",
      title: "Among Us — crewmate meme imagery",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/among-us",
      platform: "knowyourmeme",
      attribution: "InnerSloth / via Know Your Meme documentation",
      description: "Representative Among Us crewmate visual from the meme era.",
      date: "2020",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/among-us",
      title: "Among Us — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/among-us",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Documentation of Among Us meme culture.",
      date: "2020",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Among Us — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Among_Us",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
