import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m100",
  slug: "ancient-aliens-guy",
  title: "Ancient Aliens Guy",
  category: "meme",
  description:
    "Giorgio A. Tsoukalos from History Channel's Ancient Aliens — the wild-haired presenter whose gesture means 'aliens did it.'",
  imageGradient: "from-amber-600 via-yellow-500 to-orange-400",
  scores: { relevance: 4, influence: 80, cringe: 21, brainrot: 32 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 4,
    currentStatus: "historical",
    activePlatforms: [
      "wikipedia",
    ],
    popularity: 0,
    trendingScore: 27,
    recentRevival: false,
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (40 returned) for “Ancient Aliens Guy”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=15,679 for “List of Internet phenomena”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=3905 prev7=3683 (6%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Ancient”",
      "[news/recent-articles] Google News: 0 items in last 60d (40 returned) for “Ancient Aliens Guy”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Ancient Aliens Guy”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "Weak corroboration — blended heuristic (0) with AI double-check (7): Sparse recent activity, no news coverage, low Google Trends and modest Wikipedia traffic indicate the meme is barely noticeable right now.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (40 returned) for “Ancient Aliens Guy”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "2010-04-20",
  views: 4500000,
  trendDirection: "declining",
  tags: ["ancient-aliens", "reaction", "history-channel", "2010s", "conspiracy", "classic"],
  meaning:
    "A reaction image and caption format attributing any unexplained phenomenon to ancient astronauts. The still of Giorgio Tsoukalos gesturing with spiked hair is pasted over history, science, or everyday mysteries with text like 'Aliens.' It mocks (and celebrates) the leap from evidence to extraterrestrial explanation.",
  origin:
    "Giorgio A. Tsoukalos is a Swiss-born television presenter and ancient-astronaut proponent who became the face of Ancient Aliens on the History Channel; the series premiered in April 2010. Meme use of his expressive gestures and hair spread on Reddit, Tumblr, and Imgur in the early 2010s as the show gained a cult following. Know Your Meme documents the 'Ancient Aliens' meme format as one of the decade's durable reaction templates.",
  timeline: [
    { date: "Apr 2010", event: "Ancient Aliens premieres on History Channel" },
    { date: "2011–2013", event: "Tsoukalos reaction images spread on Reddit and Tumblr" },
    { date: "2013", event: "Meme Generator and quick-caption formats popularize 'Aliens' overlay" },
    { date: "2015+", event: "Becomes a mainstream shorthand for absurd causal leaps" },
    { date: "2020s", event: "Still used whenever someone over-explains with conspiracy energy" },
  ],
  examples: [
    "Pyramids exist → [Ancient Aliens Guy] Aliens.",
    "I lost my keys — must be ancient astronauts",
    "Captioning any historical mystery with Tsoukalos and 'Aliens'",
  ],
  relatedSlugs: ["philosoraptor", "expanding-brain", "is-this-a-pigeon"],
  media: [
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/8/8a/Giorgio_Tsoukalos_%28crop%29.jpg",
      title: "Giorgio A. Tsoukalos — Ancient Aliens presenter",
      source: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Giorgio_Tsoukalos_(crop).jpg",
      platform: "wikimedia",
      attribution: "Gage Skidmore / CC BY-SA 3.0",
      license: "CC BY-SA 3.0",
      description:
        "Portrait of Giorgio Tsoukalos, whose Ancient Aliens appearances define the meme.",
      date: "2010",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/ancient-aliens",
      title: "Ancient Aliens — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/ancient-aliens",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Documentation of the Ancient Aliens meme format and spread.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Ancient Aliens — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Ancient_Aliens",
      domain: "en.wikipedia.org",
    },
    {
      title: "Giorgio A. Tsoukalos — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Giorgio_A._Tsoukalos",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
