import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m53",
  slug: "arthurs-fist",
  title: "Arthur's Fist",
  category: "meme",
  description:
    "The clenched-fist Arthur Read still — the internet's default reaction image for bottled rage and 'mood.'",
  imageGradient: "from-amber-400 via-yellow-500 to-orange-600",
  scores: { relevance: 34, influence: 72, cringe: 21, brainrot: 32 },
  dynamicMetadata: {
    lastReviewed: "2026-07-25",
    currentRelevance: 34,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "x",
      "wikipedia",
    ],
    popularity: 39,
    trendingScore: 27,
    recentRevival: false,
    popularityNotes: "Status: occasionally-referenced · Relevance 34 (today's recognition, not influence) · Trending 27 (recent attention)",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=16,889 for “List of Internet phenomena”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=3790 prev7=3720 (2%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Arthur's”",
      "[news/recent-articles] Google News: 1 items in last 30d (40 returned) for “Arthur's Fist”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Know Your Meme cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Arthur's Fist”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/remix-activity] Format/remix cue (brainrot/cringe only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
  },
  addedAt: "2026-07-18",
  lastUpdated: "2026-07-25",
  historicalDate: "2016-07-27",
  views: 4100000,
  trendDirection: "declining",
  tags: ["reaction", "classic", "arthur", "2016", "twitter", "frustration"],
  meaning:
    "A reaction still of Arthur Read clenching his fist, used to signal suppressed anger, irritation, or intense 'mood' without a rant. Captions usually describe the frustrating situation above the fist.",
  origin:
    "The frame comes from the Arthur episode where Arthur punches D.W. (already famous via YouTube Poop edits). As a standalone reaction, Twitter user @AlmostJT posted the fist as 'relatable' in July 2016; it spread across Twitter and Reddit through 2016–17, with celebrity uses (e.g. LeBron James) amplifying it (Know Your Meme).",
  timeline: [
    { date: "1990s–2000s", event: "Source scene airs on Arthur; later YouTube Poop fame" },
    { date: "Jul 2016", event: "Fist still posted as a reaction image on Twitter" },
    { date: "2016–17", event: "Captions about everyday frustrations go mainstream" },
    { date: "Nov 2017", event: "LeBron James Instagram 'mood' post sparks debate" },
  ],
  examples: [
    "When someone says the microwave second doesn't count",
    "Group chat when the plans change for the third time",
    "Caption: 'mood' under the clenched fist alone",
  ],
  relatedSlugs: ["surprised-pikachu", "hide-the-pain-harold", "woman-yelling-at-cat"],
  relationships: {
    sameFormat: ["surprised-pikachu", "hide-the-pain-harold"],
    relatedTo: ["woman-yelling-at-cat"],
  },
  media: [
    // AI suggested — KYM icon is the defining fist still
    {
      role: "featured",
      type: "image",
      url: "https://i.kym-cdn.com/entries/icons/original/000/021/018/arthur.jpg",
      title: "Arthur's Fist — clenched fist reaction still",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/arthurs-fist",
      platform: "knowyourmeme",
      attribution: "Arthur / PBS Kids still (via Know Your Meme documentation)",
      description: "The clenched-fist Arthur frame used as a frustration reaction meme.",
      date: "2016",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/arthurs-fist",
      title: "Arthur's Fist — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/arthurs-fist",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Origin and celebrity uses of the Arthur's Fist reaction.",
      date: "2016",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Arthur's Fist — Wikipedia search",
      url: "https://en.wikipedia.org/w/index.php?search=Arthur%27s+Fist&title=Special:Search&fulltext=1",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
