import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m104",
  slug: "big-chungus",
  title: "Big Chungus",
  category: "meme",
  description:
    "An absurdly fat Bugs Bunny from a 1941 cartoon, repackaged as a fake PS4 game — one of 2018's most nonsensical viral jokes.",
  imageGradient: "from-gray-600 via-slate-500 to-zinc-400",
  scores: { relevance: 23, influence: 72, cringe: 21, brainrot: 32 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 23,
    currentStatus: "classic",
    activePlatforms: [
      "reddit",
      "wikipedia",
    ],
    popularity: 16,
    trendingScore: 35,
    recentRevival: false,
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=16 (Google News: 1 items in last 60d (40 returned) for “Big Chungus”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=15,679 for “List of Internet phenomena”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=3905 prev7=3683 (6%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Big”",
      "[news/recent-articles] Google News: 1 items in last 60d (40 returned) for “Big Chungus”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Big Chungus”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "Weak corroboration — blended heuristic (25) with AI double-check (20): The modest Wikipedia traffic, minimal news coverage, and lack of Google Trends activity indicate only low residual awareness, supporting a low current popularity around 20.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=16 (Google News: 1 items in last 60d (40 returned) for “Big Chungus”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "2018-12-01",
  views: 3600000,
  trendDirection: "stable",
  tags: ["bugs-bunny", "absurdist", "2018", "reddit", "looney-tunes", "classic"],
  meaning:
    "A deliberately stupid meme: a frame of obese Bugs Bunny from the 1941 short Wabbit Twouble, labeled 'Big Chungus' on a mock PlayStation 4 game cover. The humor is pure anti-comedy — treating a nonsense title like a real AAA release. It spread when a GameStop employee story about a customer asking for the fake game went viral.",
  origin:
    "Reddit user GaryTheTaco (Braden) created the PS4 cover meme privately on March 20, 2018, and posted it publicly to r/comedyheaven on December 1, 2018. The image uses a frame from Wabbit Twouble (1941) where Bugs inflates to mock Elmer Fudd. Know Your Meme documents the GameStop anecdote and Warner Bros.' later official acknowledgment as drivers of late-2018 virality.",
  timeline: [
    { date: "1941", event: "Wabbit Twouble releases — source cartoon for the fat Bugs frame" },
    { date: "Mar 2018", event: "GaryTheTaco creates the Big Chungus PS4 cover meme privately" },
    { date: "Dec 1, 2018", event: "First public Reddit post to r/comedyheaven" },
    { date: "Dec 2018", event: "GameStop customer story goes viral; meme explodes across Reddit" },
    { date: "2019+", event: "Warner Bros. references; remains an absurdist classic" },
  ],
  examples: [
    "Customer asks GameStop for Big Chungus — employee confusion story",
    "Fake sequel covers: Big Chungus 2, Xbox edition, Nintendo Switch",
    "Using 'chungus' as slang for anything comically oversized",
  ],
  relatedSlugs: ["doge", "dat-boi", "pepe"],
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/big-chungus",
      title: "Big Chungus — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/big-chungus",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Origin interview with creator GaryTheTaco and viral timeline.",
      date: "2018",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Big_Chungus",
      title: "Big Chungus — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Big_Chungus",
      platform: "wikimedia",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Big Chungus — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Big_Chungus",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
