import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m107",
  slug: "caught-in-4k",
  title: "Caught in 4K",
  category: "meme",
  description:
    "Claiming someone was 'caught in 4K' — meaning undeniable, ultra-HD proof they said or did something they can't deny.",
  imageGradient: "from-red-600 via-rose-500 to-pink-400",
  scores: { relevance: 51, influence: 68, cringe: 21, brainrot: 32 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 51,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "x",
      "wikipedia",
      "news",
    ],
    popularity: 41,
    trendingScore: 48,
    recentRevival: false,
    popularityNotes: "Relevance: Recent creation signals rose modestly. Signals: news/recent-articles=41 (Google News: 5 items in last 60d (40 returned) for “Caught in 4K”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=15,679 for “List of Internet phenomena”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=3905 prev7=3683 (6%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Caught”",
      "[news/recent-articles] Google News: 5 items in last 60d (40 returned) for “Caught in 4K”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Dictionary / Britannica cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Caught in 4K”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "Weak corroboration — blended heuristic (54) with AI double-check (48): Signals show modest, steady interest without a recent spike, so current popularity is moderate rather than high.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Recent creation signals rose modestly. Signals: news/recent-articles=41 (Google News: 5 items in last 60d (40 returned) for “Caught in 4K”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "2019-01-01",
  views: 2400000,
  trendDirection: "stable",
  tags: ["4k", "receipts", "twitter", "callout", "2019", "phrase"],
  meaning:
    "Internet slang for catching someone with irrefutable evidence — originally referencing 4K video quality as 'too clear to deny.' Used when a screenshot, clip, or archived post exposes hypocrisy, lies, or embarrassing behavior. The meme treats high-definition proof like a courtroom smoking gun.",
  origin:
    "Know Your Meme documents 'caught in 4K' rising on Black Twitter and YouTube drama commentary in the late 2010s as 4K TVs and cameras became mainstream talking points. The phrase escalated 'got caught' into a tech-flavored boast about evidence quality. It spread through reaction videos, quote-tweets, and fandom callout culture.",
  timeline: [
    { date: "Late 2010s", event: "'4K' enters slang as shorthand for ultra-clear video quality" },
    { date: "2019", event: "'Caught in 4K' spreads on Twitter and YouTube commentary" },
    { date: "2020–2021", event: "TikTok and meme pages adopt the phrase for expose edits" },
    { date: "2022+", event: "Standard callout language across fandom and politics Twitter" },
  ],
  examples: [
    "They said they never said it — here's the clip. Caught in 4K.",
    "Screenshot archive exposing a deleted tweet — 4K no cap",
    "Reaction thumbnail: 'BRO GOT CAUGHT IN 4K 💀'",
  ],
  relatedSlugs: ["side-eyeing-chloe", "woman-yelling-at-cat", "press-x-to-doubt"],
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/caught-in-4k",
      title: "Caught in 4K — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/caught-in-4k",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Documentation of the phrase and evidence-meme usage.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Caught in 4K — Urban Dictionary",
      url: "https://www.urbandictionary.com/define.php?term=Caught%20in%204k",
      domain: "urbandictionary.com",
    },
  ],
};

export default entry;
