import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m1",
  slug: "chicken-jockey",
  title: "Chicken Jockey",
  category: "meme",
  description:
    "A Minecraft movie scene that triggered legendary live-audience reactions worldwide.",
  imageGradient: "from-green-500 via-lime-400 to-yellow-300",
  scores: { relevance: 33, influence: 70, cringe: 21, brainrot: 41 },
  dynamicMetadata: {
    lastReviewed: "2026-07-24",
    currentRelevance: 33,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "news",
    ],
    popularity: 37,
    trendingScore: 28,
    recentRevival: false,
    popularityNotes: "Status: occasionally-referenced · Relevance 33 (today's recognition, not influence) · Trending 28 (recent attention)",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Chicken Jockey”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Chicken”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-05-10",
      "[news/recent-articles] Google News: 2 items in last 30d (40 returned) for “Chicken Jockey”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Know Your Meme cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Chicken Jockey”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/remix-activity] Format/remix cue (brainrot/cringe only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
  },
  addedAt: "2026-07-12",
  lastUpdated: "2026-07-24",
  views: 2100000,
  trendDirection: "declining",
  meaning:
    "Refers to a brief Minecraft Movie cameo where a baby zombie rides a chicken — audiences screamed, memed, and made it a cultural event.",
  origin:
    "In Minecraft, a chicken jockey is a baby zombie riding a chicken — a rare hostile mob players already knew from the game. A Minecraft Movie (April 2025) turned Jack Black's Steve yelling 'Chicken jockey!' into a theater ritual: teens cheered, stood on seats, and filmed the chaos for TikTok. Vulture, BBC News, and Minecraft Wiki document the wave — some cinemas banned unaccompanied minors after vandalism reports, while UK chain Cineworld ran special 'Chicken Jockey' participation screenings. The meme is less about the mob itself and more about the shared scream when the line hits.",
  timeline: [
    { date: "Pre-2025", event: "Chicken jockey exists as a Minecraft mob (baby zombie on a chicken)" },
    { date: "Mar–Apr 2025", event: "Trailers and opening weekend amplify Jack Black's 'Chicken jockey!' line" },
    { date: "Apr 2025", event: "Theater reaction videos flood TikTok; some venues restrict minors" },
    { date: "Apr 2025+", event: "Cineworld and others host participatory Chicken Jockey screenings" },
  ],
  examples: [
    "The whole theater screamed 'Chicken jockey!' with Jack Black.",
    "We went feral over a three-second chicken jockey moment.",
    "Did you know a chicken jockey is a baby zombie riding a chicken in Minecraft?",
    "My group chat after the movie: chicken jockey changed cinema forever.",
  ],
  relatedSlugs: [
    "minecraft-movie-premiere",
    "ohio-final-boss",
    "skibidi-toilet",
    "brainrot",
    "dream",
  ],
  relationships: {
    relatedEvent: ["minecraft-movie-premiere"],
    relatedTo: ["ohio-final-boss", "skibidi-toilet", "brainrot"],
    community: ["dream"],
  },
  media: [
    // Official Warner Bros. Chicken Jockey movie clip — oembed + hqdefault verified.
    {
      role: "featured",
      type: "image",
      url: "https://i.ytimg.com/vi/EY4h38NaXwU/hqdefault.jpg",
      title: "A Minecraft Movie — Chicken Jockey clip thumbnail",
      source: "YouTube / Warner Bros. Entertainment",
      sourceUrl: "https://www.youtube.com/watch?v=EY4h38NaXwU",
      platform: "youtube",
      attribution: "Warner Bros. Entertainment",
      license: "YouTube Standard License",
      description:
        "Official Warner Bros. movie-clip thumbnail for the Chicken Jockey scene that drove theater reaction memes.",
      date: "2025",
      verified: true,
    },
    {
      role: "video",
      type: "video",
      url: "https://www.youtube.com/watch?v=EY4h38NaXwU",
      title: "A Minecraft Movie | Chicken Jockey | Movie Clip",
      source: "YouTube / Warner Bros. Entertainment",
      sourceUrl: "https://www.youtube.com/watch?v=EY4h38NaXwU",
      platform: "youtube",
      attribution: "Warner Bros. Entertainment",
      license: "YouTube Standard License",
      description:
        "Official Warner Bros. Chicken Jockey clip from A Minecraft Movie — the defining visual of the meme.",
      date: "2025",
      verified: true,
    },
    {
      role: "supporting",
      type: "image",
      url: "https://i.ytimg.com/vi/wJO_vIDZn-I/hqdefault.jpg",
      title: "A Minecraft Movie — Official Trailer thumbnail",
      source: "YouTube / Warner Bros.",
      sourceUrl: "https://www.youtube.com/watch?v=wJO_vIDZn-I",
      platform: "youtube",
      attribution: "Warner Bros. Pictures",
      license: "YouTube Standard License",
      description:
        "Official movie trailer thumbnail — broader Minecraft Movie context for the Chicken Jockey meme.",
      date: "2024-11-19",
      verified: true,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/chicken-jockey",
      title: "Chicken Jockey — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/chicken-jockey",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Documentation of theater reactions and the Chicken Jockey meme wave.",
      date: "2025",
      verified: true,
    },
  ],
  sources: [
    {
      title: "A Minecraft Movie — Official Site",
      url: "https://www.minecraftmovie.com",
      domain: "minecraftmovie.com",
    },
    {
      title: "Chicken Jockey Meme: Minecraft Movie Trend, Explained — Vulture",
      url: "https://www.vulture.com/article/chicken-jockey-meme-minecraft-movie-explained.html",
      domain: "vulture.com",
    },
    {
      title: "Suffolk cinemas react to Minecraft movie chicken jockey trend — BBC News",
      url: "https://www.bbc.com/news/articles/cy8ee0er3yro",
      domain: "bbc.com",
    },
    {
      title: "Movie:Chicken jockey sensation — Minecraft Wiki",
      url: "https://minecraft.wiki/w/Movie:Chicken_jockey_sensation",
      domain: "minecraft.wiki",
    },
  ],
};

export default entry;
