import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m26",
  slug: "corn-kid",
  title: "Corn Kid",
  category: "meme",
  description:
    "Tariq, interviewed by Recess Therapy in September 2022, described his love for corn so vividly that the clip spread across TikTok and YouTube — then became an Auto-Tuned hit and months of affectionate memes.",
  imageGradient: "from-yellow-400 via-amber-400 to-yellow-300",
  scores: { relevance: 32, influence: 75, cringe: 21, brainrot: 34 },
  dynamicMetadata: {
    lastReviewed: "2026-07-25",
    currentRelevance: 32,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "tiktok",
      "news",
    ],
    popularity: 32,
    trendingScore: 31,
    recentRevival: false,
    popularityNotes: "Status: occasionally-referenced · Relevance 32 (today's recognition, not influence) · Trending 31 (recent attention)",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Corn Kid”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Corn”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-01-20",
      "[news/recent-articles] Google News: 4 items in last 30d (40 returned) for “Corn Kid”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Know Your Meme cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Corn Kid”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/gen-cohort-adoption] Cohort cue from tags (not used for relevance/trending)",
      "[catalog-evidence/remix-activity] Format/remix cue (brainrot/cringe only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
  },
  addedAt: "2026-07-17",
  lastUpdated: "2026-07-25",
  historicalDate: "2022-09-07",
  views: 2800000,
  trendDirection: "declining",
  tags: ["kids", "viral", "tiktok", "2022", "food", "wholesome"],
  meaning:
    "Corn Kid represents genuine, unironic enthusiasm — the internet loved Tariq not just for talking about corn but for the purity of his excitement. He became a symbol of wholesome virality in an era of cynical internet content. The phrase 'it's corn!' is used to express pure, simple joy about something.",
  origin:
    "Julian Shapiro-Barnum, creator of the Recess Therapy YouTube channel, interviewed a child named Tariq at a summer camp in September 2022. In the clip, Tariq describes his love for corn with extraordinary eloquence: 'It's corn! A big lump with knobs! It has the juice!' The interview was posted on September 7, 2022. The Gregory Brothers subsequently turned the audio into an Auto-Tuned song 'It's Corn' that topped charts and was featured on major outlets. Tariq appeared on Jimmy Fallon's Tonight Show.",
  timeline: [
    { date: "Sep 7, 2022", event: "Recess Therapy posts the Tariq corn interview on TikTok" },
    { date: "Sep 2022", event: "Clip goes viral across TikTok, Twitter, and YouTube" },
    { date: "Sep 2022", event: "The Gregory Brothers create 'It's Corn' auto-tuned song — millions of streams" },
    { date: "Sep 2022", event: "Tariq appears on The Tonight Show with Jimmy Fallon" },
    { date: "Oct 2022", event: "National Corn Association names Tariq an official ambassador" },
    { date: "2023+", event: "Corn Kid remains a beloved wholesome internet figure" },
  ],
  examples: [
    "'It's corn! A big lump with knobs! It has the juice!'",
    "Posting a photo of a good meal: 'it's corn 🌽' [unrelated but pure joy]",
    "When someone likes something with unironic enthusiasm: 'Corn Kid energy'",
  ],
  relatedSlugs: [
    "charlie-bit-my-finger",
    "david-after-dentist",
    "leave-britney-alone",
    "hawk-tuah",
  ],
  media: [
    // Official Recess Therapy interview — the origin clip (oembed + hqdefault verified).
    {
      role: "featured",
      type: "image",
      url: "https://i.ytimg.com/vi/1VbZE6YhjKk/hqdefault.jpg",
      title: "The CEO of Corn — Recess Therapy thumbnail",
      source: "YouTube / Recess Therapy",
      sourceUrl: "https://www.youtube.com/watch?v=1VbZE6YhjKk",
      platform: "youtube",
      attribution: "Recess Therapy",
      license: "YouTube Standard License",
      description:
        "Official Recess Therapy thumbnail for Tariq's corn interview — the clip that launched Corn Kid.",
      date: "2022-08-04",
      verified: true,
    },
    {
      role: "video",
      type: "video",
      url: "https://www.youtube.com/watch?v=1VbZE6YhjKk",
      title: "The CEO of Corn | Recess Therapy #cornboy",
      source: "YouTube / Recess Therapy",
      sourceUrl: "https://www.youtube.com/watch?v=1VbZE6YhjKk",
      platform: "youtube",
      attribution: "Recess Therapy",
      license: "YouTube Standard License",
      description:
        "Official Recess Therapy interview with Tariq — the origin of the 'It's corn!' viral moment.",
      date: "2022-08-04",
      verified: true,
    },
    {
      role: "video",
      type: "video",
      url: "https://www.youtube.com/watch?v=_caMQpiwiaU",
      title: "It's Corn - Songify This ft. Tariq and Recess Therapy",
      source: "YouTube / schmoyoho",
      sourceUrl: "https://www.youtube.com/watch?v=_caMQpiwiaU",
      platform: "youtube",
      attribution: "The Gregory Brothers / schmoyoho",
      license: "YouTube Standard License",
      description:
        "Official Gregory Brothers Songify remix that turned the Recess Therapy interview into the hit 'It's Corn' song.",
      date: "2022-08-28",
      verified: true,
    },
  ],
  sources: [
    {
      title: "Corn Kid — Know Your Meme",
      url: "https://knowyourmeme.com/memes/corn-kid-its-corn",
      domain: "knowyourmeme.com",
    },
    {
      title: "Recess Therapy — YouTube",
      url: "https://www.youtube.com/@RecessTherapy",
      domain: "youtube.com",
    },
  ],
};

export default entry;
