import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m135",
  slug: "crumbl-cookie",
  title: "Crumbl Cookie",
  category: "meme",
  description:
    "The TikTok-era Crumbl cookie hype cycle — weekly menu drops, long lines, and dupe discourse that turned a bakery into a meme brand.",
  imageGradient: "from-pink-300 via-rose-200 to-amber-100",
  scores: { relevance: 63, influence: 62, cringe: 34, brainrot: 45 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 97,
    currentStatus: "highly-active",
    activePlatforms: [
      "tiktok",
      "wikipedia",
      "news",
    ],
    popularity: 77,
    trendingScore: 60,
    recentRevival: false,
    popularityNotes: "Relevance: Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=77 (Google News: 28 items in last 60d (40 returned) for “Crumbl Cookie”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Character signals still mark this as strongly representative of chaotic internet brainrot culture. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=11,849 for “Crumbl Cookies”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=2412 prev7=2763 (-13%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Crumbl”",
      "[news/recent-articles] Google News: 28 items in last 60d (40 returned) for “Crumbl Cookie”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Crumbl Cookie”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/gen-cohort-adoption] Cohort cue from tags/title (brainrot character only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=77 (Google News: 28 items in last 60d (40 returned) for “Crumbl Cookie”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Character signals still mark this as strongly representative of chaotic internet brainrot culture.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "2020-01-01",
  views: 1900000,
  trendDirection: "declining",
  tags: ["tiktok", "food", "brand", "hype", "dupe", "2020s"],
  meaning:
    "Memes about Crumbl Cookies — oversized rotating flavors, review TikToks, queue brags, and backlash ('it's just a cookie'). The brand became a symbol of algorithm-driven food hype: filming the pink box opening, rating weekly drops, and debating whether any cookie deserves a two-hour wait.",
  origin:
    "Crumbl Cookies expanded rapidly from Utah starting in 2017, but its meme status crystallized during 2020–2022 TikTok when weekly flavor announcements drove ritual unboxing videos. Know Your Meme and food-media coverage note how Crumbl sat at the center of 'dupe' culture — fans recreating flavors at home while critics mocked the frenzy. The meme is the social performance around the product as much as the cookie itself.",
  timeline: [
    { date: "2017", event: "Crumbl Cookies founded; rapid franchise expansion begins" },
    { date: "2020–2021", event: "TikTok unboxing and review format drives mainstream hype" },
    { date: "2022–2023", event: "Backlash and dupe-recipe trend peak alongside fan devotion" },
    { date: "2024+", event: "Settles into recognizable 'Crumbl review' meme vocabulary" },
  ],
  examples: [
    "TikTok split-screen: Crumbl line vs 'homemade dupe' in twenty minutes",
    "Ironically rating a basic chocolate chip like a wine critic",
    "Meme about weekly menu FOMO when friends post the pink box",
  ],
  relatedSlugs: ["dupe-economy", "salt-bae", "hydro-flask", "prime-hydration"],
  relationships: {
    relatedEvent: ["dupe-economy"],
    sameEra: ["hydro-flask", "prime-hydration"],
  },
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/crumbl-cookies",
      title: "Crumbl Cookies — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/crumbl-cookies",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "TikTok hype and review-culture documentation.",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Crumbl_Cookies",
      title: "Crumbl Cookies — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Crumbl_Cookies",
      platform: "other",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      description: "Company background for the viral bakery brand.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Crumbl Cookies — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Crumbl_Cookies",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
