import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m109",
  slug: "crying-cat",
  title: "Crying Cat / Thumbs Up Cat",
  category: "meme",
  description:
    "A teary-eyed cat giving a thumbs up — the perfect image for 'I'm dying inside but everything is fine.'",
  imageGradient: "from-orange-400 via-amber-300 to-yellow-200",
  scores: { relevance: 27, influence: 72, cringe: 21, brainrot: 32 },
  dynamicMetadata: {
    lastReviewed: "2026-07-25",
    currentRelevance: 27,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "news",
    ],
    popularity: 30,
    trendingScore: 26,
    recentRevival: "unknown",
    popularityNotes: "Status: occasionally-referenced · Relevance 27 (today's recognition, not influence) · Trending 26 (recent attention)",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Crying Cat / Thumbs Up Cat”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/platform-activity] Wiktionary lookup unavailable for “Crying”",
      "[news/recent-articles] Google News: 2 items in last 30d (40 returned) for “Crying Cat / Thumbs Up Cat”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Know Your Meme cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Crying Cat / Thumbs Up Cat”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/remix-activity] Format/remix cue (brainrot/cringe only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-07-25",
  historicalDate: "2019-06-01",
  views: 3100000,
  trendDirection: "declining",
  tags: ["cat", "reaction", "crying", "wholesome-sad", "2019", "classic"],
  meaning:
    "A photoshopped cat with teary, pleading eyes and a human thumbs-up gesture. It expresses forced optimism through pain — smiling on the outside while falling apart. Often captioned with contradictory text ('I'm fine :)') or used as a reply when someone shares bad news you must pretend to accept.",
  origin:
    "Know Your Meme traces the Thumbs Up Crying Cat to a June 2019 tweet by @MISSINGEGO, which combined a sad cat face with a thumbs-up stock hand. The image spread quickly on Twitter and Reddit as a reaction macro. It sits in the same emotional lane as 'This Is Fine' but with more explicit performative positivity.",
  timeline: [
    { date: "Jun 2019", event: "@MISSINGEGO tweets the Thumbs Up Crying Cat composite" },
    { date: "2019", event: "Spreads across Twitter, Reddit, and Instagram reaction pages" },
    { date: "2020", event: "Peak use during lockdown 'I'm fine' coping posts" },
    { date: "2021+", event: "Remains a standard sad-wholesome reaction image" },
  ],
  examples: [
    "Boss assigns weekend work — [crying cat thumbs up] 'Can't wait!'",
    "Me pretending to enjoy small talk — thumbs up crying cat",
    "Reply image when a friend shares trauma and you don't know what to say",
  ],
  relatedSlugs: ["hide-the-pain-harold", "this-is-fine", "woman-yelling-at-cat"],
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/crying-cat",
      title: "Crying Cat — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/crying-cat",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Documentation of the Thumbs Up Crying Cat meme origin.",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/thumbs-up-crying-cat",
      title: "Thumbs Up Crying Cat — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/thumbs-up-crying-cat",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Thumbs Up Crying Cat — Know Your Meme",
      url: "https://knowyourmeme.com/memes/thumbs-up-crying-cat",
      domain: "knowyourmeme.com",
    },
    {
      title: "Crying Cat — Know Your Meme",
      url: "https://knowyourmeme.com/memes/crying-cat",
      domain: "knowyourmeme.com",
    },
  ],
};

export default entry;
