import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m111",
  slug: "crying-jordan",
  title: "Crying Jordan",
  category: "meme",
  description:
    "Michael Jordan crying at his 2009 Hall of Fame speech — pasted onto every loss, L, and disappointment on the internet.",
  imageGradient: "from-red-700 via-rose-600 to-orange-500",
  scores: { relevance: 45, influence: 82, cringe: 21, brainrot: 32 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 45,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "wikipedia",
      "news",
    ],
    popularity: 25,
    trendingScore: 62,
    recentRevival: true,
    popularityNotes: "Relevance: Recent creation signals rose modestly. Signals: wikipedia/editorial-trend=100 (Pageviews WoW last7=1710 prev7=568 (201%)); news/recent-articles=25 (Google News: 2 items in last 60d (40 returned) for “Crying Jordan”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=3,514 for “Crying Jordan”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=1710 prev7=568 (201%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Crying”",
      "[news/recent-articles] Google News: 2 items in last 60d (40 returned) for “Crying Jordan”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Crying Jordan”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Recent creation signals rose modestly. Signals: wikipedia/editorial-trend=100 (Pageviews WoW last7=1710 prev7=568 (201%)); news/recent-articles=25 (Google News: 2 items in last 60d (40 returned) for “Crying Jordan”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "2009-09-11",
  views: 4300000,
  trendDirection: "stable",
  tags: ["michael-jordan", "nba", "reaction", "2009", "sports", "classic"],
  meaning:
    "A reaction image of Michael Jordan tearfully laughing/crying during his Basketball Hall of Fame induction speech on September 11, 2009. Editors cut out his face and overlay it on athletes, celebrities, or brands suffering embarrassment or defeat. It is sports internet's default 'take the L' image.",
  origin:
    "Jordan's emotional Hall of Fame speech generated the source footage. Know Your Meme documents meme use beginning around 2012 on Twitter and sports forums, exploding during 2015–2016 NBA playoff threads. The cutout face became template fodder for any public loss — not just basketball.",
  timeline: [
    { date: "Sep 11, 2009", event: "Jordan's tearful Hall of Fame induction speech" },
    { date: "2012", event: "Crying face cutout begins circulating on Twitter and MemeGenerator" },
    { date: "2015–2016", event: "Peak NBA playoff meme season — Crying Jordan everywhere" },
    { date: "2017+", event: "Crosses into general-purpose 'loss' reaction beyond sports" },
  ],
  examples: [
    "Team loses playoff series — Crying Jordan on every player photo",
    "Brand tweet backfires — quote tweet with Crying Jordan face",
    "Friend fails an exam — 'Jordan crying' reaction image",
  ],
  relatedSlugs: ["hide-the-pain-harold", "bad-luck-brian", "success-kid"],
  media: [
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/3/3d/Michael_Jordan_crying_at_his_Hall_of_Fame_induction_ceremony.jpg",
      title: "Michael Jordan at his 2009 Hall of Fame induction",
      source: "Wikimedia Commons",
      sourceUrl:
        "https://commons.wikimedia.org/wiki/File:Michael_Jordan_crying_at_his_Hall_of_Fame_induction_ceremony.jpg",
      platform: "wikimedia",
      attribution: "Keith Allison / CC BY-SA 2.0",
      license: "CC BY-SA 2.0",
      description: "Source moment for the Crying Jordan meme cutout.",
      date: "2009",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/crying-jordan",
      title: "Crying Jordan — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/crying-jordan",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Crying Jordan — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Crying_Jordan",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
