import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m132",
  slug: "dancing-baby",
  title: "Dancing Baby",
  category: "meme",
  description:
    "The 1996 Baby Cha-Cha viral 3D animation — one of the first GIFs to email inboxes worldwide and a landmark of pre-social viral video.",
  imageGradient: "from-sky-300 via-blue-200 to-pink-200",
  scores: { relevance: 43, influence: 92, cringe: 21, brainrot: 40 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 43,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "wikipedia",
      "news",
    ],
    popularity: 37,
    trendingScore: 43,
    recentRevival: false,
    popularityNotes: "Relevance: Recent creation signals rose modestly. Signals: news/recent-articles=37 (Google News: 4 items in last 60d (40 returned) for “Dancing Baby”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Character signals still mark this as strongly representative of chaotic internet brainrot culture. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=5,399 for “Dancing baby”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=1297 prev7=1335 (-3%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Dancing”",
      "[news/recent-articles] Google News: 4 items in last 60d (40 returned) for “Dancing Baby”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Dancing Baby”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/absurdity] Tag/title absurdity cue (brainrot character only)",
      "Weak corroboration — blended heuristic (50) with AI double-check (35): Modest Wikipedia traffic and a few news mentions show some nostalgic interest, but low Google Trends, minimal recent activity, and limited platform buzz indicate the meme is only mildly popular now.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Recent creation signals rose modestly. Signals: news/recent-articles=37 (Google News: 4 items in last 60d (40 returned) for “Dancing Baby”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Character signals still mark this as strongly representative of chaotic internet brainrot culture.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "1996-01-01",
  views: 3500000,
  trendDirection: "stable",
  tags: ["1990s", "gif", "classic", "proto-meme", "email", "3d"],
  meaning:
    "A looping 3D animation of a diapered baby doing the cha-cha — also called Baby Cha-Cha or Oogachaka Baby. Symbol of early internet virality: forwarded emails, forum signatures, and TV references to 'that dancing baby.' Distinct from the 'first meme' debate — this is a specific 1990s file, not a print cartoon.",
  origin:
    "Created as a demo by character animator Michael Girard and propagated through Autodesk/Kinetix circles before spreading via email chains in 1996. Know Your Meme and Wikipedia note its appearance on Ally McBeal in 1998 as proof it crossed into mainstream TV. The GIF format — small, loopable, bizarre — set the template for decades of viral clips.",
  timeline: [
    { date: "1996", event: "Baby Cha-Cha animation spreads through email forwards" },
    { date: "1998", event: "Featured on Ally McBeal; mainstream news covers the fad" },
    { date: "2000s", event: "Becomes shorthand for '90s internet weirdness' in nostalgia posts" },
    { date: "2010s+", event: "Referenced in 'first viral video' lists alongside Hamster Dance" },
  ],
  examples: [
    "Nostalgia thread: 'remember when this was in every email?'",
    "Comparing a new viral loop to 'Dancing Baby energy'",
    "Ally McBeal clip edits in retro internet compilations",
  ],
  relatedSlugs: ["first-meme", "hamster-dance", "numa-numa", "badger-badger-badger"],
  relationships: {
    sameEra: ["hamster-dance", "all-your-base-are-belong-to-us"],
    relatedTo: ["first-meme"],
  },
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/dancing-baby",
      title: "Dancing Baby — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/dancing-baby",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "1996 Baby Cha-Cha origin and Ally McBeal moment.",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Dancing_baby",
      title: "Dancing baby — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Dancing_baby",
      platform: "other",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      description: "Encyclopedic history of the 1996 viral animation.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Dancing baby — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Dancing_baby",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
