import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m51",
  slug: "dat-boi",
  title: "Dat Boi",
  category: "meme",
  description:
    "The 2016 green frog on a unicycle — 'here come dat boi! o shit waddup!' — peak absurdist Tumblr/Twitter meme energy.",
  imageGradient: "from-green-400 via-lime-500 to-emerald-600",
  scores: { relevance: 41, influence: 70, cringe: 21, brainrot: 32 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 41,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "wikipedia",
      "news",
    ],
    popularity: 37,
    trendingScore: 42,
    recentRevival: false,
    popularityNotes: "Relevance: Recent creation signals rose modestly. Signals: news/recent-articles=37 (Google News: 4 items in last 60d (40 returned) for “Dat Boi”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=3,269 for “Dat Boi”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=760 prev7=801 (-5%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Dat”",
      "[news/recent-articles] Google News: 4 items in last 60d (40 returned) for “Dat Boi”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Dat Boi”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "Weak corroboration — blended heuristic (50) with AI double-check (32): Modest Wikipedia views, slight week‑over‑week decline, minimal news coverage and low Google Trends indicate the meme is only faintly present today.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Recent creation signals rose modestly. Signals: news/recent-articles=37 (Google News: 4 items in last 60d (40 returned) for “Dat Boi”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-18",
  lastUpdated: "2026-08-16",
  historicalDate: "2016-04-03",
  views: 3200000,
  trendDirection: "stable",
  tags: ["2016", "absurd", "frog", "tumblr", "classic", "vine-era"],
  meaning:
    "A self-contained absurdist character: a low-res unicycling frog greeted with 'here come dat boi!' / 'o shit waddup.' The joke is the frog itself — no nostalgia template required — which made it a mascot of mid-2010s surreal meme culture.",
  origin:
    "The frog asset comes from Animation Factory clip art (designer Josh Doohen). Caption culture grew from Pac-Man 'here come dat boi' posts on Tumblr (2015). Facebook page Fresh Memes About the Mojave Desert paired frog + caption in April 2016; Twitter and Reddit (/r/me_irl) pushed it mainstream (Know Your Meme, Wikipedia).",
  timeline: [
    { date: "2014–15", event: "'Dat Boi' name jokes and Pac-Man caption posts circulate" },
    { date: "Apr 2016", event: "Unicycle frog + caption explode on Facebook and Twitter" },
    { date: "May–Jun 2016", event: "Mainstream coverage; brand tweets; music videos" },
    { date: "Mar 2017", event: "/r/me_irl renaissance and 'o shit waddap' frontpage stunt" },
    { date: "Sep 2017", event: "Coordinated 'Dat Boi Renaissance' on Reddit" },
  ],
  examples: [
    "Posting the frog alone with 'here come dat boi!!!!!'",
    "'o shit waddup' as a greeting reply under any arrival joke",
    "Brand accounts awkwardly tweeting the frog in 2016",
  ],
  relatedSlugs: ["pepe", "doge", "nyan-cat", "vine-shutdown"],
  relationships: {
    sameEra: ["doge", "nyan-cat", "vine-shutdown"],
    sameFormat: ["pepe"],
    community: ["pepe"],
  },
  media: [
    // AI suggested — KYM icon is the defining frog still
    {
      role: "featured",
      type: "image",
      url: "https://i.kym-cdn.com/entries/icons/original/000/020/401/HereDatBoi.jpg",
      title: "Dat Boi — frog on a unicycle",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/dat-boi",
      platform: "knowyourmeme",
      attribution: "Animation Factory frog asset (via Know Your Meme documentation)",
      description: "The classic green frog unicycle image associated with Dat Boi.",
      date: "2016",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/dat-boi",
      title: "Dat Boi — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/dat-boi",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Full origin and Reddit revival history.",
      date: "2016",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Dat_Boi",
      title: "Dat Boi — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Dat_Boi",
      platform: "other",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      description: "Encyclopedic summary of the Animation Factory frog meme.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Dat Boi — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Dat_Boi",
      domain: "en.wikipedia.org",
    },
    {
      title: "Dat boi, explained — Vox",
      url: "https://www.vox.com/2016/5/27/11791220/dat-boi-meme",
      domain: "vox.com",
    },
  ],
};

export default entry;
