import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m36",
  slug: "disaster-girl",
  title: "Disaster Girl",
  category: "meme",
  description:
    "Zoë Roth's childhood photo in front of a burning house — the smirk that launched a thousand photoshopped disasters.",
  imageGradient: "from-orange-600 via-red-500 to-rose-600",
  scores: { relevance: 25, influence: 78, cringe: 21, brainrot: 26 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 25,
    currentStatus: "classic",
    activePlatforms: [
      "wikipedia",
    ],
    popularity: 16,
    trendingScore: 31,
    recentRevival: false,
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=16 (Google News: 1 items in last 60d (40 returned) for “Disaster Girl”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=9,515 for “Disaster Girl”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=2060 prev7=2236 (-8%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Disaster”",
      "[dictionary/platform-activity] Wiktionary last revision 2025-01-09",
      "[news/recent-articles] Google News: 1 items in last 60d (40 returned) for “Disaster Girl”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Disaster Girl”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=16 (Google News: 1 items in last 60d (40 returned) for “Disaster Girl”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-17",
  lastUpdated: "2026-08-16",
  historicalDate: "2005-01-01",
  views: 3600000,
  trendDirection: "stable",
  tags: ["photoshop", "classic", "2005", "2008", "reaction", "fire"],
  meaning:
    "A photo of a young girl smirking at the camera with a house fire behind her, used as an exploitable template implying she caused (or is enjoying) chaos. Often photoshopped onto historic disasters or personal failures.",
  origin:
    "Taken in 2005 by Dave Roth of his daughter Zoë during a controlled firefighter-training burn in Mebane, North Carolina. After JPG Magazine published the contest-winning photo in 2008, it spread on forums and early meme sites; photoshoppers placed Zoë in front of the Titanic, dinosaur extinctions, and other calamities. In 2021 Zoë Roth sold an NFT of the photograph.",
  timeline: [
    { date: "2005", event: "Dave Roth photographs Zoë at a controlled burn in Mebane, NC" },
    { date: "2008", event: "Photo wins JPG Magazine contest and spreads as Disaster Girl" },
    { date: "2008–2010s", event: "Photoshop variants place Disaster Girl at historic disasters" },
    { date: "Apr 2021", event: "Zoë Roth sells an NFT of the original photograph" },
  ],
  examples: [
    "When your group project fails but your part was fine [Disaster Girl]",
    "Me watching my code delete the database",
    "Photoshop of Disaster Girl in front of [any catastrophe]",
  ],
  relatedSlugs: ["success-kid", "bad-luck-brian"],
  media: [
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/en/1/11/Disaster_Girl.jpg",
      title: "Disaster Girl — original Zoë Roth photograph (2005)",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/File:Disaster_Girl.jpg",
      platform: "wikimedia",
      attribution: "Dave Roth (fair use for identification)",
      license: "Fair use",
      description:
        "The original Disaster Girl photo — Zoë Roth smirking in front of a controlled training fire.",
      date: "2005",
      verified: true,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/disaster-girl",
      title: "Disaster Girl — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/disaster-girl",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Origin of the Roth family photo and photoshop meme wave.",
      date: "2008",
      verified: true,
    },
  ],
  sources: [
    {
      title: "Disaster Girl — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Disaster_Girl",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
