import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m112",
  slug: "doomer-bloomer",
  title: "Doomer / Bloomer",
  category: "meme",
  description:
    "Wojak variants for pessimism (Doomer) and optimism (Bloomer) — internet archetypes for nihilism vs. choosing to improve.",
  imageGradient: "from-gray-800 via-slate-700 to-zinc-600",
  scores: { relevance: 58, influence: 74, cringe: 21, brainrot: 32 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 58,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "wikipedia",
      "news",
    ],
    popularity: 44,
    trendingScore: 46,
    recentRevival: false,
    popularityNotes: "Relevance: Recent creation signals rose modestly. Signals: news/recent-articles=44 (Google News: 6 items in last 60d (40 returned) for “Doomer meme”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=24,372 for “Karen (slang)”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=5078 prev7=5326 (-5%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Doomer”",
      "[dictionary/platform-activity] Wiktionary last revision 2025-06-23",
      "[news/recent-articles] Google News: 6 items in last 60d (40 returned) for “Doomer meme”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Doomer meme”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Recent creation signals rose modestly. Signals: news/recent-articles=44 (Google News: 6 items in last 60d (40 returned) for “Doomer meme”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "2018-09-01",
  views: 2800000,
  trendDirection: "stable",
  tags: ["wojak", "doomer", "bloomer", "4chan", "2018", "archetype"],
  meaning:
    "Doomer Wojak is a black-capped, cigarette-smoking figure representing existential pessimism, late-night despair, and 'nothing matters' energy. Bloomer Wojak is the counter-archetype — smiling, outdoors, choosing exercise and self-improvement. Together they map a 2018–2020 internet debate about mental health, masculinity forums, and whether you give up or 'make it.'",
  origin:
    "Know Your Meme traces Doomer to 4chan and Reddit edits of Wojak around September 2018, building on earlier Feels Guy sadness templates. Bloomer emerged soon after as an intentional opposite — often linked to 'blooming' or self-help irony. Both spread through Wojak variant ecosystems alongside Zoomer, Boomer, and Coomer memes.",
  timeline: [
    { date: "Sep 2018", event: "Doomer Wojak variant spreads on 4chan and r/4chan" },
    { date: "Late 2018", event: "Bloomer Wojak introduced as optimistic counterpart" },
    { date: "2019", event: "Doomer vs. Bloomer comparison memes peak on Reddit and Twitter" },
    { date: "2020", event: "Doomer imagery tied to pandemic-era nihilism discourse" },
    { date: "2021+", event: "Settles as enduring Wojak archetypes in meme vocabulary" },
  ],
  examples: [
    "3am cigarette on the porch — Doomer Wojak mood",
    "Waking up early, gym, sunlight — Bloomer arc",
    "Panel comparing Doomer collapse vs. Bloomer self-improvement",
  ],
  relatedSlugs: ["wojak", "gigachad", "soyjak", "virgin-vs-chad"],
  relationships: {
    sameFormat: ["wojak"],
    spawnedVariants: ["gigachad"],
    relatedSlang: ["npc"],
  },
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/doomer",
      title: "Doomer — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/doomer",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Documentation of the Doomer Wojak variant.",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/bloomer",
      title: "Bloomer — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/bloomer",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Documentation of the Bloomer Wojak counterpart.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Doomer / Bloomer — Wikipedia search",
      url: "https://en.wikipedia.org/w/index.php?search=Doomer%20%2F%20Bloomer&title=Special:Search&fulltext=1",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
