import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m57",
  slug: "du-bist-gut-genug",
  title: "Du bist gut genug",
  category: "meme",
  description:
    "The 2026 German 'Gut Genug' chorus earworm — falsetto 'Du bist gut genug' edits, Cleveland Jr. comparisons, and TikTok loops.",
  imageGradient: "from-violet-500 via-purple-600 to-fuchsia-500",
  scores: { relevance: 50, influence: 48, cringe: 21, brainrot: 51 },
  dynamicMetadata: {
    lastReviewed: "2026-07-25",
    currentRelevance: 50,
    currentStatus: "current",
    activePlatforms: [
      "tiktok",
      "wikipedia",
      "news",
    ],
    popularity: 49,
    trendingScore: 54,
    recentRevival: false,
    popularityNotes: "Status: current · Relevance 50 (today's recognition, not influence) · Trending 54 (recent attention)",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=24 for “Wie bist du, Frühling, gut und treu, WAB 58”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=11 prev7=3 (267%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Du”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-07-13",
      "[news/recent-articles] Google News: 17 items in last 30d (35 returned) for “Du bist gut genug”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Know Your Meme cited; Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Du bist gut genug”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/gen-cohort-adoption] Cohort cue from tags (not used for relevance/trending)",
      "[catalog-evidence/remix-activity] Format/remix cue (brainrot/cringe only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
  },
  addedAt: "2026-07-18",
  lastUpdated: "2026-07-25",
  historicalDate: "2026-05-22",
  views: 1500000,
  trendDirection: "stable",
  tags: ["tiktok", "2026", "music", "germany", "earworm", "edit"],
  meaning:
    "A song-clip meme built on Blumengarten / KitschKrieg / Shirin David's 'Gut Genug.' The looping falsetto line 'Du bist gut genug' ('You are good enough') became an edit sound — often paired with Cleveland Jr. clips for the vocal resemblance, plus misheard-lyric jokes.",
  origin:
    "Gut Genug released late May 2026; a June 2026 TikTok clip of Rayan Djima's chorus went multi-million views. English-speaking TikTok and Reels turned the line into edits and Cleveland Show mashups (Know Your Meme, Wikipedia 'Gut genug').",
  timeline: [
    { date: "May 2026", event: "'Gut Genug' song and music video released in Germany" },
    { date: "Jun 2, 2026", event: "Chorus clip posts explode on TikTok" },
    { date: "Jun 2026", event: "Cleveland Jr. edits and loop remixes go international" },
    { date: "Jun 2026+", event: "Misheard-lyric and motivational-edit variants spread" },
  ],
  examples: [
    "Looping only the 'Du bist gut genug' falsetto as a sound",
    "Cleveland Jr. rap-battle clips dubbed with the chorus",
    "Caption: 'when the German song heals your ego'",
  ],
  relatedSlugs: ["short-form-takeover", "tiktok-rise", "looksmaxxing"],
  relationships: {
    relatedEvent: ["short-form-takeover", "tiktok-rise"],
    relatedTo: ["looksmaxxing"],
  },
  media: [
    // AI suggested — KYM cover for the song meme
    {
      role: "featured",
      type: "image",
      url: "https://i.kym-cdn.com/entries/icons/original/000/056/946/dubistcover.jpg",
      title: "Du bist gut genug — meme cover",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/du-bist-gut-genug",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Cover art for the Du bist gut genug / Gut Genug viral song meme.",
      date: "2026",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/du-bist-gut-genug",
      title: "Du Bist Gut Genug — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/du-bist-gut-genug",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Song origin and TikTok edit spread.",
      date: "2026",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Gut_genug",
      title: "Gut genug — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Gut_genug",
      platform: "other",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      description: "Song chart performance and meme notes.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Du Bist Gut Genug — Know Your Meme",
      url: "https://knowyourmeme.com/memes/du-bist-gut-genug",
      domain: "knowyourmeme.com",
    },
    {
      title: "Gut genug — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Gut_genug",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
