import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m113",
  slug: "epic-handshake",
  title: "Epic Handshake",
  category: "meme",
  description:
    "The Predator arm-wrestling handshake — labeled so two unlikely groups agree on one specific thing.",
  imageGradient: "from-stone-600 via-neutral-500 to-gray-400",
  scores: { relevance: 36, influence: 76, cringe: 21, brainrot: 58 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 36,
    currentStatus: "classic",
    activePlatforms: [
      "news",
    ],
    popularity: 25,
    trendingScore: 25,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Recent creation signals rose modestly. Signals: news/recent-articles=25 (Google News: 2 items in last 60d (40 returned) for “Epic Handshake”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Character signals still mark this as strongly representative of chaotic internet brainrot culture. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Epic Handshake”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Epic”",
      "[dictionary/platform-activity] Wiktionary last revision 2023-09-30",
      "[news/recent-articles] Google News: 2 items in last 60d (40 returned) for “Epic Handshake”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Epic Handshake”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/remix-activity] Format/remix / short-form reuse cue (brainrot character only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Recent creation signals rose modestly. Signals: news/recent-articles=25 (Google News: 2 items in last 60d (40 returned) for “Epic Handshake”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Character signals still mark this as strongly representative of chaotic internet brainrot culture.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "2018-05-01",
  views: 3400000,
  trendDirection: "declining",
  tags: ["predator", "template", "agreement", "2018", "object-labeling", "classic"],
  meaning:
    "A three-panel object-labeling meme using the famous arm-wrestling handshake from the 1987 film Predator. Each muscular arm is labeled with a different group; the clasping hands in the center label what they unexpectedly agree on. Format: 'When X and Y both [agree on Z].'",
  origin:
    "The Predator handshake between Arnold Schwarzenegger and Carl Weathers is a classic film moment. Know Your Meme documents the labeled meme template spreading on Reddit around May 2018, especially r/MemeEconomy and r/dankmemes. It became one of the 2010s' most durable 'unlikely alliance' formats.",
  timeline: [
    { date: "1987", event: "Predator releases — arm-wrestling handshake scene becomes iconic" },
    { date: "May 2018", event: "Labeled handshake meme format spreads on Reddit" },
    { date: "2018–2019", event: "Peak use for political, fandom, and hobby agreement jokes" },
    { date: "2020s", event: "Remains a standard template for 'strange bedfellows' humor" },
  ],
  examples: [
    "When introverts and extroverts both hate small talk [handshake: silence]",
    "Linux users and Mac users agreeing Windows update ruined the day",
    "Two rival fandoms bonding over hating the same reboot",
  ],
  relatedSlugs: ["drake-hotline-bling", "expanding-brain", "distracted-boyfriend"],
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/epic-handshake",
      title: "Epic Handshake — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/epic-handshake",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Documentation of the Predator handshake meme template.",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Predator_(film)",
      title: "Predator (film) — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Predator_(film)",
      platform: "wikimedia",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Predator (film) — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Predator_(film)",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
