import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m40",
  slug: "expanding-brain",
  title: "Expanding Brain",
  category: "meme",
  description:
    "The multi-panel 'galaxy brain' template ranking ideas from basic to absurdly enlightened as the brain lights up.",
  imageGradient: "from-pink-400 via-fuchsia-500 to-violet-600",
  scores: { relevance: 54, influence: 72, cringe: 21, brainrot: 32 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 54,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "reddit",
      "wikipedia",
      "news",
    ],
    popularity: 41,
    trendingScore: 48,
    recentRevival: false,
    popularityNotes: "Relevance: Recent creation signals rose modestly. Signals: news/recent-articles=41 (Google News: 5 items in last 60d (40 returned) for “Expanding Brain”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=15,679 for “List of Internet phenomena”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=3905 prev7=3683 (6%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Expanding”",
      "[news/recent-articles] Google News: 5 items in last 60d (40 returned) for “Expanding Brain”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Expanding Brain”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Recent creation signals rose modestly. Signals: news/recent-articles=41 (Google News: 5 items in last 60d (40 returned) for “Expanding Brain”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-17",
  lastUpdated: "2026-08-16",
  historicalDate: "2017-02-01",
  views: 3900000,
  trendDirection: "stable",
  tags: ["object-labeling", "iq", "galaxy-brain", "2017", "reddit", "classic"],
  meaning:
    "A vertical tier list of increasingly 'enlightened' (often ironic) takes. Each panel shows a more illuminated brain — from dim to rainbow cosmic — paired with labels that escalate from normal to ridiculous. Used to mock pretension or to jokingly crown a chaotic opinion as peak IQ.",
  origin:
    "An object-labeling / IQ-chart descendant that spread on Reddit and Twitter in early 2017 (Know Your Meme documents the Expanding Brain / galaxy-brain format's rise that year). It became one of the decade's default sarcasm formats, later remade on TikTok.",
  timeline: [
    { date: "Early 2017", event: "Expanding Brain / galaxy-brain panel formats begin circulating widely" },
    { date: "2017–2018", event: "Becomes a default Reddit and Twitter sarcasm template" },
    { date: "2018+", event: "Endless remixes; often paired with other object-labeling memes" },
  ],
  examples: [
    "Level 1: Using an alarm · Level 4: Trusting the vibes to wake you up",
    "Basic take → mid take → cursed take → galaxy-brain take",
    "Ranking increasingly unhinged opinions with glowing brains",
  ],
  relatedSlugs: ["distracted-boyfriend", "philosoraptor", "wojak"],
  media: [
    // AI suggested — KYM entry icon shows the classic expanding-brain panels
    {
      role: "featured",
      type: "image",
      url: "https://i.kym-cdn.com/entries/icons/original/000/022/266/brain.png",
      title: "Expanding Brain — classic panel template",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/expanding-brain",
      platform: "knowyourmeme",
      attribution: "Know Your Meme documentation of the expanding-brain format",
      license: "Copyrighted meme composite — used for identification",
      description:
        "The familiar multi-tier glowing-brain layout that defines the Expanding Brain meme.",
      date: "2017",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/expanding-brain",
      title: "Expanding Brain — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/expanding-brain",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Origin notes, examples, and related galaxy-brain variants.",
      date: "2017",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Expanding Brain — Wikipedia search",
      url: "https://en.wikipedia.org/w/index.php?search=Expanding%20Brain&title=Special:Search&fulltext=1",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
