import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m139",
  slug: "feastables",
  title: "Feastables",
  category: "meme",
  description:
    "MrBeast's Feastables chocolate brand — golden ticket hunts, store cleanouts, and YouTube merch culture as meme material.",
  imageGradient: "from-amber-700 via-yellow-500 to-orange-600",
  scores: { relevance: 25, influence: 60, cringe: 21, brainrot: 32 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 25,
    currentStatus: "classic",
    activePlatforms: [
      "youtube",
    ],
    popularity: 16,
    trendingScore: 16,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=16 (Google News: 1 items in last 60d (40 returned) for “Feastables meme”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Feastables meme”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Feastables”",
      "[news/recent-articles] Google News: 1 items in last 60d (40 returned) for “Feastables meme”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Feastables meme”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=16 (Google News: 1 items in last 60d (40 returned) for “Feastables meme”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "2022-01-01",
  views: 2600000,
  trendDirection: "declining",
  tags: ["mrbeast", "youtube", "brand", "chocolate", "2022", "hype"],
  meaning:
    "Memes about Feastables — Jimmy Donaldson (MrBeast)'s chocolate bar line promoted through massive YouTube integrations, golden ticket contests, and fan raids on Walmart shelves. Jokes cover 'I bought every bar in the store,' taste-test loyalty, and whether creator chocolate is just hype packaging.",
  origin:
    "Feastables launched in 2022 as part of MrBeast's expanding consumer brand empire. Know Your Meme and business coverage note videos of fans clearing retail displays and hunting rare bars — turning shopping into content. The meme parallels Prime/Lunchly creator-CPG satire but with MrBeast's scale and philanthropy-adjacent branding.",
  timeline: [
    { date: "2022", event: "Feastables launches with MrBeast video integrations" },
    { date: "2022–2023", event: "Golden ticket hunts and store-emptying clips go viral" },
    { date: "2023–2024", event: "Formula reformulations spark taste-test meme wars" },
    { date: "2024+", event: "Remains a flagship example of YouTuber-as-CPG-brand" },
  ],
  examples: [
    "TikTok: clearing every Feastables bar from a Walmart shelf",
    "Meme comparing Feastables hunt to Willy Wonka golden ticket",
    "Taste test: 'MrBeast chocolate vs Hershey's' rage bait",
  ],
  relatedSlugs: ["mrbeast", "prime-hydration", "lunchly", "dupe-economy", "salt-bae"],
  relationships: {
    popularized: ["mrbeast"],
    relatedEvent: ["dupe-economy"],
    sameEra: ["prime-hydration", "lunchly"],
  },
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/events/mrbeast-feastables-display-controversy",
      title: "MrBeast Feastables Display Controversy — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/events/mrbeast-feastables-display-controversy",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "MrBeast chocolate brand hype and fan-hunt memes.",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Feastables",
      title: "Feastables — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Feastables",
      platform: "other",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      description: "Brand launch and retail phenomenon context.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Feastables — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Feastables",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
