import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m114",
  slug: "florida-man",
  title: "Florida Man",
  category: "meme",
  description:
    "The running joke that Florida news headlines read like absurdist fiction — 'Florida Man [does unhinged thing].'",
  imageGradient: "from-lime-500 via-green-400 to-emerald-300",
  scores: { relevance: 44, influence: 78, cringe: 21, brainrot: 32 },
  dynamicMetadata: {
    lastReviewed: "2026-07-25",
    currentRelevance: 44,
    currentStatus: "classic",
    activePlatforms: [
      "x",
      "news",
    ],
    popularity: 30,
    trendingScore: 51,
    recentRevival: "unknown",
    popularityNotes: "Status: classic · Relevance 44 (today's recognition, not influence) · Trending 51 (recent attention)",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Florida Man”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/platform-activity] Wiktionary lookup unavailable for “Florida”",
      "[news/recent-articles] Google News: 40 items in last 30d (40 returned) for “Florida Man”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Know Your Meme cited; Wikipedia / Wikimedia cited; Major news organization cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Florida Man”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/remix-activity] Format/remix cue (brainrot/cringe only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-07-25",
  historicalDate: "2013-01-01",
  views: 3500000,
  trendDirection: "declining",
  tags: ["florida", "news", "headline", "2013", "twitter", "classic"],
  meaning:
    "A meme format treating bizarre crime and oddity headlines from Florida as a single recurring character — 'Florida Man.' The humor combines real Sunshine State news weirdness (public records laws, regional reporting habits) with anthropomorphization: Florida Man fights gator, Florida Man wears nacho hat to DUI stop. It is part headline parody, part regional stereotype.",
  origin:
    "Know Your Meme and mainstream outlets trace '@_FloridaMan' Twitter account to January 2013, aggregating strange Florida headlines. The 'Florida Man' phrasing aligned with how news sites title stories ('Florida man arrested for…'). Twitter hashtag #FloridaMan and Reddit r/FloridaMan cemented the meme; Miami New Times and others documented the phenomenon as both joke and journalism pattern.",
  timeline: [
    { date: "Jan 2013", event: "@_FloridaMan Twitter account begins aggregating bizarre headlines" },
    { date: "2013–2014", event: "#FloridaMan hashtag and Reddit community grow" },
    { date: "2015", event: "Mainstream media explain the meme; Florida Man enters general vocabulary" },
    { date: "2019", event: "Florida Man game and merchandise peak novelty cycle" },
    { date: "2020s", event: "Still used whenever a headline sounds too unhinged to be real" },
  ],
  examples: [
    "Florida Man breaks into house to pet cat, leaves note",
    "Headline format: 'Florida Man [verb] [absurd object] while [second absurd act]'",
    "National story breaks — everyone checks if it's Florida Man again",
  ],
  relatedSlugs: ["bad-luck-brian", "this-is-fine", "ohio-final-boss"],
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/florida-man",
      title: "Florida Man — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/florida-man",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Documentation of the Florida Man headline meme.",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Florida_Man",
      title: "Florida Man — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Florida_Man",
      platform: "wikimedia",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Florida Man — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Florida_Man",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
