import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m65",
  slug: "funky-ehh",
  title: "Funky Ehh",
  category: "meme",
  description:
    "The Fortnite kid who misattributes a Janet Jackson remix as Oliver Tree — 'we'll drive a funky ehh' — and then plays the moan-car edit.",
  imageGradient: "from-fuchsia-500 via-purple-600 to-orange-400",
  scores: { relevance: 27, influence: 40, cringe: 21, brainrot: 32 },
  dynamicMetadata: {
    lastReviewed: "2026-07-25",
    currentRelevance: 27,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "tiktok",
      "news",
    ],
    popularity: 30,
    trendingScore: 26,
    recentRevival: false,
    popularityNotes: "Status: occasionally-referenced · Relevance 27 (today's recognition, not influence) · Trending 26 (recent attention)",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Funky Ehh”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Funky”",
      "[news/recent-articles] Google News: 2 items in last 30d (40 returned) for “Funky Ehh”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Know Your Meme cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Funky Ehh”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/absurdity] Tag/category absurdity cue (not used for relevance/trending)",
      "[catalog-evidence/gen-cohort-adoption] Cohort cue from tags (not used for relevance/trending)",
      "[catalog-evidence/remix-activity] Format/remix cue (brainrot/cringe only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
  },
  addedAt: "2026-07-18",
  lastUpdated: "2026-07-25",
  historicalDate: "2026-06-01",
  views: 1500000,
  trendDirection: "declining",
  tags: ["fortnite", "tiktok", "2026", "audio", "misattribution", "brainrot"],
  meaning:
    "A viral clip format around a kid in Fortnite claiming a remix of Janet Jackson's 'Someone to Call My Lover' is by Oliver Tree, singing 'Maybe we'll meet at a bar, we'll drive a fancy/funky ehh,' then playing the edit where 'car' is replaced with a moaning sound. Used as absurdist audio meme and misattribution comedy.",
  origin:
    "Documented on Know Your Meme as 'We'll Drive A Funky Ehh' / 'He'll Drive A Funky Ehh': a Fortnite gameplay clip of a kid confidently wrong about the song's artist, then blasting the remix. Spread as short-form sound and quote meme in mid-2026.",
  timeline: [
    { date: "Jun 2026", event: "Fortnite kid clip with Janet Jackson remix misattribution spreads" },
    { date: "Jun 2026+", event: "Quote, stitch, and sound remixes amplify 'funky ehh'" },
  ],
  examples: [
    "Typing 'we'll drive a funky ehh' under any wrong-artist music take",
    "Using the moan-car remix as ironic lobby music audio",
    "Stitching the Fortnite kid clip with other misheard lyrics",
  ],
  relatedSlugs: ["chicken-jockey", "npc-streaming", "short-form-takeover"],
  relationships: {
    relatedEvent: ["short-form-takeover"],
    relatedTo: ["chicken-jockey", "npc-streaming"],
    community: ["npc-streaming"],
  },
  media: [
    // AI suggested — KYM cover; human must verify
    {
      role: "featured",
      type: "image",
      url: "https://i.kym-cdn.com/entries/icons/original/000/057/087/funkyehh.jpg",
      title: "Funky Ehh — meme cover",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/well-drive-a-funky-ehh",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Cover image for the We'll Drive A Funky Ehh Fortnite clip meme.",
      date: "2026",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/well-drive-a-funky-ehh",
      title: "We'll Drive A Funky Ehh — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/well-drive-a-funky-ehh",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Clip origin and remix misattribution details.",
      date: "2026",
      verified: false,
    },
  ],
  sources: [
    {
      title: "We'll Drive A Funky Ehh — Know Your Meme",
      url: "https://knowyourmeme.com/memes/well-drive-a-funky-ehh",
      domain: "knowyourmeme.com",
    },
  ],
};

export default entry;
