import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m115",
  slug: "gorilla-glue-girl",
  title: "Gorilla Glue Girl",
  category: "meme",
  description:
    "Tessica Brown's 2021 viral video about Gorilla Glue in her hair — a cautionary tale that broke the internet for weeks.",
  imageGradient: "from-yellow-600 via-amber-500 to-orange-400",
  scores: { relevance: 0, influence: 68, cringe: 21, brainrot: 45 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 0,
    currentStatus: "historical",
    activePlatforms: [
      "tiktok",
    ],
    popularity: 0,
    trendingScore: 0,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (40 returned) for “Gorilla Glue Girl”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Character signals still mark this as strongly representative of chaotic internet brainrot culture. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Gorilla Glue Girl”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Gorilla”",
      "[dictionary/platform-activity] Wiktionary last revision 2025-09-22",
      "[news/recent-articles] Google News: 0 items in last 60d (40 returned) for “Gorilla Glue Girl”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Major news organization cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Gorilla Glue Girl”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/gen-cohort-adoption] Cohort cue from tags/title (brainrot character only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (40 returned) for “Gorilla Glue Girl”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Character signals still mark this as strongly representative of chaotic internet brainrot culture.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "2021-02-03",
  views: 3800000,
  trendDirection: "declining",
  tags: ["viral", "tiktok", "2021", "hair", "cautionary", "news"],
  meaning:
    "Meme shorthand for Tessica Brown, who went viral after posting that she used Gorilla Glue spray adhesive as hairspray and could not wash it out. The story became instant meme fodder — disbelief, sympathy, brand crisis, and jokes about never skipping the label. It also sparked copycat stunts and a larger discourse about clout-chasing vs. genuine mistakes.",
  origin:
    "On February 3, 2021, Tessica Brown posted a TikTok explaining she had used Gorilla Glue Heavy Duty Spray on her hair for a month. The video spread to Twitter and mainstream news within days. Gorilla Glue issued statements warning against hair use; a LA surgeon eventually helped remove the adhesive in a procedure covered by media. Know Your Meme and outlets like BBC documented the viral arc.",
  timeline: [
    { date: "Feb 3, 2021", event: "Tessica Brown posts TikTok about Gorilla Glue in her hair" },
    { date: "Feb 2021", event: "Video goes viral; Gorilla Glue and medical experts respond publicly" },
    { date: "Feb 2021", event: "Surgical removal procedure performed; story dominates news cycle" },
    { date: "2021", event: "Copycat incidents and meme jokes about reading product labels" },
    { date: "2022+", event: "Referenced as peak early-2021 viral absurdity" },
  ],
  examples: [
    "Using the wrong product and realizing too late — 'Gorilla Glue girl moment'",
    "Brand Twitter responding to viral crisis in real time",
    "Meme reactions: 'She used WHAT on her hair?!'",
  ],
  relatedSlugs: ["hawk-tuah", "this-is-fine", "side-eyeing-chloe"],
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/gorilla-glue-girl",
      title: "Gorilla Glue Girl — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/gorilla-glue-girl",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Documentation of the Tessica Brown viral incident.",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://www.bbc.com/news/world-us-canada-55998952",
      title: "Gorilla Glue in hair — BBC News",
      source: "BBC",
      sourceUrl: "https://www.bbc.com/news/world-us-canada-55998952",
      platform: "other",
      attribution: "BBC",
      description: "News coverage of the viral Gorilla Glue hair incident.",
      date: "2021",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Woman who used Gorilla Glue on hair — BBC",
      url: "https://www.bbc.com/news/world-us-canada-55998952",
      domain: "bbc.com",
    },
  ],
};

export default entry;
