import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m116",
  slug: "gru-plan-meme",
  title: "Gru's Plan",
  category: "meme",
  description:
    "Despicable Me's four-panel Gru whiteboard meme — steps 1–3 go well until step 4 reveals the plan was stupid all along.",
  imageGradient: "from-slate-600 via-gray-500 to-zinc-400",
  scores: { relevance: 25, influence: 78, cringe: 21, brainrot: 44 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 25,
    currentStatus: "classic",
    activePlatforms: [
      "wikipedia",
    ],
    popularity: 16,
    trendingScore: 35,
    recentRevival: false,
    popularityNotes: "Relevance: Recent creation signals rose modestly. Signals: news/recent-articles=16 (Google News: 1 items in last 60d (40 returned) for “Gru's Plan”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Character signals still mark this as strongly representative of chaotic internet brainrot culture. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=15,679 for “List of Internet phenomena”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=3905 prev7=3683 (6%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Gru's”",
      "[news/recent-articles] Google News: 1 items in last 60d (40 returned) for “Gru's Plan”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Gru's Plan”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/absurdity] Tag/title absurdity cue (brainrot character only)",
      "[catalog-evidence/remix-activity] Format/remix / short-form reuse cue (brainrot character only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Recent creation signals rose modestly. Signals: news/recent-articles=16 (Google News: 1 items in last 60d (40 returned) for “Gru's Plan”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Character signals still mark this as strongly representative of chaotic internet brainrot culture.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "2017-03-01",
  views: 4000000,
  trendDirection: "stable",
  tags: ["despicable-me", "gru", "template", "2017", "object-labeling", "classic"],
  meaning:
    "A four-panel template from Despicable Me (2010) showing Gru presenting a plan on a whiteboard. Panels 1–3 list steps with growing confidence; panel 4 shows Gru staring at the board realizing step 4 exposes a fatal flaw or self-own. Used for plans that fall apart on the last step — homework schemes, relationship moves, or any 'wait that's dumb' moment.",
  origin:
    "The scene comes from Illumination's Despicable Me (2010), where Gru outlines stealing the moon. Know Your Meme documents the labeled whiteboard format spreading on Reddit around March 2017, especially r/MemeEconomy. It became one of the most remixed animated movie templates alongside Drakeposting and Distracted Boyfriend.",
  timeline: [
    { date: "Jul 2010", event: "Despicable Me releases — Gru moon plan scene enters pop culture" },
    { date: "Mar 2017", event: "Four-panel Gru plan meme format spreads on Reddit" },
    { date: "2017–2018", event: "Peak object-labeling use across Twitter and Instagram" },
    { date: "2019+", event: "Standard template for self-own and failed scheme jokes" },
  ],
  examples: [
    "Step 1: Procrastinate · Step 4: Panic at midnight — Gru realization face",
    "Diet plan that collapses when step 4 is 'eat entire cake'",
    "Study strategy ending with 'fail exam anyway'",
  ],
  relatedSlugs: ["drake-hotline-bling", "expanding-brain", "two-buttons"],
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/grus-plan",
      title: "Gru's Plan — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/grus-plan",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Documentation of the Gru whiteboard four-panel meme.",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Despicable_Me",
      title: "Despicable Me — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Despicable_Me",
      platform: "wikimedia",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Despicable Me — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Despicable_Me",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
