import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m8",
  slug: "harlem-shake",
  title: "Harlem Shake",
  category: "meme",
  description:
    "The 30-second video format that broke YouTube in early 2013 — one person dances alone, then chaos erupts.",
  imageGradient: "from-pink-600 via-rose-500 to-red-500",
  scores: { relevance: 53, influence: 87, cringe: 36, brainrot: 28 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 53,
    currentStatus: "current",
    activePlatforms: [
      "news",
    ],
    popularity: 52,
    trendingScore: 52,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=52 (Google News: 9 items in last 60d (40 returned) for “Harlem Shake”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikipedia page “Harlem Shake (meme)” found but pageviews unavailable",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Harlem”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-06-08",
      "[news/recent-articles] Google News: 9 items in last 60d (40 returned) for “Harlem Shake”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Harlem Shake”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "Weak corroboration — blended heuristic (67) with AI double-check (38): Despite strong historical documentation, recent activity signals (news, Google Trends) are low, indicating the Harlem Shake is largely past its peak.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=52 (Google News: 9 items in last 60d (40 returned) for “Harlem Shake”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-16",
  lastUpdated: "2026-08-16",
  views: 2100000,
  trendDirection: "declining",
  meaning:
    "A ~30-second video format: one person dances alone while others ignore them; after Baauer's bass drop, the whole group erupts into chaotic dancing (often masked or costumed). In February 2013 it generated millions of uploads within roughly two weeks.",
  origin:
    "Built on Baauer's 2012–2013 trap track 'Harlem Shake' (Diplo's Mad Decent label). YouTuber Filthy Frank (George Miller) and friends filmed an early viral version uploaded via DizastaMusic in early February 2013. Wikipedia documents the subsequent flood of office, gym, university, and military remixes — YouTube reported hundreds of millions of combined views before the fad burned out mid-year. Note: the meme is unrelated to the traditional Harlem Shake dance that originated in Harlem decades earlier.",
  timeline: [
    { date: "2012", event: "Baauer's 'Harlem Shake' track circulates in electronic music circles" },
    { date: "Feb 2013", event: "Filthy Frank / DizastaMusic upload sparks the meme format" },
    { date: "Feb 2013", event: "Thousands of copycat videos flood YouTube within days" },
    { date: "Feb 2013", event: "YouTube reports hundreds of millions of combined views" },
    { date: "Mid-2013", event: "Format fades as quickly as it appeared" },
  ],
  examples: [
    "Every office did a Harlem Shake video in 2013.",
    "The Norwegian army Harlem Shake still lives rent-free in my head.",
    "Did you know the Harlem Shake meme is named after Baauer's song — not the classic Harlem dance?",
  ],
  relatedSlugs: ["rickroll", "ice-bucket-challenge"],
  media: [
    // ── FEATURED ───────────────────────────────────────────────────────────────
    // Video ID 8vJiSSAMNWw is the DizastaMusic channel upload — 70M+ views,
    // confirmed available. The original FilthyFrank channel video (8f7wj_RcqYk)
    // was removed when George Miller transitioned to the Joji persona.
    {
      role: "featured",
      type: "image",
      url: "https://i.ytimg.com/vi/8vJiSSAMNWw/hqdefault.jpg",
      title: "DO THE HARLEM SHAKE (ORIGINAL) — DizastaMusic thumbnail (Feb 2013)",
      source: "YouTube / DizastaMusic (George Miller / Filthy Frank)",
      sourceUrl: "https://www.youtube.com/watch?v=8vJiSSAMNWw",
      platform: "youtube",
      attribution: "George Miller (Filthy Frank / Joji) · Song: Baauer",
      license: "YouTube Standard License",
      description: "Thumbnail from the original Harlem Shake video that launched the viral format in February 2013, uploaded to the DizastaMusic channel.",
      date: "2013-02-02",
      verified: true,
    },
    // ── VIDEO ──────────────────────────────────────────────────────────────────
    {
      role: "video",
      type: "video",
      url: "https://www.youtube.com/watch?v=8vJiSSAMNWw",
      title: "DO THE HARLEM SHAKE (ORIGINAL) — DizastaMusic",
      source: "YouTube / DizastaMusic",
      sourceUrl: "https://www.youtube.com/watch?v=8vJiSSAMNWw",
      platform: "youtube",
      attribution: "George Miller (Filthy Frank / Joji) · Song: Baauer",
      license: "YouTube Standard License",
      description: "The original Harlem Shake video by George Miller (Filthy Frank) on the DizastaMusic channel — the upload that triggered the global viral format.",
      date: "2013-02-02",
      verified: true,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/harlem-shake",
      title: "Harlem Shake — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/harlem-shake",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Comprehensive documentation of the Harlem Shake meme including video examples and spread analysis.",
      verified: true,
    },
  ],
  sources: [
    {
      title: "Harlem Shake — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Harlem_Shake_(meme)",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
