import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m35",
  slug: "hide-the-pain-harold",
  title: "Hide the Pain Harold",
  category: "meme",
  description:
    "Hungarian stock-photo model András Arató — whose forced smile became the internet's face of polite suffering and fake enthusiasm.",
  imageGradient: "from-blue-500 via-sky-400 to-cyan-400",
  scores: { relevance: 50, influence: 76, cringe: 21, brainrot: 32 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 50,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "wikipedia",
      "news",
    ],
    popularity: 41,
    trendingScore: 27,
    recentRevival: false,
    popularityNotes: "Relevance: Recent creation signals rose modestly. Signals: news/recent-articles=41 (Google News: 5 items in last 60d (40 returned) for “Hide the Pain Harold”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=23,611 for “Hide the Pain Harold”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=3754 prev7=9388 (-60%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Hide”",
      "[news/recent-articles] Google News: 5 items in last 60d (40 returned) for “Hide the Pain Harold”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Hide the Pain Harold”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "Weak corroboration — blended heuristic (54) with AI double-check (45): Steady baseline interest (23k Wikipedia views) but a sharp recent decline, limited news and low Google‑Trends activity suggest moderate but waning popularity.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Recent creation signals rose modestly. Signals: news/recent-articles=41 (Google News: 5 items in last 60d (40 returned) for “Hide the Pain Harold”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-17",
  lastUpdated: "2026-08-16",
  historicalDate: "2011-01-01",
  views: 4500000,
  trendDirection: "declining",
  tags: ["stock-photo", "reaction", "classic", "hungary", "smile", "2011"],
  meaning:
    "Stock photos of András Arató smiling awkwardly are captioned to express internal pain, forced positivity, workplace misery, or 'I'm fine' energy — the smile that looks like it's hiding something.",
  origin:
    "Arató, a retired Hungarian electrical engineer, modeled for stock photography after being approached by a photographer. Around 2011–2012 internet users noticed his smile looked strained and nicknamed him 'Hide the Pain Harold.' The meme spread heavily on Reddit, 9GAG, and Russian social media; Arató later publicly embraced the persona.",
  timeline: [
    { date: "~2010–2011", event: "András Arató appears in stock-photo shoots" },
    { date: "2011–2012", event: "'Hide the Pain Harold' nickname and memes spread online" },
    { date: "Mid-2010s", event: "Arató reveals his identity and engages with fans" },
    { date: "2020s", event: "Remains a stable reaction image for forced smiles and quiet suffering" },
  ],
  examples: [
    "When the meeting could have been an email [Hide the Pain Harold]",
    "Smiling through a family dinner argument",
    "Customer service voice: activated",
  ],
  relatedSlugs: ["woman-yelling-at-cat", "chill-guy"],
  media: [
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/en/a/a4/Hide_the_Pain_Harold_%28Andr%C3%A1s_Arat%C3%B3%29.jpg",
      title: "Hide the Pain Harold — András Arató stock photo",
      source: "Wikipedia",
      sourceUrl:
        "https://en.wikipedia.org/wiki/File:Hide_the_Pain_Harold_(Andr%C3%A1s_Arat%C3%B3).jpg",
      platform: "wikimedia",
      attribution: "Stock photo of András Arató (fair use for identification)",
      license: "Fair use",
      description:
        "The most recognized Hide the Pain Harold stock image — Arató's strained smile that defines the meme.",
      date: "2011",
      verified: true,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/hide-the-pain-harold",
      title: "Hide the Pain Harold — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/hide-the-pain-harold",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Origin of the András Arató stock photos and meme nickname.",
      date: "2011",
      verified: true,
    },
  ],
  sources: [
    {
      title: "Hide the Pain Harold — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Hide_the_Pain_Harold",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
