import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m136",
  slug: "hydro-flask",
  title: "Hydro Flask",
  category: "meme",
  description:
    "The reusable water bottle that became a VSCO Girl totem — clanking metal straws, sticker stacks, and shorthand for a 2019 aesthetic.",
  imageGradient: "from-teal-400 via-cyan-300 to-slate-200",
  scores: { relevance: 37, influence: 60, cringe: 21, brainrot: 32 },
  dynamicMetadata: {
    lastReviewed: "2026-07-25",
    currentRelevance: 37,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "tiktok",
      "news",
    ],
    popularity: 30,
    trendingScore: 40,
    recentRevival: "unknown",
    popularityNotes: "Status: occasionally-referenced · Relevance 37 (today's recognition, not influence) · Trending 40 (recent attention)",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Hydro Flask”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/platform-activity] Wiktionary lookup unavailable for “Hydro”",
      "[news/recent-articles] Google News: 12 items in last 30d (40 returned) for “Hydro Flask”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Know Your Meme cited; Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Hydro Flask”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/gen-cohort-adoption] Cohort cue from tags (not used for relevance/trending)",
      "[catalog-evidence/remix-activity] Format/remix cue (brainrot/cringe only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-07-25",
  historicalDate: "2019-06-01",
  views: 2100000,
  trendDirection: "declining",
  tags: ["vsco-girl", "2019", "tiktok", "brand", "aesthetic", "environment"],
  meaning:
    "Memes about Hydro Flask metal water bottles as status objects — covered in stickers, paired with scrunchies and 'sksksk' humor. Represented eco-conscious performativity and teen trend identity on TikTok. Also used ironically to mock any overpriced reusable bottle culture.",
  origin:
    "Hydro Flask bottles existed for outdoor markets years earlier, but 2019's VSCO Girl meme cluster on TikTok — documented by Know Your Meme and major outlets — turned the pastel bottle into a visual punchline. The 'clank' of dropping a Hydro Flask in class became its own audio joke. The brand benefited from unpaid meme marketing while also symbolizing peak aesthetic conformity.",
  timeline: [
    { date: "2009", event: "Hydro Flask company founded in the Pacific Northwest" },
    { date: "Summer 2019", event: "VSCO Girl TikTok trend pairs Hydro Flask with scrunchies and Birkenstocks" },
    { date: "2019", event: "Parody videos and 'and I oop' audio memes peak" },
    { date: "2020s", event: "Aesthetic fades; bottle remains a generic reusable-bottle meme stand-in" },
  ],
  examples: [
    "VSCO Girl checklist meme: Hydro Flask, scrunchie, save the turtles",
    "ASMR joke: Hydro Flask hitting classroom floor",
    "Sticker-covered bottle as personality trait in teen comedy skits",
  ],
  relatedSlugs: ["dupe-economy", "crumbl-cookie", "prime-hydration", "labubu"],
  relationships: {
    sameEra: ["crumbl-cookie"],
    relatedEvent: ["dupe-economy"],
  },
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/vsco-girl",
      title: "VSCO Girl — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/vsco-girl",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "2019 aesthetic meme cluster including Hydro Flask totems.",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Hydro_Flask",
      title: "Hydro Flask — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Hydro_Flask",
      platform: "other",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      description: "Brand history and VSCO Girl cultural moment.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "VSCO Girl — Know Your Meme",
      url: "https://knowyourmeme.com/memes/vsco-girl",
      domain: "knowyourmeme.com",
    },
    {
      title: "Hydro Flask — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Hydro_Flask",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
