import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m62",
  slug: "imagine-if-ninja-got-a-low-taper-fade",
  title: "Imagine If Ninja Got a Low Taper Fade",
  category: "meme",
  description:
    "ericdoa's 2024 freestyle earworm about Ninja's haircut — the TikTok sound that made 'low taper fade' and 'still massive' into streamer meme lore.",
  imageGradient: "from-lime-400 via-green-500 to-emerald-700",
  scores: { relevance: 0, influence: 58, cringe: 21, brainrot: 45 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 0,
    currentStatus: "historical",
    activePlatforms: [
      "tiktok",
      "twitch",
    ],
    popularity: 0,
    trendingScore: 0,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (17 returned) for “Imagine If Ninja Got a Low Taper Fade”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Character signals still mark this as strongly representative of chaotic internet brainrot culture. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Imagine If Ninja Got a Low Taper Fade”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Imagine”",
      "[news/recent-articles] Google News: 0 items in last 60d (17 returned) for “Imagine If Ninja Got a Low Taper Fade”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Imagine If Ninja Got a Low Taper Fade”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/gen-cohort-adoption] Cohort cue from tags/title (brainrot character only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (17 returned) for “Imagine If Ninja Got a Low Taper Fade”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Character signals still mark this as strongly representative of chaotic internet brainrot culture.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-18",
  lastUpdated: "2026-08-16",
  historicalDate: "2024-01-05",
  views: 2800000,
  trendDirection: "declining",
  tags: ["tiktok", "ninja", "streaming", "2024", "earworm", "twitch"],
  meaning:
    "A hyperpop freestyle line — 'Imagine if Ninja got a low taper fade' — that became a TikTok sound, photoshop bait, and then a meta joke when Ninja got the cut and later insisted the meme was 'still massive.' One canonical meme; not separate articles for each alias.",
  origin:
    "Hyperpop artist ericdoa freestyled the line on Twitch in January 2024; @ericdoaclips pushed it to TikTok. Fans photoshopped Ninja with a fade; Ninja got the haircut mid-January. A later clip of him calling the meme 'still massive' spawned the dragging / future-Ninja parody wave (Know Your Meme).",
  timeline: [
    { date: "Jan 2024", event: "ericdoa freestyles the line on Twitch; TikTok sound explodes" },
    { date: "Jan 13, 2024", event: "Ninja debuts an actual low taper fade on TikTok" },
    { date: "Late Jan 2024", event: "'Still massive' dragging memes begin" },
    { date: "Late 2024", event: "Meta 'still massive' / Tfue high-taper parody variants circulate" },
  ],
  examples: [
    "Photoshop slideshows of Ninja with a fade set to the audio",
    "Ninja years in the future still saying the meme is massive",
    "Calling any over-milked meme 'still massive'",
  ],
  relatedSlugs: ["ninja", "tiktok-rise", "short-form-takeover", "npc-streaming"],
  relationships: {
    popularizedBy: ["ninja"],
    relatedEvent: ["tiktok-rise", "short-form-takeover"],
    relatedTo: ["npc-streaming"],
  },
  media: [
    // AI suggested — KYM cover for the low taper fade meme
    {
      role: "featured",
      type: "image",
      url: "https://i.kym-cdn.com/entries/icons/original/000/047/947/ninjacover.jpg",
      title: "Imagine If Ninja Got a Low Taper Fade — cover",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/imagine-if-ninja-got-a-low-taper-fade",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Cover imagery for the Ninja low taper fade TikTok meme.",
      date: "2024",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/imagine-if-ninja-got-a-low-taper-fade",
      title: "Imagine If Ninja Got a Low Taper Fade — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/imagine-if-ninja-got-a-low-taper-fade",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Freestyle origin, haircut payoff, and 'still massive' aftermath.",
      date: "2024",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Imagine If Ninja Got a Low Taper Fade — Wikipedia search",
      url: "https://en.wikipedia.org/w/index.php?search=Imagine%20If%20Ninja%20Got%20a%20Low%20Taper%20Fade&title=Special:Search&fulltext=1",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
