import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m117",
  slug: "italian-brainrot",
  title: "Italian Brainrot",
  category: "meme",
  description:
    "AI-generated hybrid creatures with rhyming pseudo-Italian names and TTS narration — TikTok's surreal 2025 brainrot wave.",
  imageGradient: "from-green-600 via-red-500 to-white",
  scores: { relevance: 44, influence: 72, cringe: 21, brainrot: 98 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 44,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "tiktok",
      "wikipedia",
      "news",
    ],
    popularity: 32,
    trendingScore: 42,
    recentRevival: false,
    popularityNotes: "Relevance: Recent creation signals rose modestly. Signals: news/recent-articles=32 (Google News: 3 items in last 60d (40 returned) for “Italian Brainrot”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Character signals still mark this as strongly representative of chaotic internet brainrot culture. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=62,044 for “Italian brainrot”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=14097 prev7=13941 (1%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Italian”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-08-09",
      "[news/recent-articles] Google News: 3 items in last 60d (40 returned) for “Italian Brainrot”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Italian Brainrot”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/absurdity] Tag/title absurdity cue (brainrot character only)",
      "[catalog-evidence/gen-cohort-adoption] Cohort cue from tags/title (brainrot character only)",
      "[catalog-evidence/remix-activity] Format/remix / short-form reuse cue (brainrot character only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Recent creation signals rose modestly. Signals: news/recent-articles=32 (Google News: 3 items in last 60d (40 returned) for “Italian Brainrot”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Character signals still mark this as strongly representative of chaotic internet brainrot culture.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "2025-01-13",
  views: 5200000,
  trendDirection: "stable",
  tags: ["brainrot", "ai", "tiktok", "2025", "gen-alpha", "italian"],
  meaning:
    "A TikTok-native meme genre: AI-generated images of absurd animal-object hybrids (a shark in Nike shoes, a bomber with a crocodile head) given rhyming Italian-ish names like Tralalero Tralala or Bombardiro Crocodilo, narrated by a male Italian text-to-speech voice saying nonsense lore. It is brainrot as worldbuilding — kids memorize character rosters like Pokémon, adults recoil at the slop aesthetic.",
  origin:
    "Wikipedia traces the trend to early January 2025 on TikTok. User @amoamimandy.1a's January 13 post pairing the 'Tralalero Tralala' audio with an AI shark in sneakers gained tens of millions of plays. Earlier audio circulated from banned user @eZburger401. The format exploded with Bombardiro Crocodilo, Lirili Larila, and dozens of spinoff characters; international variants like Tung Tung Tung Sahur followed. Forbes and other outlets covered the wave in 2025 as a Gen Alpha playground lore system built from AI image generators and Italian TTS narration.",
  timeline: [
    { date: "Jan 2025", event: "Tralalero Tralala AI shark video spreads on TikTok" },
    { date: "Jan 2025", event: "Bombardiro Crocodilo and other characters join the roster" },
    { date: "Mar 2025", event: "Streamer tier-list videos push trend into mainstream discourse" },
    { date: "2025", event: "Forbes, Capital FM, and Wikipedia document Italian brainrot globally" },
    { date: "2025+", event: "Spawns international brainrot variants and Gen Alpha playground lore" },
  ],
  examples: [
    "My cousin can name every Italian brainrot character like it's Pokémon.",
    "Tralalero Tralala is stuck in my head and I hate that I know what it is.",
    "Parents asking what 'Ballerina Cappuccina' means at dinner.",
  ],
  relatedSlugs: ["brainrot", "skibidi-toilet", "tung-tung-tung-sahur", "shrimp-jesus"],
  relationships: {
    relatedSlang: ["brainrot"],
    sameEra: ["tung-tung-tung-sahur", "skibidi-toilet"],
    sameFormat: ["shrimp-jesus"],
  },
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/italian-brainrot-ai-italian-animals",
      title: "Italian Brainrot / AI Italian Animals — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/italian-brainrot-ai-italian-animals",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Documentation of Tralalero Tralala and the Italian brainrot roster.",
      date: "2025",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Italian_brainrot",
      title: "Italian brainrot — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Italian_brainrot",
      platform: "wikimedia",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Italian brainrot — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Italian_brainrot",
      domain: "en.wikipedia.org",
    },
    {
      title: "What Is Italian Brain Rot? — Forbes",
      url: "https://www.forbes.com/sites/lesliekatz/2025/05/03/what-is-italian-brain-rot-the-surreal-tiktok-obsession-explained/",
      domain: "forbes.com",
    },
  ],
};

export default entry;
