import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m25",
  slug: "leeroy-jenkins",
  title: "Leeroy Jenkins",
  category: "meme",
  description:
    "A 2005 World of Warcraft video in which a player named Leeroy Jenkins charges recklessly into a dungeon while his teammates are still planning, destroying the raid and immortalizing a battle cry.",
  imageGradient: "from-blue-600 via-indigo-500 to-purple-500",
  scores: { relevance: 36, influence: 83, cringe: 55, brainrot: 26 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 36,
    currentStatus: "classic",
    activePlatforms: [
      "wikipedia",
      "news",
    ],
    popularity: 25,
    trendingScore: 35,
    recentRevival: false,
    popularityNotes: "Relevance: Recent creation signals rose modestly. Signals: news/recent-articles=25 (Google News: 2 items in last 60d (40 returned) for “Leeroy Jenkins”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Mockery or dated-perception signals suggest higher social cringe today.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=12,189 for “Leeroy Jenkins”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=2862 prev7=3047 (-6%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Leeroy”",
      "[dictionary/platform-activity] Wiktionary last revision 2025-06-23",
      "[news/recent-articles] Google News: 2 items in last 60d (40 returned) for “Leeroy Jenkins”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Leeroy Jenkins”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/mockery-signal] Tag mockery cue (cringe only, 1 match)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Recent creation signals rose modestly. Signals: news/recent-articles=25 (Google News: 2 items in last 60d (40 returned) for “Leeroy Jenkins”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Mockery or dated-perception signals suggest higher social cringe today.",
    },
  },
  addedAt: "2026-07-17",
  lastUpdated: "2026-08-16",
  historicalDate: "2005-05-11",
  views: 2500000,
  trendDirection: "stable",
  tags: ["gaming", "world-of-warcraft", "2005", "classic", "strategy-fail"],
  meaning:
    "Used whenever someone rushes into a situation without thinking, ignoring everyone else's careful planning. 'You pulled a Leeroy Jenkins' means you acted recklessly and ruined the plan for everyone. The phrase encapsulates the chaos that one impulsive person can unleash on a group.",
  origin:
    "On May 11, 2005, the guild 'PALS FOR LIFE' posted a video of their World of Warcraft raid attempt. While the group carefully calculated survival probabilities for an encounter in Upper Blackrock Spire, player Leeroy Jenkins was AFK. He then returned, screamed 'LEEEEROYYY JENKIIINS!', and charged into the dungeon before the raid was ready, triggering a full wipe. The video spread through gaming forums and YouTube, becoming one of the first major internet memes from video games.",
  timeline: [
    { date: "May 2005", event: "Video posted by PALS FOR LIFE — Leeroy charges into Upper Blackrock Spire" },
    { date: "2005", event: "Spread across gaming forums, Newgrounds, and early YouTube" },
    { date: "2006", event: "Referenced on Jeopardy! — mainstream cultural confirmation" },
    { date: "2008", event: "Added to World of Warcraft as an in-game achievement: 'Leeeeeeeroy!'" },
    { date: "2010s", event: "Remains a standard reference for reckless group planning in gaming culture" },
    { date: "2020", event: "Selected for preservation in the Library of Congress National Film Registry" },
  ],
  examples: [
    "Your team is planning the office party carefully, one person books the venue without asking → 'Absolute Leeroy Jenkins move'",
    "At least I have chicken.",
    "Every startup that launches before the product is ready is running a Leeroy Jenkins play",
  ],
  relatedSlugs: [
    "press-f-to-pay-respects",
    "the-cake-is-a-lie",
    "all-your-base-are-belong-to-us",
    "ah-shit-here-we-go-again",
    "arrow-to-the-knee",
    "git-gud",
  ],
  media: [
    {
      role: "featured",
      type: "image",
      url: "https://i.ytimg.com/vi/mLyOj_QD4a4/hqdefault.jpg",
      title: "Leeroy Jenkins — YouTube video thumbnail",
      source: "YouTube / J Jonah Jameson (re-upload)",
      sourceUrl: "https://www.youtube.com/watch?v=mLyOj_QD4a4",
      platform: "youtube",
      attribution: "PALS FOR LIFE (original creators, 2005)",
      description: "Thumbnail from the most widely linked HD re-upload of the original 2005 PALS FOR LIFE Leeroy Jenkins World of Warcraft video.",
      date: "2005-05-11",
      verified: true,
    },
    {
      role: "video",
      type: "video",
      url: "https://www.youtube.com/watch?v=mLyOj_QD4a4",
      title: "Leeroy Jenkins (HD) — the original 2005 WoW video",
      source: "YouTube",
      sourceUrl: "https://www.youtube.com/watch?v=mLyOj_QD4a4",
      platform: "youtube",
      attribution: "PALS FOR LIFE (original creators, 2005); re-uploaded by J Jonah Jameson",
      description: "The full Leeroy Jenkins video — 1 minute 17 seconds that launched one of internet culture's most enduring phrases. The original raid planning, the AFK return, and the immortal battle cry.",
      date: "2005-05-11",
      verified: true,
    },
  ],
  sources: [
    {
      title: "Leeroy Jenkins — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Leeroy_Jenkins",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
