import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m50",
  slug: "lord-farquaad-e",
  title: "Lord Farquaad E",
  category: "meme",
  description:
    "The deep-fried Markiplier-as-Lord-Farquaad image stamped with a giant Impact 'E' — a 2018 peak of absurdist dank meme humor.",
  imageGradient: "from-yellow-400 via-lime-500 to-green-700",
  scores: { relevance: 25, influence: 76, cringe: 40, brainrot: 40 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 25,
    currentStatus: "classic",
    activePlatforms: [
      "wikipedia",
    ],
    popularity: 16,
    trendingScore: 32,
    recentRevival: false,
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=16 (Google News: 1 items in last 60d (21 returned) for “Lord Farquaad E”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Character signals still mark this as strongly representative of chaotic internet brainrot culture. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=55,361 for “Internet meme”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=13130 prev7=13608 (-4%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Lord”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-07-17",
      "[news/recent-articles] Google News: 1 items in last 60d (21 returned) for “Lord Farquaad E”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Lord Farquaad E”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/absurdity] Tag/title absurdity cue (brainrot character only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=16 (Google News: 1 items in last 60d (21 returned) for “Lord Farquaad E”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Character signals still mark this as strongly representative of chaotic internet brainrot culture.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-18",
  lastUpdated: "2026-08-16",
  historicalDate: "2018-02-15",
  views: 1900000,
  trendDirection: "stable",
  tags: ["deep-fried", "markiplier", "shrek", "2018", "dank", "ironic"],
  meaning:
    "A deliberately incomprehensible deep-fried mashup: Markiplier's face on Lord Farquaad (later Zuckerberg edits), captioned only with the letter E. Used as a symbol of how weird millennial/dank humor looked from the outside — and as a punchline inside that humor.",
  origin:
    "A Markiplier-on-Farquaad edit circulated from 2015 (Cyndago). The deep-fried 'E' version appeared on Tumblr's photo-frier blog in February 2018 and exploded on Reddit (/r/dankmemes, /r/deepfriedmemes, /r/me_irl) in April 2018 as 'Lord Marquaad E' (Know Your Meme).",
  timeline: [
    { date: "May 2015", event: "Early Markiplier/Farquaad face swap posted on Twitter" },
    { date: "Feb 2018", event: "Deep-fried 'E' version posted on Tumblr photo-frier" },
    { date: "Apr 2018", event: "Reddit spread; Zuckerberg-body variants on deepfriedmemes" },
    { date: "May 2018", event: "Covered by The Daily Dot; referenced by PewDiePie" },
    { date: "2018+", event: "Letter-meme spin-offs (M, C) and 'weird humor' templates" },
  ],
  examples: [
    "Memes Then / Memes Now panels ending on Farquaad E",
    "'Why is millennial humor so weird?' templates featuring the E face",
    "Any deep-fried reaction that answers a question with just 'E'",
  ],
  relatedSlugs: ["distorted-meme-face", "markiplier", "expanding-brain"],
  relationships: {
    sameFormat: ["distorted-meme-face"],
    popularizedBy: ["markiplier"],
    sameEra: ["expanding-brain"],
  },
  media: [
    // AI suggested — KYM entry icon is the defining deep-fried E image
    {
      role: "featured",
      type: "image",
      url: "https://i.kym-cdn.com/entries/icons/original/000/026/008/Screen_Shot_2018-04-25_at_12.24.22_PM.png",
      title: "Lord Farquaad E / Lord Marquaad E — defining image",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/lord-marquaad-e",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description:
        "The deep-fried Markiplier–Farquaad composite with Impact letter E.",
      date: "2018",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/lord-marquaad-e",
      title: "Lord Marquaad E — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/lord-marquaad-e",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Origin and Reddit spread of the Lord Farquaad E meme.",
      date: "2018",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Lord Farquaad E — Wikipedia search",
      url: "https://en.wikipedia.org/w/index.php?search=Lord%20Farquaad%20E&title=Special:Search&fulltext=1",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
