import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m118",
  slug: "mission-failed-successfully",
  title: "Mission Failed Successfully",
  category: "meme",
  description:
    "Hitman's 'Mission Failed' screen turned into a joke — you technically lost but somehow achieved the real goal.",
  imageGradient: "from-red-800 via-rose-700 to-orange-600",
  scores: { relevance: 0, influence: 68, cringe: 55, brainrot: 58 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 0,
    currentStatus: "historical",
    activePlatforms: [
      "wikipedia",
    ],
    popularity: 0,
    trendingScore: 21,
    recentRevival: false,
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (40 returned) for “Mission Failed Successfully”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Character signals still mark this as strongly representative of chaotic internet brainrot culture. Cringe: Mockery or dated-perception signals suggest higher social cringe today.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=2,543 for “List of viral music videos”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=526 prev7=612 (-14%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Mission”",
      "[dictionary/platform-activity] Wiktionary last revision 2025-10-31",
      "[news/recent-articles] Google News: 0 items in last 60d (40 returned) for “Mission Failed Successfully”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Mission Failed Successfully”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/mockery-signal] Tag mockery cue (cringe only, 1 match)",
      "[catalog-evidence/remix-activity] Format/remix / short-form reuse cue (brainrot character only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (40 returned) for “Mission Failed Successfully”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Character signals still mark this as strongly representative of chaotic internet brainrot culture.",
      cringe: "Mockery or dated-perception signals suggest higher social cringe today.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "2016-01-01",
  views: 2200000,
  trendDirection: "declining",
  tags: ["hitman", "gaming", "irony", "2016", "template", "classic"],
  meaning:
    "A caption meme pairing Hitman's red 'Mission Failed' UI with scenarios where failure was the point — or where a botched plan accidentally succeeded at something else. The oxymoron 'failed successfully' captures gaming irony and everyday life: you lost the stated objective but won the joke, the chaos, or the unintended outcome.",
  origin:
    "The Hitman series (IO Interactive) displays a prominent 'Mission Failed' screen when objectives go wrong. Know Your Meme documents players screenshotting these moments for humor around 2016, and the phrase 'mission failed successfully' spreading on Reddit and Tumblr as a general ironic success/failure format — related to but distinct from the 'Task failed successfully' Windows meme.",
  timeline: [
    { date: "2000s–2010s", event: "Hitman 'Mission Failed' screen becomes iconic in gaming" },
    { date: "2016", event: "'Mission failed successfully' captions spread on Reddit" },
    { date: "2018–2020", event: "Used for life fails that secretly worked out" },
    { date: "2020s", event: "Standard format for ironic outcome posts across gaming Twitter" },
  ],
  examples: [
    "Bombed the exam but skipped a party — Mission Failed Successfully",
    "Hitman NPC dies accidentally — Mission Failed (that's the joke)",
    "Tried to cook dinner, ordered pizza — failed successfully",
  ],
  relatedSlugs: ["press-f-to-pay-respects", "ah-shit-here-we-go-again", "this-is-fine"],
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/mission-failed-successfully",
      title: "Mission Failed Successfully — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/mission-failed-successfully",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Documentation of the Hitman-based ironic failure meme.",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/hitman",
      title: "Hitman — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/hitman",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Hitman (franchise) — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Hitman_(franchise)",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
