import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m2",
  slug: "ohio-final-boss",
  title: "Ohio Final Boss",
  category: "meme",
  description:
    "Gen Alpha absurdist lore: the climactic 'final boss' of Only-in-Ohio surrealism — often tied to Satoyu0704's phonk/suit persona and Ohio chaos edits.",
  imageGradient: "from-red-600 via-rose-500 to-orange-400",
  scores: { relevance: 34, influence: 58, cringe: 21, brainrot: 41 },
  dynamicMetadata: {
    lastReviewed: "2026-07-25",
    currentRelevance: 34,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "tiktok",
      "wikipedia",
    ],
    popularity: 41,
    trendingScore: 20,
    recentRevival: false,
    popularityNotes: "Status: occasionally-referenced · Relevance 34 (today's recognition, not influence) · Trending 20 (recent attention)",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=16,889 for “List of Internet phenomena”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=3790 prev7=3720 (2%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Ohio”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-06-17",
      "[news/recent-articles] Google News: 0 items in last 30d (40 returned) for “Ohio Final Boss”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Know Your Meme cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Ohio Final Boss”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/absurdity] Tag/category absurdity cue (not used for relevance/trending)",
      "[catalog-evidence/gen-cohort-adoption] Cohort cue from tags (not used for relevance/trending)",
      "[catalog-evidence/remix-activity] Format/remix cue (brainrot/cringe only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
  },
  addedAt: "2026-07-10",
  lastUpdated: "2026-07-25",
  views: 510000,
  trendDirection: "declining",
  tags: ["ohio", "brainrot", "gen alpha", "tiktok", "phonk", "satoyu"],
  meaning:
    "A fictional supervillain / peak-absurdity character embodying Ohio's meme reputation for bizarre, unexplainable events. Used as shorthand for anything maximally weird online.",
  origin:
    "Grew out of the 'Only in Ohio' format on TikTok, which packages bizarre or surreal content under the premise that Ohio is uniquely strange. As the format escalated, creators added fictional creatures and lore — including Satoyu0704's suited 'Ohio Final Boss' persona — treating Ohio absurdity as an RPG-style climactic enemy.",
  timeline: [
    { date: "2022–2023", event: "'Only in Ohio' TikTok format goes mainstream" },
    { date: "2022+", event: "Satoyu0704 suit/phonk edits nicknamed Ohio Final Boss" },
    { date: "2024", event: "Meme escalates to 'Final Boss' tier edits and lore threads" },
    { date: "2025–2026", event: "'Ohio Final Boss' becomes shorthand for peak internet absurdity" },
  ],
  examples: [
    "Ohio final boss just spawned at my local Walmart",
    "Defeating the Ohio final boss is this generation's Dark Souls",
    "Bro lives in Ohio — he's fighting the final boss IRL",
  ],
  relatedSlugs: [
    "skibidi-toilet",
    "chicken-jockey",
    "brainrot",
    "tung-tung-tung-sahur",
    "npc-streaming",
  ],
  relationships: {
    relatedTo: ["skibidi-toilet", "tung-tung-tung-sahur", "chicken-jockey"],
    relatedSlang: ["brainrot"],
    sameEra: ["npc-streaming"],
  },
  media: [
    // AI suggested — Satoyu0704 / Ohio Final Boss KYM entry icon; human must verify and set verified: true
    {
      role: "featured",
      type: "image",
      url: "https://i.kym-cdn.com/entries/icons/original/000/042/521/averagecitizeninohio.jpg",
      title: "Satoyu0704 — Ohio Final Boss (suit / phonk persona)",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/people/satoyu0704-ohio-final-boss",
      platform: "knowyourmeme",
      attribution: "Satoyu0704 / via Know Your Meme documentation",
      description:
        "Defining visual of Satoyu0704 in the suit persona nicknamed the Ohio Final Boss, with Only-in-Ohio caption styling.",
      date: "2022",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/people/satoyu0704-ohio-final-boss",
      title: "Satoyu0704 / Ohio Final Boss — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/people/satoyu0704-ohio-final-boss",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Documentation of Satoyu0704 as the Ohio Final Boss meme persona.",
      date: "2022",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Satoyu0704 / Ohio Final Boss — Know Your Meme",
      url: "https://knowyourmeme.com/memes/people/satoyu0704-ohio-final-boss",
      domain: "knowyourmeme.com",
    },
    {
      title: "Only in Ohio — Know Your Meme",
      url: "https://knowyourmeme.com/memes/only-in-ohio",
      domain: "knowyourmeme.com",
    },
  ],
};

export default entry;
