import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m137",
  slug: "prime-hydration",
  title: "Prime Hydration",
  category: "meme",
  description:
    "Logan Paul and KSI's Prime drink — schoolyard resale hype, taste-test wars, and influencer merch culture turned energy-drink meme.",
  imageGradient: "from-blue-600 via-cyan-400 to-yellow-400",
  scores: { relevance: 92, influence: 58, cringe: 23, brainrot: 32 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 92,
    currentStatus: "highly-active",
    activePlatforms: [
      "youtube",
      "news",
    ],
    popularity: 73,
    trendingScore: 73,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=73 (Google News: 24 items in last 60d (40 returned) for “Prime Hydration”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Prime Hydration”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Prime”",
      "[dictionary/platform-activity] Wiktionary last revision 2025-10-09",
      "[news/recent-articles] Google News: 24 items in last 60d (40 returned) for “Prime Hydration”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Prime Hydration”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=73 (Google News: 24 items in last 60d (40 returned) for “Prime Hydration”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "2022-01-01",
  views: 2800000,
  trendDirection: "declining",
  tags: ["logan-paul", "ksi", "youtube", "brand", "2022", "hype"],
  meaning:
    "Memes about Prime Hydration — the brightly packaged sports drink co-founded by Logan Paul and KSI. Jokes cover scalping at school, blind taste tests, 'Prime vs Gatorade' loyalty wars, and skepticism that YouTubers can sell anything. A case study in creator-led CPG going viral through fan armies and controversy.",
  origin:
    "Prime launched in 2022 with massive YouTube promotion from Paul and KSI. Know Your Meme and business press documented shortages, resale markup memes, and UK school bans making headlines. The product sat alongside Lunchly and other creator brands as meme fodder about influencer economies — fans defending it, critics calling it overpriced electrolyte water with hype.",
  timeline: [
    { date: "2022", event: "Prime Hydration launches with Paul and KSI promotion" },
    { date: "2022–2023", event: "School resale and shortage memes spread on TikTok" },
    { date: "2023", event: "Regulatory scrutiny and taste-test backlash cycles in news" },
    { date: "2024+", event: "Settles into creator-brand meme vocabulary with Feastables and Lunchly" },
  ],
  examples: [
    "Kid selling Prime out of a backpack at markup — meme caption 'entrepreneur'",
    "TikTok blind taste test: Prime vs tap water drama",
    "Comment section war: 'KSI carried' vs 'Logan carried'",
  ],
  relatedSlugs: ["logan-paul", "ksi", "feastables", "lunchly", "dupe-economy", "salt-bae"],
  relationships: {
    popularized: ["logan-paul", "ksi"],
    relatedEvent: ["dupe-economy"],
    sameEra: ["feastables", "lunchly"],
  },
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/cultures/prime-energy-hydration-drink",
      title: "Prime Energy / Hydration Drink — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/cultures/prime-energy-hydration-drink",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Prime Hydration hype and meme documentation.",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Prime_(drink)",
      title: "Prime (drink) — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Prime_(drink)",
      platform: "other",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      description: "Product launch and cultural reception.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Prime (drink) — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Prime_(drink)",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
