import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m49",
  slug: "quandale-dingle",
  title: "Quandale Dingle",
  category: "meme",
  description:
    "A 2021–2022 Gen Alpha shitpost character — a funny real name turned goofy-ahh lore, freestyles, and deep-fried edits.",
  imageGradient: "from-lime-500 via-emerald-600 to-teal-700",
  scores: { relevance: 20, influence: 68, cringe: 21, brainrot: 32 },
  dynamicMetadata: {
    lastReviewed: "2026-07-25",
    currentRelevance: 20,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "tiktok",
    ],
    popularity: 30,
    trendingScore: 15,
    recentRevival: "unknown",
    popularityNotes: "Status: occasionally-referenced · Relevance 20 (today's recognition, not influence) · Trending 15 (recent attention)",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Quandale Dingle”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Quandale”",
      "[news/recent-articles] Google News: 0 items in last 30d (30 returned) for “Quandale Dingle”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Know Your Meme cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Quandale Dingle”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/absurdity] Tag/category absurdity cue (not used for relevance/trending)",
      "[catalog-evidence/gen-cohort-adoption] Cohort cue from tags (not used for relevance/trending)",
      "[catalog-evidence/remix-activity] Format/remix cue (brainrot/cringe only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
  },
  addedAt: "2026-07-18",
  lastUpdated: "2026-07-25",
  historicalDate: "2021-09-13",
  views: 2800000,
  trendDirection: "declining",
  tags: ["gen alpha", "brainrot", "tiktok", "deep-fried", "goofy ahh", "2021", "2022"],
  meaning:
    "An absurdist meme character built around the real name Quandale Dingle: login-screen jokes, distorted stand-in faces, fake crime lore, and deep-voiced freestyles. Used as a shorthand for pure goofy-ahh brainrot humor rather than as a biography of the real person.",
  origin:
    "In September 2021 a TikTok of a Windows login screen for user 'Quandale Dingle' spread for the absurd name alone (Know Your Meme). Through late 2021–2022, creators layered distorted images (often of NBA YoungBoy), RapTV-style parody posts, and Ticklemytip's deep Quandale voice / freestyles, turning the name into a Gen Alpha shitpost fixture.",
  timeline: [
    { date: "Sep 2021", event: "TikTok login-screen clip for 'Quandale Dingle' spreads" },
    { date: "Late 2021", event: "Distorted stand-in faces and ironic compilations take off" },
    { date: "Early 2022", event: "Fake lore, RapTV parody posts, and voice freestyles explode on TikTok" },
    { date: "Apr 2022", event: "Ticklemytip's 'Dingle Race Freestyle' and related sounds go viral" },
    { date: "2022+", event: "Name becomes a staple of goofy-ahh / brainrot meme culture" },
  ],
  examples: [
    "Fake news chyron: 'Quandale Dingle escapes prison, declares war on Italy'",
    "Deep-voiced freestyle clips used as TikTok sounds",
    "Calling any chaotic Gen Alpha edit 'peak Quandale energy'",
  ],
  relatedSlugs: ["brainrot", "distorted-meme-face", "skibidi-toilet", "ohio-final-boss"],
  relationships: {
    relatedSlang: ["brainrot"],
    sameFormat: ["distorted-meme-face"],
    sameEra: ["skibidi-toilet", "ohio-final-boss"],
    community: ["brainrot"],
  },
  media: [
    // AI suggested — KYM cover; human must verify and set verified: true
    {
      role: "featured",
      type: "image",
      url: "https://i.kym-cdn.com/entries/icons/original/000/039/721/cover6.jpg",
      title: "Quandale Dingle — Know Your Meme cover",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/quandale-dingle",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description:
        "Entry cover representing the Quandale Dingle shitpost character (not a portrait of the private individual).",
      date: "2021",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/quandale-dingle",
      title: "Quandale Dingle — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/quandale-dingle",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Origin, voice lore, and spread of the Quandale Dingle meme.",
      date: "2021",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Quandale Dingle — Know Your Meme",
      url: "https://knowyourmeme.com/memes/quandale-dingle",
      domain: "knowyourmeme.com",
    },
    {
      title: "Who Or What Is The 'Quandale Dingle' Meme? — Know Your Meme",
      url: "https://knowyourmeme.com/editorials/guides/who-or-what-is-the-quandale-dingle-meme-heres-your-answer",
      domain: "knowyourmeme.com",
    },
  ],
};

export default entry;
