import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m124",
  slug: "reddit-discord-mod",
  title: "Reddit / Discord Mod",
  category: "meme",
  description:
    "The stereotype meme of the overweight, basement-dwelling forum moderator — a punchline about unpaid internet authority and moderation culture.",
  imageGradient: "from-indigo-900 via-purple-800 to-slate-700",
  scores: { relevance: 92, influence: 58, cringe: 21, brainrot: 32 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 92,
    currentStatus: "highly-active",
    activePlatforms: [
      "reddit",
      "discord",
      "wikipedia",
      "news",
    ],
    popularity: 73,
    trendingScore: 61,
    recentRevival: false,
    popularityNotes: "Relevance: Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=73 (Google News: 24 items in last 60d (40 returned) for “Reddit meme”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=15,907 for “Doge (meme)”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=3769 prev7=3829 (-2%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Reddit”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-08-06",
      "[news/recent-articles] Google News: 24 items in last 60d (40 returned) for “Reddit meme”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Reddit meme”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=73 (Google News: 24 items in last 60d (40 returned) for “Reddit meme”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "2018-01-01",
  views: 1750000,
  trendDirection: "rising",
  tags: ["stereotype", "reddit", "discord", "moderation", "4chan", "satire"],
  meaning:
    "A caricature — often a Wojak or photo edit of an overweight man at a computer — representing the joke that Reddit or Discord moderators are power-tripping volunteers with no offline life. Used to mock bans, rule enforcement, or anyone acting like an unpaid cop in a server. The meme is insult comedy about platform governance, not a portrait of any one person.",
  origin:
    "Moderator stereotypes circulated on 4chan and Reddit for years, but the visual template crystallized in the late 2010s alongside Wojak variant culture and 'jannie' (janitor) slang on /pol/ and related boards. Know Your Meme documents composite images pairing mod jokes with basement setups, energy drinks, and fedora tropes. Discord's rise in gaming communities gave the format a second label — same joke, different platform logo.",
  timeline: [
    { date: "2010s", event: "'Internet janitor' jokes target forum volunteers on imageboards" },
    { date: "2018–2019", event: "Visual Wojak mod caricatures spread on Reddit and Twitter" },
    { date: "2020", event: "Discord mod variant peaks during server moderation debates" },
    { date: "2021+", event: "Used in meta-memes about bans, powermods, and server drama" },
  ],
  examples: [
    "Posting the mod Wojak when someone deletes a joke for 'rule 4'",
    "'Discord mod' caption on a neckbeard stock photo after a timeout",
    "Ironically calling yourself mod after pinning your own meme",
  ],
  relatedSlugs: ["wojak", "soyjak", "gigachad", "npc", "trollface"],
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/discord-mods-please-keep-memes-out-of-general",
      title: "Discord Mods — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/discord-mods-please-keep-memes-out-of-general",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Discord moderator stereotype memes and starter-pack culture.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Reddit / Discord Mod — Wikipedia search",
      url: "https://en.wikipedia.org/w/index.php?search=Reddit%20%2F%20Discord%20Mod&title=Special:Search&fulltext=1",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
