import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m119",
  slug: "return-to-monke",
  title: "Return to Monke",
  category: "meme",
  description:
    "'Reject modernity, return to monke' — an anarcho-primitivist joke about abandoning civilization for ape simplicity.",
  imageGradient: "from-amber-800 via-yellow-700 to-lime-600",
  scores: { relevance: 28, influence: 70, cringe: 21, brainrot: 32 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 28,
    currentStatus: "classic",
    activePlatforms: [],
    popularity: 16,
    trendingScore: 16,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Recent creation activity still looks similar (sparse recent creation). Signals: news/recent-articles=16 (Google News: 1 items in last 60d (40 returned) for “Return to Monke”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Return to Monke”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/platform-activity] Wiktionary lookup unavailable for “Return”",
      "[news/recent-articles] Google News: 1 items in last 60d (40 returned) for “Return to Monke”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Return to Monke”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "Weak corroboration — blended heuristic (25) with AI double-check (30): Documentation scores are high but recent news, platform activity, and trends are low, indicating modest current popularity.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Recent creation activity still looks similar (sparse recent creation). Signals: news/recent-articles=16 (Google News: 1 items in last 60d (40 returned) for “Return to Monke”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "2019-02-01",
  views: 2600000,
  trendDirection: "declining",
  tags: ["monke", "ape", "primitivism", "2019", "4chan", "ironic"],
  meaning:
    "A meme phrase pairing 'reject modernity' with 'return to monke' (deliberate misspelling of monkey). Usually illustrated with apes, chimps, or orangutans living simply while humans suffer modern life. It is ironic anarcho-primitivism — joking that tech, jobs, and discourse are unbearable and we'd be happier as apes. Often overlaps with Harambe nostalgia and 'monke' fandom humor.",
  origin:
    "Know Your Meme traces the phrase to 4chan and Reddit around early 2019, building on earlier 'monke' ape worship humor and Harambe meme legacies. Facebook groups like 'Reject modernity return to monke' helped push it mainstream in 2020. The intentional 'monke' spelling matches doge-era ironic broken English.",
  timeline: [
    { date: "Early 2019", event: "'Reject modernity, return to monke' spreads on 4chan and Reddit" },
    { date: "2020", event: "Facebook meme pages and Twitter adopt the format widely" },
    { date: "2020–2021", event: "Peak use during pandemic 'civilization failed' irony" },
    { date: "2022+", event: "Remains shorthand for anti-modernity jokes and ape reaction images" },
  ],
  examples: [
    "Office job meltdown — 'reject modernity return to monke'",
    "Ape photo with caption about abandoning smartphones for banana",
    "Comparing complex politics to simple monke life",
  ],
  relatedSlugs: ["doge", "cheems", "wojak", "dat-boi"],
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/return-to-monke",
      title: "Return to Monke — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/return-to-monke",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Documentation of the reject modernity / return to monke meme.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Return to Monke — Wikipedia search",
      url: "https://en.wikipedia.org/w/index.php?search=Return%20to%20Monke&title=Special:Search&fulltext=1",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
