import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m24",
  slug: "salt-bae",
  title: "Salt Bae",
  category: "meme",
  description:
    "Turkish chef Nusret Gökçe's viral salt-sprinkling gesture — sliding salt down his forearm and into his dishes — became one of the defining reaction images and GIFs of 2017.",
  imageGradient: "from-amber-500 via-yellow-400 to-orange-300",
  scores: { relevance: 35, influence: 70, cringe: 31, brainrot: 29 },
  dynamicMetadata: {
    lastReviewed: "2026-07-25",
    currentRelevance: 40,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "instagram",
      "wikipedia",
      "news",
    ],
    popularity: 41,
    trendingScore: 39,
    recentRevival: false,
    popularityNotes: "Status: occasionally-referenced · Relevance 40 (today's recognition, not influence) · Trending 39 (recent attention)",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=35,457 for “Salt Bae”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=9424 prev7=7054 (34%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM last updated ~3485d ago (2017-01-07)",
      "[dictionary/authority-documentation] Wiktionary page “Salt”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-04-23",
      "[news/recent-articles] Google News: 5 items in last 30d (40 returned) for “Salt Bae”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Know Your Meme cited; Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Salt Bae”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/remix-activity] Format/remix cue (brainrot/cringe only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
  },
  addedAt: "2026-07-17",
  lastUpdated: "2026-07-25",
  historicalDate: "2017-01-07",
  views: 3100000,
  trendDirection: "declining",
  tags: ["chef", "viral", "2017", "reaction", "gesture", "instagram"],
  meaning:
    "A reaction image or GIF showing Nusret Gökçe (Salt Bae) performing his signature forearm salt-sprinkling move — used to represent someone doing something with excessive style, confidence, or flair. The image is dropped in comments when someone does something impressively extra or lavish.",
  origin:
    "On January 7, 2017, Turkish restaurateur Nusret Gökçe posted an Instagram video of himself preparing and seasoning meat in an elaborate fashion, culminating in a slow-motion salt sprinkle where he lets salt cascade down his forearm into the meat. The clip went internationally viral within days. Gökçe's Nusr-Et restaurant chain subsequently became a global brand, with celebrity appearances and viral moments at each opening.",
  timeline: [
    { date: "Jan 7, 2017", event: "Nusret Gökçe posts the salt-sprinkling Instagram video — goes internationally viral within 48 hours" },
    { date: "Jan 2017", event: "Meme format spreads across Twitter, Reddit, Facebook — remixed and photoshopped endlessly" },
    { date: "2017–2018", event: "Salt Bae becomes a global cultural figure; opens restaurants in New York, London, Dubai" },
    { date: "2022", event: "Viral controversy at the FIFA World Cup in Qatar — Salt Bae on the pitch touching the World Cup trophy" },
    { date: "2022+", event: "Meme usage declines but remains a recognizable cultural reference" },
  ],
  examples: [
    "Someone posting a perfectly executed recipe photo: [Salt Bae GIF]",
    "When you add the final touch to your outfit and it just works: Salt Bae",
    "Game developer adding one final bug fix before launch: [Salt Bae sprinkling salt]",
  ],
  relatedSlugs: [
    "gigachad",
    "distracted-boyfriend",
    "change-my-mind",
    "drake-hotline-bling",
    "feastables",
    "prime-hydration",
  ],
  media: [
    // CC BY 3.0 still of Nusret performing the salt pose — Commons file verified.
    {
      role: "featured",
      type: "image",
      url: "https://upload.wikimedia.org/wikipedia/commons/9/97/Salt_Bae.png",
      title: "Nusret Gökçe (Salt Bae) — signature salt pose (2018)",
      source: "Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Salt_Bae.png",
      platform: "wikimedia",
      attribution: "Terron F.Beckham (CC BY 3.0)",
      license: "CC BY 3.0",
      description:
        "Nusret Gökçe performing the forearm salt-sprinkle gesture that became the Salt Bae meme.",
      date: "2018-02-10",
      verified: true,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/salt-bae",
      title: "Salt Bae — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/salt-bae",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Origin of the salt-sprinkle clip and its reaction-GIF era.",
      date: "2017",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Nusret_G%C3%B6k%C3%A7e",
      title: "Nusret Gökçe — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Nusret_G%C3%B6k%C3%A7e",
      platform: "other",
      attribution: "Wikipedia contributors",
      description: "Biography of the chef behind the Salt Bae meme.",
      date: "2017",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Nusret Gökçe — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Nusret_G%C3%B6k%C3%A7e",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
