import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m3",
  slug: "skibidi-toilet",
  title: "Skibidi Toilet",
  category: "meme",
  description:
    "DaFuq!?Boom!'s surreal YouTube series of toilet-headed characters vs. camera-heads — the defining Gen Alpha brainrot mythology of the 2020s.",
  imageGradient: "from-cyan-500 via-blue-500 to-indigo-600",
  scores: { relevance: 42, influence: 76, cringe: 81, brainrot: 92 },
  dynamicMetadata: {
    lastReviewed: "2026-07-25",
    currentRelevance: 42,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "youtube",
      "wikipedia",
      "news",
    ],
    popularity: 41,
    trendingScore: 45,
    recentRevival: false,
    popularityNotes: "Status: occasionally-referenced · Current Popularity 42 (today's activity, not influence) · Trending 45 (recent attention)",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=33,575 for “Skibidi Toilet”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=7788 prev7=7279 (7%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Skibidi”",
      "[news/recent-articles] Google News: 12 items in last 30d (40 returned) for “Skibidi Toilet”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Know Your Meme cited; Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Skibidi Toilet”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/absurdity] Tag/category absurdity cue (not used for relevance/trending)",
      "[catalog-evidence/gen-cohort-adoption] Cohort cue from tags (not used for relevance/trending)",
      "[catalog-evidence/remix-activity] Format/remix cue (brainrot/cringe only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
  },
  addedAt: "2026-06-15",
  lastUpdated: "2026-07-25",
  views: 1200000,
  trendDirection: "declining",
  tags: ["brainrot", "gen alpha", "youtube", "gmod", "dafuq boom", "short-form"],
  meaning:
    "A YouTube web series of toilet-headed characters singing and fighting camera-headed figures — absurdist short-form storytelling that became Gen Alpha's default brainrot reference.",
  origin:
    "Georgian animator Alexey Gerasimov (DaFuq!?Boom!) built Skibidi Toilet in Garry's Mod, a Source-engine sandbox where creators pose custom models. The first short went live on 7 February 2023: a toilet with a human head lip-syncs a distorted 'Skibidi dop dop' hook while Cameramen look on. Later episodes added lore — alliances, titans, base raids — so the series behaves like a serialized cartoon, not a one-off joke. YouTube Shorts and schoolyard retellings pushed it far past the original channel: kids recited episode plots the way earlier generations traded Pokémon lore. Wikipedia and contemporary coverage treat it as a defining early-2020s youth-internet franchise, not only a meme still.",
  timeline: [
    { date: "Feb 2023", event: "DaFuq!?Boom! uploads Episode 1 on the skibidi channel" },
    { date: "Mid-2023", event: "Episodes rack up hundreds of millions of views; Cameramen vs Toilets lore expands" },
    { date: "2024", event: "Gen Alpha obsession peaks — classroom slang and cosplay treat Skibidi as shared mythology" },
    { date: "2025–2026", event: "Still the yardstick for 'brainrot tier' absurdist short-form series" },
  ],
  examples: [
    "Episode 1 (Feb 2023): a singing toilet head greets Cameramen — the clip kids still mean when they say 'Skibidi Toilet.'",
    "A middle-schooler narrates later episodes as if they are Marvel movies: Titan Cameraman vs Skibidi bosses, alliance arcs, cliffhanger 'next episode' hype.",
    "Adults use 'Skibidi-tier brainrot' as a label for any loop of nonsense audio + uncanny CGI that younger siblings will not stop watching.",
    "Annoying Orange comparisons: both are YouTube-native character franchises that adults dismiss and kids treat as real lore.",
  ],
  relatedSlugs: [
    "dafuq-boom",
    "ohio-final-boss",
    "chicken-jockey",
    "brainrot",
    "tung-tung-tung-sahur",
    "npc-streaming",
  ],
  relationships: {
    popularizedBy: ["dafuq-boom"],
    relatedSlang: ["brainrot"],
    relatedTo: ["ohio-final-boss", "tung-tung-tung-sahur", "chicken-jockey"],
    sameEra: ["npc-streaming"],
  },
  // Phase 7 — optional cultural intelligence (internal; not a public UI field)
  intelligence: {
    era: ["gen-alpha", "short-form"],
    originPlatform: "youtube-shorts",
    culturalCategory: ["meme", "brainrot", "serialized-web-series"],
    audience: ["gen-alpha", "gen-z"],
    formatType: "animated-meme",
    signals: ["Brainrot", "Gen Alpha", "Short-form video", "YouTube Shorts"],
  },
  // VIDEO-FIRST: the series itself is the defining media — official Episode 1
  // thumbnail + embed. Do not use unrelated photos of the creator or cosplay.
  media: [
    {
      role: "featured",
      type: "image",
      url: "https://i.ytimg.com/vi/tzD9OxAHtzU/hqdefault.jpg",
      title: "skibidi toilet — Episode 1 thumbnail (Feb 2023)",
      source: "YouTube / skibidi (DaFuq!?Boom!)",
      sourceUrl: "https://www.youtube.com/watch?v=tzD9OxAHtzU",
      platform: "youtube",
      attribution: "DaFuq!?Boom! / skibidi channel",
      license: "YouTube Standard License",
      description:
        "Official Episode 1 thumbnail — the first Skibidi Toilet short that launched the series in February 2023.",
      date: "2023-02-07",
      verified: true,
    },
    {
      role: "video",
      type: "video",
      url: "https://www.youtube.com/watch?v=tzD9OxAHtzU",
      title: "skibidi toilet — Episode 1 (official)",
      source: "YouTube / skibidi (DaFuq!?Boom!)",
      sourceUrl: "https://www.youtube.com/watch?v=tzD9OxAHtzU",
      platform: "youtube",
      attribution: "DaFuq!?Boom! / skibidi channel",
      license: "YouTube Standard License",
      description:
        "Official Episode 1 of Skibidi Toilet — the origin short of the Gen Alpha series created by DaFuq!?Boom!",
      date: "2023-02-07",
      verified: true,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://www.youtube.com/@DaFuqBoom",
      title: "DaFuq!?Boom! — official YouTube channel",
      source: "YouTube / DaFuq!?Boom!",
      sourceUrl: "https://www.youtube.com/@DaFuqBoom",
      platform: "youtube",
      attribution: "DaFuq!?Boom!",
      description: "Official creator channel for the Skibidi Toilet series.",
      verified: true,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/skibidi-toilet",
      title: "Skibidi Toilet — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/skibidi-toilet",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Series history, episodes, and cultural impact documentation.",
      date: "2023",
      verified: true,
    },
  ],
  sources: [
    {
      title: "Skibidi Toilet — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Skibidi_Toilet",
      domain: "en.wikipedia.org",
    },
    {
      title: "DaFuq!?Boom! — official YouTube channel",
      url: "https://www.youtube.com/@DaFuqBoom",
      domain: "youtube.com",
    },
    {
      title: "skibidi toilet — Episode 1 (official)",
      url: "https://www.youtube.com/watch?v=tzD9OxAHtzU",
      domain: "youtube.com",
    },
  ],
};

export default entry;
