import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m123",
  slug: "soyjak",
  title: "Soyjak",
  category: "meme",
  description:
    "The open-mouthed, excited Wojak variant — Soyjak — used to mock over-the-top enthusiasm and the endless Wojak derivative wars.",
  imageGradient: "from-yellow-300 via-amber-200 to-orange-300",
  scores: { relevance: 65, influence: 65, cringe: 21, brainrot: 32 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 65,
    currentStatus: "current",
    activePlatforms: [
      "news",
    ],
    popularity: 50,
    trendingScore: 50,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=50 (Google News: 8 items in last 60d (40 returned) for “Soyjak meme”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Soyjak meme”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Soyjak”",
      "[news/recent-articles] Google News: 8 items in last 60d (40 returned) for “Soyjak meme”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Soyjak meme”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=50 (Google News: 8 items in last 60d (40 returned) for “Soyjak meme”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "2017-01-01",
  views: 2200000,
  trendDirection: "declining",
  tags: ["wojak", "4chan", "reaction", "irony", "imageboard", "variant"],
  meaning:
    "A Wojak derivative with a wide-open mouth and exaggerated excited expression — the visual shorthand for nerdy hype, cringe fandom, or performative joy. Often contrasted with stoic or Chad Wojaks in multi-panel edits. Distinct from base Wojak (Feels Guy): Soyjak is specifically the gaping, soy-faced reaction archetype.",
  origin:
    "Soyjak emerged from the Wojak ecosystem on 4chan and related boards in the late 2010s as users remixed the base Feels Guy template. Know Your Meme traces 'soyjak' naming to mockery of overly enthusiastic online behavior; the face spread alongside other Wojak variants like Doomer and NPC. It is a derivative meme, not a separate character origin — the joke is how one simple line drawing spawned an entire cast of emotional stereotypes.",
  timeline: [
    { date: "~2017", event: "Open-mouth excited Wojak edits circulate in Wojak threads" },
    { date: "2018–2019", event: "'Soyjak' name sticks; used in contrast panels with Chad archetypes" },
    { date: "2020–2022", event: "Explosion of Wojak subvariants; Soyjak remains a core reaction type" },
    { date: "2023+", event: "Still actively edited in political and fandom meme wars" },
  ],
  examples: [
    "Soyjak cheering a mediocre product announcement vs Chad unimpressed",
    "Reply image when someone gets overly excited about a minor patch note",
    "Multi-panel Wojak comics pairing Soyjak with Doomer and Gigachad",
  ],
  relatedSlugs: ["wojak", "gigachad", "virgin-vs-chad", "npc", "pepe"],
  relationships: {
    memberOf: ["wojak"],
    sameFormat: ["gigachad", "virgin-vs-chad"],
  },
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/soyjak",
      title: "Soyjak — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/soyjak",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Documentation of the open-mouth Wojak variant and naming.",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/wojak",
      title: "Wojak — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/wojak",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Parent template for the Soyjak derivative.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Soyjak — Wikipedia search",
      url: "https://en.wikipedia.org/w/index.php?search=Soyjak&title=Special:Search&fulltext=1",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
