import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m126",
  slug: "stonks",
  title: "Stonks",
  category: "meme",
  description:
    "Meme Man in front of a rising stock chart with the misspelled caption STONKS — the ironic finance bro reaction for gains that make no sense.",
  imageGradient: "from-orange-500 via-amber-400 to-yellow-300",
  scores: { relevance: 25, influence: 70, cringe: 24, brainrot: 44 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 25,
    currentStatus: "classic",
    activePlatforms: [
      "wikipedia",
    ],
    popularity: 16,
    trendingScore: 35,
    recentRevival: false,
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=16 (Google News: 1 items in last 60d (40 returned) for “Stonks meme”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Character signals still mark this as strongly representative of chaotic internet brainrot culture. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=15,679 for “List of Internet phenomena”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=3905 prev7=3683 (6%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “Stonks”",
      "[news/recent-articles] Google News: 1 items in last 60d (40 returned) for “Stonks meme”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Stonks meme”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/absurdity] Tag/title absurdity cue (brainrot character only)",
      "[catalog-evidence/remix-activity] Format/remix / short-form reuse cue (brainrot character only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=16 (Google News: 1 items in last 60d (40 returned) for “Stonks meme”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Character signals still mark this as strongly representative of chaotic internet brainrot culture.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "2017-06-01",
  views: 4100000,
  trendDirection: "stable",
  tags: ["meme-man", "finance", "wallstreetbets", "2017", "irony", "template"],
  meaning:
    "An image macro pairing the 3D-rendered Meme Man head with a stock market graphic and the word 'STONKS' (a deliberate misspelling of 'stocks'). Signals ironic celebration of financial decisions that are obviously bad — or unexpectedly good. The joke is confident ignorance dressed up as Wall Street wisdom.",
  origin:
    "Know Your Meme traces the earliest Stonks post to a Facebook group in June 2017. Meme Man — the surreal 3D head — was already an established character; adding a rising chart and misspelled caption created a durable finance meme. The format exploded again in 2021 when Reddit's r/wallstreetbets GameStop frenzy brought 'stonks' language into mainstream news.",
  timeline: [
    { date: "Jun 2017", event: "Earliest documented Stonks macro on Facebook" },
    { date: "2018–2019", event: "Spreads on Reddit alongside Not Stonks reverse variants" },
    { date: "Jan 2021", event: "GameStop / WSB mania revives Stonks at mainstream scale" },
    { date: "2021+", event: "'Not Stonks' and derivative charts remain common" },
  ],
  examples: [
    "Stonks meme after buying the top of a crypto pump",
    "Not Stonks when a portfolio drops after overconfidence",
    "WSB thread screenshot + Stonks for a YOLO trade",
  ],
  relatedSlugs: ["expanding-brain", "surprised-pikachu", "this-is-fine", "doge"],
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/stonks",
      title: "Stonks — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/stonks",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Meme Man finance macro origin and WSB revival.",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/meme-man",
      title: "Meme Man — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/meme-man",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Character behind the Stonks template.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Stonks — Wikipedia search",
      url: "https://en.wikipedia.org/w/index.php?search=Stonks&title=Special:Search&fulltext=1",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
