import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m63",
  slug: "tel-aviv-impressed",
  title: "Tel Aviv Impressed",
  category: "meme",
  description:
    "A blank-faced Netanyahu still captioned '*Tel Aviv Impressed*' — an Ohio Impressed-style reaction for content read as 'spiritually Israeli.'",
  imageGradient: "from-blue-600 via-sky-500 to-white",
  scores: { relevance: 37, influence: 42, cringe: 37, brainrot: 33 },
  dynamicMetadata: {
    lastReviewed: "2026-07-25",
    currentRelevance: 27,
    currentStatus: "occasionally-referenced",
    activePlatforms: [],
    popularity: 32,
    trendingScore: 22,
    recentRevival: false,
    popularityNotes: "Status: occasionally-referenced · Relevance 27 (today's recognition, not influence) · Trending 22 (recent attention)",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Tel Aviv Impressed”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Tel”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-01-04",
      "[news/recent-articles] Google News: 1 items in last 30d (40 returned) for “Tel Aviv Impressed”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Know Your Meme cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Tel Aviv Impressed”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/absurdity] Tag/category absurdity cue (not used for relevance/trending)",
      "[catalog-evidence/remix-activity] Format/remix cue (brainrot/cringe only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
  },
  addedAt: "2026-07-18",
  lastUpdated: "2026-07-25",
  historicalDate: "2023-10-01",
  views: 900000,
  trendDirection: "declining",
  tags: ["reaction", "ohio impressed", "format", "2020s", "politics"],
  meaning:
    "A reaction-image format: a blank expression from Israeli Prime Minister Benjamin Netanyahu captioned '*Tel Aviv Impressed*,' modeled on the Ohio Impressed / King Von reaction series. Used online as a deadpan reaction to content perceived as aligned with Israeli aesthetics, politics, or discourse — especially around mid-2020s Israel–Hamas conflict commentary (Know Your Meme).",
  origin:
    "Derived from the Ohio Impressed reaction template (itself part of the broader 'Ohio' / Squid Game-edit reaction lineage). The Tel Aviv variant swaps in a Netanyahu still and Tel Aviv as the place-name caption; documented on Know Your Meme as a political-reaction spin on that format.",
  timeline: [
    { date: "Early 2020s", event: "Ohio / Ohio Impressed reaction images circulate widely" },
    { date: "2023–2024", event: "Tel Aviv Impressed variant spreads as conflict-related reaction format" },
    { date: "2024+", event: "Continues as niche political reaction alongside other place-name Impressed edits" },
  ],
  examples: [
    "Commenting '*Tel Aviv Impressed*' under a clip with Israeli flags or aesthetics",
    "Pairing the blank Netanyahu still with unrelated 'spiritually Israeli' vibes",
    "Format cousins: Ohio Impressed, other city-name Impressed reactions",
  ],
  relatedSlugs: ["ohio-final-boss", "this-is-fine", "hide-the-pain-harold"],
  relationships: {
    sameFormat: ["ohio-final-boss"],
    relatedTo: ["this-is-fine", "hide-the-pain-harold"],
  },
  media: [
    // AI suggested — KYM cover; human must verify
    {
      role: "featured",
      type: "image",
      url: "https://i.kym-cdn.com/entries/icons/original/000/056/555/cover_(5).jpg",
      title: "Tel Aviv Impressed — reaction cover",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/tel-aviv-impressed",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Cover still documenting the Tel Aviv Impressed reaction format.",
      date: "2023",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/tel-aviv-impressed",
      title: "Tel Aviv Impressed — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/tel-aviv-impressed",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Format origin and usage as Ohio Impressed derivative.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Tel Aviv Impressed — Wikipedia search",
      url: "https://en.wikipedia.org/w/index.php?search=Tel%20Aviv%20Impressed&title=Special:Search&fulltext=1",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
