import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m21",
  slug: "the-rizzler",
  title: "The Rizzler",
  category: "meme",
  description:
    "An internet archetype and cultural title for someone possessing supernatural levels of rizz — effortless, almost implausible charisma.",
  imageGradient: "from-violet-500 via-purple-500 to-fuchsia-600",
  scores: { relevance: 65, influence: 78, cringe: 21, brainrot: 75 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 65,
    currentStatus: "current",
    activePlatforms: [
      "tiktok",
      "wikipedia",
      "news",
    ],
    popularity: 50,
    trendingScore: 52,
    recentRevival: false,
    popularityNotes: "Relevance: Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=50 (Google News: 8 items in last 60d (40 returned) for “The Rizzler”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Character signals still mark this as strongly representative of chaotic internet brainrot culture. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=28,586 for “The Rizzler”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=5447 prev7=5095 (7%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] No Wiktionary page for “The”",
      "[news/recent-articles] Google News: 8 items in last 60d (40 returned) for “The Rizzler”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “The Rizzler”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/absurdity] Tag/title absurdity cue (brainrot character only)",
      "[catalog-evidence/gen-cohort-adoption] Cohort cue from tags/title (brainrot character only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=50 (Google News: 8 items in last 60d (40 returned) for “The Rizzler”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Character signals still mark this as strongly representative of chaotic internet brainrot culture.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-16",
  lastUpdated: "2026-08-16",
  views: 920000,
  trendDirection: "stable",
  tags: ["rizz", "viral", "charisma", "tiktok", "character", "meme"],
  meaning:
    "The highest possible title in 'rizz' culture. 'The Rizzler' represents someone who has achieved a legendary, almost supernatural level of effortless charisma. The title is both given sincerely to individuals who go viral for impressive social skills, and used ironically as a meme archetype.",
  origin:
    "Spawned from the viral 'rizz' culture of 2022–2023. Viral clips of individuals demonstrating remarkable charisma gave rise to the 'Rizzler' title, eventually turning it into an internet meme character rather than a specific person — applied broadly and often ironically.",
  timeline: [
    {
      date: "2022–2023",
      event: "'Rizz' culture peaks — internet begins assigning the 'Rizzler' title to especially charismatic viral clips",
    },
    {
      date: "2023–2024",
      event: "'The Rizzler' becomes a recognized meme archetype used both sincerely and ironically",
    },
  ],
  examples: [
    "That was the most Rizzler move I've ever witnessed in my life",
    "The Rizzler has entered the chat",
    "He's not just rizzy — he's THE Rizzler",
  ],
  relatedSlugs: ["rizz", "kai-cenat"],
  media: [
    // Official Theo Von interview featuring Christian Joseph (The Rizzler).
    {
      role: "featured",
      type: "image",
      url: "https://i.ytimg.com/vi/Yr6HCkBEins/hqdefault.jpg",
      title: "The Rizzler on This Past Weekend with Theo Von",
      source: "YouTube / Theo Von",
      sourceUrl: "https://www.youtube.com/watch?v=Yr6HCkBEins",
      platform: "youtube",
      attribution: "Theo Von / This Past Weekend",
      license: "YouTube Standard License",
      description:
        "Official interview thumbnail featuring Christian Joseph (The Rizzler) — the person behind the viral Rizz Face.",
      date: "2025",
      verified: true,
    },
    {
      role: "video",
      type: "video",
      url: "https://www.youtube.com/watch?v=Yr6HCkBEins",
      title: "The Rizzler | This Past Weekend w/ Theo Von #600",
      source: "YouTube / Theo Von",
      sourceUrl: "https://www.youtube.com/watch?v=Yr6HCkBEins",
      platform: "youtube",
      attribution: "Theo Von / This Past Weekend",
      license: "YouTube Standard License",
      description:
        "Full Theo Von interview with The Rizzler (Christian Joseph).",
      date: "2025",
      verified: true,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/The_Rizzler",
      title: "The Rizzler — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/The_Rizzler",
      platform: "other",
      attribution: "Wikipedia contributors",
      description: "Biography of Christian Joseph and the Rizz Face phenomenon.",
      date: "2023",
      verified: true,
    },
  ],
  sources: [
    {
      title: "The Rizzler — Wikipedia",
      url: "https://en.wikipedia.org/wiki/The_Rizzler",
      domain: "en.wikipedia.org",
    },
    {
      title: "The Rizzler | This Past Weekend w/ Theo Von #600",
      url: "https://www.youtube.com/watch?v=Yr6HCkBEins",
      domain: "youtube.com",
    },
  ],
};

export default entry;
