import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m127",
  slug: "this-you",
  title: "This You?",
  category: "meme",
  description:
    "The quote-tweet comeback — 'this you?' — paired with someone's old hypocritical post, the standard accountability check on Twitter/X.",
  imageGradient: "from-sky-500 via-blue-400 to-indigo-500",
  scores: { relevance: 82, influence: 64, cringe: 21, brainrot: 40 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 82,
    currentStatus: "current",
    activePlatforms: [
      "x",
      "wikipedia",
      "news",
    ],
    popularity: 64,
    trendingScore: 54,
    recentRevival: false,
    popularityNotes: "Relevance: Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=64 (Google News: 16 items in last 60d (40 returned) for “This You?”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Character signals still mark this as strongly representative of chaotic internet brainrot culture. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=7,032 for “NPC (meme)”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=1626 prev7=1845 (-12%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “This”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-08-13",
      "[news/recent-articles] Google News: 16 items in last 60d (40 returned) for “This You?”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] No Wikipedia / KYM / dictionary / major-news URLs on entry sources",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “This You?”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/absurdity] Tag/title absurdity cue (brainrot character only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=64 (Google News: 16 items in last 60d (40 returned) for “This You?”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Character signals still mark this as strongly representative of chaotic internet brainrot culture.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "2019-01-01",
  views: 2100000,
  trendDirection: "stable",
  tags: ["twitter", "comeback", "quote-tweet", "accountability", "text-meme"],
  meaning:
    "A reply or quote-tweet that says 'this you?' while attaching an old screenshot of the same person saying the opposite. The format turns someone's past post into evidence against their current take — hypocrisy, flip-flopping, or deleted-tweet archaeology made public.",
  origin:
    "The phrase circulated on Black Twitter and fandom spaces before becoming a mainstream Twitter/X comeback in the late 2010s. Know Your Meme notes that pairing the words with a dug-up tweet turned an everyday question into a meme template — especially during political and celebrity pile-ons. It thrives on the platform's permanent archive of old posts.",
  timeline: [
    { date: "Late 2010s", event: "'This you?' used in fandom and call-out quote-tweets" },
    { date: "2019–2020", event: "Format standardizes as hypocrisy screenshot reply" },
    { date: "2021+", event: "Spreads to TikTok text overlays and Instagram story call-outs" },
    { date: "2020s", event: "Remains a default Twitter/X accountability phrase" },
  ],
  examples: [
    "Celebrity takes a stance; reply quotes their 2014 tweet: 'this you?'",
    "Politician's old statement resurfaced under a new press release",
    "TikTok text meme: 'this you?' over a friend's contradictory texts",
  ],
  relatedSlugs: ["change-my-mind", "woman-yelling-at-cat", "distracted-boyfriend", "surprised-pikachu"],
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/this-you",
      title: "This You? — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/this-you",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Quote-tweet comeback format and spread.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Coverage — vice.com",
      url: "https://www.vice.com/en/article/this-you-black-twitter-receipts/",
      domain: "vice.com",
    },
  ],
};

export default entry;
