import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m128",
  slug: "tide-pod-challenge",
  title: "Tide Pod Challenge",
  category: "meme",
  description:
    "The 2018 panic-and-meme cycle around eating laundry detergent pods — a cautionary tale of irony becoming headline news.",
  imageGradient: "from-orange-400 via-blue-500 to-white",
  scores: { relevance: 4, influence: 69, cringe: 41, brainrot: 50 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 4,
    currentStatus: "historical",
    activePlatforms: [
      "wikipedia",
    ],
    popularity: 0,
    trendingScore: 22,
    recentRevival: false,
    popularityNotes: "Relevance: Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (40 returned) for “Tide Pod Challenge”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=791 for “Internet challenge”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=176 prev7=201 (-12%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Tide”",
      "[dictionary/platform-activity] Wiktionary last revision 2025-10-07",
      "[news/recent-articles] Google News: 0 items in last 60d (40 returned) for “Tide Pod Challenge”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Major news organization cited",
      "[google-trends/search-interest] Google Trending RSS unavailable",
      "[reddit/discussion-volume] Reddit search unavailable for “Tide Pod Challenge”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "Weak corroboration — blended heuristic (0) with AI double-check (7): All signals show negligible recent activity—no news coverage, declining Wikipedia views, and low platform engagement—indicating the Tide Pod Challenge is essentially dormant now.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Little recent creation activity detected. Signals: news/recent-articles=0 (Google News: 0 items in last 60d (40 returned) for “Tide Pod Challenge”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "2018-01-01",
  views: 2900000,
  trendDirection: "declining",
  tags: ["2018", "challenge", "safety", "irony", "news", "viral-panic"],
  meaning:
    "Jokes and forbidden-fruit memes about biting into brightly colored Tide Pods — framed as a 'challenge' despite little evidence of widespread participation. Used online to mock reckless trends, Gen Z recklessness stereotypes, or anything that looks edible but should not be eaten. The meme layer often outran the actual behavior.",
  origin:
    "Tide Pods' candy-like appearance inspired Photoshop jokes for years before 2018. Know Your Meme and major outlets documented how Onion-style satire and shitposting collided with real poison-control warnings when the phrase 'Tide Pod challenge' hit cable news. Procter & Gamble and YouTube responded with safety messaging; the meme became a case study in moral panic amplification.",
  timeline: [
    { date: "2013–2017", event: "Pod-as-food jokes circulate in forums and image macros" },
    { date: "Jan 2018", event: "'Tide Pod challenge' headlines; poison-control calls discussed in media" },
    { date: "Jan 2018", event: "YouTube restricts challenge content; Tide runs safety ads" },
    { date: "2018+", event: "Meme persists as shorthand for stupid internet challenges" },
  ],
  examples: [
    "I almost ate a Tide Pod for the meme — thankfully I didn't.",
    "That decision was peak Tide Pod Challenge energy.",
    "Remember when the news thought kids were actually eating laundry pods?",
  ],
  relatedSlugs: ["nyan-cat", "this-is-fine", "surprised-pikachu", "corn-kid"],
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/tide-pods",
      title: "Tide Pods — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/tide-pods",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Pod-eating meme history and 2018 challenge panic.",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://www.theguardian.com/us-news/2018/jan/18/tide-pod-challenge-viral-social-media",
      title: "Tide pod challenge — The Guardian",
      source: "The Guardian",
      sourceUrl: "https://www.theguardian.com/us-news/2018/jan/18/tide-pod-challenge-viral-social-media",
      platform: "other",
      attribution: "The Guardian",
      description: "News coverage of the 2018 viral cycle and safety response.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Tide pod challenge: viral social media — The Guardian",
      url: "https://www.theguardian.com/us-news/2018/jan/18/tide-pod-challenge-viral-social-media",
      domain: "theguardian.com",
    },
  ],
};

export default entry;
