import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m129",
  slug: "tuxedo-winnie-the-pooh",
  title: "Tuxedo Winnie the Pooh",
  category: "meme",
  description:
    "The two-panel Pooh upgrade meme — plain Pooh vs tuxedo Pooh — used to roast a basic idea next to its supposedly refined version.",
  imageGradient: "from-amber-600 via-yellow-400 to-red-700",
  scores: { relevance: 32, influence: 75, cringe: 21, brainrot: 34 },
  dynamicMetadata: {
    lastReviewed: "2026-07-25",
    currentRelevance: 32,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "wikipedia",
    ],
    popularity: 38,
    trendingScore: 19,
    recentRevival: false,
    popularityNotes: "Status: occasionally-referenced · Relevance 32 (today's recognition, not influence) · Trending 19 (recent attention)",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=16,889 for “List of Internet phenomena”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=3790 prev7=3720 (2%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Tuxedo”",
      "[dictionary/platform-activity] Wiktionary last revision 2025-11-01",
      "[news/recent-articles] Google News: 0 items in last 30d (13 returned) for “Tuxedo Winnie the Pooh”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Know Your Meme cited; Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Tuxedo Winnie the Pooh”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/remix-activity] Format/remix cue (brainrot/cringe only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-07-25",
  historicalDate: "2019-02-01",
  views: 3800000,
  trendDirection: "declining",
  tags: ["template", "comparison", "2019", "drake", "upgrade", "irony"],
  meaning:
    "A vertical two-panel image macro: top shows Winnie the Pooh in a simple pose labeled with a mundane choice; bottom shows Pooh in a tuxedo labeled with a pretentious or 'refined' version of the same thing. The joke is fake sophistication — calling something classy when it is barely different.",
  origin:
    "Know Your Meme traces the tuxedo Pooh template to a February 2019 edit on /r/MemeEconomy, evolving from earlier 'Galaxy Brain'-style upgrade charts. It rode the same comparison-meme wave as Drakeposting and Expanding Brain — simple labels, escalating panels, instant readability. Disney's Pooh design made the contrast visually obvious.",
  timeline: [
    { date: "Feb 2019", event: "Tuxedo Pooh two-panel format posts to /r/MemeEconomy" },
    { date: "2019", event: "Spreads across Reddit, Twitter, and Instagram as upgrade meme" },
    { date: "2019–2020", event: "Variants multiply — three-panel and ironic reverse edits" },
    { date: "2020s", event: "Remains a stock comparison template alongside Drake and Brain formats" },
  ],
  examples: [
    "Top: 'streaming' / Bottom tuxedo Pooh: 'collecting physical media'",
    "Top: 'instant coffee' / Bottom: 'French press at 6 a.m.'",
    "Ironic reverse where tuxedo Pooh is clearly the worse option",
  ],
  relatedSlugs: ["drake-hotline-bling", "expanding-brain", "two-buttons", "change-my-mind"],
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/tuxedo-winnie-the-pooh",
      title: "Tuxedo Winnie the Pooh — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/tuxedo-winnie-the-pooh",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "2019 two-panel upgrade template origin.",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://en.wikipedia.org/wiki/Winnie-the_Pooh",
      title: "Winnie-the-Pooh — Wikipedia",
      source: "Wikipedia",
      sourceUrl: "https://en.wikipedia.org/wiki/Winnie-the_Pooh",
      platform: "other",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      description: "Character background for the meme's source material.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Tuxedo Winnie the Pooh — Know Your Meme",
      url: "https://knowyourmeme.com/memes/tuxedo-winnie-the-pooh",
      domain: "knowyourmeme.com",
    },
    {
      title: "Winnie-the-Pooh — Wikipedia",
      url: "https://en.wikipedia.org/wiki/Winnie-the_Pooh",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
