import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m47",
  slug: "two-buttons",
  title: "Two Buttons",
  category: "meme",
  description:
    "The sweaty 'Daily Struggle' comic — a character stuck choosing between two contradictory red buttons.",
  imageGradient: "from-red-500 via-rose-500 to-pink-400",
  scores: { relevance: 66, influence: 84, cringe: 21, brainrot: 58 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 66,
    currentStatus: "current",
    activePlatforms: [
      "news",
    ],
    popularity: 60,
    trendingScore: 60,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=60 (Google News: 13 items in last 60d (40 returned) for “Two Buttons”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Absurdity / cohort character cues still match the prior brainrot reading. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Two Buttons”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Two”",
      "[dictionary/platform-activity] Wiktionary last revision 2025-06-22",
      "[news/recent-articles] Google News: 13 items in last 60d (40 returned) for “Two Buttons”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Wikipedia / Wikimedia cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Two Buttons”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/remix-activity] Format/remix / short-form reuse cue (brainrot character only)",
      "Weak corroboration — blended heuristic (77) with AI double-check (55): Documentation and legacy references are strong, but low platform activity and Google Trends indicate the meme isn’t currently spiking.",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=60 (Google News: 13 items in last 60d (40 returned) for “Two Buttons”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Absurdity / cohort character cues still match the prior brainrot reading.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-18",
  lastUpdated: "2026-08-16",
  historicalDate: "2014-10-25",
  views: 5000000,
  trendDirection: "declining",
  tags: ["template", "comic", "choice", "2014", "classic", "jake-clark"],
  meaning:
    "An exploitable comic of a sweating character torn between two labeled buttons with conflicting options. Captures impossible or hypocritical choices. Later variants show pressing both buttons at once.",
  origin:
    "Animator Jake Clark posted the original 'Daily Struggle' comic to Tumblr on October 25, 2014 (buttons labeled 'BE A DICK' / 'DON'T BE A DICK'). It spread via Imgur and Reddit, becoming a durable dilemma template.",
  timeline: [
    { date: "Oct 2014", event: "Jake Clark posts original Tumblr comic" },
    { date: "2015", event: "Imgur/Reddit popularization as 'Daily Struggle'" },
    { date: "2020+", event: "'Press both buttons' remixes revive the format" },
  ],
  examples: [
    "Buttons: 'sleep' vs 'finish the assignment'",
    "Buttons: contradictory political takes — character sweating",
  ],
  relatedSlugs: [
    "drake-hotline-bling",
    "expanding-brain",
    "change-my-mind",
    "distracted-boyfriend",
  ],
  relationships: {
    sameFormat: ["drake-hotline-bling", "expanding-brain", "change-my-mind"],
  },
  media: [
    // AI suggested — KYM Daily Struggle / Two Buttons icon; human must verify
    {
      role: "featured",
      type: "image",
      url: "https://i.kym-cdn.com/entries/icons/original/000/019/571/dailystruggg.jpg",
      title: "Two Buttons / Daily Struggle — comic template",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/daily-struggle-two-buttons",
      platform: "knowyourmeme",
      attribution: "Jake Clark / via Know Your Meme documentation",
      description: "The sweating two-buttons dilemma comic that defines the format.",
      date: "2014",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/daily-struggle-two-buttons",
      title: "Daily Struggle / Two Buttons — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/daily-struggle-two-buttons",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Origin of the two-buttons / daily struggle meme.",
      date: "2014",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Two Buttons — Wikipedia search",
      url: "https://en.wikipedia.org/w/index.php?search=Two%20Buttons&title=Special:Search&fulltext=1",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
