import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m130",
  slug: "virgin-vs-chad",
  title: "Virgin vs Chad",
  category: "meme",
  description:
    "The Wojak comparison panels pitting a nervous Virgin against a confident Chad — internet archetyping turned into a meme factory.",
  imageGradient: "from-slate-400 via-gray-300 to-amber-400",
  scores: { relevance: 36, influence: 74, cringe: 21, brainrot: 41 },
  dynamicMetadata: {
    lastReviewed: "2026-07-25",
    currentRelevance: 36,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "wikipedia",
    ],
    popularity: 43,
    trendingScore: 22,
    recentRevival: false,
    popularityNotes: "Status: occasionally-referenced · Relevance 36 (today's recognition, not influence) · Trending 22 (recent attention)",
    evidenceNotes: [
      "[wikipedia/search-interest] Wikimedia pageviews 30d=13,347 for “Chad (slang)”",
      "[wikipedia/editorial-trend] Pageviews WoW last7=3479 prev7=2935 (19%)",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Virgin”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-05-31",
      "[news/recent-articles] Google News: 0 items in last 30d (40 returned) for “Virgin vs Chad”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Know Your Meme cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Virgin vs Chad”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/remix-activity] Format/remix cue (brainrot/cringe only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-07-25",
  historicalDate: "2017-10-01",
  views: 3200000,
  trendDirection: "declining",
  tags: ["wojak", "comparison", "4chan", "archetype", "2017", "template"],
  meaning:
    "Side-by-side panels contrasting 'The Virgin [X]' — anxious, awkward Wojak energy — with 'The Chad [Y]' — exaggerated confidence and jawline. Each row compares habits, hobbies, or opinions to imply one side is pathetic and the other absurdly superior. Often ironic; the Chad is as much parody as ideal.",
  origin:
    "Know Your Meme documents Virgin vs Chad emerging from /r9k/ and Wojak culture around October 2017, building on earlier 'virgin walk' jokes. The format merged with Gigachad imagery and Soyjak reactions, becoming one of the most remixed Wojak templates. It spread beyond incel forums into general-purpose comparison memes — sometimes edgy, often self-deprecating.",
  timeline: [
    { date: "Oct 2017", event: "Virgin vs Chad panels gain traction on 4chan and Reddit" },
    { date: "2018", event: "Gigachad edits merge with the format" },
    { date: "2019–2021", event: "Mainstream-adjacent variants for hobbies, fandoms, and jobs" },
    { date: "2020s", event: "Still used in Wojak ecosystem alongside Soyjak and Doomer" },
  ],
  examples: [
    "Virgin 'checks notifications' vs Chad 'phone on airplane mode forever'",
    "Virgin study playlist vs Chad listening to the same song on loop",
    "Ironic Chad labeled as the clearly worse life choice",
  ],
  relatedSlugs: ["wojak", "soyjak", "gigachad", "npc", "expanding-brain"],
  relationships: {
    memberOf: ["wojak"],
    sameFormat: ["gigachad", "soyjak"],
  },
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/virgin-vs-chad",
      title: "Virgin vs Chad — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/virgin-vs-chad",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Wojak comparison template origin and variants.",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/wojak",
      title: "Wojak — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/wojak",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Parent meme family for Virgin and Chad figures.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Virgin vs Chad — Know Your Meme",
      url: "https://knowyourmeme.com/memes/virgin-vs-chad",
      domain: "knowyourmeme.com",
    },
    {
      title: "Wojak — Know Your Meme",
      url: "https://knowyourmeme.com/memes/wojak",
      domain: "knowyourmeme.com",
    },
  ],
};

export default entry;
