import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m59",
  slug: "wilson-lo-siento",
  title: "Wilson Lo Siento",
  category: "meme",
  description:
    "A floating chicken on flood debris dubbed with Spanish Cast Away audio — '¡Wilson! ¡Lo siento!' — peak absurdist TikTok tragedy comedy.",
  imageGradient: "from-sky-500 via-cyan-600 to-blue-800",
  scores: { relevance: 33, influence: 48, cringe: 21, brainrot: 31 },
  dynamicMetadata: {
    lastReviewed: "2026-07-25",
    currentRelevance: 33,
    currentStatus: "occasionally-referenced",
    activePlatforms: [
      "tiktok",
    ],
    popularity: 43,
    trendingScore: 20,
    recentRevival: false,
    popularityNotes: "Status: occasionally-referenced · Relevance 33 (today's recognition, not influence) · Trending 20 (recent attention)",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Wilson Lo Siento”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Wilson”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-07-21",
      "[news/recent-articles] Google News: 0 items in last 30d (6 returned) for “Wilson Lo Siento”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] Know Your Meme cited",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Wilson Lo Siento”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/gen-cohort-adoption] Cohort cue from tags (not used for relevance/trending)",
      "[catalog-evidence/remix-activity] Format/remix cue (brainrot/cringe only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
  },
  addedAt: "2026-07-18",
  lastUpdated: "2026-07-25",
  historicalDate: "2023-08-30",
  views: 1200000,
  trendDirection: "declining",
  tags: ["tiktok", "absurdist", "2023", "cast away", "viral video"],
  meaning:
    "A tragicomic edit pairing footage of a chicken drifting on debris in floodwater with the Spanish dub of Cast Away's Wilson scene ('¡Wilson! ¡Lo siento!' — 'Wilson! I'm sorry!'). Used as absurdist melodrama, nostalgia bait, and parody soundtrack.",
  origin:
    "On August 30, 2023, TikToker @recidivo posted the chicken-in-flood clip with Spanish Cast Away audio; it exploded to tens of millions of views. Parodies (AI movie posters, trailers, brand uses) followed in late 2023 (Know Your Meme).",
  timeline: [
    { date: "2022", event: "Source flood footage circulates from Central American storm coverage" },
    { date: "Aug 30, 2023", event: "TikTok edit with Spanish Cast Away audio goes viral" },
    { date: "Oct–Nov 2023", event: "Parody trailers, AI posters, and platform remixes spread" },
    { date: "2026", event: "Resurfaces as nostalgia / Great Meme Reset throwback" },
  ],
  examples: [
    "Stitching any 'goodbye' moment with '¡Wilson! ¡Lo siento!'",
    "Fake movie trailers about the floating chicken",
    "Captioning a lost object drifting away as Wilson",
  ],
  relatedSlugs: ["dat-boi", "great-meme-reset", "coffin-dance"],
  relationships: {
    sameFormat: ["dat-boi"],
    relatedEvent: ["great-meme-reset"],
    relatedTo: ["coffin-dance"],
  },
  media: [
    // AI suggested — KYM cover; human must verify
    {
      role: "featured",
      type: "image",
      url: "https://i.kym-cdn.com/entries/icons/original/000/047/286/hq720_(1).jpg",
      title: "Wilson Lo Siento — meme cover",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/wilson-lo-siento",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Cover still representing the floating-chicken Wilson Lo Siento meme.",
      date: "2023",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/wilson-lo-siento",
      title: "Wilson! Lo Siento! — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/wilson-lo-siento",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "Origin and spread of the Wilson Lo Siento TikTok meme.",
      date: "2023",
      verified: false,
    },
  ],
  sources: [
    {
      title: "Wilson Lo Siento — Wikipedia search",
      url: "https://en.wikipedia.org/w/index.php?search=Wilson%20Lo%20Siento&title=Special:Search&fulltext=1",
      domain: "en.wikipedia.org",
    },
  ],
};

export default entry;
