import type { MemeEntry } from "@/types";

const entry: MemeEntry = {
  id: "m134",
  slug: "zendaya-theory",
  title: "Zendaya Theory",
  category: "meme",
  description:
    "A fake TikTok creepypasta about Zendaya's 2014 oversized hat — absurd conspiracy edits where the joke is that there is no theory.",
  imageGradient: "from-gray-900 via-purple-900 to-black",
  scores: { relevance: 79, influence: 49, cringe: 21, brainrot: 45 },
  dynamicMetadata: {
    lastReviewed: "2026-08-16",
    currentRelevance: 86,
    currentStatus: "highly-active",
    activePlatforms: [
      "tiktok",
      "news",
    ],
    popularity: 68,
    trendingScore: 68,
    recentRevival: "unknown",
    popularityNotes: "Relevance: Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=68 (Google News: 19 items in last 60d (40 returned) for “Zendaya Theory”) Influence: Permanent cultural impact is not changed by a dynamic refresh. Brainrot: Character signals still mark this as strongly representative of chaotic internet brainrot culture. Cringe: Not enough mockery / social-awkwardness signals to reassess cringe.",
    evidenceNotes: [
      "[wikipedia/search-interest] No confident English Wikipedia match for “Zendaya Theory”",
      "[know-your-meme/authority-documentation] Know Your Meme entry located",
      "[know-your-meme/platform-activity] KYM entry exists; last-updated date not parseable",
      "[dictionary/authority-documentation] Wiktionary page “Zendaya”",
      "[dictionary/platform-activity] Wiktionary last revision 2026-03-21",
      "[news/recent-articles] Google News: 19 items in last 60d (40 returned) for “Zendaya Theory”",
      "[creator-pages/recent-uploads] No YouTube channel_id URLs on entry sources — creator RSS skipped",
      "[authority-sources/authority-documentation] No Wikipedia / KYM / dictionary / major-news URLs on entry sources",
      "[google-trends/search-interest] Not on current Google US Trending RSS (10 topics) — not treated as zero search interest",
      "[google-trends/editorial-trend] Absence from daily trending list → not currently spiking",
      "[reddit/discussion-volume] Reddit search unavailable for “Zendaya Theory”",
      "[youtube/recent-uploads] YOUTUBE_DATA_API_KEY not set — YouTube live search skipped",
      "[catalog-evidence/gen-cohort-adoption] Cohort cue from tags/title (brainrot character only)",
    ],
    providersUsed: [
      "wikipedia",
      "know-your-meme",
      "dictionary",
      "news",
      "creator-pages",
      "authority-sources",
      "google-trends",
      "reddit",
      "youtube",
      "catalog-evidence",
    ],
    usedCatalogFallback: false,
    scoreReasons: {
      relevance: "Ongoing new posts/uploads/discussion support steady Current Relevance. Signals: news/recent-articles=68 (Google News: 19 items in last 60d (40 returned) for “Zendaya Theory”)",
      influence: "Permanent cultural impact is not changed by a dynamic refresh.",
      brainrot: "Character signals still mark this as strongly representative of chaotic internet brainrot culture.",
      cringe: "Not enough mockery / social-awkwardness signals to reassess cringe.",
    },
  },
  addedAt: "2026-07-23",
  lastUpdated: "2026-08-16",
  historicalDate: "2025-05-01",
  views: 2400000,
  trendDirection: "declining",
  tags: ["tiktok", "2025", "creepypasta", "parody", "celebrity", "conspiracy"],
  meaning:
    "Ominous TikTok edits pairing low-res photos of Zendaya in a giant black Emporio Armani hat (2014 Teen Vogue party) with spooky music and fake 'case file' narration — implying secrets under the brim. The punchline: there is no real theory. It parodies creepypasta and true-crime TikTok by refusing to explain anything while sounding serious.",
  origin:
    "Zendaya's 2014 hat was already an internet joke ('let me not forget my big hat'). In May 2025, TikToker @thesnakesbloxx posted an edit mixing a glitched red-carpet clip with the hat photos and Ethel Cain audio; it passed 17 million views in days. Know Your Meme, Vulture, and Teen Vogue documented the bit — followers begged for explanations that never arrive. Met Gala 2025 hat fashion reignited the meme.",
  timeline: [
    { date: "Sep 2014", event: "Zendaya wears oversized hat to Teen Vogue Young Hollywood Party" },
    { date: "May 1, 2025", event: "@thesnakesbloxx posts the founding 'Zendaya Theory' TikTok" },
    { date: "May 2025", event: "Copycat creepypasta edits and fake missing-person posters spread" },
    { date: "May 2025", event: "Met Gala wide-brim look revives the hat joke at scale" },
  ],
  examples: [
    "Robotic narrator: 'We know what it means — do you?' with no answer",
    "Fake abduction report listing hair color as 'hat'",
    "Comment section begging for the theory and getting more vagueness",
  ],
  relatedSlugs: ["skibidi-toilet", "roman-empire-meme", "low-cortisol", "surprised-pikachu"],
  media: [
    {
      role: "reference",
      type: "embed",
      url: "https://knowyourmeme.com/memes/zendaya-theory",
      title: "Zendaya Theory — Know Your Meme",
      source: "Know Your Meme",
      sourceUrl: "https://knowyourmeme.com/memes/zendaya-theory",
      platform: "knowyourmeme",
      attribution: "Know Your Meme / Literally Media",
      description: "May 2025 TikTok creepypasta parody documentation.",
      verified: false,
    },
    {
      role: "reference",
      type: "embed",
      url: "https://www.vulture.com/article/zendaya-hat-theory-tiktok-meme-explained.html",
      title: "Zendaya Hat Theory — Vulture",
      source: "Vulture",
      sourceUrl: "https://www.vulture.com/article/zendaya-hat-theory-tiktok-meme-explained.html",
      platform: "other",
      attribution: "Vulture / New York Magazine",
      description: "Explainer on the 2014 hat photo and 2025 TikTok revival.",
      verified: false,
    },
  ],
  sources: [
    {
      title: "What Is the Zendaya Hat Theory? — Vulture",
      url: "https://www.vulture.com/article/zendaya-hat-theory-tiktok-meme-explained.html",
      domain: "vulture.com",
    },
  ],
};

export default entry;
