/**
 * Centralized search / SEO / duplicate-detection aliases.
 *
 * Stored separately from article files so entries stay focused on content.
 * Keys are canonical entry slugs; values are alternate queries people use.
 *
 * Expand this map as new slang spellings and SEO phrases appear.
 */

export type AliasRegistry = Readonly<Record<string, readonly string[]>>;

/**
 * Seed aliases for high-traffic terms.
 * Do not invent meanings — only capture known alternate spellings / search phrases.
 */
export const ALIAS_REGISTRY: AliasRegistry = {
  gyatt: ["gyat", "gyatt meaning", "what does gyatt mean", "gyat meaning"],
  "kai-cenat": [
    "kai",
    "kai cenat",
    "who is kai cenat",
    "kai cenat streamer",
  ],
  amp: ["any means possible", "amp crew", "amp streamers"],
  pewdiepie: ["felix kjellberg", "pewds", "pewdiepie youtube"],
  aura: ["aura points", "aura farming", "aura meaning"],
  "type-shii": ["type shit", "type shi", "type shii", "type shii meaning"],
  sigma: ["sigma male", "sigma male meaning", "what is a sigma"],
  "sigma-grindset": ["sigma grindset", "sigma mindset"],
  brainrot: [
    "brain rot",
    "gen alpha brainrot",
    "brainrot meaning",
    "what is brainrot",
  ],
  rizz: ["rizz meaning", "what does rizz mean", "charisma rizz"],
  "no-cap": ["no cap", "no cap meaning", "nocap"],
  "fanum-tax": ["fanum tax", "fanumtax", "what is fanum tax"],
  "demure-mindful": [
    "very demure very mindful",
    "demure",
    "very demure",
    "demure mindful",
  ],
  "jools-lebron": ["jools lebron", "joolieannie", "demure girl"],
  "skibidi-toilet": [
    "skibidi",
    "skibidi toilet",
    "skibidi toilet meme",
    "skibidi guy",
    "skibidi man",
    "camera head toilet",
  ],
  gigachad: ["giga chad", "giga-chad", "gigachad meme"],
  "one-does-not-simply": [
    "one does not simply",
    "one does not simply walk into mordor",
    "boromir meme",
  ],
  "ohio-final-boss": [
    "ohio final boss",
    "only in ohio",
    "satoyu",
    "ohio meme",
  ],
  glazing: ["glaze", "glazing meaning", "what does glazing mean"],
  "crash-out": ["crash out", "crashout"],
  "locked-in": ["locked in", "lock in"],
  pookie: ["pookie meaning"],
  "ate-left-no-crumbs": ["ate and left no crumbs", "left no crumbs", "she ate"],
  mewing: ["mew", "mewing meaning", "mewing jawline"],
  looksmaxxing: ["looks maxxing", "looksmax", "looksmaxxing meaning"],
  "distracted-boyfriend": ["distracted boyfriend meme", "distracted boyfriend"],
  "this-is-fine": ["this is fine meme", "this is fine dog"],
  "expanding-brain": ["expanding brain meme", "galaxy brain meme"],
  "surprised-pikachu": ["surprised pikachu meme"],
  mogging: ["mog", "mogged", "mogging meaning", "what does mogging mean"],
  "standing-on-business": [
    "standing on business",
    "stand on business",
    "standing on business meaning",
  ],
  npc: ["npc meaning", "what does npc mean", "calling someone an npc"],
  "npc-streaming": [
    "npc stream",
    "npc streaming",
    "pinkydoll",
    "ice cream so good",
  ],
  deadass: ["dead ass", "deadass meaning", "what does deadass mean"],
  bet: ["bet meaning", "bet slang", "what does bet mean"],
  "understood-the-assignment": [
    "understood the assignment",
    "she understood the assignment",
    "understood the assignment meaning",
  ],
  "main-character-energy": [
    "main character energy",
    "main character syndrome",
    "main character energy meaning",
  ],
  "drake-hotline-bling": [
    "drakeposting",
    "drake meme",
    "hotline bling meme",
    "drake hotline bling",
  ],
  "change-my-mind": ["change my mind meme", "crowder meme"],
  "coffin-dance": ["coffin dance meme", "dancing pallbearers", "astronomia coffin"],
  "among-us-era": ["among us meme", "among us memes", "among us era"],
  "is-this-a-pigeon": ["is this a pigeon", "is this a pigeon meme"],
  "two-buttons": ["two buttons meme", "daily struggle meme", "sweating buttons"],
  loss: ["loss meme", "is this loss", "| || || |_"],
  "gamestop-wallstreetbets": [
    "gamestop",
    "wallstreetbets",
    "gme squeeze",
    "gamestop squeeze",
  ],
  "area-51-raid": ["storm area 51", "area 51 raid", "area 51 meme"],
  "bereal-wave": ["bereal", "bereal app"],
  "threads-launch": ["threads meta", "threads app", "instagram threads"],
  "twitter-x-transition": [
    "twitter x",
    "twitter rebrand",
    "elon musk twitter",
    "x formerly twitter",
  ],
  dream: ["dream smp", "dream youtube", "dream minecraft"],
  "gta-6-release": [
    "gta 6",
    "gta 6 hype",
    "gta6",
    "grand theft auto 6",
    "gta vi",
    "gta 6 trailer",
  ],
  ishowspeed: [
    "darren watkins",
    "ishowspeed streamer",
    "who is ishowspeed",
  ],
  barbenheimer: ["barbie oppenheimer", "barbieheimer"],
  "dafuq-boom": ["dafuq boom", "skibidi toilet creator", "alexey gerasimov"],
  "quandale-dingle": [
    "quandale",
    "quandale dingle",
    "quandale dingle meme",
  ],
  "lord-farquaad-e": [
    "lord marquaad e",
    "lord farquaad e",
    "markiplier e",
    "farquaad e",
  ],
  "dat-boi": ["dat boi", "datboi", "here come dat boi", "o shit waddup"],
  "josh-hutcherson-whistle-edit": [
    "josh hutcherson whistle",
    "hutcherson whistle edit",
    "josh whistle edit",
  ],
  "arthurs-fist": ["arthur's fist", "arthur fist", "arthur clenched fist"],
  "100-men-vs-1-gorilla": [
    "100 men vs gorilla",
    "100 men vs 1 gorilla",
    "men vs gorilla",
  ],
  "handsome-squidward": [
    "handsome squidward",
    "squidward falling",
    "beautiful squidward",
  ],
  "overly-attached-girlfriend": [
    "overly attached girlfriend",
    "oag meme",
    "overly attached gf",
  ],
  "du-bist-gut-genug": [
    "du bist gut genug",
    "gut genug",
    "you are good enough song",
  ],
  "dafoe-looking-up": [
    "willem dafoe looking up",
    "dafoe looking up",
    "van gogh looking up",
  ],
  "most-liked-egg": [
    "instagram egg",
    "world record egg",
    "most liked egg",
    "egg gang",
  ],
  harambe: ["harambe meme", "harambe the gorilla", "dicks out for harambe"],
  "yanny-vs-laurel": ["yanny or laurel", "yanny laurel", "laurel or yanny"],
  "nothing-beats-a-jet2-holiday": [
    "jet2 holiday",
    "nothing beats a jet2 holiday",
    "jet2holiday",
  ],
  "my-shayla": ["my shayla", "my shayla meaning", "oh my god my shayla"],
  "wilson-lo-siento": [
    "wilson lo siento",
    "wilson lo siento meme",
    "wilson chicken",
  ],
  "all-your-base-are-belong-to-us": [
    "all your base",
    "all your base are belong to us",
    "aybabtu",
    "for great justice",
  ],
  "ah-shit-here-we-go-again": [
    "ah shit here we go again",
    "here we go again meme",
    "cj here we go again",
    "ah shit here we go again meme",
  ],
  "imagine-if-ninja-got-a-low-taper-fade": [
    "ninja low taper fade",
    "low taper fade meme",
    "the low taper fade meme",
    "imagine if ninja got a low taper fade",
    "still massive",
    "low taper fade",
  ],
  "tel-aviv-impressed": [
    "tel aviv impressed",
    "tel aviv impressed meme",
  ],
  "tylenol-baby": ["tylenol baby", "tylenol baby meme"],
  "funky-ehh": [
    "funky ehh",
    "we'll drive a funky ehh",
    "well drive a funky ehh",
    "he'll drive a funky ehh",
    "funky ehh meme",
  ],
  geeg: ["geeg meaning", "geeg gg", "geeg slang"],
  ez: ["ez meaning", "ez slang", "gg ez", "easy slang gaming"],
  performative: [
    "performative male",
    "performative man",
    "performative guy",
    "performative aesthetic",
    "performative tiktok",
  ],
  "numa-numa": [
    "numa numa",
    "numa numa dance",
    "gary brolsma",
    "dragostea din tei meme",
  ],
  "badger-badger-badger": [
    "badger badger badger",
    "badger badger",
    "mushroom mushroom",
    "weebl badgers",
  ],
  "charlie-the-unicorn": [
    "charlie the unicorn",
    "candy mountain",
    "filmcow charlie",
  ],
  "dramatic-chipmunk": [
    "dramatic chipmunk",
    "dramatic prairie dog",
    "dramatic hamster",
  ],
  "peanut-butter-jelly-time": [
    "peanut butter jelly time",
    "pbjt",
    "dancing banana",
    "it's peanut butter jelly time",
  ],
  "hamster-dance": [
    "hamster dance",
    "hampster dance",
    "the hampster dance",
    "hampton the hampster",
  ],
  "end-of-ze-world": [
    "end of ze world",
    "end of the world flash",
    "fire ze missiles",
    "but i am le tired",
  ],
  "star-wars-kid": [
    "star wars kid",
    "ghyslain raza",
    "star wars kid video",
  ],
  "afro-ninja": ["afro ninja", "afro ninja fail", "afro ninja video"],
  "double-rainbow": [
    "double rainbow",
    "what does it mean",
    "double rainbow guy",
    "hungrybear9562",
  ],
  "press-f-to-pay-respects": [
    "press f to pay respects",
    "press f",
    "f to pay respects",
    "press x to pay respects",
  ],
  "can-it-run-crysis": [
    "can it run crysis",
    "but can it run crysis",
    "crysis meme",
  ],
  "the-cake-is-a-lie": [
    "the cake is a lie",
    "cake is a lie",
    "portal cake",
  ],
  "arrow-to-the-knee": [
    "arrow to the knee",
    "arrow in the knee",
    "i took an arrow to the knee",
    "skyrim arrow to the knee",
  ],
  "do-a-barrel-roll": [
    "do a barrel roll",
    "barrel roll",
    "peppy barrel roll",
  ],
  "press-x-to-doubt": [
    "press x to doubt",
    "x to doubt",
    "(x) doubt",
    "la noire doubt",
  ],
  "git-gud": ["git gud", "get good", "git gud meaning"],
  noob: ["n00b", "newbie", "noob meaning", "noob slang"],
  lag: ["laggy", "lag meaning", "ping lag", "network lag"],
  gg: ["good game", "gg meaning", "gg wp", "ggs"],
  "charlie-bit-my-finger": [
    "charlie bit my finger",
    "charlie bit me",
    "charlie bit my finger video",
  ],
  "david-after-dentist": [
    "david after dentist",
    "is this real life dentist",
    "david after dentist video",
  ],
  "evolution-of-dance": [
    "evolution of dance",
    "judson laipply",
    "evolution of dance youtube",
  ],
  "leave-britney-alone": [
    "leave britney alone",
    "chris crocker",
    "cara cunningham britney",
  ],
  shoes: [
    "kelly shoes",
    "kelly's shoes",
    "liam kyle sullivan shoes",
    "shoes youtube kelly",
  ],
  fred: ["fred figglehorn", "fred youtube", "lucas cruikshank", "fяed"],
  "annoying-orange": [
    "annoying orange",
    "the annoying orange",
    "dane boedigheimer",
  ],
  "youtube-rewind": [
    "youtube rewind",
    "yt rewind",
    "rewind 2018",
    "youtube rewind 2018",
  ],
  cheems: ["cheems doge", "balltze", "cheemsburbger", "cheems meme"],
  popcat: ["pop cat", "popcat click", "oatmeal cat", "popcat meme"],
  longcat: ["long cat", "longcat is long", "longcat meme"],
  "ceiling-cat": ["ceiling cat", "basement cat", "ceiling cat meme"],
  "o-rly-owl": ["o rly", "o rly owl", "oh really owl", "ya rly"],
  "side-eyeing-chloe": [
    "side eyeing chloe",
    "side eye chloe",
    "side eyeing chloe meme",
  ],
  myspace: ["my space", "myspace.com", "top 8", "myspace top 8"],
  newgrounds: ["new grounds", "newgrounds.com", "newgrounds flash"],
  "4chan": ["4 chan", "fourchan", "4chan.org", "/b/"],
  "musical-ly": [
    "musically",
    "musical.ly",
    "musical ly",
    "musically app",
  ],
  tumblr: ["tumblr.com", "tumblr blog", "reblog culture"],
  "hey-thats-pretty-good": [
    "hey that's pretty good",
    "that's pretty good idubbbz",
    "hey thats pretty good",
  ],
  "hot-damn": [
    "hot damn",
    "holt hot damn",
    "captain holt hot damn",
    "brooklyn nine nine hot damn",
  ],
  "shrek-smirk": [
    "shrek smirk",
    "shrek rizz",
    "shrek looking up smiling",
    "shrek lightskin stare",
  ],
  cottagecore: ["cottage core", "cottagecore aesthetic", "cottagecore tiktok"],
  "dark-academia": [
    "dark academia",
    "dark academia aesthetic",
    "darkacademia",
  ],
  "influencer-culture": [
    "influencer culture",
    "influencers",
    "internet influencer",
  ],
  "creator-economy": [
    "creator economy",
    "the creator economy",
    "creator monetization",
  ],
  "streamer-culture": [
    "streamer culture",
    "twitch culture",
    "live streaming culture",
    "twitch streaming culture",
  ],
  "youtube-creator-era": [
    "youtube creator era",
    "youtube creators",
    "youtube celebrity era",
    "youtuber era",
  ],
  "instagram-culture": [
    "instagram culture",
    "insta culture",
    "ig culture",
  ],
  "reddit-culture": ["reddit culture", "reddit hive mind", "subreddit culture"],
  "discord-culture": ["discord culture", "discord servers", "discord vc"],
  "snapchat-culture": [
    "snapchat culture",
    "snap streaks",
    "snapchat streaks culture",
  ],
  "unboxing-culture": ["unboxing", "unboxing videos", "unboxing culture"],
  "influencer-marketing": [
    "influencer marketing",
    "influencer ads",
    "sponsored influencer",
  ],
  "brand-social-media-wars": [
    "brand social media wars",
    "brand twitter wars",
    "wendys twitter",
    "brands roasting each other",
  ],
  fomo: ["fear of missing out", "fomo meaning", "fomo slang"],
  "old-money": [
    "old money aesthetic",
    "quiet luxury",
    "quiet luxury aesthetic",
    "stealth wealth",
  ],
  "dupe-economy": [
    "dupe culture",
    "dupes",
    "stanley cup craze",
    "stanley tumbler craze",
    "stanley quencher",
  ],
  "tiktok-rise": [
    "tiktok culture",
    "tiktok era",
    "rise of tiktok",
    "tiktok's rise",
  ],
  "clean-girl-aesthetic": [
    "clean girl",
    "clean girl aesthetic",
    "cleangirl",
  ],
  "y2k-revival": ["y2k aesthetic", "y2k fashion revival", "y2k tiktok"],
};
